### ISSUE TITLE
Label overlap values in itinerary details (French)

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#1007]
Hi,

I’ve noticed this bug in osm : 
![9E51EB17-4266-497C-81BB-5D3D2663EC8F](https://user-images.githubusercontent.com/59312735/103387897-919ffb80-4b06-11eb-8e93-21130fb20605.jpeg)

The label truncate a part of the value 

I’ve saw this issue on an iPhone XS with osm 3.81 in French.

**Comment by vshcherb** [comment]
We need to make it 1liner
