### ISSUE TITLE
file not found 

### ISSUE THREAD

**Issue by Romil12345** [osmandapp/OsmAnd-ios#102]
'OsmAndCore/QtExtensions.h'  and  'OsmAndCore.h' file not found

**Comment by guoliang1206** [comment]
same issue and not found a solution

**Comment by Darshan-Sonigara** [comment]
same issue

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-core/blob/master/include/OsmAndCore.h
https://github.com/osmandapp/OsmAnd-core/blob/master/include/OsmAndCore/QtExtensions.h
