### ISSUE TITLE
« Distance » label in itinerary 

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#1022]
Hello, I’m using the last beta on osmand iOS. I was wondering what’s the goal of « distance » label since we cannot click on it?
![A910E7C7-E73A-42AF-AFAC-9EBFE31E72D8](https://user-images.githubusercontent.com/59312735/104730598-a1d8ed00-573a-11eb-8b3f-6f7d125abb4b.jpeg)

thank you

**Comment by vshcherb** [comment]
It's just label

**Comment by vshcherb** [comment]
Altitude over distance
