### ISSUE TITLE
Mapillary stays activated if we click in another position

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#1036]
In iOS 14.3 with latest osmand beta (3.90.1.7), I do not activate mapillary : 
![88314130-80F9-4EA2-82C5-C013629E60E1](https://user-images.githubusercontent.com/59312735/105394566-0b1a9d80-5c1e-11eb-865c-b0c043b6302a.png)

then, I click in a point of the map and I want to see nearby, so I click on mapillary photo : 
![ED46C1E3-6D44-4E72-A613-E79EE24B750D](https://user-images.githubusercontent.com/59312735/105394712-39987880-5c1e-11eb-84fd-f21a00847ea4.png)
![B8DC303D-730D-4F6E-8314-EEA69A44C8B7](https://user-images.githubusercontent.com/59312735/105394804-52089300-5c1e-11eb-9bf0-8b7469e4653d.png)

now, two possibilities : 
(1)-I click on the top left botton and the mapillary points are gone from the map just like before using it
(2)-I click in another mapillary position : 
![BAD82C12-7E98-4D57-97E9-C2350CFF2797](https://user-images.githubusercontent.com/59312735/105395182-c17e8280-5c1e-11eb-9a71-3a41769f3d59.png)

If I do so mapillary stays active on the map even after closing the view :  
![416194D7-97E3-47F2-8B6A-278076C78521](https://user-images.githubusercontent.com/59312735/105395340-e8d54f80-5c1e-11eb-8670-927a51f34ddf.png)

Shouldn’t we have the behavior (1) on each situation after closing mapillary?

**Comment by vshcherb** [comment]
- If you click (1) Mapillary layer should be disabled cause you simply didn't enable it in Map Layers. 
- On the other hand if you enabled it in Configure Map, then X should not close the layer.

I think here devs need to pay attention that X behaves differently in 2 situations.
