### ISSUE TITLE
Routing with intermediate destinations is not possible

### ISSUE THREAD

**Issue by FriedelXT** [osmandapp/OsmAnd-iOS#1067]
### Description

A route created with osmand with accessible intermediate destinations is not possible, although this is suggested. Especially in the new version.
You can create a route with drag and drop, but there are no intermediate destinations. So the dashboard does not show: "xxx kilometers to the intermediate line or xxx minutes to the intermediate destination". Only the distance to the destination the arrival time is displayed.
After saving the "route" all brown flags are no longer available.
Please check 

### Your Environment
OsmAnd Version: newest
Android/iOS version: 14.4
Device model: XR

**Maps used (online or offline):**   doesnt matter

**Comment by vshcherb** [comment]
Well rtept are not intermediate points, we don't consider to add them cause they are irrelevant for many cases and could simply be viewed as points to take a turn. It's probably better to have waypoints and add them to the track.

What's should be supported is editing mode, once you open that file for editing <rtept> should be displayed as points to tangle. It should be supported both on Android / iOS

**Comment by vshcherb** [comment]
Well I understand that we want to use special points as intermediate points  unfortunately it's not supported yet. We need to have UI to mark it unmark and even more we need to extend our GPX file support to store it there, so later we could use it.

**Comment by maksim-paulau** [comment]
What about Android? It will be nice to have this feature too. It's extremely important for travelling by car. When I load a route I can see just star points, but I can't see how much time/kilometers is left to the next intermediate point.

**Comment by vshcherb** [comment]
Unfortunately it's not clear any more what needs to be supported, please test latest 4.2 Beta iOS build and everything should be present already
