### ISSUE TITLE
search for the target by setting the geographical coordinates

### ISSUE THREAD

**Issue by riccardopastocchi** [osmandapp/OsmAnd-iOS#1072]
Is it possible to search for the target by setting the geographical coordinates, as it already happens for Android? But above all to improve the second phase, that is, once the coordinates have been written, to be able to go immediately to the display of the target on the map, without making other steps. 

![coord](https://user-images.githubusercontent.com/78115599/106807156-1da6c500-6669-11eb-90b2-e5419599b515.png)

**Comment by vshcherb** [comment]
Good request, I don't think it's first prio feature to migrate or not but it's definitely on the list.

**Comment by vshcherb** [comment]
Yes, we've added in 4.1 single search for coordinates (this screenshot is for adding a batch of coordinates).
