### ISSUE TITLE
unnecessarily large fields in Advanced view when editing OSM data

### ISSUE THREAD

**Issue by stragu** [osmandapp/OsmAnd-iOS#1081]
When editing OSM data, and using the "Advanced" view, the fields are very large when they should really only use the space necessary to display the tag and value.

![image](https://user-images.githubusercontent.com/1747497/107118773-aa9e8800-68ce-11eb-8a0b-736638791e08.png)

In version: 3.90.2 (in OsmAnd) / 3.92 (in App Store)

**Comment by vshcherb** [comment]
Should be fixed in testflight version
