### ISSUE TITLE
Displaying the address: house number has the wrong order

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd-iOS#1089]
displaying the address: house number has the wrong order

OSM: https://www.openstreetmap.org/way/230003896

= The House number is "4 1/2“.

![photo_2021-02-10 16 45 15](https://user-images.githubusercontent.com/72389175/107525294-60175700-6bbf-11eb-9686-c1872ef647ad.jpeg)

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/10825
