### ISSUE TITLE
iPad issue with POI personalized search

### ISSUE THREAD

**Issue by attilagib** [osmandapp/OsmAnd-iOS#1101]
I would like to report an issue i saw on my iPad Pro i did not see on my iPhone.

The deletion of a personalized POI search does not work at all then if I create several POI personalized searches, they will stay in the category list forever.
The app version i am using : 3.90.2.

I did not notice the same issue on my iPhone 11
The same app version is used on my iPhone.

**Comment by PaulStets** [comment]
Can confirm, for some reason the confirmation action sheet does not appear on the iPad.

**Comment by Skalii** [comment]
fix was added in 3.90.8

**Comment by vshcherb** [comment]
Release version is coming early May. So the fix will be part of 4.0 release. Beta of 3.91 is available as well.
