### ISSUE TITLE
Missing trails for Touring view

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#1106]
IOS WILL NOT display trails and is MISSING a lot of detail in the Touring View. It will show the label for trails, but NO trail.

**Comment by vshcherb** [comment]
Probably duplicate, there was this issue before

**Comment by PaulStets** [comment]
Fixed in https://github.com/osmandapp/OsmAnd-resources/commit/3fe1db2c5d917a203a58f1a37089b6fd82d96e8e
