### ISSUE TITLE
CSS for Wikipedia

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-ios#112]
Add CSS file that we use for Android Wikipedia screen to the iOS.
https://github.com/osmandapp/Osmand/blob/master/OsmAnd/assets/article_style.css
![img_0131](https://user-images.githubusercontent.com/9365308/43727090-a82b9406-99a9-11e8-91a9-dc14104f5e22.PNG)

**Comment by PaulStets** [comment]
Added CSS, title, and RTL support.
