### ISSUE TITLE
Picking certain map styles throws app in crash loop

### ISSUE THREAD

**Issue by jeffreytigch** [osmandapp/OsmAnd-iOS#1122]
I could not find a CONTRIBUTING.md, so I hope I am providing you enough info. 

I was checking out different map styles, but on two of the map styles, the app crashes and keeps crashing during startup. I can use the app again after reinstalling the app.

The map styles I am talking about are Offroad and Topo. I am using an iPhone XS, latest app version (3.9.5) and iOS 14.4.

**Comment by vshcherb** [comment]
It is fixed with https://github.com/osmandapp/OsmAnd-resources/commit/4ccc41387c5edf6e834b97b0760fd0f40aeae33d
