### ISSUE TITLE
wrong display of average speed in track statistics

### ISSUE THREAD

**Issue by stragu** [osmandapp/OsmAnd-iOS#1130]
In the "Speed" section of a track's statistics, what I assume is the average speed is displayed as `<average speed> <some time>` when it should probably be displayed as `"Average speed" <average speed>`, just like the max speed underneath.

![image](https://user-images.githubusercontent.com/1747497/111890173-b4b9b780-8a32-11eb-92b5-7ebc02347da7.png)

Version: 3.90.7 on iOS 14.4

**Comment by dmpr0** [comment]
# Review
- [ ]  Speed doesn't show up at all for tracks exported from Strava
