### ISSUE TITLE
[feature request] Allow uploading tracks to OpenStreetMap

### ISSUE THREAD

**Issue by stragu** [osmandapp/OsmAnd-iOS#1132]
Given that OsmAnd already integrate OSM editing and opening OSM notes, it would be fabulous to also allow users to upload their GPX tracks straight to their OSM account.

Currently, the workflow looks like: go to track > export > share with other app > upload to OpenStreetMap, potentially on different device.

If the user has already linked their OSM account to OsmAnd, with the OpenStreetMap Editing plugin activated, there could be another option in the three-dot menu, for example "upload to OSM".

The API details are here: https://wiki.openstreetmap.org/wiki/API_v0.6#GPS_traces

Interestingly, the OSM Wiki says that OsmAnd iOS already supports that: https://wiki.openstreetmap.org/wiki/Upload_GPS_tracks#Applications_supporting_direct_upload_of_GPS_traces

**Comment by lekseys** [comment]
Fixed the [wiki](https://wiki.openstreetmap.org/w/index.php?title=Upload_GPS_tracks&diff=prev&oldid=2423056). Removed information about support for uploading tracks.

I'm waiting for version 4.3-iOS.

**Comment by dmpr0** [comment]
### 

Visibility:
* Public – https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml/#L1098
* Identifiable – https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml/#L1096
* Trackable – https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml/#L1095
* Private – https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml/#L1097


<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/211330125-c9d7a894-aa7a-497f-aea8-f3b6a5d2a8c6.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/211330128-3afdc6ee-b059-4d3c-bdc9-9e68b570f7b4.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
19.02.23 master - Done

**Comment by dmpr0** [comment]
Available to test in the latest TestFlight build 4.4.6.1

**Comment by dmpr0** [comment]
## Review
- [ ]  RTL issues on Visibility screen. (NavBar is native?)

<img src="https://user-images.githubusercontent.com/9365308/226332464-2b307f09-d1ae-4c0d-bca5-111e011a7256.png"  width="300" height="auto"/> 

- - - 
- [ ]  Chevrons ">" has different size. Use new TabelCells
<img src="https://user-images.githubusercontent.com/9365308/226332663-cd8449f4-2e57-476b-b2e1-617200e40a00.png"  width="300" height="auto"/>

**Comment by PaulStets** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2742

**Comment by Zirochkabila** [comment]
4.4.7.2
No information is available in the track loading bar



<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/232221742-aac03b43-db84-4559-a033-a135af502258.jpeg"  width="470" height="auto"/> </th>
    <td><video source src="https://user-images.githubusercontent.com/104760013/232221751-ee05b864-1318-41fe-b6db-8397873b09a8.mp4"  width="300" height="auto"/> </td>
  </tr>
</table>
