### ISSUE TITLE
CarPlay nav freeze

### ISSUE THREAD

**Issue by wojosc** [osmandapp/OsmAnd-iOS#1148]
### Description
The navigation screen on CarPlay freezes when phone screen turnes off/standby.
Other zu like path description will keep running. When turning phone screen back on navigation will refresh and work till next Standby

### How to reproduce?
While navigation turn off the screen of your iPhone

### Your Environment
OsmAnd Version:
Android/iOS version: iOS
Device model: iPhone 12

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by vshcherb** [comment]
Well I can open and close it immediately cause more fixes will be provided with 4.0, please try public beta and give feedback.

**Comment by r33zA** [comment]
Hi. Is the public beta for iOS the TestFlight one? I’m running TestFlight Ver. 3.90.7.1 and its still present. Cheers.

**Comment by PaulStets** [comment]
@r33zA Hi, the fix is not in the public beta yet. It will be included in the next stable public beta version.
