### ISSUE TITLE
OsmAnd crash when clicking on a POI which has wrong code

### ISSUE THREAD

**Issue by MonterossaOSM** [osmandapp/OsmAnd-iOS#1167]
Hi, I edited a POI in OsmAnd map date (https://www.openstreetmap.org/node/2399202263), but made a mistake in the opening hours format. After an update of the map data in the OsmAnd app, every time I clicked on the POI to view the content, the app crashed.

It would be nice, if the app would just not return any data, but stays open.

I am now in the process of editing the code, so by the time you will try to replicate this, it may just show the corrected information.

**Comment by vshcherb** [comment]
```Di+Mi 08:00 - 18:00, Do+Fr 8:00-19:00```

**Comment by MonterossaOSM** [comment]
With corrected opening_hour syntax, the app now works fine and just shows the information entered.
However, I would still wish the app not to crash, but just do nothing upon finding bad codes.

**Comment by scaidermern** [comment]
I suggest to reopen this ticket. A wrong opening hours syntax must not lead to an OsmAnd crash.

**Comment by MonterossaOSM** [comment]
I agree and have reopened the ticket. However, since I corrected the mistake in my code, it can't be replicated any longer.
