### ISSUE TITLE
OsmAnd changes to the default profile when exiting a route

### ISSUE THREAD

**Issue by hugh-martin** [osmandapp/OsmAnd-iOS#1169]
App version: 3.90.7 (iOS)

To replicate the issue, do the following:
- Switch to any profile other your default profile.
- Set up a route.
- Tap the Cancel button to exit the route.
- Verify that the profile has been changed to your default profile.

Thank you for a great app!

**Comment by vshcherb** [comment]
You can change global default profile in Global Settings, it should help to keep it always the same

**Comment by hma-github-intel-svc** [comment]
I am not sure that is a reasonable solution to this issue, but OK.
