### ISSUE TITLE
wrong level calculation

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#1180]
Hello,

I detected a problem in calculating the difference in height.

on the curve of the slopes it is flat while on the trail it is not at all.

<img src="https://user-images.githubusercontent.com/79785663/115989350-2ea70880-a5be-11eb-8d7a-f7a76dd13193.jpeg"  width="300" height="auto"/>

**Comment by dmpr0** [comment]
I have tried to build a route using Plan Rout in this area and using regular navigation, I didn't find any issues.
@Hades1503 Are you still can reproduce it?

**Comment by Hades1503** [comment]
Indeed, I just did a test again and it works properly.

When there are changes on a path, the update distorts altitude and/or slope data.
