### ISSUE TITLE
rendering ignores new `highway=busway` tag

### ISSUE THREAD

**Issue by stragu** [osmandapp/OsmAnd-iOS#1184]
With the [recent approved proposal](https://wiki.openstreetmap.org/wiki/Proposed_features/Tag:highway%3Dbusway) about using [`highway=busway`](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dbusway) over the combination of `highway=service` and `access` + `bus` tags, OSM contributors have already started updating tags, but it results in missing roads in the OsmAnd rendered maps. For example, this is in my area:

![image](https://user-images.githubusercontent.com/1747497/116321724-efff9100-a7fd-11eb-9c82-c977961411d1.png)

Admittedly, it is more of a pressing issue for the ones who use OsmAnd live, but it will definitely leave big holes in maps very quickly for most users.

Every OsmAnd iOS map type is affected.

There is an [equivalent issue opened for OSM Carto](https://github.com/gravitystorm/openstreetmap-carto/issues/4226).

Version:

* OsmAnd iOS 3.90.7

**Comment by kolgza** [comment]
This has been fixed:

https://github.com/osmandapp/OsmAnd/issues/11451

https://github.com/osmandapp/OsmAnd-resources/commit/36c2a1528299de4f98a7e27481d00ce3a290215a

**Comment by stragu** [comment]
Fabulous, I didn't realise it could have relied on one single fix for both platforms. It does make sense now.

Thanks for the quick response! Looking forward to the next release.
