### ISSUE TITLE
Map orientation threshold issues: setting not registered, and not even used

### ISSUE THREAD

**Issue by stragu** [osmandapp/OsmAnd-iOS#1185]
I noticed two issue with the Map orientation threshold used in navigation:

## 1. Setting not registered depending on where it is changed

When accessing the setting using `Side panel > Settings > (profile) > Navigation settings > Map behavior > Map orientation threshold`, changing the value does get registered.

However, accessing the setting using `Navigation button > Options > Navigation settings > Map behavior > Map orientation threshold` does not register the change (or so it seems: the value displayed next to "Map orientation threshold" does not change, but the tick mark does move to the correct spot in the list of speeds).

https://user-images.githubusercontent.com/1747497/116331786-cd787280-a813-11eb-9259-482e7fa2c71a.mp4

## 2. Setting is not used while navigating

The other thing I noticed is that my map _never_ switches to the direction of movement while navigating, whatever value I have the Map orientation threshold setting on. Not sure if others observed that? It seems it has been the case for me for a number of OsmAnd versions.

## Version used

OsmAnd iOS 3.90.7 on iOS 14.4

**Comment by PaulStets** [comment]
Hi, @stragu, thank you for the feedback. This issue will be fixed in the next release.

**Comment by stragu** [comment]
Thank you! 👍🏼

**Comment by stragu** [comment]
Hi @PaulStets 

I am now using OsmAnd 4.1.1 and can confirm that (1) was fixed, however (2) seems to still be an issue: the map orientation still does not change when reaching the threshold during navigation.

**Comment by PaulStets** [comment]
Hi @stragu.
Could you please check if you are changing the setting for the correct application mode (e.g. if you calculate a car route, change the setting for the car profile)
