### ISSUE TITLE
crash on startup (iPhone 4s)

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd-ios#119]
Can’t open OsmAnd app after latest few updates on iPhone 4s with ios 9.3.5.

**Comment by alyonapinchuk** [comment]
The same issue with iPad 3.

**Comment by PaulStets** [comment]
Unfortunately, there are no crash logs for iPhone 4s and iPad 3 available at the moment. It would be nice if someone with the device could test the newest version. My best guess is the lack of RAM.
