### ISSUE TITLE
Pedestrian routing doesn't work in Paris

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#1190]
Doesn't build a route for pedestrian navigation type.
Map - Paris
Start: 48.8930, 2.3138
Finish : 48.8590, 2.3462
ver. 3.90.7
Calculation finishes by app crash.

For Car and Bicycle, it works without any problem.

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/way/401253691

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/commit/4534cf90c20939e90510eef79664972b33e93bb2
