### ISSUE TITLE
Navigation: swap start/destination doesn't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1235]
# Review
- [x]  Navigation screen jumps from middle position to the top and back right after taping "Swap"

## ToDo
Testflight build 3.91.5
Trying to swap start and destination points, every time I try to tap on the icon, the menu for "Add starting point" is opened.
![IMG_4950](https://user-images.githubusercontent.com/9365308/119660699-35809f80-be38-11eb-8c06-e2f0036cd9a5.PNG)

**Comment by Skalii** [comment]
[Fix jumping route navigation screen](https://github.com/osmandapp/OsmAnd-iOS/pull/1281)
