### ISSUE TITLE
Not working export in OsmAnd 3.99

### ISSUE THREAD

**Issue by tbkrtz** [osmandapp/OsmAnd-iOS#1262]
https://user-images.githubusercontent.com/40862958/121070434-fefb3b00-c7ce-11eb-84d7-0b5c6a71cf2b.MOV

The export function in the new version 3.99.3 is not working. 
After continuing it returns only to the settings screen. 
Or ist there something I'm doing wrong?

Thank you for this great app!
Best regards!

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback.
Try to install TestFlight version 3.99.3 https://testflight.apple.com/join/7poGNCKy

**Comment by PaulStets** [comment]
Hi, @tbkrtz could you please specify the selected export types in the Meine Orte section?

**Comment by tbkrtz** [comment]
> Hello! Thank you for the feedback.
> 
> Try to install TestFlight version 3.99.3 https://testflight.apple.com/join/7poGNCKy

Thank you for the reply! This is the version I have installed.

> Hi, @tbkrtz could you please specify the selected export types in the Meine Orte section?

I tried all possible ways:
- Only settings 
- Only POIs
- Only tracks
- ...

Something different I could try?
Thanks!

**Comment by PaulStets** [comment]
Everything in the code seems correct. Have you tried restarting the device? Might be a system storage issue.

**Comment by tbkrtz** [comment]
> Everything in the code seems correct. Have you tried restarting the device? Might be a system storage issue.

I've just restarted the device but nothing changed.

**Comment by PaulStets** [comment]
Hi, @tbkrtz, this issue will be fixed in the next build.

**Comment by dmpr0** [comment]
3.99.4
Now it crashes when I select all "Settings" and tap "Continue".

**Comment by Skalii** [comment]
> Now it crashes when I select all "Settings" and tap "Continue".

will be fixed in the next build

**Comment by dmpr0** [comment]
# Review build 3.99.5
- [ ]  Settings > Export > Crash. It's happened only after selection "Quick actions"

**Comment by tbkrtz** [comment]
> # Review build 3.99.5
> 
> - [ ]  Crash while trying to export "Quick actions" no matter from what place it was launched (settings or profile)

For me the app isn't crashing anymore.

But I don't know if all tracks are exported:
![image](https://user-images.githubusercontent.com/40862958/121947695-a25fc900-cd56-11eb-82a7-30d1bcc2abaf.jpeg)

I have 20 tracks with three over 500  KB.
The estimated file size is over 5 MB.
But the exported file is only 339 KB...

![image](https://user-images.githubusercontent.com/40862958/121948127-25811f00-cd57-11eb-8ed9-ac00863e22ef.jpeg)

When I try to import the file every Track has 0 points: 

![image](https://user-images.githubusercontent.com/40862958/121948639-c66fda00-cd57-11eb-8c0c-2c412e543b4f.png)

Could I import these tracks to look if they are complete? 
Are the tracks replaced or added?

Thanks!

**Comment by Skalii** [comment]
[Fix import/export quick actions](https://github.com/osmandapp/OsmAnd-iOS/pull/1288)
