### ISSUE TITLE
Change Folder Color bug

### ISSUE THREAD

**Issue by tbkrtz** [osmandapp/OsmAnd-iOS#1270]
With each selection the text moves more to the left:

https://user-images.githubusercontent.com/40862958/121412746-559a7d80-c965-11eb-94c2-69e2c25492e8.MOV

OsmAnd 3.99.3

**Comment by Skalii** [comment]
[Change Folder Color bug](https://github.com/osmandapp/OsmAnd-iOS/pull/1278)

**Comment by dmpr0** [comment]
# Review, build 3.99.5
- [ ]  I still can reproduce the issue.
![photo_2021-06-14 17 48 20](https://user-images.githubusercontent.com/9365308/121911780-b85e9100-cd38-11eb-9b14-265ea8fe8634.jpeg)
