### ISSUE TITLE
Broken position of hamburger menu

### ISSUE THREAD

**Issue by hellojaccc** [osmandapp/OsmAnd-iOS#1279]
~~Not sure what it called, but its position is broken
Device : iPhone SE 2
iOS : 14.6~~

![21-06-13 09-07-05 0688](https://user-images.githubusercontent.com/71537512/121794257-bebe1180-cc41-11eb-95c8-3a47bbc51757.png)

Sorry, i misunderstood the idea of this button. please close the issue

**Comment by vshcherb** [comment]
Buttons will be positionned correctly next release.
