### ISSUE TITLE
IOS does not import individual tracks from .gpx file

### ISSUE THREAD

**Issue by fjfilips** [osmandapp/OsmAnd-iOS#1287]
### Description
On IOS OsmAnd, when I try to open a .gpx file that has multiple tracks, all of the tracks appear as a single track.  The track starts out as an attachment to an email, then I "open in" OsmAnd to import the .gpx file.

### How to reproduce?
Try to import a .gpx file that has multiple tracks.  I am attaching an example file that has multiple tracks.  This is a critical issue for me, as I have the need to select individual tracks to follow on organized rides where the tracks are provided at the start of the ride.  Can this please be fixed ASAP?  When I try to open this .gpx file in IOS MotionX or TopoMaps+, the tracks are properly imported individually so only OsmAnd is unable to import the tracks on IOS.  I really need these tracks in OsmAnd so that I can use custom maps behind the tracks.  THANKS!

### Your Environment
OsmAnd Version: 3.90.7
Android/iOS version: IOS
Device model:  11

**Maps used (online or offline):**   Either
[PALMS TO PINES 2021 FINAL.zip](https://github.com/osmandapp/OsmAnd/files/6517256/PALMS.TO.PINES.2021.FINAL.zip)

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by drtbyk** [comment]
Please fix this issue. It is very annoying that GPX (and KML) files are not parsed properly. 
Tracks have Segments. Tracks are not Segments.
A GPX Track: **<trk>...</trk>** 
A GPX Track Segment: <trk>...**<trkseg>...</trkseg>**...</trk> , a portion of a Track.

**Comment by jojojones** [comment]
I just imported NEBDR and exact same issue.  Osmand makes it 1 track in only 1 color and all the names are gone.

I just tested it on android and it imports 2 colors and all tracks have their individual names. THIS IS BROKEN!!! 

Please fix.

**Comment by drtbyk** [comment]
After exercising the OsmAnd-iOS IMPORT feature for a few days, it is clear that the GPX import is unlike any other GPX compliant Nav App. Normally, exclusivity is a good thing for an application. Except, when that exclusivity causes the user to do unnatural things just to import their standard GPX files. 

Case in point: 
1. OsmAnd-iOS IMPORT of a GPX file will only see a users WAYPOINTS if the file is named FAVORITES.GPX. But, if there are Tracks in that file, the import FAILS.
2. OsmAnd Import of a standard GPX file, not named FAVORITES, with multiple Tracks and WAYPOINTS, the Waypoints are ignored and the individual Tracks are combined as a SINGLE TRACK.

These are conditions that must be changed if OsmAnd-iOS wants the level of growth that it should have.

**Comment by vshcherb** [comment]
1. WAYPOINTS vs FAVORITES.GPX, it's not correct. You shouldn't use FAVORITES.GPX if they are not favourites and obviously you couldn't have tracks in that file. Waypoints should be displayed once you enable the track itself. 
2. OsmAnd doesn't support tracks split. And it doesn't necessarily need to display it. It still could display those files but you can't show/hide individual tracks.


OsmAnd was used already for 10 years and only recently we've started getting feedback about automatic split, so the segments could be used in navigation easier and possibility to show/hide individual tracks from track collection.

**Comment by drtbyk** [comment]
@vshcherb - I now see the association between Waypoints and Tracks. But, the GPX file I'm Importing with 2300 Campground Waypoints shouldn't be classified as Favorites. They are just "My Places" and it doesn't seem as though they should be associated with an empty Track instance given that there is no Track in the GPX file I'm Importing. Currently all of the features I am looking for to manage my Waypoint(s) Group(s) are under the TRACKS functions. It would seem like the Waypoints features/functions should be moved up to My Places - at the same management level as Favorites.

**Comment by Skalii** [comment]
- [х] fix track names for multitrack
- [x] fix coloring of lines for multitrack
- [x] fix graphics for multitrack

**Comment by drtbyk** [comment]
Hopefully this fix will include changing the GPX_Extensions schema for Tracks so that it supports multi-track Extension attributes for both Export and Import of GPX and OSF multi-track files:
`<trk>
	<extensions>
        <show_arrows>...</show_arrows>
        <show_start_finish>...</show_start_finish>
        <split_interval>...</split_interval>
        <split_type>no_split</split_type>
        <color>...</color>
        <width>...</width>
  	</extensions>
 </trk>`

Not only will this help the user but it also makes it viable for other GPX generating Apps (like FURKOT.com) to creat OsmAnd compatible multi-track Exports.

**Comment by jojojones** [comment]
Unfortunately I just ran a test using four. Two the new beta released today and it does import the waypoints better now but it still will not display the names. It also will not allow proper import of the individual tracks. It creates numbered segments and has no name associated with it. I suggest anybody do a simple online search for NABDR and use that GPX or MABDR and import either of those and if you want to see how it should work I hate to say this but download the free version of Gaia and import it and they will come in with all the track names as individual tracks in each with a different color which is the way it supposed to work . Please fix this because it’s a hassle to have to break out individual tracks

**Comment by drtbyk** [comment]
Well, I don't think OsmAnd (Android or iOS) is going to support Garmin GPX Track Extensions like Gaia GPS does) which is how the Track Color attributes are tagged in  all of the [US Backcountry Discovery Routes](ridebdr.org) files: example attached.
[NEBDR-Apr2021.zip](https://github.com/osmandapp/OsmAnd-iOS/files/7962845/NEBDR-Apr2021.zip)

But, I hope that OsmAnd does understand that most folks in the motorcycling community (and I think others) often rely upon GPX files that have multiple Tracks and Waypoints that are not necessarily physically connected - and, may only be loosely associated with each other.

**Comment by drtbyk** [comment]
I might add that this "feature" request has been here for a long time now....I was @allthingssatnav
https://github.com/osmandapp/OsmAnd-iOS/issues/65#issue-93130780

**Comment by jojojones** [comment]
Cartograph v3 as of today now brings in complex multitrack gpx files with correct track colors.  No jangle.

**Comment by drtbyk** [comment]
I don't know of any other mobile Nav App that treats GPX files the way OsmAnd currently does. I don't really expect OsmAnd to support **_Garmin_** GPX Track Extension schema like is used in the BDR files mentioned above - but hopefully the whole GPX Track handling will get reworked a bit.

**Comment by jojojones** [comment]
I think they thinkthey already fixed it as per the change log on 4.2.0 “Fixed import of GPX files from OSF package”
I think the waypoints are a bit better but the individual track names and colors from a large single gpx like MABDR do not work….and according to a previous poster above…likely will never work unless the app is completely overhauled.

**Comment by drtbyk** [comment]
The OSF GPX import is a different issue (#1725) but is connected by way of how OsmAnd has architected the use of GPX data and therefore the GPX Extension schema. As discussed, OsmAnd treats a GPX file's data as a single "instance" of travel data. Meaning, everything: Waypoint(s), Track(s) are all related. This is much different from the rest of the GPX world.

**Comment by dmpr0** [comment]
Track names and Colors of tracks are fixed and available in TestFlight 4.2.0.5 https://testflight.apple.com/join/7poGNCKy

**Comment by drtbyk** [comment]
Track names are being shown in TestFlight v4.2.0.5 in the My Places->Tracks list. But, they are not showing when selecting Navigate from the Map Screen.
![90511691-00DC-4415-8E57-CD09AE8F495D](https://user-images.githubusercontent.com/8745955/165010918-7af285ae-6bf0-41e5-a6fd-6dbb9ebb9325.jpeg)

**Comment by Skalii** [comment]
[Fix track segment names on "Select segment" screen](https://github.com/osmandapp/OsmAnd-iOS/pull/1904)
