### ISSUE TITLE
Add new quick action, keyboard overlaps "Apply" button

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1304]
Build 4.0.1 there is no way to save quick action if you want to rename it before because the keyboard is overlapping the "Apply" button.

# Review
- [x] Change name, tap on "Back" > Alert: Exit without saving > Exit > changed name will be saved anyway.

**We need to:**
- [x]  Show the "Apply" button above the keyboard
- [x] Show "Exit without saving" alert if the user makes a change to quick action and tap back without applying these changes.

![photo_2021-06-24 18 18 34](https://user-images.githubusercontent.com/9365308/123288850-99ba8000-d518-11eb-99dc-20710e58c105.jpeg)

**Comment by Skalii** [comment]
[Quick action - exit dialog \ apply button](https://github.com/osmandapp/OsmAnd-iOS/pull/1315)

**Comment by Skalii** [comment]
[Save name of quick action after cancelling changes](https://github.com/osmandapp/OsmAnd-iOS/pull/1348)
