### ISSUE TITLE
Follow track crash, if track starting point is to far away from location

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1307]
# Review
- [ ]  Crashing after taping on "Options" in the same conditions.

My location is in Kyiv, I choose tracks that were located in London, navigation trying to calculate route but it ends in crashing the whole app.

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-iOS/pull/1314
