### ISSUE TITLE
Crash: Profile "Reset to default"

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1308]
Choose profile "Walking" tap on "Reset to default" app will crash, "OsmAnd Settings": Default profile, CarPlay profile will be resetting too as a profile list visibility.
After restart:
• All custom profiles will be deleted
• All OsmAnd settings will be changed to default.

**Comment by Skalii** [comment]
[Fix profile reset \ refactoring profile settings](https://github.com/osmandapp/OsmAnd-iOS/pull/1319)
