### ISSUE TITLE
POI custom filter doesn't work correctly

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1335]
When you create custom filter for example Tourism and select beach and Camp site the application is searching only for camp site.

![image](https://user-images.githubusercontent.com/80623554/124717465-cfdf0300-df0d-11eb-8907-a6885981b337.png)
![image](https://user-images.githubusercontent.com/80623554/124717493-d8373e00-df0d-11eb-9b65-7dff85da2a4c.png)
![image](https://user-images.githubusercontent.com/80623554/124717506-dcfbf200-df0d-11eb-9a0b-8481dfd10ddf.png)

**Comment by Skalii** [comment]
[Sync PoiUIFilter with Android](https://github.com/osmandapp/OsmAnd-iOS/pull/1365)
