### ISSUE TITLE
Arabic regional translation (ar_SA)

### ISSUE THREAD

**Issue by abdullahO2** [osmandapp/OsmAnd-iOS#1342]
hi
Please update the Arabic translation of "Phrases" section on weblate:
https://hosted.weblate.org/projects/osmand/phrases/ar/

thank you and best regards

**Comment by vshcherb** [comment]
done

**Comment by abdullahO2** [comment]
OsmAnd-iOS/Resources/phrases.xml cannot be translated like on android version ?

**Comment by vshcherb** [comment]
It's the same and synchronized each build.

**Comment by abdullahO2** [comment]
Sorry, the Arabic translation did not appear with me because the device was set to "**ar_SA**" Arabic (Saudi Arabia), and when I put it on Arabic in general, I found it translated. Is it possible to apply the Arabic translation to the Arabic branches like:


ar | Arabic
-- | --
ar_AE | Arabic (United Arab Emirates)
ar_BH | Arabic (Bahrain)
ar_DZ | Arabic (Algeria)
ar_EG | Arabic (Egypt)
ar_IQ | Arabic (Iraq)
ar_JO | Arabic (Jordan)
ar_KW | Arabic (Kuwait)
ar_LB | Arabic (Lebanon)
ar_LY | Arabic (Libya)
ar_MA | Arabic (Morocco)
ar_OM | Arabic (Oman)
ar_QA | Arabic (Qatar)
ar_SA | Arabic (Saudi Arabia)
ar_SD | Arabic (Sudan)
ar_SY | Arabic (Syria)
ar_TN | Arabic (Tunisia)
ar_YE | Arabic (Yemen)



</body>

</html>

**Comment by abdullahO2** [comment]
(ar_SA) "Arabic (Saudi Arabia)" can be be synchronized with (ar) "Arabic" or we have to download (ar) and upload it as (ar_SA) on weblate

**Comment by abdullahO2** [comment]
this part also has update fom weblate:
OsmAnd-resources/poi/phrases/ar/

**Comment by vshcherb** [comment]
That needs to be investigated by developers, so it will taken up in 4.1. For now difference between languages could be stored in Weblate but it probably won't be displayed.

Updates will be posted here.

**Comment by dmpr0** [comment]
@abdullahO2 Hi! 
We make another approach to fix the issues, you can try to test in TestFligh build https://testflight.apple.com/join/7poGNCKy. It will be available in the release version soon.
