### ISSUE TITLE
Bug 4.0.3

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#1347]
Hello,

update 4.0.3 beug.

- when a profile is selected (hiking, cycling, car) the application does not load the map preferences for each profile.

- OSM modifications are frozen when editing a POI.

the slope color is not available on the gpx tracks, is it a bug or an oversight?

iPhone 11 Pro - iOS 14.6

**Comment by vshcherb** [comment]
Fixed with 4.0.4.

Slope color is not available on the gpx tracks - is not available for iOS in this release
