### ISSUE TITLE
OSM Editing, clear name button doesn't works

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1359]
The button with "X" right to the POI name doesn't work, it should clear the text field.

iOS: 14.6
OsmAnd: 4.0.4.1
![Снимок экрана 2021-07-08 в 14 09 29](https://user-images.githubusercontent.com/9365308/124912019-1dcf3600-dff6-11eb-9c5f-6b7472c608ca.png)

**Comment by Skalii** [comment]
[Fix clear buttons OSM Editing](https://github.com/osmandapp/OsmAnd-iOS/pull/1389)
