### ISSUE TITLE
Some POI categories do not show on the map

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1362]
One scenario: when you select in the Configure map -> POI overlay -> Filling station, Parking, Public transport, Routes, Wikipedia, only Filling station icons are displaying on the map.
Second scenario: When you select to display Parking, Public transport, Routes, Wikipedia, only Parking icons appear. 
Also, if you select show on the map only Filling station or Parking they are displaying correctly. 
Public transport, Routes, Wikipedia POIs are not displaying in general, not only in groups. 

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/80623554/124924593-49591d00-e004-11eb-903d-3c42b9a1df6a.jpeg"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/124924622-4f4efe00-e004-11eb-93e6-76591a95966a.jpeg"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/124924929-9dfc9800-e004-11eb-8f71-9edbeb895742.jpeg"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/124924914-989f4d80-e004-11eb-9a35-0220420aeb04.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table> 

OsmAnd 4.0

**Comment by PaulStets** [comment]
Fixed in a90636b881aab0fc1fbd2d465ae301948fb7c5b8
