### ISSUE TITLE
Record and create tracks supported by Garmin Basecamp

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#1366]
# Review
- [x]  Tracks created while recording or in "Plan route" don't open in Garmin Basecamp, android tracks open without error. 

[Android_2022-03-17_13-28_Thu.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/8284317/Android_2022-03-17_13-28_Thu.gpx.zip)

[iOS_2022-03-17_13-19_Wed.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/8284318/iOS_2022-03-17_13-19_Wed.gpx.zip)

[iOS_PlanRoute.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/8284356/iOS_PlanRoute.gpx.zip)

 <img width="372" alt="Screenshot 2022-03-17 at 13 33 32" src="https://user-images.githubusercontent.com/9365308/158800284-6158c919-00e5-421c-ad52-c37b596922d3.png">

# To Do
In order to support Garmin Basecamp track, it should strictly follow xml schema restrictions. It could be compared and looked at OsmAnd android GPX format.

**Comment by yuliiastets** [comment]
PR: https://github.com/osmandapp/OsmAnd-core/pull/300

**Comment by yuliiastets** [comment]
PR: https://github.com/osmandapp/OsmAnd-core/pull/308
