### ISSUE TITLE
Waypoints no longer show their label/name on the map after updating to 4.0.5 iOS

### ISSUE THREAD

**Issue by adegans** [osmandapp/OsmAnd-iOS#1369]
### Description
In previous versions I could navigate a GPX file with waypoints and see the waypoint name on the map as I drive past it.
This no longer seems to work.

Previously waypoints and POI were purple star icons. Now they're black or dark blue and show no name.

The same files and newer files used to work on previous versions.

Screenshot: https://disk.stor.fit/index.php/s/jgesmXgWNPYCKEf

### How to reproduce?
Display a GPX track/file on the map.

### Your Environment
OsmAnd Version: 4.0.5
Android/iOS version: iOS 14.newest
Device model: iPhone 7 Plus

**Comment by adegans** [comment]
Extra info.
I found out that when I go in Menu > Configure Map > (enable) POI overlay labels.
The GPX labels show. Not sure if that's an intentional change.

If so, however, this option is then misleading as WAYPOINTS are not POI. And this option enables other things as well, which is not always desirable.

**Comment by vshcherb** [comment]
This is intentional. I think before this release there were not showing at all or couldn't be switched off. The label is incorrect cause it's POI / Favorites / GPX labels = Point labels

**Comment by adegans** [comment]
They were always visible yes.
But with this option I can turn them on, that's fine.

Though, as you noted, the label for the option is wrong/incomplete.

**Comment by PaulStets** [comment]
Renamed to Point Labels (POI, Favorites) in both iOS and Android to avoid confusion.

**Comment by dmpr0** [comment]
Available on the latest TestFlight https://testflight.apple.com/join/7poGNCKy
