### ISSUE TITLE
GPX navigation unreliable/broken after update 4.0.5 iOS

### ISSUE THREAD

**Issue by adegans** [osmandapp/OsmAnd-iOS#1370]
### Description
Since the 4.0.5 update - Loading a GPX file, or several, now results in a little popup screen thingy claiming the GPX file has multiple segments and has me choose one. Except, before I can choose, the menu closes and discards my route.
So in effect I can't start to follow a track.

I've tried files with a Route, just waypoints, just a track or any useful combination of those... Nothing seems to work anymore.

Before the update I could load up a GPX with POI, Waypoints and a track and just start navigating that with the "Follow a track" feature. Now I can't.

### How to reproduce?
Try starting to follow a track.

### Your Environment
OsmAnd Version: 4.0.5
Android/iOS version: iOS 14.newest
Device model: iPhone 7 Plus

**Maps used (online or offline):**   
Stock maps, Mexico.
Hillshade plugin.

**Comment by adegans** [comment]
I'm finding this out as I use Osmand...
I'm on a trip, this file I'm supposed to ride today but now can't use Osmand for it.
GPX file: https://disk.stor.fit/index.php/s/ETe6myJDpern8tQ

This gpx shows the issue. I've tried others too, which worked in the previous version of Osmand.
This one I used last week and worked perfectly fine - GPX: https://disk.stor.fit/index.php/s/d5CGXsjaaRoqTew

**Comment by adegans** [comment]
Extra info.
There are 2 different workflows you can do to start the track. Here is what I discovered so far.

1.
Menu > My places > Tracks > Import > (Select track) > (Enable) Show on map.
Then, go back to the map and click Navigation (next to the menu button) > (Select track from 'displayed tracks') >  (Segment selection pops up). This works but then the next issue is that the routing is wrong as shown in https://github.com/osmandapp/OsmAnd/issues/12140

Or

2.
With no track displayed. Click Navigation (next to the menu button) > Options > Follow track > (Select the track from the popup menu) > (Segment selection pops up) and this fails. The menu closes immediately and then I can't proceed.
I can try this over and over, but I can't start the track. So my only option is to discard the route.

**Comment by PaulStets** [comment]
Fixed the original issue in https://github.com/osmandapp/OsmAnd-iOS/pull/1383.
As for the second issue, I was not able to reproduce it with any routing configuration. If you have a reliable way to reproduce it, please provide more details.

**Comment by adegans** [comment]
I think the routing mess has something to do with the POI.
The extra routing is done between them it seems.
The attached gpx file has this issue every time… so it’s easy to reproduce.

Still, in some cases I'm sent into side roads only to be turned around on the next crossing to continue on the original road. Sometimes this considerably lengthens the route (100s of kilometers) and ofcourse is very confusing.

**Comment by adegans** [comment]
This now also happens on Osmand 4 on Android.
