### ISSUE TITLE
Create favorites with "№" sign

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1377]
When I try to save the point from the map to the favorites, (favorite by default use point name) alert was showing, telling that it doesn't support some symbols, in my case `U+2116 №`.

![telegram-cloud-photo-size-2-5465476537521386292-y](https://user-images.githubusercontent.com/9365308/126765311-e71b524c-7f25-4645-bc3a-45ba32cb4519.jpg)

**Comment by Skalii** [comment]
[Fix favorite name with №](https://github.com/osmandapp/OsmAnd-iOS/pull/1395)
