### ISSUE TITLE
Space in Category Names before üäö

### ISSUE THREAD

**Issue by michaelkrnac** [osmandapp/OsmAnd-ios#139]
In the German Translation there is a space infront of üäö characters in categories.
For Example
"Sehenswürdigkeiten" or "Kultstätte"

![image1](https://user-images.githubusercontent.com/3944657/45537607-f8e5f480-b804-11e8-8eea-a321174e2d3a.png)

**Comment by mguaylambert** [comment]
I can confirm the same for : é, è, à, ë, ô in French.

**Comment by schwindp** [comment]
Just to add a bit more details: Happens as well in
OsmAnd v2.40 using iOS 12.1.2
