### ISSUE TITLE
Sorts the recorded tracks

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1407]
Sort the recorded tracks in the order they were created. The last recorded track is on the top. (already implemented in the Android version).

<img src="https://user-images.githubusercontent.com/80623554/128020848-5f47c126-f260-4f1c-b98d-ff4d85b7c1ff.png"  width="300" height="auto"/>

**Comment by vshcherb** [comment]
As on Android we should have 3 type of sorting here.

**Comment by dmpr0** [comment]
Merge to https://github.com/osmandapp/OsmAnd-Issues/issues/2348
