### ISSUE TITLE
Public transportation lines corrupted

### ISSUE THREAD

**Issue by R3gi** [osmandapp/OsmAnd-iOS#1415]
Public transportation lines in station detail appear corrupted. It seems to be OK in iD and other apps.

Example:
![image](https://user-images.githubusercontent.com/2983869/128496272-81232259-7a9e-4d29-a540-3ff05e1d0a1c.png)

http://osmand.net/go.html?lat=50.07494&lon=14.43690&z=19
https://www.openstreetmap.org/node/4715159302

OsmAnd 4.0.6 (the problem appeared even in previous versions)

**Comment by PaulStets** [comment]
Hi, @R3gi, could you please specify which map you are using. I'm unable to reproduce this issue with the standard Czech Republic or Prague map.
![telegram-cloud-photo-size-2-5231083370266604669-y](https://user-images.githubusercontent.com/20681525/128861913-4efc7180-4aef-4a34-83a8-f6801681add8.jpg)

**Comment by vshcherb** [comment]
It looks like map was corrupted by whatever reason and needs to be redownloaded

**Comment by R3gi** [comment]
I'm using the standard Prague map (Česká republika – Praha) with live hourly updates.

The issue seems to be resolved by deleting and downloading the map again.

When I deleted the map, certain data persisted (no matter how many times I have redownloaded the map and/or restarted the app).

![image](https://user-images.githubusercontent.com/2983869/128884461-f8190221-48f0-406e-ba4a-c26e24e60077.png)

How can I clear the remaining data (without resetting the whole app)?

I'm worried the issue may appear again, because we still don't know what has caused it.

**Comment by PaulStets** [comment]
Somehow, the live updates were not deleted with the map. I have created a separate issue for that: https://github.com/osmandapp/OsmAnd-iOS/issues/1425 
As for the broken bus stops, if you are able to reproduce it again, please contact us with the coordinates of the place. This is probably related to broken live updates.
