### ISSUE TITLE
macOS: parts of menu missing

### ISSUE THREAD

**Issue by rdoeffinger** [osmandapp/OsmAnd-iOS#1418]
Parts or all of the bottom entries of the menu are missing when running on macOS in a window size that is not high enough.
Can be pretty confusing since there's no indication (at least if the window is a little smaller than in my screenshot) that something is missing, so not easy to realize that e.g. fullscreen mode would fix it.
Would be nice to have fixed if easy to do.
<img width="1440" alt="Screenshot 2021-08-07 at 14 57 48" src="https://user-images.githubusercontent.com/5464937/128601074-d827d999-83f6-427a-9ab2-f6c64dff0732.png">

**Comment by PaulStets** [comment]
@rdoeffinger Fixed for the iPad but should be fixed for mac as well. Please let me know if it's fixed. You can test it in the next testflight build (4.1.0.3 which will be probably out in a week or so) or wait for the next major release.

**Comment by rdoeffinger** [comment]
Thanks, I did not have time to figure out the testflight stuff, but I can confirm it works perfectly now with the just released version.
If I was very picky, I could mention that if you  make the window too small so it's impossible to fit the full menu there is no way to access the entries not fitting or even an indication that they are missing.
But I suspect it's not worth the effort to do anything about that corner case.
