### ISSUE TITLE
Import of favorites not working

### ISSUE THREAD

**Issue by tbkrtz** [osmandapp/OsmAnd-iOS#1419]
When importing an exported backup of the favorites, the points are only imported as a track, which must be separately shown on the map. 

However, it should be imported back into the structure under "my places".

**Comment by tbkrtz** [comment]
Found the failure, the file was renamed during the export. 

With renaming the file to favorites it works.

**Comment by dmpr0** [comment]
We two different names for file depend on how the export operation was doing.
• If you tap on the "Export favorites" action on the My Places screen, OsmAnd will propose to export "favourites.gpx" file
• if you tap on "Edit" select needed points, tap Export, OsmAnd will propose to export "Exported favorites.gpx" file

<table style="width:100%">
  <tr>
    <th>"Export favorites" action</th>
    <th>Export selected items</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/129021782-69148f4f-ecfe-45cd-b783-6c0a15a3df5f.png"  width="400" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/129021776-a0720922-fbfb-4ab7-85ed-ad84e8b745c4.png"  width="400" height="auto"/> </th>
  </tr>
</table>

**Comment by PaulStets** [comment]
Fixed in https://github.com/osmandapp/OsmAnd-iOS/pull/1439
