### ISSUE TITLE
Investigate incremental changes not being deleted with the region map

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/OsmAnd-iOS#1425]
Some map objects are still visible after deleting the region map.

**Comment by R3gi** [comment]
![image](https://user-images.githubusercontent.com/2983869/128991132-ed253a28-5264-45c1-ba37-fbb5f1bd8b08.png)
Example

**Comment by Skalii** [comment]
[Fix Map and Resources - refresh layer](https://github.com/osmandapp/OsmAnd-iOS/pull/1640)
