### ISSUE TITLE
font too small in Wikipedia articles

### ISSUE THREAD

**Issue by stragu** [osmandapp/OsmAnd-iOS#1469]
Currently, the default font size used in Wikipedia articles is too small, and is not customisable.
This is an accessibility issue: many users would find the default to be just not large enough for them.

![photo_2021-08-28_22-08-17](https://user-images.githubusercontent.com/1747497/131217381-08845d19-22f9-408e-8108-0f151db1bf19.jpg)

Version: 4.0.6

**Comment by PaulStets** [comment]
The article content was scaling incorrectly. It will look like this:
![Simulator Screen Shot - iPhone Xʀ - 2021-09-28 at 12 34 18](https://user-images.githubusercontent.com/20681525/135062653-aa79cf96-fd3b-4a49-83d3-2a94fd8b0781.png)

**Comment by stragu** [comment]
Thank you! Looking forward to the update :+1:

**Comment by dmpr0** [comment]
# Review
- [ ]  Font is too big in iPhone landscape mode
![IMG_2AB4A58258D1-1](https://user-images.githubusercontent.com/9365308/135289637-b3e0adc1-ef56-4f4b-a6a6-cc931845860e.jpeg)

**Comment by stragu** [comment]
Maybe smaller (top, left, right) margins and a smaller button at the bottom would be enough for the landscape issue?
