### ISSUE TITLE
The issue with the track that includes <rtept> points

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1473]
- [x] When you select track with <rtept> points for navigation, the application selects this track as an intermediate point and does not use it for navigation.![telegram-cloud-photo-size-2-5373106200599705162-y](https://user-images.githubusercontent.com/80623554/134944626-e819213e-ccfa-45bb-8cb8-5103d4f3a0d6.jpg)![image](https://user-images.githubusercontent.com/80623554/131650064-abf1c0f4-10de-41d0-897d-903eb574b59f.png)
- [x] When you try to edit track via Plan Route, it does not even display.
![image](https://user-images.githubusercontent.com/80623554/131650523-f81897f8-ddb4-4f94-af69-d1a7cafb6655.png)
- [x] When you select follow track for navigation the Start button is not activated. P.S. When you select Reverse track direction Start button activates.
![telegram-cloud-photo-size-2-5373106200599705162-y](https://user-images.githubusercontent.com/80623554/134945123-b40f38e8-28c4-44ff-8073-b9465ff0811d.jpg)
[utf-8.zip](https://github.com/osmandapp/OsmAnd-iOS/files/7243343/utf-8.zip)

**Comment by dmpr0** [comment]
# Review
- [ ]  If the start point is a point on the map, the route doesn't calcualte.

**Comment by PaulStets** [comment]
The first point is related to the core-legacy commit which will not be used in the 4.1 release branch, so it should be fixed separately.
