### ISSUE TITLE
Several tags are deleted when uploading to OSM

### ISSUE THREAD

**Issue by NKAmapper** [osmandapp/OsmAnd-iOS#1477]
### Description

OsmAnd is removing certain tags when uploading to OSM. It seems that tags not displayed in the app are being deleted.

This bug is so destructive to OSM that all uploads from OsmAnd to OSM should be halted if possible. Action should also be taken to restore the deleted tags in OSM caused by OsmAnd users.

### How to reproduce?

1) Select a POI on the map and edit it (or just select it for editing).
2) Upload it to OSM.
3) The tags which were not displayed in the app have now silently been removed from OSM.

Example: https://www.openstreetmap.org/node/35784739/history.  Several tags have been removed in the last changeset although not a single edit was done in the app.

Several other examples for another user: https://www.openstreetmap.org/user/Jostein%20Kjønigsen/history

### Your Environment
OsmAnd Version: 4.0.6
iOS version: 14.5.1
Device model: iPhone 12 Pro
My OSM account: https://www.openstreetmap.org/user/NKA

**Comment by dmpr0** [comment]
We need to:
- [ ]  Fix how "Offline editing" options are works.
- [ ] Fix issue with `&` symbol.

**Comment by scaidermern** [comment]
Is there any plan how to fix all those bad OsmAnd-ios edits? It should be easy to identify them by the created_by tag in the changeset.

**Comment by mathiash98** [comment]
@PaulStets was this fixed or just closed? I can't seem to find any commits related to this in the different repos

**Comment by PaulStets** [comment]
Sorry, forgot to reference the commit. I have synced the code with the Android version in https://github.com/osmandapp/OsmAnd-iOS/commit/c116a6e14aa5de32f8ffbbb60719ec0533e4172d

**Comment by mathiash98** [comment]
> Sorry, forgot to reference the commit. I have synced the code with the Android version in [c116a6e](https://github.com/osmandapp/OsmAnd-iOS/commit/c116a6e14aa5de32f8ffbbb60719ec0533e4172d)

Super! Great stuff 🥇

**Comment by dmpr0** [comment]
# Review 
- [ ]  If Offline Editing is disabled, on the "Edit POI" screen, the "Save" button should be replaced by "Upload".
