### ISSUE TITLE
Make Tracks selectable an add switch "Display all tracks on map"

### ISSUE THREAD

**Issue by Kettenknecht** [osmandapp/OsmAnd-iOS#1504]
Please, please, please make track selectable by touching on them in map view. And add a switch to display all tracks on the map. This would make osmand so much better for hiking.

**Comment by vshcherb** [comment]
This request is duplicated with make selectable routes / roads on the map and yes we're working to have completely new function to be able to display all local tracks on the map, that's probably coming next year Q1
