### ISSUE TITLE
Quick action button animation

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1526]
Use Fade effect to hide the quick action button when the context menu is opening

https://user-images.githubusercontent.com/9365308/135094115-4d95a9f5-8d57-4a83-8fbf-5dcde7b17bb3.MP4

**Comment by Skalii** [comment]
[Fix quick actions - button animation](https://github.com/osmandapp/OsmAnd-iOS/pull/1909)
