### ISSUE TITLE
Crash, Render and Navigation problems in areas  where live update  ist enabled 

### ISSUE THREAD

**Issue by michaelkrnac** [osmandapp/OsmAnd-iOS#1532]
OsmAnd crashes a lot on my iPhone SE 2020.
Sometimes on start it does not show the map, only the grid and the hill shading is visible.
I have a lot of crashes on scrolling and routing.

Now i was on a vacation and OsmAnd worked fine without crashing.
In the area of the vacation i do not have live update enabled.
In my home area i have live update enabled and there it crashes over and over again.

May it has something todo with live updates?

IOS 15, OsmAnd 4.0.6
But had the same problems with previous versions and iOS 14
The Maps are all German restricts.

**Comment by vshcherb** [comment]
Well we need to investigate of course, do you have the crashes with 1 live region or all? If you can reproduce crashes with 1-2 maps it would be great cause in that case we can investigate it easier

**Comment by michaelkrnac** [comment]
Yesterday i installed the test flight version. Today i send a screenshot of the maps I am using with live. I also produced some crashes while scrolling. Hope you retrieve those files and some log files.

The areas I am using the most ist germany: baden_wuerttemberg, rheinland_pfalz, Bayern

**Comment by PaulStets** [comment]
Hi, @michaelkrnac. I have tested the map of Bayern with live updates and hillshades and did not see any issues. I have also searched for crash reports from iPhone SE 2020 and was not able to find any that match your description. We will address the most frequent and serious crashes in the next official release, so it may fix your problems. 
For now, I think we should close this issue. However, if you have any additional information that could help us reproduce the issue you described, please specify it here for further investigation.

**Comment by michaelkrnac** [comment]
I have started sending each crash report. Do you recive them? Osmand 4.1.1 is almost not Usable with live updates for me ☹️

**Comment by vshcherb** [comment]
Yes we receive crash reports and check them regularly
