### ISSUE TITLE
difficulty path does not work

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#1535]
### Osmand 4.1.0.6

<table style="width:100%">
  <tr>
    <th>Osmand:</th>
    <th>Topo:</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/79785663/136564654-23f48e2e-f81e-4926-9c00-b60d95245e78.png"  width="400" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/79785663/136564793-08b0f054-fd97-4de7-b0c2-a068e23ffa09.png"  width="400" height="auto"/> </th>
  </tr>
</table>

### Osmand 4.0.6

<table style="width:100%">
  <tr>
    <th>Osmand:</th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/79785663/136564926-4be7358a-0a77-46aa-bffb-1a94b3d9b332.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Skalii** [comment]
[Fix route parameters in Map Settings](https://github.com/osmandapp/OsmAnd-iOS/pull/1576)

**Comment by Hades1503** [comment]
On Osmand iOS 4.1.0.12 same problem

**Comment by dmpr0** [comment]
@Hades1503 please check 4.1.0.13, it will be available today.

**Comment by Hades1503** [comment]
It works on IOS 4.1.0.13
