### ISSUE TITLE
Live updates enabled when swiping back

### ISSUE THREAD

**Issue by R3gi** [osmandapp/OsmAnd-iOS#1540]
Region's live updates are enabled when visiting the region screen and swiping back.

1. Visit the Live Updates screen and make sure there's a map region with disabled live updates.
2. Tap the region with disabled updates.
3. Notice the live updates switch is enabled.
4. Swipe to right to go back to the Live Updates screen.
5. Region's live updates are now enabled. I would expect it to be disabled / in previous state, actually the same like hitting the Cancel button. Or that the switch won't be automatically enabled.

https://user-images.githubusercontent.com/2983869/136999607-19afb900-032a-4d02-b504-1726d16a6b37.MOV

OsmAnd v4.0.6

**Comment by dmpr0** [comment]
# Review
- [ ]  All settings should be applied only after tapping the "Apply" button in navbar, currently, if you tap on the "Live Updates" switch and swipe the screen back, it will apply and a map is moved to the live updates list.
