### ISSUE TITLE
Request: show street name in other map views besides auto

### ISSUE THREAD

**Issue by barteis** [osmandapp/OsmAnd-iOS#1550]
A nice feature of the Android version is its ability to show not only street names, but trail/walking path names with turn-by-turn navigation.  In the iOS version, this is also possible, but only in with the auto view.  Could street name display be extended to the  walking and bicycling views as well?  And/or made an option in Configure screen menu?    Thanks!

**Comment by PaulStets** [comment]
Fixed in https://github.com/osmandapp/OsmAnd-iOS/pull/1898
