### ISSUE TITLE
Show user points above POI

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1559]
User points: favorites, gpx waypoints, and all others should be shown above POIs. On the attached screenshot GPX waypoint is below "orange" POI.

<img src="https://user-images.githubusercontent.com/9365308/139098741-1c0392a8-12d3-481c-a77e-55fd6da59299.PNG"  width="300" height="auto"/>

**Comment by Skalii** [comment]
[Fix POI Layer - order](https://github.com/osmandapp/OsmAnd-iOS/pull/2037)
