### ISSUE TITLE
Traces gpx tab 4.1.0.10

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#1561]
Hello,

OsmAnd version 4.1.0.10

Problems of displaying directional arrows for GPX tracks.
![image](https://user-images.githubusercontent.com/79785663/139238445-d150067d-3537-48cb-a9ad-82e1cbff15c4.png)
Inconsistency of icons analysis on the map and appearances (same icon)
![image](https://user-images.githubusercontent.com/79785663/139238495-17eb8be7-2be9-487d-bfa0-bb3b6116695f.png)
Problems of the settings of thickness of the gpx tracks and unconscious behavior

https://youtu.be/EZ8KZZIeIYE

**Comment by vshcherb** [comment]
Please check new beta
