### ISSUE TITLE
Wiki POIs on the map

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#1563]
The issue with POI of Wiki articles when we use Search menu -> Categories.

The points of WIKI are shown on the map not only with a match in name, but most likely any match from the text.

![image](https://user-images.githubusercontent.com/44466116/139453980-5036e07c-88e2-43a7-afb3-aaee519d4641.png)
![image](https://user-images.githubusercontent.com/44466116/139453993-b0b9fb4a-e3bb-4bc2-a853-63b10a9aba16.png)

**Comment by dmpr0** [comment]
Fixed on the latest TestFlight build, available by the link https://testflight.apple.com/join/7poGNCKy
