### ISSUE TITLE
.obf problem with modified map style

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#1564]
Hello,

When you import a profile with some settings and a modified map style into OsmAnd, the application correctly imports the settings and the modified map style but it does not activate the modified style in the new profile. 
You have to go to the settings each time to select the modified map style. 

This problem is on android and iOS and on all the latest versions of osmand (even those in iOS development). 4.0.6, 4.1.0.6, 4.1.0.10
iPhone 6s, X, 11 pro

**Comment by dmpr0** [comment]
Fixed on the latest TestFlight builds https://testflight.apple.com/join/7poGNCKy
