### ISSUE TITLE
Resets track color to default after editing track via Plan route tool

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1569]
## How to reproduce:

Change the track color. Then edit track via Plan route->when you save track the color will be changed to default color. 

https://user-images.githubusercontent.com/80623554/139860778-7e6833b5-c896-4a25-91bb-e5a3a3a66162.MOV

**Comment by Skalii** [comment]
[Fix GPX - Appearance settings after editing](https://github.com/osmandapp/OsmAnd-iOS/pull/1785)
