### ISSUE TITLE
Navigation Color

### ISSUE THREAD

**Issue by FriedelXT** [osmandapp/OsmAnd-iOS#1579]
Please create a possibility to change the line color when navigating regardless of the selected map.

I find the Garmin-typical color (magenta) such as the off-road map, the most visible.

As far as I am concerned, the suit can also be uniform with all maps magenta.

**Comment by dmpr0** [comment]
Available in the current TestFlight build 4.2.0.5 https://testflight.apple.com/join/7poGNCKy

**Comment by FriedelXT** [comment]
Nice update..thank you. But you forgot transparence. 

Von meinem iPad gesendet

**Comment by dmpr0** [comment]
@FriedelXT 
Yes :) Transparency and custom color selection is on the list too and will be available soon.

**Comment by FriedelXT** [comment]
Yeah!!! Thanks

--

Friedhelm Walldorf

Riphausstrasse 11

D-45731 Waltrop



Mobil: +4915123509915

eMail: ***@***.***

**Comment by FriedelXT** [comment]
Osmand nearly perfect. 
But pls pls do a deal with kurviger.de for motorcycle routing. I would pay for it! 
They do perfect routing for motos

--

Friedhelm Walldorf

Riphausstrasse 11

D-45731 Waltrop



Mobil: +4915123509915

eMail: ***@***.***
