### ISSUE TITLE
Feature request: Apple CarPlay integration

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#158]
Since iOS 12, you can now add support for CarPlay navigation to your app.

(CarPlay is an iOS feature that lets an Apple iPhone use a compatible car's infotainment screen and controls as a dumb terminal. Before this fall, only Apple Maps could be used on CarPlay, but now any navigation app can implement support.)

I fully realize that this is not an easy undertaking, but on the other hand it would be a perfect match for OsmAnd's offline, open source maps. And it would also be a big competitive advantage, as so far only Google Maps, Waze, and Sygic have CarPlay support.

So it makes sense to at least get this feature out on the table.

The developer documentation is at https://developer.apple.com/documentation/carplay, and there's a good introductory article at https://blog.flitsmeister.nl/start-developing-your-navigation-app-for-carplay-6e4c6c2b4e47

**Comment by F3000** [comment]
Is there any progress ?

**Comment by smokemyshoes** [comment]
This feature would be absolutely killer. I really hope you are making progress on this one...

TIA

**Comment by nateberkopec** [comment]
[More docs from Apple here](https://developer.apple.com/documentation/carplay/adding_carplay_support_to_your_navigation_app).

I'd be more than willing to alpha test on a real CarPlay system if required.

**Comment by Djedouas** [comment]
> I'd be more than willing to alpha test on a real CarPlay system if required.

Me too !

**Comment by yakamama** [comment]
Any news from Carplay intergration ??? Pleasssssse

**Comment by vshcherb** [comment]
Hopefully will be done before summer 2021

**Comment by nateberkopec** [comment]
That would be great! It's the only thing that prevents me from making Osmand my "daily driver" maps app (ha!)

**Comment by yakamama** [comment]
> That would be great! It's the only thing that prevents me from making Osmand my "daily driver" maps app (ha!)

Me too !!!

**Comment by smokemyshoes** [comment]
This feature request was closed without any comments so just out of curiosity, is this functionality to be expected in a new release soon?

Thanks in advance!

**Comment by PaulStets** [comment]
@smokemyshoes Sorry, I forgot this was a public issue. The public beta will probably roll out today or tomorrow. We will be very grateful for any feedback.

Here is how it's going to look like:
<img width="403" alt="Screenshot 2021-02-24 at 12 09 57" src="https://user-images.githubusercontent.com/20681525/108985248-84803280-7699-11eb-8e31-515282489cb4.png">
<img width="403" alt="Screenshot 2021-02-24 at 12 10 06" src="https://user-images.githubusercontent.com/20681525/108985255-86e28c80-7699-11eb-8be2-cd977cef4377.png">
<img width="401" alt="Screenshot 2021-02-24 at 12 10 55" src="https://user-images.githubusercontent.com/20681525/108985259-877b2300-7699-11eb-9a43-d800f31a0d17.png">

**Comment by PaulStets** [comment]
I'm reopening this issue to gather feedback. Any information is welcome.

**Comment by vshcherb** [comment]
Initial implementation is rolled out, so feel free to open new issues to get it to a better state.

**Comment by nateberkopec** [comment]
Woohoo! I'm so excited. Next time I actually leave the house 😆 I'll report back.
