### ISSUE TITLE
Beta version crashes when hitting the new 'Routes' submenu

### ISSUE THREAD

**Issue by tonedivad** [osmandapp/OsmAnd-iOS#1584]
I reversed back to the current iOS version so I am posting here an issue I have encountered when testing my custom rendering file on the TestFlight beta version. Basically, the app crashed when I hit the new 'collapse' option in the 'Configure Map' menu. I suspect that it may be caused by new options that I defined in the <renderingProperty ...  category="routes"> or that I defined alternative 'possibleValues' /'name' that are not compliant with the next version. 

I must add that the current categories system on iOS is way better than Android where new or non-default <renderingProperty> categories are all over the place in the 'Configure Map' menu. As it stands it works great and it really helps to keep everything tidy and more compact. The only improvement I see would be to display these category options in the same order as they are defined in the render.xml rather than in alphabetical order.  

 Let me know if you need more infos. Cheers!

 D

**Comment by tonedivad** [comment]
A quick update on that issue. I have just reinstalled the test flight version 4.1.0.14 on my iPhone SE 2016 (iOS: 14.5.1). I did all my experiments on new 'pedestrian mode' with  default parameters:

 1) Osmand map type -> **no problems**
 2) Topo map type -> I can interact with the cycling/MTB/hiking routes but the app **crashes** when I hit the 'Show All' submenu
 3) Custom rendering file where I try to make sure that attributes names differ from the default rendering style while keeping <renderingProperty ... category="routes"/> (see below) -> app **crashes** instantly
 4) Same custom rendering file but giving a different name to the category <renderingProperty ... category="itineraries"/> -> **works** as expected with everything in the 'Itineraries' submenu
 
 Hopefully it helps you to see clearer into that is not necessarily a bug of major importance but that may occur when 'stupid' people like me are playing with the custom rendering files!
 
  D
 
 >>>
renderingProperty that I defined in point 3):
 
 	<renderingProperty attr="displayRouteName" name="Route name options" description="Display route name" type="string" possibleValues="NameIds,None" defaultValueDescription="default" category="routes"/>
	<renderingProperty attr="overlayRoute" name="Route style options" description="Display routes on top" type="string" possibleValues="LargeUnderlay,LargeOverlay,ThinLine" defaultValueDescription="" category="routes"/>
        
	<renderingProperty attr="showCyclingRoutes" name="Show cycling routes" description="Show cycling routes" type="string" possibleValues="CycleRoutes,NodeNetworkRoutes" defaultValueDescription="disabled" category="routes"/>
	<renderingProperty attr="showMTBRoutes" name="Show mountain biking routes" description="Show MTB routes" type="boolean" possibleValues="" defaultValueDescription="false" category="routes"/>
        <renderingProperty attr="showHorseRoutes" name="Show horse riding routes" description="Show horse riding routes" type="boolean" possibleValues="" defaultValueDescription="false" category="routes"/>
        <renderingProperty attr="showHikingRoutes" name="Show walking routes" description="Show walking routes" type="string" possibleValues="LongDistance,LongAndRegional,All" defaultValueDescription="disabled" category="routes"/>

        <renderingProperty attr="showWinterSlope" name="Show winter routes" description="Show ski/nordic hiking routes" type="boolean" possibleValues="" defaultValueDescription="false" category="routes"/>
        <renderingProperty attr="showWinterSkiSlope" name="Show winter ski pistes" description="Show downhill ski" type="boolean" possibleValues="" defaultValueDescription="false" category="routes"/>
 
 <<<

**Comment by Skalii** [comment]
[Fix Configure Map - Routes - for custom map styles](https://github.com/osmandapp/OsmAnd-iOS/pull/1611)
