### ISSUE TITLE
Unable to delete favorites

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1594]
https://t.me/c/1265587788/3234
https://t.me/c/1265587788/3235

https://user-images.githubusercontent.com/9365308/141322989-ca0e4699-9a5a-48ce-8001-1c4dbb999462.MP4

**Comment by Skalii** [comment]
[Fix My Places - Favorites - Delete](https://github.com/osmandapp/OsmAnd-iOS/pull/1596)
