### ISSUE TITLE
The voice guidance does not work while connecting to the Car system via Bluetooth

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1599]
OsmAnd 4.0.6, checked on two car systems. The voice guidance without connection to the Car system works.

**Comment by vshcherb** [comment]
If music is played from iPhone then voice guidance should also work.

**Comment by anastasiia936** [comment]
From the support requests: change between navigation and radio does not work.

**Comment by answerviews** [comment]
Issue have been observed for years on iPhone here. Only teardown of app operation and app restart helps. To put in other words: only following sequence of activation works:
* first enable device bluetooth
* then start OsmAnd app
* lets calculate the route
* enter navigation mode

Navigation voice prompts on bluetooth to car audio don't work if app gets started before device bluetooth gets enabled.
