### ISSUE TITLE
Contour line adjustment

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#1602]
On a modified map style I added an extra contour line setting that I named "+". 

The application displays in the settings "rendering_value_+..." on iOS. 
![image](https://user-images.githubusercontent.com/79785663/141615440-ab845cb6-aabc-40da-a11d-87d8e374b2a2.jpeg)

On android it correctly displays only the "+".

**Comment by vshcherb** [comment]
Looks like ios doesn't handle missing translations correctly and displays key instead of '+" itself

**Comment by Skalii** [comment]
[Fix Contour Lines - custom names of rendering values](https://github.com/osmandapp/OsmAnd-iOS/pull/1642)
