### ISSUE TITLE
Tilted map bug

### ISSUE THREAD

**Issue by Altonss** [osmandapp/OsmAnd-iOS#1605]
When the map is tilted, there is a blue square on the top of the screen. Is this normal?
![image](https://user-images.githubusercontent.com/66519591/141995339-6c907a2e-b7a0-486b-a2d7-aa2dc0262de9.png)

**Comment by vshcherb** [comment]
Yes, it's normal we plan to make it nicer to display clouds. Though this is done to avoid too much performance degradation of displaying to many tiles

**Comment by Altonss** [comment]
Thank you for the information, I didn't know :)
