### ISSUE TITLE
Combine "Select elevation fluctuation" with "Use elevation data" into one parameter

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#1647]
There are two settings for using Elevation data for routing:
- Select elevation fluctuation 
- Use elevation data

Combine "Select elevation fluctuation" and "Use elevation data" into one parameter **"Preferred terrain"**

# ToDo
- [x]  **"Preferred terrain"**
- - [x] **Any:** similar to disabled "use elevation data". Icon = `ic_custom_terrain_any`
- - [x] **Flat:** same as in "Select elevation fluctuation" . Icon = `ic_custom_terrain_flat`
- - [x] **Hilly:**. same as in "Select elevation fluctuation". icon = `ic_custom_terrain_less_hilly`
- - [x] **Less hilly:** same as in "Select elevation fluctuation". Icon = `ic_custom_terrain_hilly`
- [x]  Icon should represent selected option.
<table style="width:100%">
  <tr>
    <th colspan=4><a href="https://www.figma.com/file/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=855%3A37837">Preferred terrain</a></th>
  </tr>
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/151380946-075d52c0-a672-4e15-8326-da9f0ec15eaa.png"  width="160" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/151380955-4df59d6f-3e66-4b06-8b0a-e98ba0bbbc31.png"  width="160" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/151380961-45220890-2f64-4aec-be0c-d1e00cb6c6be.png"  width="160" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/151380958-60b98c11-10a1-483f-8766-1ca802e3ac7f.png"  width="160" height="auto"/> </th>
  </tr>
</table>  

## Access
**"Preferred terrain"** should be accessible in listed places (if a profile with "Cycle" navigation type is selected)
- [x]  Navigation – Options
- [x]  Profile > Navigation settings > Route parameters

<table style="width:100%">
  <tr>
    <th><a href="https://www.figma.com/file/ZHXxcxI05wG6OUlOjwFHXn/Route-Preparation?node-id=601%3A30117">Navigation > Options </a> </th>
    <th><a href="https://www.figma.com/file/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=855%3A37836">Route parameters</a>  </th>
  </tr>
  <tr>
    <th valign=top><img src="https://user-images.githubusercontent.com/9365308/151382964-71a320d8-4436-4202-913f-ca525955b1d5.png"  width="150" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/9365308/151382978-bd05bc7b-6fb2-40f8-ae7d-a4beb6ef6c4b.png"  width="150" height="auto"/> </th>
  </tr>
</table> 

Android task https://github.com/osmandapp/OsmAnd-Issues/issues/199

**Comment by Skalii** [comment]
[Combine use elevation data](https://github.com/osmandapp/OsmAnd-iOS/pull/1776)

**Comment by Skalii** [comment]
[Fix preferred terrain ui](https://github.com/osmandapp/OsmAnd-iOS/pull/1802)
[Fix Route Line Appearance - opening screen from Route info -> Navigation settings](https://github.com/osmandapp/OsmAnd-iOS/pull/1803)
