### ISSUE TITLE
OSMAnd 4.1.0 quits during routing on iOS and iPadOS 15.2

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd-iOS#1709]
### Description
The app frequently closes when planning routes with multiple stops

### How to reproduce?
Start a route.  Keep adding stops by selecting points from the map.  After the 2nd or 3rd intermediate point the app will close without warning and without any error messages.

This did not happen in the previous version and I planned a route with 6 stops just yesterday without any trouble.

### Your Environment
OsmAnd Version: 4.1.0
iOS version: 15.2
Device model: iPhone XR and iPad Pro

**Maps used (online or offline):**   
If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs and its edition date.

**Comment by kevinp2** [comment]
FYI, I updated to OSMAnd 4.0.1 on iOS 15 a few hours ago, and this bug appears to be fixed.  I will keep an eye on it and report back tomorrow.

Nice work!

**Comment by DicePenguin** [comment]
I notice the application right out crashes or exits after a while, regardless of using intermediate points.

**Comment by vshcherb** [comment]
4.1.1 fixed regression and it now works as 3.9 but we keep investigation of new 4.1.0 algorithm and it will be less memory consuming
