### ISSUE TITLE
Add option to manage tracks folder in My places->Tracks menu

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1711]
It would be great to be able to manage the tracks folder via Menu->My places->Tracks. 
Add the opportunity to: 
1.  Rename track folder
2. Remove track folder
3. Change track color for all tracks in one folder

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/146950311-558dc04e-895c-4616-831b-c2eb96a7ebea.png)

**Comment by dmpr0** [comment]
https://github.com/osmandapp/OsmAnd-iOS/issues/1407

**Comment by dmpr0** [comment]
Merge to https://github.com/osmandapp/OsmAnd-Issues/issues/1914
