### ISSUE TITLE
Request to have the option to disable CarPlay

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd-iOS#1713]
The CarPlay app unfortunately displays only a tiny fraction of the information available on the iOS app.  Missing information includes speed limits, turn lanes, stop signs and most of the features that make OSMAnd so useful.

But if I plug my phone into my car, the iPhone display switches off and only the CarPlay display can be used.

I would like to request a way to fully or partially disable the CarPlay app.  Reasonable options include:

1. An app setting to globally enable or disable CarPlay.
2. When the phone is plugged in, ask the user if CarPlay should be used.  If the user says No, continue to use the iPhone display only.
3. (Best option): Have both iPhone and CarPlay displays running simultaneously, each with its normal feature set.

**Comment by Raphty** [comment]
I don't quite understand. You can already disable any app in carplay itself (on the iPhone, not on the car dashboard). Why add this to the app itself? I don't think any other apps do this.

here how to disable any carplay app: [settings] -> [general] -> [carplay] select the car, and sort and disable apps as you please

on the other hand, the fact that the app isn't working while carplay is activated gets on my nerves as well, but if the carplay app would work better I wouldn't mind as much.
but this issue I would consider closed.

**Comment by kevinp2** [comment]
> I don't quite understand. You can already disable any app in carplay itself (on the iPhone, not on the car dashboard). Why add this to the app itself? I don't think any other apps do this.
> 
> here how to disable any carplay app: [settings] -> [general] -> [carplay] select the car, and sort and disable apps as you please

Thanks, I had no idea that this was possible!

> 
> on the other hand, the fact that the app isn't working while carplay is activated gets on my nerves as well, but if the carplay app would work better I wouldn't mind as much. but this issue I would consider closed.

I have made this suggestion above, so would like to keep this Issue open:

_(Best option): Have both iPhone and CarPlay displays running simultaneously, each with its normal feature set._
