### ISSUE TITLE
Device is in 12 hour format, but time data in OsmAnd is not.

### ISSUE THREAD

**Issue by DicePenguin** [osmandapp/OsmAnd-iOS#1722]
### Description
My device is in 12 hour format. However, time data is still in 24 hour format. I see no setting to switch between time formats. Most users in the US use 12 hour format. Notice the device is in 12 hour format at the top left corner.

### Your Environment
OsmAnd Version: 4.1.1
iOS version: 15.1
Device model: iPhone XR

Pictures for elaboration are below:
<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/84756738/148083452-4e38f5e8-61d8-4a74-b957-b892ded81332.jpg"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/84756738/148083482-e2aec855-2951-4058-bc39-253b2ae77ba9.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
# ToDo
- [ ]  Use system time format for displaying opening hours.

Related Android issue https://github.com/osmandapp/OsmAnd/issues/12536

**Comment by Skalii** [comment]
[Opening Hours - Add AM/PM format (core-legacy)](https://github.com/osmandapp/OsmAnd-core-legacy/pull/68)
[Opening Hours - Add AM/PM format (iOS)](https://github.com/osmandapp/OsmAnd-iOS/pull/1742)

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/309
https://github.com/osmandapp/OsmAnd-iOS/pull/1864

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/309
https://github.com/osmandapp/OsmAnd-iOS/pull/1864

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/68
https://github.com/osmandapp/OsmAnd-iOS/pull/1742
