### ISSUE TITLE
OsmAnd v4.1.1 Crashes when changing Track Appearance

### ISSUE THREAD

**Issue by drtbyk** [osmandapp/OsmAnd-iOS#1723]
**Description**

Open My Places -> My Tracks -> select a Track (any Track) -> Appearance -> Width -> click on **Second**: App Crashes and must be restarted.

![8A6FDD98-C0E5-41D4-8475-AE85DBBB30A7](https://user-images.githubusercontent.com/8745955/148665062-ccf50b55-9c99-459d-8707-39a5c5076f0b.jpeg)

**Your Environment**

iPadOS 15.2
iPad Pro 12.9" (5th Gen) A2379

**Comment by drtbyk** [comment]
Well, I can no longer reproduce the screen that is shown in the screenshot. Therefore I am closing this issue. Odd that the screen would change without an update...

**Comment by drtbyk** [comment]
No longer reproducible...

**Comment by vshcherb** [comment]
Well probably it will be reproduce later and we will reference to that issue then
