### ISSUE TITLE
Export & Import of Tracks via an OSF file: FAIL.

### ISSUE THREAD

**Issue by drtbyk** [osmandapp/OsmAnd-iOS#1725]
**Description**
Export Tracks from one iPhone to another iPhone. The expectation is that my Tracks and their attributes will be imported into another OsmAnd-iOS device unchanged because I'm using the Export and not the Share (GPX) feature.

Both iPhones have the exact same Settings/Profile configurations accomplished by using the Export function.

**Workflow**:
 Settings -> Export -> My Places -> Tracks -> select the Tracks (22) to Export -> Apply -> Continue - Save as File. Open FILES app -> Select OSF Exported file -> Share with OsmAnd App on another iPhone.

**Results**
The iPhone on the left shows the Tracks as configured for Export. The iPhone on the Right shows the results of importing the OSF file from the iPhone on the left.

None of the original Track attributes from the left iPhone were imported to the iPhone on the right and many of the Tracks were corrupted with additional looping segments. REPEATABLE file attached
![F0A0D72D-145B-454D-B4A7-04CB7E51BEA0](https://user-images.githubusercontent.com/8745955/148700490-e02c126b-8b60-49c6-ba32-50db830f4223.jpeg)

[Export 22 Africa Tracks.zip](https://github.com/osmandapp/OsmAnd-iOS/files/7835959/Export.22.Africa.Tracks.zip)

**Devices**
iPhone (Left):
iOS: v15.2
Model: A2484
OsmAnd v4.1.1

iPhone (Right):
iOS: v15.2
Model: A1865
OsmAnd v4.1.1

**Comment by drtbyk** [comment]
I have been unable to determine the cause of the bad-Export (adding a duplicate of the original Track data, without the Track NAME & DESCRIPTION attributes, to the GPX. But, OsmAnd-iOS is consistent in doing this to the same Track(s) when Exported via OSF or GPX file format.

Compare the screenshot below with the one on the right above:
![17E91E86-445B-4279-B1EF-BE47C8FEDBDA](https://user-images.githubusercontent.com/8745955/149259340-96edc038-b0a1-40a9-927c-27c2b4dc6e78.jpeg)

I have GPX Exported this Track a number of times and it always has the corruption. 
[2022-1-12_GSE22_(Africa)_-_Day_22.zip](https://github.com/osmandapp/OsmAnd-iOS/files/7859531/2022-1-12_GSE22_.Africa._-_Day_22.zip)

**Comment by drtbyk** [comment]
After further investigation, OsmAnd-iOS is corrupting the GPX file upon Import. Any GPX Track `<trk>...</trk>` that has a Track Segment `<trkseg>...</trkseg>` within the Track, OsmAnd has added multiple of the original Track.  Making what should be a 249mi Track into a 1010mi Track - as can be seen in the screenshot above. This is repeatable.

**Comment by vshcherb** [comment]
Good finding, going to fix it.

**Comment by dmpr0** [comment]
# ToDo
- [ ] Tracks that exported using Settings > Export option, doesn't have <extensions> tags. Tracks that exported individually, thru track > export, has them.

**Comment by dmpr0** [comment]
Fixed, available in the latest 4.2.0.5 TestFlight builds https://testflight.apple.com/join/7poGNCKy
