### ISSUE TITLE
Widget goes under the screen when the download dialog appears

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1726]
Widget goes under the screen when the download dialog appears

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/9365308/148751133-c32d2eff-011f-4174-8ec8-52883ea43ec1.jpeg"  width="300" height="auto"/></th>
    <th><img src="https://user-images.githubusercontent.com/9365308/148751129-28aa7d3d-75b7-43b8-9dcc-efcf23be3b99.jpeg"  width="300" height="auto"/></th>
  </tr>
</table>

**Comment by Skalii** [comment]
[Fix right widget frame when download map widget is visible](https://github.com/osmandapp/OsmAnd-iOS/pull/1759)
