### ISSUE TITLE
Application crash during edit track

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1727]
### How to reproduce

Touch route
Actions
Edit track
Touch point
(Menu option appears)
Add points after
App crashes.

Does the same for Add points before.

OsmAnd 4.1.11

Video and track are available via the link: 
https://drive.google.com/drive/folders/142_tYg0p0fBgbHo4CoI6HvGL80QjHpvE?usp=sharing

**Comment by Skalii** [comment]
[Fix edit track - add points before/after](https://github.com/osmandapp/OsmAnd-iOS/pull/1739)
