### ISSUE TITLE
Feature Request: My Tracks access from main menu slide-over

### ISSUE THREAD

**Issue by drtbyk** [osmandapp/OsmAnd-iOS#1729]
It would be very helpful to reduce the number of menu click-throughs if there were a "My Tracks" action on the main menu slide-over: as in the modified screenshot below.

![C5AD4765-80B4-4B1A-AAED-9076C4D62F73](https://user-images.githubusercontent.com/8745955/148861406-9ebd7473-4b0e-49fb-8af1-de9473180eac.jpeg)

Cheers,

**Comment by dmpr0** [comment]
Duplicate https://github.com/osmandapp/OsmAnd-iOS/issues/1622
