### ISSUE TITLE
v4.1.1 - Export Track via GPX: FAIL.

### ISSUE THREAD

**Issue by drtbyk** [osmandapp/OsmAnd-iOS#1731]
**DESCRIPTION**
I've selected one of my Tracks from My Tracks and then selected EXPORT -> Save to File. The resulting GPX file has an additional Track added before my original Track (which is named) in the GPX file attached below. The additional Track is a loop of the original plus a point to point segment between Destination and Start (a straight line). The resulting EXPORT GPX file is attached.

This is the similar to the type of OSF Export corruption noted in #1725 

On a side note the EXPORTED GPX file has added OsmAnd-iOS Extension data (which is great) without providing OsmAnd attribution in the header. The Header still contains the original imported GPX attributions.

![2B79161F-938A-4034-A088-4DF2F82CB1D1](https://user-images.githubusercontent.com/8745955/149029982-4c01b744-24ae-47b9-b580-2c3f8fc10d9d.png)

**ENVIRONMENT**
iPhone 13 Pro Max Model: MLL53LL/A
IOS V15.2 (19C57)

[GSE22_(Africa)_-_Day_3_-_Wed,_Sep_7,_2022.zip](https://github.com/osmandapp/OsmAnd-iOS/files/7850190/GSE22_.Africa._-_Day_3_-_Wed._Sep_7._2022.zip)

**Comment by drtbyk** [comment]
Upon exercising GPX import/export I was unable to reproduce this GPX added Track data when Exporting. I'm closing this until I can determine the conditions that caused the above issue.

**Comment by vshcherb** [comment]
Ok, there is another issue open by open probably related about import failing and introducing wrong `trkseg`
