### ISSUE TITLE
The button 'Hide' current track does not work

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1737]
## How to reproduce

Start track recording->Press on the Trip recording widget->Show info->Press show/Hide track.
The track will be displayed regardless of whether the track display on the map is enabled or disabled.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/80623554/150341394-157584e0-adc8-4c07-acd5-dfeec453b84f.jpg"  width="300" height="auto"/></th>
    <th><img src="https://user-images.githubusercontent.com/80623554/150341400-5df09792-58d1-46ad-b81b-656b8aefb5d3.jpg"  width="300" height="auto"/></th>
  </tr>
</table>

**Comment by Skalii** [comment]
[Fix Recording Track - Show/hide button](https://github.com/osmandapp/OsmAnd-iOS/pull/1782)
