### ISSUE TITLE
No option to add photo for OpenPlaceReviews

### ISSUE THREAD

**Issue by stragu** [osmandapp/OsmAnd-iOS#1738]
Hi there!

I installed the OpenPlaceReviews plugin but I don't see any other option apart from the Mapillary option when looking at a POI's details.

This is the POI detail view:

![POI details, shows "Images nearby: we do not have photos for this location"](https://user-images.githubusercontent.com/1747497/150465962-d477ba9b-49e8-40f6-b165-3122211816f1.png)

And this is after tapping the "Add photos" button:

!["Get mapillary" prompt when hitting the "add photos" button.](https://user-images.githubusercontent.com/1747497/150466005-e60fb8be-e9b3-4538-82d1-7eedbe9960aa.png)

Using:

* OsmAnd 4.1.1
* iOS 14.8

**Comment by vshcherb** [comment]
OpenPlaceReviews is shutdown :-(
