### ISSUE TITLE
Track waypoints from "Currently recording tracks" doesn't visible until saving 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1741]
Track waypoints added to "currently recording track" doesn't visible on the map before track saving. Waypoint was added to the area visible on the screen.

# Review
- [x]  Track waypoints appearance resets to default (star with circle) after saving the "current track".

# ToDo
- [x]  Track waypoints should be visible before recorded track will be saved or recording stopped.

<img src="https://user-images.githubusercontent.com/9365308/150792688-1e216176-9bd8-4fc0-97cf-da35c93aab30.jpeg"  width="300" height="auto"/>

**Comment by Skalii** [comment]
[Fix Current Recording Track - Waypoints, Appearance, Show/Hide, Tap](https://github.com/osmandapp/OsmAnd-iOS/pull/1752)

**Comment by Skalii** [comment]
[Fix Waypoints - Extensions](https://github.com/osmandapp/OsmAnd-iOS/pull/1781)
