### ISSUE TITLE
Address search issue (CarPlay)

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1744]
I try to find the address. The first provided option cannot be selected. After hitting the search button, the first item in the list is not selectable either, but the second one is. Also after selecting the second option, the navigation route calculation got stuck in 99% and never finished. This seems to happen time to time.

 iOS 15.2 iPhone 12 Pro. 
OsmAnd version is 4.1.1.

**Comment by dmpr0** [comment]
Additional feedback from users:
Navigation to a location is not possible. If I can search for the location, I click on the location and nothing happens. Navigation to a POI works.

**Comment by PaulStets** [comment]
Fixed in https://github.com/osmandapp/OsmAnd-iOS/pull/1887
