### ISSUE TITLE
Add extended palette for coloring tracks / favorites / ...

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1761]
It would be nice to have more colors that you can choose for the tracks. 
Add the extended palette like in the Android version.
<table style="width:100%">
      <tr>
<th><img src="https://user-images.githubusercontent.com/80623554/152750762-559a748f-db4e-4e79-b67b-49fa8fe2481f.png"  width="auto" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/80623554/152750779-88c3d148-e4b8-40a7-a9f8-6b942ba67dc8.png"  width="auto" height="auto"/> </th>
  </tr>
</table>

**Comment by Skalii** [comment]
[Track appearance - coloring palette](https://github.com/osmandapp/OsmAnd-iOS/pull/2841)

**Comment by Skalii** [comment]
[fix custom track colors](https://github.com/osmandapp/OsmAnd-iOS/pull/2869)

**Comment by Skalii** [comment]
[Favorites/Waypoints - custom colors](https://github.com/osmandapp/OsmAnd-iOS/pull/2897)
[Favorites - alpha coloring](https://github.com/osmandapp/OsmAnd-core/pull/552)

**Comment by alex-osm** [comment]
- [ ] remove dictionary with colors ids

**Comment by Skalii** [comment]
[fix coloring palette](https://github.com/osmandapp/OsmAnd-iOS/pull/2917)
