### ISSUE TITLE
Graph measure units missed strings?

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1779]
Graph show meters as "units_m".

- [x]  Fix "units_m" in graph.

<img src="https://user-images.githubusercontent.com/9365308/150544269-f2a2ae3d-2c2d-4a42-adfa-3cfc91212ff8.jpg"  width="300" height="auto"/>

**Comment by Skalii** [comment]
[Fix Units Localization](https://github.com/osmandapp/OsmAnd-iOS/pull/1780)
