### ISSUE TITLE
Edit profile list does not save the changes

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1796]
## How to reproduce
Open OsmAnd-> go to the Settings-> Edit profile list -> Remove Truck and Motorcycle profile -> Done. Restart the app and when you check in the Menu-> Settings ->Edit profile list and the profiles that you previously removed will be there.

**Comment by vshcherb** [comment]
You can't remove Truck & Motorcycle profiles, it should be forbidden. You can only disable them.

**Comment by Skalii** [comment]
[Fix default profiles](https://github.com/osmandapp/OsmAnd-iOS/pull/1801)
