### ISSUE TITLE
Marker line & Map magnifier

### ISSUE THREAD

**Issue by abdullahO2** [osmandapp/OsmAnd-iOS#1804]
hello
I noticed that the Marker line in the iOS system is affected by Map magnifier and becomes more like hidden at the lowest levels of Map magnifier, and the following are images showing that:
![image](https://user-images.githubusercontent.com/61907628/157697942-7d8538b7-df4e-4306-bdac-22b36099cc06.png)
![image](https://user-images.githubusercontent.com/61907628/157698711-f8f6d534-4a64-4bb9-93dd-f3af52dae31f.png)

Also I suggest making the map marker direction line enabled by default, a picture of what I mean:

![image](https://user-images.githubusercontent.com/61907628/157700676-09677a2c-11e8-43df-ae71-9218611c4e97.png)

And this proposal is suitable for all versions on Android and iOS

Regards
Abdullah

**Comment by abdullahO2** [comment]
Comparison between routing path and Marker line in the iOS OsmAnd:
![image](https://user-images.githubusercontent.com/61907628/157712660-18a0d3ca-f987-478d-957e-52b5ab08347c.png)

**Comment by abdullahO2** [comment]
also Is it possible to customize the Marker line to make the user choose the thickness, shape and color of the line?

**Comment by Skalii** [comment]
[Fix map density - line widths](https://github.com/osmandapp/OsmAnd-iOS/pull/1841)
[Fix map density - icon size](https://github.com/osmandapp/OsmAnd-core/pull/304)

**Comment by abdullahO2** [comment]
I tried the latest version on test flight and the problem was fixed, thank you very much
