### ISSUE TITLE
Can't import favourites.gpx as favourites only as GPX track

### ISSUE THREAD

**Issue by nougatbyte** [osmandapp/OsmAnd-iOS#1836]
Desired behaviour (Tested in the android version):
When a GPX is imported that has no tracks (as in only wpt tags but no trk)it gets added as a favourite - if it has a track it gets added as a track.

Observed behaviour on ipadOS:
No matter what kind of gpx I try to import it always gets treated like a track and not as favourite.

OSMand version 4.1.1 
ipadOS version 15.4

Example GPX Code for testing:
`<?xml version="1.0" encoding="UTF-8"?>
<gpx
  version="1.1"
  creator="Runkeeper - http://www.runkeeper.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://www.topografix.com/GPX/1/1"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd"
  xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1">
<wpt lat="37.778259000" lon="-122.391386000"><ele>3.4</ele><time>2016-06-17T23:41:03Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
<wpt lat="37.778194000" lon="-122.391226000"><ele>3.4</ele><time>2016-06-17T23:41:13Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
<wpt lat="37.778297000" lon="-122.391174000"><ele>3.4</ele><time>2016-06-17T23:41:18Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
<wpt lat="37.778378000" lon="-122.391117000"><ele>3.4</ele><time>2016-06-17T23:41:23Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
<wpt lat="37.778449000" lon="-122.391039000"><ele>3.4</ele><time>2016-06-17T23:41:26Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
<wpt lat="37.778525000" lon="-122.390942000"><ele>3.4</ele><time>2016-06-17T23:41:29Z</time><extensions><gpxtpx:TrackPointExtension><gpxtpx:hr>171</gpxtpx:hr></gpxtpx:TrackPointExtension></extensions></wpt>
</gpx> `

**Comment by vshcherb** [comment]
Favorites are imported only if Favorites has specific name, "favorites.gpx" or "favourites.gpx"

**Comment by nougatbyte** [comment]
I also tried this but it doesnt work for me.
Am I doing something wrong?

Screencast of trying to add favourites.gpx:
https://cloud.mvhost.de/s/qNkt9HC2pPTRHis

**Comment by Skalii** [comment]
[Fix import from "Files" on devices](https://github.com/osmandapp/OsmAnd-iOS/pull/1862)

**Comment by dmpr0** [comment]
Fixed. 
You can test it by installing the latest TestFlight build https://testflight.apple.com/join/7poGNCKy

**Comment by jmendys** [comment]
iOS: All my favorities are gone, I can't import any file (regardless of its file name) and even when I add a POI as a favorite in the app and then replace this file with my own it does not show anything. Adding another POI as favorite creates a new favorites.gpx file with only this one POI.
