### ISSUE TITLE
4.2.0.10 crash by clicking on a POI that contains the image key

### ISSUE THREAD

**Issue by clwacker** [osmandapp/OsmAnd-iOS#1859]
If you want to see more information for a specific POI, the app crashes if the POI contains the image key.

OsmAnd 4.2.0.10
IOS 15.4.1

**Comment by vshcherb** [comment]
Could you please give an example of such POI

**Comment by clwacker** [comment]
quite all nodes with image= give a crash, for example:
https://www.openstreetmap.org/node/9494934443
https://www.openstreetmap.org/node/2627101623

**Comment by clwacker** [comment]
Same problem after upgrade to 4.2.0.11 
Here are 2 examples:
- Coffrane: boundary stone:  http://osmand.net/go.html?lat=47.0114961&lon=6.8567004&z=18 
- Hôtel de Ville - La Baie Du Lac, L'Abbaye:  http://osmand.net/go.html?lat=46.6484864&lon=6.3172897&z=18
If you select an object with tag=image, OsmAnd crash immediately
