### ISSUE TITLE
Display of Wikimedia Commons Category images for a POI 

### ISSUE THREAD

**Issue by clwacker** [osmandapp/OsmAnd-iOS#1860]
I noticed that the nodes added since a few months in OSM and which contain the key wikimedia_commons=Category:abc are displayed in OsmAnd 4.1.1 as thumbnails without photo and which contain only the name of the file to display + WikiMedia Commons logo. When clicking on the thumbnails, the screen that opens and should show the photo informs that the file does not exist.
It should also be noted that the number of thumbnails displayed in OsmAnd corresponds to the number of photos that are stored in Wikimedia Commons for the node.

As far as the thumbnails are concerned, the name of the file appears truncated and therefore it is not possible to check whether it is correct. However, the numbers that appear after https://upload.wikimedia.org/wikipediacommons/thumb/ suggest that they do not seem to be correct when compared to the information of the photos stored in Wikimedia. The file name that follows these numbers looks correct. Is the error from Wikimedia or from OsmAnd?

Regarding the display or attempted display of a photo by clicking on a thumbnail, the file name that is accessed is visible and has 2x the prefix File: which is not correct. The file name with only one prefix File: would be the correct name. Is it OsmAnd that adds the 2nd prefix File: ? If so it would probably be easy to correct the error and the picture would be displayed.

OsmAnd 4.1.1
IOS 15.4.1

Screenshots of the node https://www.openstreetmap.org/node/9494934443 is showed as an example.

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/97670456/161517179-0711cf37-9648-47b9-8db2-3d986d2d0597.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/97670456/161517209-f0b98c96-e2ed-4bdd-946c-81eaffbe422e.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
iOS doesn't show image from `image` tag.
Wrong parsing of Wikimedia commons links.

<table style="width:100%">
  <tr>
    <th>First image from 'image' tag</th>
    <th colspan=2>Wikimedia commons image</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/202212300-f748d9c4-a3a8-4237-96ca-f213751ba25b.png"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/202212324-8a52801e-bcb0-4963-b053-40fd8324c553.png"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/202212342-895afc17-dace-4362-99a2-d14ec266ba7b.png"  width="200" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
@clwacker Hi!
Fix available in TestFlight build https://testflight.apple.com/join/7poGNCKy, and soon will be available in 4.3 release.

**Comment by clwacker** [comment]
Yes I have already seen that this morning in the last TestFlight build. Thanks a lot!

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2325
