### ISSUE TITLE
Crash and slow route calculation on iOS comparing to Android

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1863]
## Description
The application is crashing while calculating the route with a distance of 634 km, even if you add an intermediate point in the middle of the route.

OsmAnd 4.1.1 iphone X, iphone 13 Pro
Offline maps, updated 1.03.2022

## How to reproduce

Create navigation between points:
Start point: 49.46822 11.17391
Intermediate point: 52.15459 11.63342
Finish point: 53.55154 9.99385

In Tesflfight 4.2 the app is not crash but calculates a route for 17 minutes.

**Comment by anastasiia936** [comment]
The route 
Start: 50.10284 N. 10.99915 E
Finish: 46.4906700 N. 11.3398200 E

**Comment by alisa911** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/1966
https://github.com/osmandapp/OsmAnd-core-legacy/pull/91

**Comment by dmpr0** [comment]
TestFlight 4.2.1 (4.2.1.1)
iPhone XS Max, iOS: 15.4.1

Start: 50.10284 N. 10.99915 E
Finish: 46.4906700 N. 11.3398200 E
Time: 3 m 20 sec



Start: 50.10284 N. 10.99915 E
Intermediate point 48.20860° N, 11.64681° E
Finish: 46.4906700 N. 11.3398200 E
Time: 2 m 11 sec
