### ISSUE TITLE
Open the link shared via Osmand

### ISSUE THREAD

**Issue by abdullahO2** [osmandapp/OsmAnd-iOS#1865]
Hello
There is an issue with opening the link shared via Osmand like this link:
http://osmand.net/go.html?lat=28.18366&lon=41.62206&z=18
When we open the link and the application is closed, the program does not go to the site, and when you open it and the application is running in the background, the program will go to the site.

This problem is only present on the app on iOS while on Android everything works perfectly.

regards
Abdullah

**Comment by Skalii** [comment]
[Fix link opening](https://github.com/osmandapp/OsmAnd-iOS/pull/1871)

**Comment by abdullahO2** [comment]
thank you

**Comment by abdullahO2** [comment]
The problem is back with the latest version on ios 4.2
