### ISSUE TITLE
Add Speed limits widget and Warnings to Carplay

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1869]
It could be useful to be able to enable the speed limit widget in the CarPlay.

**Comment by Raphty** [comment]
Pleas do this!

**Comment by PaulStets** [comment]
Done
<img width="420" alt="Screenshot 2022-12-19 at 11 56 33" src="https://user-images.githubusercontent.com/20681525/208398598-2c0c69da-9fb7-4723-8b44-63a6af15ac18.png">

**Comment by Zirochkabila** [comment]
4.4.2.0
Done

<img width="691" alt="Screenshot 2022-12-21 at 12 10 44" src="https://user-images.githubusercontent.com/104760013/208879896-4c97059f-54dd-4cf8-82a1-26fe93304834.png">

**Comment by dmpr0** [comment]
Review https://github.com/osmandapp/OsmAnd-iOS/issues/2464
