### ISSUE TITLE
Crash during edit track

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#1875]
## How to reproduce

Open track -> Edit track (motorcycle profile)-> Add a few points (around 5-10)-> Press done->the app craches.
Tested on iPhone X with OsmAnd 4.1.1 and Testflight 4.2, with map updated from 1 Apr 2022. 
https://drive.google.com/file/d/1KYOtc7OOax9NPrk55FUeI88h6-ua5YUQ/view?usp=drivesdk
[2204 HU Mariposa.zip](https://github.com/osmandapp/OsmAnd-iOS/files/8496595/2204.HU.Mariposa.zip)

**Comment by PaulStets** [comment]
No longer reproducible. Probably was fixed with another issue

**Comment by vshcherb** [comment]
Missing info:
- Example of this track
- Approximate time frame when it was in beta or in production?
- Commit was fixed and commit was introduced
