### ISSUE TITLE
UI glitch in "3D" mode

### ISSUE THREAD

**Issue by leochras** [osmandapp/OsmAnd-iOS#1919]
OsmAnd v4.2.0.13 in iOS 15.4.1

There's a black bar on the horizon, and the measure tool goes beyond it. Maybe there should be a border for the measure tool.

![OSmandGlitch](https://user-images.githubusercontent.com/16163571/166200294-c6f4b600-a844-42ce-9829-2b2821f823ea.jpeg)

The black bar also resizes when moving the angle

https://user-images.githubusercontent.com/16163571/166201894-f589d7c3-8fd0-4fae-8a39-d50169192a02.mp4

**Comment by dmpr0** [comment]
iPad Air

<img src="https://user-images.githubusercontent.com/9365308/167900386-063b48ca-1f2d-4519-8e86-a35ef197156d.PNG"  width="600" height="auto"/> 

<img src="https://user-images.githubusercontent.com/9365308/167900411-8306cd38-517d-4d3d-bc53-43e66891d9a0.PNG"  width="600" height="auto"/>

**Comment by alexey-pelykh** [comment]
It's happening when a (non-uniform?) scale is applied to the viewport if "Display position is always in center" is turned off

**Comment by Zirochkabila** [comment]
### Description
When displaying the map in 2.5d mode, the upper part of the map is displayed in blue

### Steps to reproduce
Display the map in 2.5d

### Actual result
The upper part of the map is displayed in blue
[RPReplay_Final1655111900.mov.zip](https://github.com/osmandapp/OsmAnd-iOS/files/8890247/RPReplay_Final1655111900.mov.zip)


### Expected result
The map is all displayed 


### Your Environment
OsmAnd Version: 4.2.2
Android/iOS version: iOS 15.2
Device model: iPad mini 4

**Comment by dmpr0** [comment]
https://github.com/osmandapp/OsmAnd-iOS/issues/1710

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/b5f8f53c591977519fd8ec58ce3069e9c23ec932
https://github.com/osmandapp/OsmAnd-iOS/commit/51d35103f923476105064922b3a50c7b41fa9bc3

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd/commit/ce8e2e2bfe8c160d21997a1670ff83d1a6f0116e
https://github.com/osmandapp/OsmAnd/commit/b5f8f53c591977519fd8ec58ce3069e9c23ec932

https://github.com/osmandapp/OsmAnd-iOS/commit/26c89f39847705f28929104b185fb1c4e5827907

**Comment by leochras** [comment]
Seems to be fixed, thanks 👍
