### ISSUE TITLE
Add to Download Maps -> Local access to rendering styles & routing files

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#1920]
Main purpose of this request to be able to rename & delete these files.

https://github.com/osmandapp/OsmAnd/issues/14178

**Comment by dmpr0** [comment]
Done by implementing visibility of OsmAnd data in system **Files** app.
<img src="https://user-images.githubusercontent.com/9365308/173786293-ab5bb716-e728-4049-a220-4dd44810e1a2.jpeg"  width="250" height="auto"/> 

### Map style
<table style="width:100%">
  <tr>
    <th>After import</th>
    <th>Renamed</th>
    <th>Renamed</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/173785879-68795de2-9ce4-479f-b473-68d13671d658.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/173785887-48bed815-4113-4f50-bd8c-d29bdbca2de0.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/173785883-d933795b-46f9-47f2-a256-d218461e97df.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>  

### Routing file
<table style="width:100%">
  <tr>
    <th>After import</th>
    <th>Renamed</th>
    <th>Renamed</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/173786419-2fc59d67-0891-475f-8817-bcfaa2cd28ea.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/173786238-c0018d80-ae05-4047-8531-85e4b54e792b.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/173786473-7b7c7cac-22fe-4674-aa8f-1d4276ce8319.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>
