### ISSUE TITLE
Redo bottom sheets: reset to default, open wikipedia using system UI

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1947]
# ToDo
## Reset to default
- [x]  Redo to system alert. [Figma](https://www.figma.com/file/hDV38Vox3pSU6cGgPlOFmu/Settings?node-id=1725%3A49531&t=fkH6RvbNLZrD8Whn-1)
<table style="width:100%">
  <tr>
    <th>Current</th>
    <th>New</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/167871611-86880a30-4378-4e3a-84ac-77e7433b8402.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/212114255-2dc9114d-d0f2-4cb1-98cf-b0059ab2a477.png"  width="300" height="auto"/> </td>
  </tr>
</table>

## Wikipedia
- [x]  Redo as action sheet. [Figma](https://www.figma.com/file/EBH9oaJaJxCqrdLMZkAcAh/Context-menu?node-id=1805%3A34533&t=HnWXQVHCXdPd2k2D-1)
<table style="width:100%">
  <tr>
    <th>Current</th>
    <th>New</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/167871599-4efe9ab8-5944-47e9-9e4d-0112467bda1c.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/212115662-bc001596-8408-4d97-a174-9662f2e8684f.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2490

**Comment by Zirochkabila** [comment]
05.02.2023 Master branch - **Done**
