### ISSUE TITLE
Download map menu is under the status bar on iPad

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1949]
Download map menu under the status bar on iPad on both portrait and landscape mode.
TestFlight 4.2.0.16
- [x]  Fix download map dialog position

<img src="https://user-images.githubusercontent.com/9365308/167901146-050f9875-a677-45a1-8bae-b7f71d8f6758.PNG"  width="600" height="auto"/> 
<img src="https://user-images.githubusercontent.com/9365308/167901165-cd85ca05-5b2a-4ed5-95de-f92db91f507b.PNG"  width="auto" height="600"/>

**Comment by Skalii** [comment]
[Fix downloadMapWidget position](https://github.com/osmandapp/OsmAnd-iOS/pull/1958)
