### ISSUE TITLE
[Feature Request] Add option to disable the green map-downloads overlay

### ISSUE THREAD

**Issue by martinbrieger** [osmandapp/OsmAnd-iOS#1955]
I use OsmAnd on my iPad Pro and my M1-MacBook as my personal world atlas. Currently I have around 100GB of local maps covering most countries (including reliefs).
OsmAnd does a fantastic job and I am more than happy with the performance and possibilities!
However, what really annoys me is the green overlay indicating which map I downloaded. Because I have most countries, the whole map looks green even from a pretty zoomed-in view. This kinda ruins the whole atlas-experience as you can see below:
<img width="1194" alt="grafik" src="https://user-images.githubusercontent.com/49117740/168467452-b23f34f2-f9c5-4c9b-abb9-038c457843ce.png">
<img width="1194" alt="grafik" src="https://user-images.githubusercontent.com/49117740/168467502-56a4ceba-94ba-441f-97ab-4930213feac7.png">

I already tried adjusting the zoom-level of the map which leads to the green overlay appearing later during zoom-in, but this doesn't solve the issue and leads to worse performance.

**It would be great if you could implement an option to simply disable the green map-overlay.**

Thanks in advance!

PS: And yes I know OsmAnd is not supposed to be a world atlas 😎

**Comment by drtbyk** [comment]
Another vote for this Option request. Planning long cross-continent trips is rather frustrating with the green-overlay.

**Comment by dmpr0** [comment]
Similar Android task https://github.com/osmandapp/OsmAnd/issues/15011

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2329

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2329
