### ISSUE TITLE
Can not find a street when entering its name with the sign "-"

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#1964]
### Description
When user to find a street called "Ferdinand-Alzer-Straße" in the municipality of Lennestadt, Germany (this street exists on the map in a normal manner with exactly this name) user typed it in in exactly this way but they did not get any results. Then user typed it in without the hyphens (namely "Ferdinand Alzer Straße") and the algorithm instantly found it.

On android device street name can be found.
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/169342916-5bdd71de-0c46-4910-b6fd-7a4d6cf10684.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Steps to reproduce

1. typed "Ferdinand-Alzer-Straße" in search line

### Actual result
The street not displayed in found

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/169301243-92780579-2eec-4ba1-8c65-34427f54e5fd.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/169301428-f0e63999-a4ef-4983-be3a-6006071f6b6b.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Expected result
The street is shown in the found

### Your Environment
OsmAnd Version: 4.2.0
Android/iOS version: iOS 15.2
Device model: iPad

**Comment by vshcherb** [comment]
Android is searching fine

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/1973
