### ISSUE TITLE
fire_hydrant:position not shown in details

### ISSUE THREAD

**Issue by breucode** [osmandapp/OsmAnd-iOS#1965]
In the details of a fire hydrant, the position is not shown. In the Android app, this information is displayed.

It would be nice to have this information in the details, so it is easier to locate hydrants.

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback. 
What version of OsmAnd are you using? 
Could you please provide coordinates for one of these POI?

We have fixed issues with the details list in the POI context menu, it will be available in 4.2

**Comment by breucode** [comment]
Thanks for the quick reply. I just updated to 4.2 and the issue is gone. Thanks for the help and the great app :)
