### ISSUE TITLE
Blue artefacts on the coast and land of Tenerife when working with the zoom

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#1968]
### Description
When working with the zoom on the island appear blue artefacts in the form of lines and squares
https://osmandhelp.zendesk.com/agent/tickets/37741

### Steps to reproduce

1. Open these coordinates

28.04427° N, 16.54868° W
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/169522697-43e193d5-5667-465e-8874-458efb31cda6.PNG"  width="300" height="auto"/> </th>
  </tr>
</table> 

28.06675° N, 16.70878° W
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/169522718-406ba47d-05a0-4863-8d7b-bb43278e3597.PNG"  width="300" height="auto"/> </th>
  </tr>
</table> 

28.15993° N, 16.82074° W
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/169522734-1832d791-2c83-4f59-bb1b-42e10bff2964.PNG"  width="300" height="auto"/> </th>
  </tr>
</table> 

28.35871° N, 16.90820° W
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/169524438-80dffd35-9aca-4945-9aa4-9703f79df158.PNG"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Actual result
The user observes bugs on the shoreline of the island, the sea zone and the land

### Expected result
The user observes a map of the island according to its real appearance

### Your Environment
OsmAnd Version: 4.2.0
Android/iOS version: iOS 15.2
Device model: iPad mini 4

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/14333
