### ISSUE TITLE
Application unusable since update 4.2

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#1971]
Hello,
Following the update to 4.2, the application is unusable. 
-The application is constantly frozen 
-The registration of trace beug enormously. 
-The application is very slow to open as well as to use
iPhone 11 pro iOS 15.5 Osmand 4.2
![image](https://user-images.githubusercontent.com/79785663/170003722-501820b9-ad39-43a7-b376-3ab8373b011f.png)![image](https://user-images.githubusercontent.com/79785663/170003752-77369b2d-b281-4d41-bdb7-d79ff0aa858c.png)

**Comment by vshcherb** [comment]
This is particularly strange as the map rendering engine was not updated in 4.2.

**Comment by Hades1503** [comment]
This could happen rarely. now it's systematic... even without using the app much

**Comment by vshcherb** [comment]
We've noticed 1 bug when app remains completely frozen with using sqlite files, so I think we're going to fix it.

**Comment by PaulStets** [comment]
Should be fixed in the next TestFlight build.
