### ISSUE TITLE
Online map download does not work 4.2

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#1972]
It doesn't work with all online maps

iPhone 11 pro iOS 15.5 Osmand 4.2

<table style="width:100%">
  <tr>
    <th><img src="https://user-images.githubusercontent.com/79785663/170006232-d3cd0aae-a312-45ab-8209-5772486dc4f7.png"  width="300" height="auto"/> </th>
    <th><img src="https://user-images.githubusercontent.com/79785663/170006452-23514c07-21a3-43e6-b802-1ab69a45479c.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by StrikeLines** [comment]
Adding here since it seems to be related: 
We are no longer able to display imported sqlitedb raster layers in version 4.2. Osmand appears to recognize the filetype, but raster layers will not display as overlays or underlays since the 4.2 update.

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-iOS/pull/1976
