### ISSUE TITLE
Save button under home indicator

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1974]
## ToDo

- [x]  Increase **Save** button height. The button should be inside a safe area.
- [x] If the keyboard is open, the button should be above it.
 
<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/170207545-461e93d1-0549-4deb-86c2-b10c97299fc6.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/170207548-62e78415-3eef-4673-9af0-5203d0c56afe.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Skalii** [comment]
[Fix Search - Save button for custom POI](https://github.com/osmandapp/OsmAnd-iOS/pull/2001)
