### ISSUE TITLE
Route construction error when using the pedestrian profile.

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#1978]
### Description
Route construction error when using the pedestrian profile (and bicycle too).
https://osmandhelp.zendesk.com/agent/tickets/37789

### Steps to reproduce

1. Navigation
2. Pedestrian profile
3. Starting point
4. Destination

### Actual result

Route construction error 

48.86747,8.94900

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/170233182-462d1209-7600-4e3c-bd56-478a51d7e242.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Expected result

Route construction righte

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/170233576-d358c3f1-c48f-470f-9d68-743c621fa6fd.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table> 

### Your Environment
OsmAnd Version: 4.2.1
Android/iOS version: iOS 15.2
Device model: iPad

**Comment by vshcherb** [comment]
Please recreate ticket with guidelines .
