### ISSUE TITLE
Remove dialog for downloading "World overview map"

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#1986]
# ToDo
OsmAnd on iOS is still prompted to download the "World Overview Map". This is now unnecessary as we are distributing a mini version of the "World Overview Map" with the build.

- [x]  Remove dialog.

<img src="https://user-images.githubusercontent.com/9365308/170978943-2f3bef41-9dd6-4cdd-8c9d-a6ae6078d63f.jpg"  width="300" height="auto"/>

**Comment by Skalii** [comment]
[Remove World base download dialog](https://github.com/osmandapp/OsmAnd-iOS/pull/2177/files)
