### ISSUE TITLE
Customize route line menu format glitch

### ISSUE THREAD

**Issue by barteis** [osmandapp/OsmAnd-iOS#1990]
4.2-iOS; iPhone 13 Mini

This is minor, but could be a problem for new users: the menu at Navigate / Customize route line cuts off the "Apply" option at the top right.  At least on my phone in English.  See screenshot.

![Screen glitch](https://user-images.githubusercontent.com/36173950/171044134-af1851e7-500f-4342-a923-28e729fe938f.jpg)

**Comment by Skalii** [comment]
[Fix Route line Appearance - navigation bar width](https://github.com/osmandapp/OsmAnd-iOS/pull/2019)
