### ISSUE TITLE
[help request] Bluetooth Keyboard - no reaction

### ISSUE THREAD

**Issue by Dennis650** [osmandapp/OsmAnd-iOS#2000]
Hello everyone, 
I'm currently playing with Arduino and would like to control the great OsmAnd-App on iOS with BLE (Motorcycle). I selected the keyboard as an external device in the OsmAnd profile.
I try to use arrows-keys to move the map section left, right, up and down and also to zoom. Unfortunately, OsmAnd does not respond to keyboard input. However, other iOS apps such as "Notes" are responsive.
Can you give me a hint what I might have to adjust or what I'm doing wrong? Greetings Dennis

**Comment by vshcherb** [comment]
It's not supported yet by OsmAnd on iOS. We're going to implement it here https://docs.osmand.net/docs/user/map/interact-with-map#external-input-device-buttons

**Comment by DennisRieg** [comment]
Thank you very much! This will be a great feature for motorcyclists.

**Comment by joostbijl** [comment]
Looking forward to this feature for iOS users of https://jaxeadv.com/barbuttons/

**Comment by alex-osm** [comment]
https://developer.apple.com/documentation/uikit/mac_catalyst/handling_key_presses_made_on_a_physical_keyboard?language=objc

**Comment by dmpr0** [comment]
## ToDo
- [ ]  Add support for basic key presses, similar to Android https://docs.osmand.net/docs/user/map/interact-with-map#external-input-device-buttons-android

**Comment by dmpr0** [comment]
Tested, all basic keys working. 
Available in TestFlight 4.4.6.9

Button | Action
-- | --
C | "My location"
D | "Map orientation"
↑ | Move up
↓ | Move down
← | Move left
→ | Move right
"+" | Zoom in
"-" | Zoom out
