### ISSUE TITLE
Street name widget doesn't show turn direction

### ISSUE THREAD

**Issue by barteis** [osmandapp/OsmAnd-iOS#2014]
Version 4.2.2
I'm not sure if this is a bug or a "Nice to have", but it would be nice if the  Street name widget (from Configure screen) showed the turning direction, as it does in the Android version.  Instead, the yellow arrow points up seemingly in all cases, indicating "straight ahead".  In the attached image, the Next turn widget is correct. Voice navigation was too.  Thanks!    

![IMG_0818](https://user-images.githubusercontent.com/36173950/172938512-f463f6f4-ffff-49ae-9598-b922d2de6129.jpg)

**Comment by vshcherb** [comment]
It's a bug cause we want to have consistent behavior with Android

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2057

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2075

**Comment by nnngrach** [comment]
synced code with android

**Comment by ivanPyrohivskyi** [comment]
48.14031 11.52831
48.14510 11.54127

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/101
