### ISSUE TITLE
Blinks when recording track at each new point

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2017]
### Description

Regression

Blinking of the recorded track at each new track point
https://osmand.net/map?start=50.436075%2C30.506189&end=50.439461%2C30.501981&pin=50.436561%2C30.505503&mode=bicycle

### Steps to reproduce
Start navigation -> Select point of departure 50.43607, 30.50619 -> Select destination 50.43946, 30.50198 -> turn on Simulate navigation -> press Start -> press Rec

### Actual result
Blinking of the recorded track at each new track point
[RPReplay_Final1654871596.mov.zip](https://github.com/osmandapp/OsmAnd-iOS/files/8879818/RPReplay_Final1654871596.mov.zip)

### Expected result
When recording the track the track remains stable

### Your Environment
OsmAnd Version: 4.2.2
Android/iOS version: iOS 15.2
Device model: iPad mini 4

**Comment by PaulStets** [comment]
FYI, regression is when something that used to work correctly doesn't work anymore. The recording track always blinked before, so it's not an example of regression.
