### ISSUE TITLE
Map freezes when zooming in

### ISSUE THREAD

**Issue by fnuttens** [osmandapp/OsmAnd-iOS#2020]
I systematically encounter this bug since version 4.2.

If I zoom in too close, the app stops rendering, basically.

https://user-images.githubusercontent.com/8812165/173207377-f044ce29-27c3-491e-8352-602b773368e1.MOV

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd/issues/14483 will be fixed
