### ISSUE TITLE
Speed in Realistic simulation mode is greater than maximum allowed speed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2023]
### Description
In Motorcycle navigation mode, the upper part of the map is displayed in blue (the navigation in this mode uses 2.5d https://github.com/osmandapp/OsmAnd-iOS/issues/1919#issuecomment-1153748856), speed in Realistic simulation mode is displayed like a top speed
https://osmand.net/map?start=50.454751%2C30.445358&end=50.448760%2C30.480865&pin=50.436561%2C30.505503&mode=car#16/50.4521/30.4552

### Steps to reproduce
Select Motorcycle profile -> Set Start position 50.45475, 30.44536 -> Select Destination 50.44876, 30.48086 -> Option -> Simulate navigation -> Realistic mode -> Start navigation

### Actual result
In Motorcycle navigation mode, the upper part of the map is displayed in blue, speed in Realistic simulation mode is displayed like a top speed 
[RPReplay_Final1655113811.mov.zip](https://github.com/osmandapp/OsmAnd-iOS/files/8890473/RPReplay_Final1655113811.mov.zip)

### Expected result

Speed in Realistic simulation mode is displayed like realistic

### Your Environment
OsmAnd Version: 4.2.2
Android/iOS version: iOS 15.2
Device model: iPad mini 4

**Comment by Zirochkabila** [comment]
The bug is still present on OsmAnd version 4.2.4, released: 2022-06-15

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/174614513-260a5889-103f-44e7-beee-812567406ff1.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2042
https://github.com/osmandapp/OsmAnd/pull/14593

**Comment by ivanPyrohivskyi** [comment]
No need to move to r4.2
