### ISSUE TITLE
The buttons of activation profile was stuck

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2024]
### Description
Profile activation buttons is stuck (Truck, Motorcycle, Truck, Motorcycle)

### Steps to reproduce
Menu -> Settings -> turn on Motorcycle button

### Actual result
The button is stuck
https://user-images.githubusercontent.com/104760013/173351390-3393abd8-c422-4a27-9460-40a8cadc4f06.MP4

### Expected result
Switches respond on tap

### Workaround

??? 

### Your Environment
OsmAnd Version: 4.2.2
Android/iOS version: iOS 15.2
Device model:  iPad mini 4

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-Issues/issues/154
