### ISSUE TITLE
Changing the route during construction 

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2025]
### Description
Changing the route during construction 
https://osmand.net/map?start=46.788777%2C11.949692&end=46.591900%2C15.676117&pin=50.436561%2C30.505503&mode=car#8/46.300/14.568

### Steps to reproduce
Select start point 46.78878, 11.94969 -> Select Destination 46.59190, 15.67612 -> press Start button

### Actual result
Changing the route during construction 
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/173374662-e85f972d-8109-408e-891c-0275f09f889c.PNG"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The route is builds

### Your Environment
OsmAnd Version: 4.2.2
Android/iOS version: iOS 15.2
Device model: iPad mini 4

**Comment by vshcherb** [comment]
As I see on screenshot maps are not downloaded so not clear if there is a problem. Dialog of missing maps during routing is not implemented on iOS yet.
