### ISSUE TITLE
Road signs for Canada: Railway crossing, Speed limit

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2031]
Follow up https://github.com/osmandapp/OsmAnd/issues/9192

## ToDo
While navigating in Canada show Canadian road signs for **Speed limit** and **Railway crossing**.

- [x] Speed limit
- [x] Railway crossing

Resources: [Canada_Roadsigns.zip](https://github.com/osmandapp/OsmAnd-iOS/files/8908248/Canada_Roadsigns.zip)

**Comment by Skalii** [comment]
[Road signs - add new for Canada](https://github.com/osmandapp/OsmAnd-iOS/pull/2049)
