### ISSUE TITLE
Searching city doesn't work in "Download maps"

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#2032]
# Review
Tested on 4.2.3
- [x]  Downloaded World base map, doesn't affect on search results.

<table style="width:100%">
  <tr>
    <th colspan=2>Android</th>
    <th colspan=2>iOS</th>
  </tr>
  <tr>
    <th>Mini basemap</th>
    <th>World basemap</th>
    <th>Mini basemap</th>
    <th>World basemap</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/176639231-65a34b72-7233-4087-8a18-587550252962.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/176639241-d2c641de-b5c7-4ee2-a2ee-aeb50007b032.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/176639017-77d4b3ca-61d6-4271-a8d4-35bb721cf128.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/176639017-77d4b3ca-61d6-4271-a8d4-35bb721cf128.jpg"  width="300" height="auto"/> </td>
  </tr>
</table> 

# ToDO
https://github.com/osmandapp/OsmAnd/issues/14470

**Comment by Skalii** [comment]
[Resources - search by basemap/mini (iOS)](https://github.com/osmandapp/OsmAnd-iOS/pull/2045)
[Resources - search by basemap/mini (core)](https://github.com/osmandapp/OsmAnd-core/pull/336)

**Comment by Skalii** [comment]
[Fix cities search](https://github.com/osmandapp/OsmAnd-iOS/pull/2235)

**Comment by Zirochkabila** [comment]
4.3.0.20 
**The main problem is solved**
But if there is a space after the city name, the city is not displayed in the search. Looks like [14470](https://github.com/osmandapp/OsmAnd/issues/14470#issuecomment-1152312814)

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/196725148-09a41466-9997-4fa4-bdca-5ec01ac8844e.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Skalii** [comment]
[Resources - trim search text](https://github.com/osmandapp/OsmAnd-iOS/pull/2249)
