### ISSUE TITLE
GPX Waypoints : <link> tags not taken into account

### ISSUE THREAD

**Issue by LucasLf** [osmandapp/OsmAnd-iOS#2039]
Hi,

I have a GPX file with waypoints which include "link" tags but it seems not to be managed by the iOS version.
I have test tested the two syntaxes below but none of them works : 
```
<link href="https://www.test.io" />
```
```
<link>https://www.test.io</link>
```
I am not sure if it is a bug or kind of a new feature request. 

Thanks,

**Comment by vshcherb** [comment]
Should be working now

**Comment by vshcherb** [comment]
Documentation - https://osmand.net/docs/user/personal/tracks/#add-waypoint
1. Add subsection "Display custom GPX tags" - link / others + screenshot - *not editable in OsmAnd - link / cmt and other all extensions
2. 'Waypoint format description' -> 'Waypoint in GPX file'. Create waypoint - look all tags and describe: category / time / ... 
3. Move 'Add waypoint' to level 1 (now level 2)
