### ISSUE TITLE
Compass: add "Always" hidden mode

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2046]
Android task https://github.com/osmandapp/OsmAnd/issues/14649
 
## ToDo
In the current implementation of the compass button, it has two modes: **On** or **Off**, by off means **Visible if map is rotated**. We need to add a third option - [ ] **Always hidden**.
Icons: [compass-icons.zip](https://github.com/osmandapp/OsmAnd-iOS/files/9010736/compass-icons.zip)

Make 3 options:
- [x]  **Always visible**
- - [x] Icon `ic_action_compass_north`
- [x] **Always hidden**
- - [x] Icon `ic_action_compass_hidden`
- [x] **Visible if map is rotated**
- - [x] Icon `ic_action_compass_rotated`
- - [x] Selected by default

<table style="width:100%">
  <tr>
    <th>Configure Screen</th>
    <th>Compass</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/176440154-a39fa29c-15ae-4379-98ce-bc11da1c5945.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/176440175-0052f1d3-0afc-47e7-8e5f-95d6243b86d6.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Skalii** [comment]
[Compass options](https://github.com/osmandapp/OsmAnd-iOS/pull/2062)
