### ISSUE TITLE
The App kills CarPlay every 2 or 3 minutes when using OsmAnd navigation

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2058]
### Description
The App kills CarPlay every 2 or 3 minutes when using the Live version of the OsmAnd 

### Steps to reproduce
Start CarPlay 

### Actual result
The CarPlay is turned off

### Expected result
The CarPlay continues to work

### Your Environment
OsmAnd Version: 4.2.2
Android/iOS version: iOS 15.5
Device model: iPhone 12

**Comment by vshcherb** [comment]
Not reproduced
