### ISSUE TITLE
While OsmAnd navigation is running (Live updates are used), the built-in radio is turned off 

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2059]
### Description
While running OsmAnd Live version built-in radio is muted

### Steps to reproduce
Start CarPlay with the radio on 

### Actual result
The built-in radio is turned off

### Expected result
The built-in radio continues to work

### Your Environment
OsmAnd Version: 4.2.2
Android/iOS version: iOS 15.5
Device model: iPhone 12

**Comment by dmpr0** [comment]
Could be related https://github.com/osmandapp/OsmAnd-iOS/issues/1599

**Comment by vshcherb** [comment]
How OsmAnd Live related to builtin radio, it looks rather confusing detail than comprehensible.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd-iOS/issues/1599
