### ISSUE TITLE
The Mapillary layer is displayed on the map after turning off the Mapillary plugin

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2061]
### Description
The Mapillary layer is displayed on the map after turning off the Mapillary plugin

### Steps to reproduce
Menu > Plugins > Mappilary > on > Configure map > Street-level imagery > Enabled > Menu > Plugins > Mappilary > off

### Actual result
The Mapillary layer is displayed on the map 
https://drive.google.com/file/d/10xxtu72GgrVMpl2tC10kBDWoAnwtTrD3/view?usp=sharing

### Expected result
The Mapillary layer is undisplayed on the map

### Your Environment
OsmAnd Version: 4.2.2
Android/iOS version:  iOS 15.5
Device model: iPad mini 4

**Comment by DmitrySvetlichny** [comment]
#2277
