### ISSUE TITLE
When you switch between user maps, the map is no longer displayed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2066]
### Description
When you switch between user maps, the map is no longer displayed
After a few switches (on average after 3-4 or more, but sometimes two times is enough), the maps simply cease to be displayed, only a layer in a cell with crosses
https://drive.google.com/file/d/1yP82zaXM9jsGNxbxy20uSzuh-MQzt7vu/view?usp=sharing
https://drive.google.com/file/d/1W25I9XgzvrwQYTeFPRBNwo7HTT9le4HO/view?usp=sharing

### Steps to reproduce
Configure map > Map type > chose "bigfile.cc" > chose "chornobyl zone" (Repeat switching between cards as many times as needed (5 or more))

### Actual result
The map is no longer displayed

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/177531223-8ab4d2a0-6753-4197-a0cb-e5d5f6c03f74.PNG"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/177531268-2f811bbb-ed32-4243-9f80-bfc3dfe3f050.PNG"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The map is displayed

### Your Environment
OsmAnd Version: 4.2.2
Android/iOS version: iOS 15.5
Device model: iPad mini 4

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/03ed6c0cb0cc282fd4ae1f7da6c6b74c1d420e41
https://github.com/osmandapp/OsmAnd-core/commit/8f9d54ed577f2b47095732348280e6bdf92974e3
