### ISSUE TITLE
"Shortcuts" when navigating with a GPX

### ISSUE THREAD

**Issue by barteis** [osmandapp/OsmAnd-iOS#2067]
Similar to [#11235 in the Android version ](https://github.com/osmandapp/OsmAnd/issues/11235), which was closed in 6/21.  The shortcutting seems to arise only when navigating to the Nearest point.  Navigating to the Start of the track works fine.  

![IMG_0869](https://user-images.githubusercontent.com/36173950/177664117-d31e6502-b82d-4bf4-b21c-95d25518c646.png)

**Comment by Zirochkabila** [comment]
> 

Please describe in detail the steps for reproducing

**Comment by barteis** [comment]
I see it frequently while navigating GPXs I've created with Plan a route on curvy hiking trails. I don't know whether you can reproduce without actually doing the same, or whether it can be simulated.  

o Use Plan a route to create a GPX using Walking to calculate the route between points.  
o Use that GPX to navigate.  
o Look for places where the GPX has "shortcutted" the route.  These section  will eventually correct as you traverse them, but in the meantime, they artificially reduce the estimated distance and of course are imprecise.

See also this conversation on the same topic in the Android version with @vshcherb at [Osmandpp/OsmAnd  #11174](https://github.com/vshcherb).
Here's[ the GPX I created and used as seen in  the screenshot](https://drive.google.com/file/d/1IHgDXDninCcPZvsiZIZ01sAaZqrt3VFa/view?usp=sharing).

Thanks.

**Comment by Zirochkabila** [comment]
> 

Your case was tested on an Android device and on an iOS device - it could not be reproduced (exactly the scenario that you described above).
But, I was able to find other errors - there is a possibility that they are related to what you see. 
That's why the bug report was created https://github.com/osmandapp/OsmAnd-iOS/issues/2068

**Comment by barteis** [comment]
Thanks Anatolii.  [#2068](https://github.com/osmandapp/OsmAnd-iOS/issues/2068) better describes what I'm seeing.
