### ISSUE TITLE
lost water, road and routes Cycling

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#2073]
hello, 

there are many problems displaying roads, routes and water.

Route bicycle
![image](https://user-images.githubusercontent.com/79785663/178107367-f7bc685d-2718-42fb-adbd-1774f7d2de34.png)
![image](https://user-images.githubusercontent.com/79785663/178107381-f40df0f7-37eb-4c71-877e-1e2767f164bc.png)

Road
![image](https://user-images.githubusercontent.com/79785663/178107420-6d672537-b648-4216-a3d2-fe0f2783ab28.png)![image](https://user-images.githubusercontent.com/79785663/178107435-bbde5d69-85fa-4c68-aabf-469423ea5e54.png)
![image](https://user-images.githubusercontent.com/79785663/178107451-58eaa4a9-637f-4232-8465-caf28bf531d7.png)![image](https://user-images.githubusercontent.com/79785663/178107460-bfba6848-ef75-4bb1-a2d2-47cbbf57973d.png)

Water
![image](https://user-images.githubusercontent.com/79785663/178107537-abb5b992-6542-496f-ab82-4d5159c45cb9.png)![image](https://user-images.githubusercontent.com/79785663/178107554-856a31a2-c848-4328-9d42-ad95956d5070.png)![image](https://user-images.githubusercontent.com/79785663/178107564-2d5154b0-9efe-4cf6-8c01-84864b8655df.png)![image](https://user-images.githubusercontent.com/79785663/178107581-f8b6aa73-28b6-46c8-bcb8-91d910d0ccbc.png)

iPhone 11pro iOS 15.5 Osmand 4.2.3

Use Osmand style (défault) and my custom render https://github.com/Hades1503/OsmAnd_Cycling_Map

**Comment by vshcherb** [comment]
Please open separate issue for water and road you can also make screenshots smaller by  using custom xml 
```
<img src="https://user-images.githubusercontent.com/79785663/178107381-f40df0f7-37eb-4c71-877e-1e2767f164bc.png" width="25%" />
```
<img src="https://user-images.githubusercontent.com/79785663/178107381-f40df0f7-37eb-4c71-877e-1e2767f164bc.png" width="25%" />
