### ISSUE TITLE
app crashing

### ISSUE THREAD

**Issue by Hades1503** [osmandapp/OsmAnd-iOS#2079]
I regularly have the app crashing for no apparent reason.

https://youtube.com/shorts/H3oo7iRBXiY?feature=share

![image](https://user-images.githubusercontent.com/79785663/178521722-934b1dc9-66ad-41c5-8e56-6a9516ed2ea6.png)![image](https://user-images.githubusercontent.com/79785663/178521800-22dc2e5f-a54f-4f20-868d-8c94a77480fc.png)

I did not activate the Osmand live option (even if I took the subscription) to see if that was what made it crash. it still hangs...

the application is not usable as is.

I downloaded the whole of France + level curves + shading + slope = ~10Go
I have 4GB of storage left on the phone so it's not due to a lack of storage.

even by resetting the application, uninstalling, etc nothing helps.

iPhone 11pro 
iOS 15.5
OsmAnd 4.2.3

**Comment by juliusvaart** [comment]
I can confirm same rendering issues. 

OsmAnd 4.2.3
iOS 15.5
iPhone Xs

**Comment by vshcherb** [comment]
Merged to this https://github.com/osmandapp/OsmAnd-iOS/issues/2066. And another issue is already fixed https://github.com/osmandapp/OsmAnd/issues/14483
