### ISSUE TITLE
Map lost after few zoom in/out

### ISSUE THREAD

**Issue by wiivanil** [osmandapp/OsmAnd-iOS#2081]
After making some zoom in and out the map disappear. I have to close OsmAnd and reopen it to view the map again. But the problem continue to happen when I zoom.

In the video you can see the problem at 0:20

https://user-images.githubusercontent.com/19471063/179682556-1ec3b655-6d16-41ca-944f-572a9b9073cc.MOV

![image](https://user-images.githubusercontent.com/19471063/179677654-80072818-14e1-4f36-aeb8-d4eeed50f599.png)

**Comment by wiivanil** [comment]
Do you know when the update will be available?
Thank you

**Comment by vshcherb** [comment]
Already available for 20% - tomorrow 100%
