### ISSUE TITLE
Crash on exporting profiles

### ISSUE THREAD

**Issue by juliusvaart** [osmandapp/OsmAnd-iOS#2084]
settings > backup into file

It only works with the “Overview” profile. All my other profiles crash the app.

iPhone Xs
iOS 15.5
OsmAnd 4.2.4

**Comment by Zirochkabila** [comment]
4.3.0.13 **Not reproduced**

**Comment by juliusvaart** [comment]
Still getting the crash when exporting profiles.

Now with:

- iPhone 13 Pro
- iOS 16.0.3
- OsmAnd Testflight 4.3.0.16

**Comment by Zirochkabila** [comment]
@juliusvaart Please send your profiles for checking

**Comment by juliusvaart** [comment]
Exported the profiles one by one and have two that crash the app. Walking and Offroad.

Can’t export these, so made screenshots from my walking profile.

https://www.dropbox.com/s/2ed7khtdk51hmz5/OsmAnd-walking-profile.zip?dl=1

**Comment by juliusvaart** [comment]
I’ve reset the Offroad profile, and can export it now.

**Comment by Zirochkabila** [comment]
@juliusvaart  Is, the problem solved, and the issue can be closed?

**Comment by juliusvaart** [comment]
Also reset the Walking profile. And can export all. So maybe it was just an error somewhere in my configuration. Thanks for the attention to my issue!
