### ISSUE TITLE
OsmAnd UI creates wrong  opening hours

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd-iOS#2087]
### Description
See the attached picture.  OSMAnd correctly shows the opening hours but then wrongly decides that the facility is closed

OSM:
https://www.openstreetmap.org/way/1080674336

opening hours: Mo-Su 5:00 AM-9:00 PM

![1FAD64E2-A9E3-4AA3-8B68-3C30B8680614](https://user-images.githubusercontent.com/609677/181066939-9c8d51ea-2e85-4ecc-b742-5ae03524262f.jpeg)

### Your Environment
OsmAnd Version: 4.2.4
Android/iOS version: iOS 15.5
Device model: iPhone XR

**Comment by vshcherb** [comment]
To test: If you create new POI with opening hours, it should always use 24H format regardless System settings

**Comment by Zirochkabila** [comment]
4.3.0.28
Not Reproduced
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/200875536-ec44fd99-352b-4b17-afcd-a620a2c45cdf.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by scaidermern** [comment]
So at least since July OsmAnd writes wrong opening hours to OSM, if not even longer? Why don't get serious bugs like this one a higher priority?

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/commit/f38fee531f110239676730ba9bd517002c097fca

**Comment by scaidermern** [comment]
Thanks for the fix.

Is there a plan to fix the POIs that have been wrongly tagged by OsmAnd?

**Comment by vshcherb** [comment]
probably no, as usual it would be good just to have common validator against all values Opening Hours. So AM/PM is not only error and OsmAnd is not only source of error in opening hours.

**Comment by Zirochkabila** [comment]
4.4.1.3
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/207529175-8a78a014-225a-43fc-bcaa-f85d2c92d353.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
Done, tested on this point https://www.openstreetmap.org/node/9680230313
