### ISSUE TITLE
<renderingAttribute name="route" > no opacity

### ISSUE THREAD

**Issue by FriedelXT** [osmandapp/OsmAnd-iOS#2088]
Hello,

Is it possible that in "<renderingAttribute name="route" >" only this color can be opacity? :

<case color="#882a4bd1" strokeWidth="12:8" color_3="#ffde5b" color_2="#bfccff" strokeWidth_3="5:7">

I tried others....nothing. No Opacity.
I wish guiding lines in magenta. Like in Garmin navigators. In my opinion it is the best Color for guiding routes,

**Comment by vshcherb** [comment]
In this release we've itnroduced customizing route line, so you should be able to configure.

OsmAnd uses ARGB colors i.e. "#aaaaaaaa" - half transparent grey
