### ISSUE TITLE
The `.chart` file cannot be imported 

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2091]
### Description
The file (GPX track - wpt.chart format) cannot be imported in iOS but can be imported in the Android version

### Steps to reproduce
Select track
(ask me file)

### Actual result
The track cannot be imported 
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/182128580-22e5feae-f1bc-4b79-badd-f0ecbc882b13.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The track will be imported 

### Your Environment
OsmAnd Version: 4.3.0
Android/iOS version: iOS 15.5
Device model: iPad mini 4

**Comment by Zirochkabila** [comment]
[36 (1).chart.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10253885/36.1.chart.zip)

4.4.1.5
File doesn't open

OsmAnd~ 4.4.0#14031mqta, released: 2022-12-18
File opened

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/208300524-62407ae2-575b-4a27-b8a5-269675529df9.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
We only support '.wpt.chart'
