### ISSUE TITLE
When you resize the text, the Orange POI icons stay small

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2094]
### Description
When you resize the text, the POI icons retain their standard size 

### Steps to reproduce
Configure map > POI Overlay > Cafe and restaurant > Text size > 300%

### Actual result
The POI icons retain their standard size 
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/182183935-090069d4-766e-40d8-ac20-ca58b0902e1b.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The POI icons resize according to the size of the text

### Your Environment
OsmAnd Version: 4.3.0
Android/iOS version: iOS 15.5
Device model: iPad mini 4

**Comment by Skalii** [comment]
[Fix POI icon resizing](https://github.com/osmandapp/OsmAnd-iOS/pull/2333)

**Comment by dmpr0** [comment]
# Review
**Text size** on Android applies to: orange POI icons, favorites, track waypoints, location icon, start/finish icons of the track.

|  | Android | iOS |
|---|---|---|
| Orange POI | ✅  | ✅  | 
| POI on the map | ✅  | ✅  |
| Favorites | ✅  | ❌  | 
| Track waypoints | ✅  | ❌  | 
| Location icon | ✅  |  ❌ | 
| Start/finish icons of the track | ✅  | ❌  |

**Comment by Skalii** [comment]
[Fix resizing map icons r4.3](https://github.com/osmandapp/OsmAnd-iOS/pull/2364)

**Comment by Zirochkabila** [comment]
4.4.1.1
OSM poi doesn't change size - every else is changing


https://user-images.githubusercontent.com/104760013/206486598-90eaa9cf-2a0b-4545-ab64-0064368d32bb.mp4

**Comment by Skalii** [comment]
[Fix resizing OSM note/bug icons r4.3](https://github.com/osmandapp/OsmAnd-iOS/pull/2384)

**Comment by Zirochkabila** [comment]
4.4.1.4
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/207858382-84bfe862-3bcf-4e96-9993-7f5dae2efe9a.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
