### ISSUE TITLE
When recording a track, the route flashes

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2095]
### Description
When recording a track, the route being recorded flashes

### Steps to reproduce
Navigation > Add start point > Select destination > REC > Shoe on map > OK > Navigation > Start

### Actual result
When recording a track, the route being recorded flashes

https://user-images.githubusercontent.com/104760013/182325191-b12bf1c7-b465-4deb-befc-834630d3b83e.mp4

### Expected result
When recording a track, the track being recorded does not flash

### Your Environment
OsmAnd Version: 4.3.0
Android/iOS version: iOS 15.5
Device model: iPad mini 4

**Comment by EugeneZmeuk** [comment]
The same issue  #2017
