### ISSUE TITLE
Unit of contour line files not always visible

### ISSUE THREAD

**Issue by scaidermern** [osmandapp/OsmAnd-iOS#2096]
Reported by a user in https://t.me/OsmAndMaps

OsmAnd offers different contour lines of different sizes but with the same name for downloading:

![photo_2022-07-29_15-06-13](https://user-images.githubusercontent.com/1040784/181767138-71dbd94e-fe16-4ec0-98a9-a611b1f18c1c.jpg)
![photo_2022-07-29_15-06-18](https://user-images.githubusercontent.com/1040784/181767142-c43ffaa8-ad0e-4f76-b176-3a8625725a86.jpg)

The description should contain information about which one of them is in meters and which is in feet 🦶🦶.

**Comment by PaulStets** [comment]
It will be fixed in the next build.

**Comment by scaidermern** [comment]
> It will be fixed in the next build.

What about the Android version? The same problem exists here. OsmAnd also offers multiple contour lines for download in this widget without providing details about the unit they are using.

**Comment by PaulStets** [comment]
@scaidermern Please create an issue in the Android repository with a reference to this issue. It will be sufficient for the Android team to identify the problem.

**Comment by scaidermern** [comment]
> @scaidermern Please create an issue in the Android repository with a reference to this issue. It will be sufficient for the Android team to identify the problem.

Well, I _did_ create this issue in the Android repository but it was moved to this repository.

I will create a new one.

**Comment by PaulStets** [comment]
Oh, it's probably because the screenshots are from the iOS version :)

**Comment by dmpr0** [comment]
Fixed
![Screenshot 2022-09-05 at 12 30 39](https://user-images.githubusercontent.com/9365308/188417328-7e9c04b2-d75f-4959-bdf2-43f9df2d2270.png)
