### ISSUE TITLE
Crashes when attempting to Attach [GPX] \to roads

### ISSUE THREAD

**Issue by barteis** [osmandapp/OsmAnd-iOS#2097]
Version 4.3.0 on an iPhone 13 Mini

Plan a route / Open existing track / (downloaded GPX) / Options / Route between points / Continue / Apply / (change routing from Driving to Walking) 

...crashes the app.  I'm using a GPX downloaded from AllTrails: https://www.alltrails.com/trail/us/california/resaca-san-geronimo-ridge-and-manzanita-fire-road

OsmAnd for Android v 4.2.7 handles the same GPX fine, including using the "Attached" GPX for turn-by-turn navigation.  

Thanks!

**Comment by vshcherb** [comment]
Can you please share the track itself somehow? Send it to support for example.

**Comment by barteis** [comment]
How's this?
https://drive.google.com/file/d/1SNWpJ1aN3fW66uqMOzak7sJ0ZKxJwdCy/view?usp=sharing

**Comment by vshcherb** [comment]
I've sent request access

**Comment by barteis** [comment]
I granted access.  And just for good measure, I sent the GPX to support.  Thanks!

**Comment by Zirochkabila** [comment]
> 
Thank you for the detailed description of the steps - it speeds up the testing process a lot.

Your case was tested with version 4.3.0 - as you can see in the attached video, it failed to reproduce. GPX track was attached to the road.


https://user-images.githubusercontent.com/104760013/183612968-b0450c22-2475-44c4-9bbb-50837065e55e.mp4

**Comment by barteis** [comment]
Thanks for looking into this.  When I reported the issue, OsmAnd was "reliably " crashing using
a few imported GPXs.  But when I tried to replicate it today, the app worked perfectly, as your video showed.  I'm not sure what the difference was, but I'm glad it works.

**Comment by vshcherb** [comment]
Yes, glad that we keep improving )
