### ISSUE TITLE
The app crashes when you click on the track properties

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2103]
### Description
The app crashes when you click on track properties (action or track buttons)
[utf-8''пт 29 июля 2022 (1).gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/9260397/utf-8.29.2022.1.gpx.zip)

### Steps to reproduce
Select GPX track > Action

### Actual result
The app crashes

https://user-images.githubusercontent.com/104760013/182867535-d3609710-5588-4a68-8e64-5248468270d8.MOV

### Expected result
Track properties (options or track information) are displayed

### Your Environment
OsmAnd Version: 4.2.4
Android/iOS version: iOS 12.5
Device model: iPhone 6 Plus

**Comment by mic140** [comment]
same result with: select track > Track
