### ISSUE TITLE
Map movement on location/direction change is not smooth

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#2105]
Map movement caused by location (gps) or direction change (compass) appears very jerky. Map movement by hand (fingers) is however very smooth. Please see the attached screen recording. 

The option “Animate location change” is on. Does it actually do anything, though?

https://user-images.githubusercontent.com/3635696/183361738-4befbad9-4c1c-4f32-bb03-543f9da370c2.mov

I have the issue on an iPhone 13 and an iPhone X, with iOS 15.6.

The issue happens independent of the battery level, even if connected to power.

**Comment by MagielBruntink** [comment]
Here is another screen recording of the issue during car navigation.
https://user-images.githubusercontent.com/3635696/183434643-dc825073-7f15-414c-9a70-836155cd60b2.mov

**Comment by adrianmihalko** [comment]
Same problem here.

**Comment by vshcherb** [comment]
Please test latest Testflight build it should be fixed.
