### ISSUE TITLE
Contour lines are visible even if disabled on the LightRS map type

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#2107]
Repro:
- Download contour data
- Switch to LightRS map type
- Disable contour lines 
- Zoom in a bit and observe contour lines

App version 4.2.4.

**Comment by Zirochkabila** [comment]
4.3.0 test flight - reproduce


https://user-images.githubusercontent.com/104760013/183865004-8eecb255-5087-44f7-95a2-b714cbae73f2.mp4
