### ISSUE TITLE
Adding parking spot with plugin does not work

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#2110]
No map marker is actually added to the map
Repro:
- install parking spot plugin
- hit add Parking in the map pin actions
- or add the Add parking place action first to the quick actions button, then use it
- it looks like a map marker is being added in the menu below, but nothing stays on the map
- where the map marker button is normally it says Dismiss with a red cross

**Comment by Zirochkabila** [comment]
4.3.0 test flight - not reproduce
the parking spot is added to the map


https://user-images.githubusercontent.com/104760013/183861886-2606e1aa-fcc4-4ee0-8c3f-33190b611daf.mp4

**Comment by MagielBruntink** [comment]
I was using 4.2.4. How to obtain 4.3 test flight app?

**Comment by Zirochkabila** [comment]
Download the TestFlight app from the App Store

**Comment by MagielBruntink** [comment]
Tried with 4.30 beta but same issue, no map marker or waypoint stays. Only way is the save a favorite but that’s not how it is supposed to work, right?

https://user-images.githubusercontent.com/3635696/183956065-e0014499-a8dc-4a83-9875-09ca1bb19465.mp4

**Comment by Zirochkabila** [comment]
Do you make it this way: Press > Action > Add Parking > Save?

**Comment by MagielBruntink** [comment]
Wow, I totally missed the Save button… I guess because normal Map Markers don’t need it. Anyway, thanks!

**Comment by Zirochkabila** [comment]
You're welcome, have a good evening!
