### ISSUE TITLE
No setting to disable: download sends UUID & number of days since install

### ISSUE THREAD

**Issue by sneak** [osmandapp/OsmAnd-iOS#2115]
https://github.com/osmandapp/OsmAnd-iOS/blob/master/Sources/AppHost/OsmAndAppImpl.mm#L695-L696

https://github.com/osmandapp/OsmAnd-iOS/blob/master/Sources/AppHost/OsmAndAppImpl.mm#L1179-L1192

This appears to send the number of days since install, as well as a UUID, to the index server when fetching indices, without respect for the analytics preference.

This is a data leak that allows for a user's travel history to be tracked by the server, as these requests include client IP and a unique tracking identifier, and client IP is coarse (city-level) geolocation.  This means the server can see the various cities the given `userIosId` travels to as the client IP changes over time.

**Comment by sneak** [comment]
This spyware feature also exists in the Android version, and fails to respect the user's consent choice there as well. It seems unlikely that this is an accident.

**Comment by sneak** [comment]
It appears that @PaulStets is the person responsible for implementing this privacy-violating spyware.

https://github.com/osmandapp/OsmAnd-iOS/commit/1de9a08db42d2b8cff839cee0ec3fae93e6bae53

**Comment by vshcherb** [comment]
UUID is anonymized randomly generated key per installation, cause this key is not associated with any advertisement id or not transferred to any other 3rd party or even used, this key doesn't require consent. As you mentioned the IP could provide more information cause it's location specific.

This approach helps to the server monitor fair usage of resources.

**Comment by sneak** [comment]
You're not understanding me.

You do not have consent from the user to transmit a unique tracking identifier for that user.

When you do so, you leak *to the server* the IP address history of that user, because you can correlate the various client IPs from the unique tracking identifier.  This allows you to identify someone's travel history!

You cannot transmit unique, tracking identifiers from a user's system without their consent.  To do so without consent is unethical.

It's not anonymous - it uniquely identifies the user.  It also divulges the user's IP to you.

> cause this key is not associated with any advertisement id or not transferred to any other 3rd party or even used, this key doesn't require consent

This is false: it *is* used - to make an HTTP request to your server.  It *does* require consent because you are tracking the user and phoning home to your server with telemetry data without the user's knowledge, and, critically, **you do so even when the user has explicitly disabled telemetry**.

**Comment by scaidermern** [comment]
Even a unique, per installation generated UUID is enough to identify a particular user given enough data.

**Comment by scaidermern** [comment]
What about a random UUID that gets generated at startup and regenerated every hour? Will this be sufficient for your purpose? Will it be sufficient to protect the privacy of the users?

**Comment by zander** [comment]
The topic contains a rather useful piece of info that seems to be ignored here. The information is transfered in a download. But OSMAnd is an offline map and downloads only happen very sporadically. And then only when the user initiates a refresh of their maps.

An IP address is "leaked" during download. But the download doesn't happen unless you are actively hitting the menu buttons for that. Most people won't do that on holidays as we are typically talking about a dozen or more megabytes for a map-section.

Next to that you seem to assume bad intent on the side of the download server and its logging. Not all companies behave like facebook, though. Most actually care about privacy laws.

All in all, this looks like a good wakeup call, but the tone and what is implied with this are not in evidence.

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/15058
