### ISSUE TITLE
Change route line to plot under road shields and street names

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#2117]
Currently the route line over plots road shields and names. See screenshot:

<img src="https://user-images.githubusercontent.com/3635696/184234017-f81d88ac-84e4-4fb5-aa04-58b5abbbdb92.png" height="50%" width="50%" /> 

It would be preferable to be able to read the road shields and names always clearly.

**Comment by ivanPyrohivskyi** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/369
https://github.com/osmandapp/OsmAnd/pull/15286
https://github.com/osmandapp/web/pull/37

**Comment by vshcherb** [comment]
https://docs.osmand.net/docs/technical/algorithms/map-rendering-layers

**Comment by dmpr0** [comment]
The shield is above the route line, but the street name is not.
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/191956172-2e745180-a669-47a0-8fb2-3c461a52cc8a.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/191956180-8b43ee89-23bb-422c-ae65-72021c0cd6eb.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
To [nnngrach](https://github.com/nnngrach) need to move https://github.com/osmandapp/OsmAnd/pull/15408 on iOS
