### ISSUE TITLE
Extend route line coloring options to include slope

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#2118]
In particular for cycling and hiking it would be really nice to see the upcoming slope by the route line color.

**Comment by vshcherb** [comment]
I think it's already available but probably requires live subscription. So it's going to be updated in 4.3 cause we restructure with pro subscription.

**Comment by MagielBruntink** [comment]
I have live subscription but see only Custom and Altitude options for the route line (if Map Style is disabled).

**Comment by vshcherb** [comment]
Should be available in latest TestFlight
