### ISSUE TITLE
Crash during plan route (iphone 6+ OS 12.5.5)

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2123]
OsmAnd 4.2.4 while Planning the route the app is crashing.

**Comment by vshcherb** [comment]
Same as https://github.com/osmandapp/OsmAnd-iOS/issues/2124 ?

**Comment by Zirochkabila** [comment]
Version 4.2.4.1 and version 4.2.4.2 - could not reproduce. iPad 4 mini 15.6
