### ISSUE TITLE
Crash while overview the route

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2124]
IPHONE 12 MINI IOS 15.5 model MGE33QL/A
4.2.4 (OSMAND)
When overviewing the route the app is crashing.

**Comment by Zirochkabila** [comment]
Version 4.2.4.1 and version 4.2.4.2 - could not reproduce. iPad 4 mini 15.6
Perhaps the user was using a custom navigation profile?
