### ISSUE TITLE
Move pin to center of visible map area

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2130]
If I disable Display position always in the center and use searching, the search result will be hidden by the maps Context menu.
OsmAnd 4.2.4

https://user-images.githubusercontent.com/80623554/184920249-7c74b9b2-ef20-4013-a659-05112ef55e54.MP4

**Comment by dmpr0** [comment]
We need to test it again when this task will be finished.
https://github.com/osmandapp/OsmAnd-Issues/issues/1615

**Comment by Skalii** [comment]
[Fix pin centering](https://github.com/osmandapp/OsmAnd-iOS/pull/2708)

**Comment by alex-osm** [comment]
Not reproduced

**Comment by Zirochkabila** [comment]
4.4.8.2
**Taping on POI on the map** item doesn't work


https://user-images.githubusercontent.com/104760013/235108016-5834d282-904d-4e1e-a1b8-e5d7f3bbd294.mp4
