### ISSUE TITLE
Control buttons disappear 

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2133]
### Description
Control buttons disappear when the weather widget is activated (Navigation, Menu...)

### Steps to reproduce
Menu > Plugins > Ski map > Back

### Actual result
Control buttons disappear 

https://user-images.githubusercontent.com/104760013/185370325-9950ecd8-a3e7-433c-933e-b465c822a257.mp4

### Expected result
Control buttons are still present 

### Your Environment
OsmAnd Version: 4.3.0.5
Android/iOS version: iOS 15.5
Device model: iPad mini 4

**Comment by vshcherb** [comment]
Merge to existing issue

**Comment by Zirochkabila** [comment]
# https://github.com/osmandapp/OsmAnd-Issues/issues/1469
