### ISSUE TITLE
Attach to roads: track creates wrong segment

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#2137]
When following a track (attached to roads or not) cycling navigation is often giving really weird prompts, like turning right/left on an obvious straight road without intersections. It also misses prompts on obvious turning points.

It’s hard to say for sure, but it may be that the navigation prompts are given in the wrong order (ie the prompts don’t match the points on the navigated route?) 

It appears that the issue is worse if “attached to roads” has been turned on, but it’s hard to confirm.

**Comment by MagielBruntink** [comment]
[route.zip](https://github.com/osmandapp/OsmAnd-iOS/files/9387542/route.zip)

**Comment by Zirochkabila** [comment]
It was not reproduced - the voice prompts on the iOS and Android versions of the application work correctly, in accordance with the prompts that are displayed on the map of the OsmAnd web version, as well as the actual turns on the route.

Please clarify:
1. What language of voice prompts do you use when navigating
2. What version of the application do you use
3. OS version
4. A short video where you could see that the voice prompts are different from the actual turns on the map 

But, on the Android version, the app crashes after the track has been attached to the road and the track navigation is started.
[exception (10).log](https://github.com/osmandapp/OsmAnd-iOS/files/9425581/exception.10.log)

**Comment by MagielBruntink** [comment]
It's no so easy to replicate, as the issue happens mostly durig navigation. I have attached a track that shows some issues with the "attach to the roads" enabled.

1. Voice prompts are in Dutch. But it's not the voice prompts only that are off - also the on-screen prompts.
2. iOS app 4.2.4
3. 15.6.1
4. I have two recordings of simulated navigation:

[This first one](https://share.icloud.com/photos/007A4Nz5YjvOzlCAUdn5r0Yhg) is without "attach to the roads" and shows overall OK prompts. However it misses a prompt for going straight on the intersection with the "Torenweg" (0:17), which the second recording with "attach to the roads" does show.

[The second one](https://share.icloud.com/photos/0b26g3Co_MBZfffPo7j1QVjOg) has "attach to the roads" enabled for Cycling. The navigation course line at the "Bergstraat" and "Dorpstraat" intersection appears broken. The simulation gets past that corner but it does get confused. After that, the prompts are off somewhat as well.

I'm not sure exactly when the issue is being caused here. It seems the "attach to the roads" behavior has an impact on where prompts show, but it can also create route pieces that are redundant or wrong. It seems that those cause problems for the prompts later on. Just speculating here, of course.

Here is the GPX file containing the track:
[broken-nav.zip](https://github.com/osmandapp/OsmAnd-iOS/files/9430647/broken-nav.zip)

**Comment by Zirochkabila** [comment]
The street name widget on the unattached track does not display the actual direction of movement precisely because the track is not attached to the road - there is no actual data.

But, I was able to reproduce the following (4.3.0.6):
1. It is not possible to display the direction arrows on the track after their activation

https://user-images.githubusercontent.com/104760013/186945451-a413ebfa-ee43-4f61-b3cf-42eda9bdc36e.mp4


2. After attaching the track to the road, a small route is added (if you attach it with the car profile, a new route does not appear)
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/186945592-18f3f8f5-af81-4c1d-8266-4e19c6e6a830.jpeg"  width="300" height="auto"/> </th>
 <th><img src="

**Comment by MagielBruntink** [comment]
I think what happens during actual navigation (on cycle) is that such little extra routes are added sometimes, leading strange prompts. Could it be related to track points being not exactly on the road?

**Comment by Zirochkabila** [comment]
Yes, it's quite possible.
