### ISSUE TITLE
CarPlay less of an priority?

### ISSUE THREAD

**Issue by Raphty** [osmandapp/OsmAnd-iOS#2138]
So I recently had a look into the pricing page again and I realized something. CarPlay support is not free. 

I was paying because I wanted to support the project as a whole but when I now realized that CarPlay is a paid feature I wondered if it gets the appropriate support.  

I don't follow most of the issues and I don't know how many people are actually paying. But if you charge for something it should be higher in priority then the thing that is free. This is at least what I expect as a paying customer. 

Still love the project and think this is the best alternative to google and Apple. 

Major downside still traffic. But other then that great. 

Keep up the great work.

**Comment by vshcherb** [comment]
Car Play is not a separate paid feature it's included in the bundle of all map downloads. Indeed we've just did full retest and we have 1 critical issues and 2 important features to implement:
- Issue - with voice doesn't hand over back to Radio
- Feature - show lanes 
- Feature - display speed alerts or traffic warnings on the screen

**Comment by Raphty** [comment]
Yes @vshcherb you are of course correct it comes in a bundle, but it is a paid feature none the less, and I had the feeling that most of the issues related to carplay are being shot down and not investigated.

As I said, love the project and am happy to support.
