### ISSUE TITLE
City search "Show on map" button is missing.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2140]
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/185894279-ac32d7c2-f98a-4cfb-af4e-b98711f875f9.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/185894256-76d4e5d3-9b7a-4d03-8986-1e140b809a9b.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2217
