### ISSUE TITLE
Show lanes in CarPlay

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2141]
- OsmAnd on CarPlay is missing lanes
- Check Next street (from demo)
- Display next turn if lanes are not available

![telegram-cloud-photo-size-2-5244742444304678298-x](https://user-images.githubusercontent.com/1042025/188850089-f8606108-6839-46fc-ba41-a2756dfd9f78.jpg)

![telegram-cloud-photo-size-2-5244742444304678300-y](https://user-images.githubusercontent.com/1042025/188850138-bd4afb95-cd92-4569-911c-b75fd6675299.jpg)

![telegram-cloud-photo-size-4-5771717244848553598-y](https://user-images.githubusercontent.com/1042025/188850187-5286aad4-0476-4f48-9a23-93ee7e759201.jpg)

**Comment by Zirochkabila** [comment]
[Untitled.mov.zip](https://github.com/osmandapp/OsmAnd-iOS/files/9716990/Untitled.mov.zip)

**Comment by Zirochkabila** [comment]
4.3.0.16

<img width="1433" alt="Screenshot 2022-10-13 at 18 18 00" src="https://user-images.githubusercontent.com/104760013/195638031-8cf97087-d569-4394-9f20-1fcf1e32f4fd.png">
