### ISSUE TITLE
OsmAnd (online tiles) disappear

### ISSUE THREAD

**Issue by immergruen** [osmandapp/OsmAnd-iOS#2147]
Good day

I do have an issue with my OsnAmd (online tiles). Initially after installing the App (iPhone) I'm able to select the OsmAnd (online tiles), but after a while (sometimes within days or weeks) the online tiles disappear and I can't reselect them in the map settings. I do have the all inclusive licence.

Is there something I can do to prevent this issue?

Best regards,
Stefan

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/112057302/186585105-b7b3efb6-eea7-4e47-9179-044755500207.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/112057302/186585109-3214e813-2837-4bca-84a3-0072ee84c1c1.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
> 

What version of OsmAnd are you using?

**Comment by immergruen** [comment]
OsmAnd 4.2.4

Am 30.08.2022 um 15:02 schrieb Anatolii ***@***.***>:

﻿

What version of OsmAnd are you using?
