### ISSUE TITLE
TestFlight iOS CarPlay is broken

### ISSUE THREAD

**Issue by Raphty** [osmandapp/OsmAnd-iOS#2162]
The screen stays blank but interestingly the app now works while in CarPlay.

**Comment by vshcherb** [comment]
from your message it's not clear when it works and when doesn't.

**Comment by Raphty** [comment]
It never works on CarPlay

**Comment by Raphty** [comment]
The app on the iPhone now displays things.

**Comment by vshcherb** [comment]
Going to update testflight tomorrow and going to test carplay specifically
