### ISSUE TITLE
Removing track segment: add confirmation alert

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2164]
## ToDo
Currently deleting track segment made without confirmation alert and there are no ways to undo the action, we need to add system default confirmation alert.
- [x]  Add confirmation aler for track segment removing.

**Comment by Skalii** [comment]
[Track menu - Segments - confirmation alert for segment removing](https://github.com/osmandapp/OsmAnd-iOS/pull/2178)
