### ISSUE TITLE
Highway shields in default.render.xml broken for A45, displays white shield

### ISSUE THREAD

**Issue by chereskata** [osmandapp/OsmAnd-iOS#2167]
### Description

On default based renderers the A45 is missing its blue hexagon and has a white rectangle instead

![OSMAnd](https://user-images.githubusercontent.com/87526889/188311288-d0e1ad85-d4cf-410c-9cd6-bcfa302c6e9d.png) ![LightRS](https://user-images.githubusercontent.com/87526889/188311289-6bd0c937-acda-4d34-ac5e-6acd54f98b66.png)

Comparing the relations of A40 and A45 yields no (usable) difference, although i noticed that all "B" relations have traffic_sign="DE:401" but motorways are missing traffic_sign="DE:405"

![out](https://user-images.githubusercontent.com/87526889/188311395-685a3cfe-059d-43e3-a67a-e1edc2ea4879.png)

A somewhat related issue here: https://github.com/osmandapp/OsmAnd/issues/15240

### How to reproduce?
Go to 51.48033 7.39257 and enable {OSMAnd, default}.render.xml

### Your Environment
OsmAnd Version: 4.2.4
Android/iOS version: iOS

**Maps used (online or offline):**   
offline only

**Comment by chereskata** [comment]
Interestingly, [Organic Maps](https://github.com/organicmaps/organicmaps) showcases a similar problem,
![out](https://user-images.githubusercontent.com/87526889/188635876-d97fa8d0-a9b9-4d22-a5a3-c12fe19f8e6f.png)

Another spot, where the hexagons just disappear (52.31948 7.96005):

![IMG_5328 out](https://user-images.githubusercontent.com/87526889/188642021-5264e534-fe00-4747-a047-edde6987a81e.png) ![IMG_5329 out](https://user-images.githubusercontent.com/87526889/188642027-c58cf6b2-0dfc-4a5a-8411-2d4af72103af.png)

**Comment by xmd5a2** [comment]
https://www.openstreetmap.org/way/27425883
This is shield from motorway_link and it comes not from A 45 relation.
LightRS is independent from default.render.xml

**Comment by chereskata** [comment]
The whole A45 does not have shields. Also A1 as i showed above from 52.31948 7.96005 northwards
