### ISSUE TITLE
When navigating in the GPX, which is far from the geolocation, animation crashes happen

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2173]
### Description
When you start GPX track navigation, the app flies over the map

### Steps to reproduce
Select a GPX that is far away from the actual location > Navigation > Start

### Actual result
Navigation does not work

https://user-images.githubusercontent.com/104760013/188914007-703f3d55-7098-4c0d-90d7-d17be66ca734.mp4

### Expected result
Start of track navigation

### Your Environment
OsmAnd Version: 4.3.0.9
Android/iOS version: 15.6.1
Device model: iPad mini 4

**Comment by dmpr0** [comment]
Not reproducible
