### ISSUE TITLE
Auto-select last used folder for new favorite

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2182]
## Request
When you add a few favorites while adding a new point will be comfortable if OsmAnd could offer to save to the last used folder. In the Android version this option is realized.  

## ToDo
- [x]  Auto-select last used folder when adding new favorite point.
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/206415926-76395ac8-090e-452a-87a0-6462639a904a.mov
"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
Done in master branch

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2426
