### ISSUE TITLE
Slopes and hillshade are not displayed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2189]
### Description
Slopes and hillshade are not displayed

### Steps to reproduce
Configure map > Terrain > Hislshade > Download map

### Actual result
Slopes and hillside are not displayed

### Expected result
Slopes and hillshade are displayed on map

### Your Environment
OsmAnd Version: 4.3.0.10
Android/iOS version: iOS 15.7
Device model: iPad mini 4

**Comment by vshcherb** [comment]
Restarting app  doesn't sound as smooth UI Behavior if I understand correctly it's a required step
