### ISSUE TITLE
Track recorded during navigation snaps to the road on iOS

### ISSUE THREAD

**Issue by sanketgarade** [osmandapp/OsmAnd-iOS#2196]
### Description

With navigation turned on and all default settings if I have enabled track recording then the recorded track is snapped to the already existing road. 

### How to reproduce?

On iPhone , 
Enable navigation to any place. 
Use car or bicycle mode. (I've tested on these both.) In the mode you've selected make sure that auto record track is enabled. Once you start navigation and end it later, observe the recorded track. It is snapped to the road (creating a very clean GPS track).

Additionally you can do on another iOS device (at the same time) - do not do navigation, but manually turn on track recording. On this device you'll observe that the recorded track does not snap to the road (creating a zigzag track which we normally expect to see).

Conclusion- snapping of track happens only when navigation is turned on. 

In below image -
Red track and blue track are recorded simultaneously on 2 iOS devices. 
Red = snappy = navigation on
Blue = zigzag = navigation off

![image](https://user-images.githubusercontent.com/74632379/190901783-b1417fcc-125d-439f-9e97-7b9ad6727eab.jpeg)

### Your Environment
OsmAnd Version: 4.2.4
Android/iOS version: iOS 15.5
Device model: iPhone

**Maps used (online or offline):**   

Offline 
Maharashtra 1-august-2022

**Comment by vshcherb** [comment]
Do you run simulation or really follow the track?

**Comment by sanketgarade** [comment]
> Do you run simulation or really follow the track?

I followed the track. I had 2 phones like explained above. Both were strapped to the same holder and I drove in a car recording this.

**Comment by PaulStets** [comment]
Should be fixed in the next build.
