### ISSUE TITLE
City search on iOS not showing "show on map"

### ISSUE THREAD

**Issue by sanketgarade** [osmandapp/OsmAnd-iOS#2197]
### Description

If I search a city from the "search city" feature, it finds the city but it also lists internal locations and forces me to select that too.
I was told that this doesn't happen on android. There a "show on map" Is displayed at the top which seems to be missing in iOS in this case. 

### How to reproduce?

See video. 

https://user-images.githubusercontent.com/74632379/190887379-f37dc146-b033-4366-b2ed-72fb2d4e8f0e.MOV

### Your Environment
OsmAnd Version: 4.2.4
Android/iOS version: iOS 16
Device model: iPhone 12 

**Maps used (online or offline):**   

Offline. 
Maharashtra, India.
1-September-2022

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd-iOS/issues/2140
