### ISSUE TITLE
Share: include coordinates, remove image.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2205]
It seems that the share is broken, it doesn't contain coordinates and link wth the osmand.net url.

## ToDo
- [ ]  Share data should includes
```
POI Name
Address
Location: geo:50.44737,30.52296?z=19
https://osmand.net/go?lat=50.44737&lon=30.52296&z=19
```
- [ ]  Remove image

## How to reproduce
* Select any POI on the map
* In the context menu click on **Share**
* Select any supported app (text messenger for example) 
* Location coordinates and https://osmand.net/go link is missing.

### Android vs iOS comparison:
* Share from Android includes:
```
McDonald's
Хрещатик вулиця (Бегічевська Гора) 19а, Київ
Location: geo:50.44737,30.52296?z=19
https://osmand.net/go?lat=50.44737&lon=30.52296&z=19
```

* Share from iOS:
```
McDonald's
Хрещатик вулиця (Бегічевська Гора) 19а, Київ
```
<img src="https://user-images.githubusercontent.com/9365308/192266297-20d12b4e-b741-475e-8d87-6d4f7ae34dd0.jpg"  width="300" height="auto"/>

**Comment by PaulStets** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2261

**Comment by Zirochkabila** [comment]
4.3.0.23

If you open the link (the one that was shared, POI) when the application is active - OsmAnd opens at the POI location.  If you open the link when the application is closed - OsmAnd opens at the location of the last map view (does not move the map to the POI)

**Comment by PaulStets** [comment]
> 4.3.0.23
> 
> If you open the link (the one that was shared, POI) when the application is active - OsmAnd opens at the POI location.  If you open the link when the application is closed - OsmAnd opens at the location of the last map view (does not move the map to the POI)

Out of scope of this issue. Please create a new one.
