### ISSUE TITLE
Objects on the map are half transparent

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2208]
OsmAnd Maps TestFlight 4.3.0.12
<img src="https://user-images.githubusercontent.com/9365308/192806434-1b5d9556-ca85-4ee6-ad3f-a01aa2fb5a76.PNG"  width="300" height="auto"/> 

# Technical details
- [x] To @nnngrach need to add https://github.com/osmandapp/OsmAnd/commit/d0ee9f9422ca59c933a57b009afb98a7b746cd58#diff-113aef580da7d06dc055fed0169f8c42527cb8bd161c2ffe8de6d09d24929696R109 to this place https://github.com/osmandapp/OsmAnd-iOS/blob/4d6a396552f96254966e4ad134dbce63ced70f5d/Sources/Controllers/Map/OAMapViewController.mm#L1881
And find where to set default 50% transparency in the start

- [x] And move commit https://github.com/osmandapp/OsmAnd/commit/65c3e7e05cfe6175e489bc357836837f732c6efd to iOS

**Comment by ivanPyrohivskyi** [comment]
To @nnngrach need to add https://github.com/osmandapp/OsmAnd/commit/d0ee9f9422ca59c933a57b009afb98a7b746cd58#diff-113aef580da7d06dc055fed0169f8c42527cb8bd161c2ffe8de6d09d24929696R109 to this place https://github.com/osmandapp/OsmAnd-iOS/blob/4d6a396552f96254966e4ad134dbce63ced70f5d/Sources/Controllers/Map/OAMapViewController.mm#L1881
And find where to set default 50% transparency in the start

And move commit https://github.com/osmandapp/OsmAnd/commit/65c3e7e05cfe6175e489bc357836837f732c6efd to iOS

**Comment by Zirochkabila** [comment]
4.3.0.17 **Fixed**
