### ISSUE TITLE
Cannot copy name of POI

### ISSUE THREAD

**Issue by dpriskorn** [osmandapp/OsmAnd-iOS#2236]
# 🚀 feature request

### Description

When clicking on a POI I can neither select nor long click->copy the name. 

As a user I want to copy the name so I can search for the telephone number to a bike shop because the data is missing in OSM. 

### Describe the solution you'd like
Enable selection as a minimum. Long click to copy is nice to have. 

### platform 
I'm on iOS.

**Comment by dmpr0** [comment]
Hi! 
The current version allows copying POI name by tapping **Share** > **Copy POI name**.
I completely agree with you, that a long tap on the POI name is a standard pattern.
<img src="https://user-images.githubusercontent.com/9365308/195777809-39f7e36c-5ca4-4d86-b4c1-7bc4e502752c.jpg"  width="300" height="auto"/>
