### ISSUE TITLE
Add display of decimal numbers in maximum and average speeds (in OsmAnd iOS)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2239]
### Description
Add display of decimal numbers in maximum and average speeds (in OsmAnd iOS)
[2022-07-25.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/9811363/2022-07-25.gpx.zip)

### Actual result
![photo_2022-10-18 17 17 08](https://user-images.githubusercontent.com/104760013/196457550-fef62f87-8a92-4ed1-8ff1-02e56129df57.jpeg)

### Expected result
![photo_2022-10-18 17 17 21](https://user-images.githubusercontent.com/104760013/196457576-b5c47349-4224-4958-80c4-39663b724959.jpeg)

**Comment by hasanov080** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2274#issue-1427473468
