### ISSUE TITLE
External keyboard isue

### ISSUE THREAD

**Issue by kytu282** [osmandapp/OsmAnd-iOS#2242]
hello, the other day I realized that in iOS the external keyboard functions are not activated, only zoom in and zoom out works, in android I think this problem has been corrected, could it be corrected in iOS? 

Thanks in advance

**Comment by Dennis650** [comment]
Hello, 
what keys work for zooming? 
I created an issue for it: https://github.com/osmandapp/OsmAnd-iOS/issues/2000
Thanks and greetings Dennis

**Comment by vshcherb** [comment]
Duplicate
