### ISSUE TITLE
World mini base map displayed in local Maps & Resources 

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2256]
### Description
World mini base map displayed in local Map & Resources 

### Steps to reproduce
Menu > Maps & Resources > Local 

### Actual result
World mini base map displayed
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/197509376-4c01444b-65ba-49e8-afc8-1920c214c2a1.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
World mini base map should not be displayed in this menu section

### Your Environment
OsmAnd Version: 4.3.0.22
Android/iOS version: iOS 15.7
Device model: iPad mini 4

**Comment by Skalii** [comment]
[World mini basemap - hide on local resources screen r4.3](https://github.com/osmandapp/OsmAnd-iOS/pull/2459)

**Comment by Zirochkabila** [comment]
4.4.4.2
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/212952325-35692d97-343e-4135-9687-f3e7fb5bba11.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
