### ISSUE TITLE
[iOS] Extra space before an umlaut in POI Overlay dialogue

### ISSUE THREAD

**Issue by schwindp** [osmandapp/OsmAnd-ios#226]
OsmAnd v2.40
iOS 12.1.2

When opening the POI-Overlay dialogue, there's an extra space before the Umlaut in "Gemischtwarengeschäft und Supermarkt". See attached screenshot.

![img_0027](https://user-images.githubusercontent.com/187595/51442223-05121f00-1cdb-11e9-978c-a25653fa8287.jpg)

**Comment by mguaylambert** [comment]
I believe this is the same as : https://github.com/osmandapp/OsmAnd-ios/issues/139

**Comment by schwindp** [comment]
Thanks @mguaylambert
