### ISSUE TITLE
Add the ability to resize my location icon

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2262]
In the android version you can change the text size setting and my position icon will also be changed. In the iOS version it does not work like that. Add the ability to resize my position icon.
<table style="width:100%">
  <tr>
    <th>Text size 300% Android</th>
    <th>Text size 300% iOS</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/80623554/197788413-04b1d85e-dda0-4fc5-8547-47c79a32fc81.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/80623554/197788458-da9958ac-edd8-4686-b03b-21b1a32305cd.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

Also please make available to change my location icon size for CarPlay.

**Comment by dmpr0** [comment]
Possibly a duplicate https://github.com/osmandapp/OsmAnd-iOS/issues/2094?

**Comment by vshcherb** [comment]
Actually it looks like Android issue though if people don't complain about Android we're not going to fix it.
