### ISSUE TITLE
Incorrect object shown in the context menu

### ISSUE THREAD

**Issue by PaulStets** [osmandapp/OsmAnd-ios#227]
![simulator screen shot - iphone x - 2019-02-12 at 15 55 59](https://user-images.githubusercontent.com/20681525/52640254-c1c45e00-2ede-11e9-951e-d73ab4c1f4bc.png)

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-core/commit/72cb6537d466121aaabd866b0448cc39e2019890
