### ISSUE TITLE
Downloading progress bar is buggy

### ISSUE THREAD

**Issue by hackthe1** [osmandapp/OsmAnd-iOS#2270]
https://user-images.githubusercontent.com/101349513/198529990-4fac5db3-089f-4da7-8e83-1615cd429467.MOV

**Comment by Zirochkabila** [comment]
Downloading progress bar in the latest nightly version and the version from the master branch as of 07.02.23 works without bugs

**Comment by vshcherb** [comment]
Should be fixed in last 4.3 release, hopefully this week rollout.
