### ISSUE TITLE
When planning a route, part of the route between points disappears

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2272]
### Description
When planning a route, part of the route between points disappears

### Steps to reproduce
Create a track in Plan a Route with two segments> Walking > Select last point of the first segment > Move > Apply

### Actual result
Part of the route between points disappears

https://user-images.githubusercontent.com/104760013/198579766-e2f818b0-96f1-4704-940e-dc733070871b.mp4

### Expected result
The route is displayed in full

### Your Environment
OsmAnd Version: 4.3.0.23
Android/iOS version: iOS 15.7
Device model: iPad mini 4

**Comment by PaulStets** [comment]
Also fixed:
- Move point didn't work at all
- Close or Done buttons left the route planning in the Move point mode which led to strange behavior
