### ISSUE TITLE
French label for Updating miss a space

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#2276]
![092A6EE9-65FC-4E3C-9A10-591D698BEE32](https://user-images.githubusercontent.com/59312735/198832041-fef595ba-c1a6-4ee8-9f1d-a2b865c70b2d.png)
Everything is on the title. It should be « mise à jour automatique » instead of « miseà jour automatique »

**Comment by vshcherb** [comment]
Already fixed https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values-fr/strings.xml#L1606
