### ISSUE TITLE
The buttons at the top of the screen overlap each other

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2288]
### Description
When you open the Route between points menu, the buttons at the top of the screen overlap each other

### Steps to reproduce
Menu > Plan a route > Create new route > Route between points

### Actual result
The buttons at the top of the screen overlap each other

https://user-images.githubusercontent.com/104760013/199532889-1700baf2-a147-4a0f-9064-85770eb45a4c.mp4

### Expected result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/199533852-37091d13-ff4b-45f1-bce8-212bb5d50b6a.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.3.0.25
Android/iOS version: iOS 15.7
Device model: iPad mini 4

**Comment by vshcherb** [comment]
Duplicate ...
