### ISSUE TITLE
Add ability to hide GPX waypoints 

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd-iOS#229]
Please add the option to hide waypoints from map display since it is difficult to see the track if there are a lot of points.
![image](https://user-images.githubusercontent.com/40493090/53244399-70248c00-36b3-11e9-919f-7bdd6e20dccb.png)

**Comment by ELetun** [comment]
Is it still impossible to remove GPX waypoint? Its ultra important for my purpose
