### ISSUE TITLE
Not shifted center of the map in CarPlay

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2291]
### Description
If selecting United States as Driving region does not move the map center

### Steps to reproduce
Menu > Settings > Driving > General settings > Driving region > United States > Start navigation

### Actual result
Not shifted center of the map
<img width="1126" alt="Screenshot 2022-11-03 at 17 39 58" src="https://user-images.githubusercontent.com/104760013/199949170-9f637c56-1e3b-4422-b53c-6ad16e0f0dfe.png">

### Expected result
The center of the map shifts to the right ()
<img width="1126" alt="Screenshot 2022-11-03 at 17 41 01" src="https://user-images.githubusercontent.com/104760013/199949300-e10adb97-be2c-443d-b191-94dc7802da21.png">

### Your Environment
OsmAnd Version: 4.3.0.26
Android/iOS version: 
Device model:

**Comment by dmpr0** [comment]
![Screenshot 2022-11-18 at 17 55 21](https://user-images.githubusercontent.com/9365308/202746716-9d22e17b-70af-4c59-a92c-529782e5f0d3.png)
