### ISSUE TITLE
Crash when going to Categories in Search

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2299]
### Description
When you go to Categories in Search, the application crashes

### Steps to reproduce
Search > Categories

### Actual result
Crash 

https://user-images.githubusercontent.com/104760013/200861692-e3a696b1-41c9-425a-a7e4-401288ef6f50.mp4

### Expected result
The Categories opens

### Your Environment
OsmAnd Version: 4.3.0.28
Android/iOS version: iOS 15.7
Device model: iPad mini 4

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/a2234f76be0b8c6d977925a76658c93feda817d4
