### ISSUE TITLE
Afternoon times in opening hours reset to am

### ISSUE THREAD

**Issue by jakecoppinger** [osmandapp/OsmAnd-iOS#2300]
On iOS OsmAnd I'm currently unable to add opening hours to a node that ends after midday (PM). The time automatically becomes AM. This also occurs with 24 hour time.

This is a really bad bug - I'm not able to survey opening hours at all in the current state.

**Comment by Zirochkabila** [comment]
[2087](https://github.com/osmandapp/OsmAnd-iOS/issues/2087#issuecomment-1308960398)
