### ISSUE TITLE
"Share > Copy address" for Favorite point works after re-opening.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2302]
### How to reproduce
* Select any point on the map, better if it a POI
* Add point to **Favorites**
* When context menu will opens after saving favorite
* Tap on **Share**
* In share sheet select **Copy POI address**

### Expected result
* Taping **Share** > **Copy POI address** right after saving a point will copy address

Maybe similar Android task https://github.com/osmandapp/OsmAnd/issues/14065
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/207825040-ed4e978e-35b0-4010-a4b0-22d3a1d19ee2.png"  width="300" height="auto"/> </td>
    <td><video source src="https://user-images.githubusercontent.com/9365308/207825202-abbaaf33-b62f-4bfe-a1a5-202e6f9681b5.mov"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2732
