### ISSUE TITLE
Public Transport iOS - transport order

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#2307]
Tested on TestFlight 4.3.0.31
- [x]  Should be fixed on iOS too?
- [x]  iOS: Route order the same as on Android

<table style="width:100%">
  <tr>
    <th colspan=2>iOS</th>
    <th colspan=2>Android</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/201638490-ab00342e-a7e7-40ab-aa31-d5c57d7d6cbc.PNG"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/201638494-19693b20-2d9f-41ef-b955-da3fdfc64d3e.PNG"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/201638767-44109b7b-79ae-458e-9682-7a080a74b8a4.png"  width="200" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/201638774-0ddf4701-d62a-4444-86c9-e32564711c2f.png"  width="200" height="auto"/> </td>
  </tr>
</table>

_Originally posted by @dmpr0 in https://github.com/osmandapp/OsmAnd/issues/15374#issuecomment-1313454805_

**Comment by DmitrySvetlichny** [comment]
Needs to be fixed C&P in OATransportStopViewController and OAPOIViewController

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14116mqta, released: 2023-01-19
4.4.4.3
Same - Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/213492711-071077af-4f53-4f0a-aa5b-a00a3b38c9fd.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/213492702-348988ff-ffaf-477c-aa43-4133531b8c21.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14139mqta, released: 2023-01-31
4.4.5.2

Stops are different
Name of the stop is outside the menu

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/215735602-6a0d3ea7-0f17-496a-ba1e-09c326475c5a.jpeg"  width="500" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/215735606-67b0517b-1fa9-484a-9293-dd59455ed0f8.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
<img src="https://user-images.githubusercontent.com/9365308/217206193-3c895405-f088-4a08-8437-46b2fd5643fe.jpg"  width="300" height="auto"/>
