### ISSUE TITLE
Feature request: minimize groups of Favourites

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd-iOS#232]
Please add the ability to minimize groups of Favourites. It is difficult to find a Favourite when there are too many of them and the list is too long. Minimizing groups would help to find a particular Favourite faster.

**Comment by AnnBibyk** [comment]
Fixed by @AnnBibyk 
https://github.com/osmandapp/OsmAnd-iOS/pull/682
