### ISSUE TITLE
Sunrise / Sunset widget

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-iOS#233]
Currently, information about sunrise & sunset are accessible under "Settings > General settings" (at the end of the view). I don't know why this function was created in the first place, but I think the settings screen is not the right place for displaying it. Meanwhile it might be useful for some users just as the battery level and actual time for example.
I suggest to remove this functionality from the settings and create a widget with it. Just like the "Arrival time" widget it would be great to offer the possibility to switch between showing the *time* of sunrise/sunset or the *remaining time* before sunrise/sunset. To avoid cluttering the map maybe the widget could only display the "next event" : info about sunset during daytime and about sunrise during night.

**Comment by dmpr0** [comment]
### Sunrise widget. [Figma](https://www.figma.com/file/95sVxDjUfZ0afiW7XmTUYx/Configure-screen?node-id=425%3A92499)
- [ ] Icon `widget_sunrise_day/night`
- [ ] Description `Shows time of the next sunrise or time left to sunrise.`
- [ ] Settings **Show**, allows to switch mode from **Next sunsire** to **Time left**
- - [ ]  **Next sunrise**: show the time of the next sunrise with the day in shortened format, example: `07:36 Thurs`. `Thurs` should use a smaller font size similar to `km/h`. `h or m` should use a smaller font size similar to `km/h`.
- - [ ] **Time left**: show the time left to sunrise, example `05:25 h`. Time in widget needs to be updated.
- - [ ]  Widget mode should be switched by clicking on the widget.

### Sunset widget. [Figma](https://www.figma.com/file/95sVxDjUfZ0afiW7XmTUYx/Configure-screen?node-id=425%3A92508)
- [ ] Icon `widget_sunset_day/night`
- [ ] Description `Shows time of the next sunset or time left to sunset.`
- [ ] Settings **Show**, allows to switch mode from **Next sunset** to **Time left**
- - [ ] **Next sunset**: show the time of the next sunrise with the day in shortened format, example: `17:44 Wed`. `Wed` should use a smaller font size similar to `km/h`
- - [ ] **Time left**: show the time left to sunrise, example `05:25 h` or `0:25 m`. `h or m` should use a smaller font size similar to `km/h`. Time in widget needs to be updated.
- - [ ]  Widget mode should be switched by clicking on the widget.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2664/files

**Comment by Zirochkabila** [comment]
4.4.6.9

- [ ] Sunrise data in the Sunrise widget is displayed on the current day, not the next day

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/226653887-c4c8a185-2164-4a72-90e4-bf089c81c38e.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.6.11
Still present

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/227726579-38c05230-2881-462f-93f9-98e938034cca.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
## Review
 Time left: show the time left to sunrise, example 05:25 **h**
- [ ]  "h" for hours and "m" for minutes is missing to **Time left** mode.
