### ISSUE TITLE
Map isn't added in weather forecast

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2330]
### Description
`The first video was recorded in 4.3.0.34, the second in 4.3.0.35 - the same behavior as in the first video in 4.3.0.35 was not possible. But, the behavior was the same`

If you add a map for offline forecast and then stop loading:
1. A circle appears on the right side, near the "Select" button
2. It is no longer possible to add a map

### Steps to reproduce
Menu > Maps & Resources > Updates >  Weather forecast > Select > Entire world > Apply > Stop downloading > Yes

### Actual result
Map isn't added in weather forecast

https://user-images.githubusercontent.com/104760013/204100849-cc53ec94-3a0b-4214-bb56-8f2200b98491.mov

https://user-images.githubusercontent.com/104760013/204100926-e4b6b356-d669-41d1-9f52-14fc4b36a36b.mp4

### Expected result
Map is added to the weather forecast, and the circle isn't displayed on the left part of the button

### Your Environment
OsmAnd Version: 4.3.0.35
Android/iOS version: iOS 15.7
Device model: iPad mini 4

**Comment by dmpr0** [comment]
Don't reproduced in 4.3

**Comment by Zirochkabila** [comment]
4.4.1.4
Behavior fixed
But, there is still a UI bug - a circle is displayed after stopping the Weather forecast loading

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/208303065-35f1eab9-a226-4fb6-afb6-d9d183eb86e6.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.5.8
Done
