### ISSUE TITLE
Map type UI bug

### ISSUE THREAD

**Issue by juliusvaart** [osmandapp/OsmAnd-iOS#2345]
4.3.0

In map settings:

<img src="https://user-images.githubusercontent.com/764084/205226339-3ae9b57a-c558-4ccf-a8e4-4bc362730c88.jpeg"  width="300" height="auto"/>

**Comment by Zirochkabila** [comment]
4.4.0.40
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/205926958-c8d9d4c3-17ed-4329-be6c-8f4fd49a7a5d.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

@juliusvaart  Please tell us on which device you managed to reproduce.

**Comment by juliusvaart** [comment]
iPhone 13 Pro
iOS 16.1.1
Localization: Dutch

The _"Touring view (contrast and details)"_ string is longer and pushes the label. Try the wider one.

**Comment by Zirochkabila** [comment]
Done
<img width="334" alt="Screenshot 2022-12-09 at 13 22 02" src="https://user-images.githubusercontent.com/104760013/206691696-866ddfe6-66f7-4fe7-ac0c-29d2e55a29bf.png">

**Comment by dmpr0** [comment]
# Review
- [ ]  TabelCell labels, in this example **Map type** should be in priority and should be presented in one line

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/207024400-dc24b503-a4b9-4191-9b46-4872203217a5.jpeg"  width="600" height="auto"/> </td>
  </tr>
</table>

**Comment by Skalii** [comment]
[Fix value cell](https://github.com/osmandapp/OsmAnd-iOS/pull/2485)

**Comment by Zirochkabila** [comment]
Master branch 
Done
<img width="708" alt="Screenshot 2023-01-24 at 16 41 34" src="https://user-images.githubusercontent.com/104760013/214326133-0711250d-f978-4de6-9a39-9a6f56730bfe.png">
