### ISSUE TITLE
Add waypoint > Select track dialog have wrong title.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2349]
## ToDo
- [x]  Rename dialog **Open existing track** to **Select track** when it's launching from Context Menu > Add waypoint

### How to reproduce
TestFlight 4.3.0.39

* Chose any point on the map
* Click **Actions** > **Add waypoint**
* New dialog will opens with title **Open existing track**
The title is correct for **Plan Route** > **Open existing track** but not for Add waypoint action.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/205606677-d1c3884a-98b0-4f75-9433-2de71884a0d9.MP4"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2974

**Comment by DmitryAlexei** [comment]
https://docs.osmand.net/docs/user/personal/tracks#add-waypoint
we need to describe the process of adding a Waypoint to a track

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/personal/tracks/#add-waypoint
https://osmand.net/docs/user/map/map-context-menu#-add--edit--track-waypoint
