### ISSUE TITLE
Plan route approximation issue

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd-iOS#2350]
By PlanRoute build route by this points with Car profile

56.63059,47.89169
56.6309,47.89327
56.63184,47.89518
56.632065,47.89744

Extra segment on point 3
<img width="200" alt="Screenshot 2022-12-05 at 15 47 50" src="https://user-images.githubusercontent.com/35684515/205619266-4a164ef5-db5b-49c5-887c-213e7edbf93e.png">

Extra segment on point 4
<img width="200" alt="Screenshot 2022-12-05 at 15 48 06" src="https://user-images.githubusercontent.com/35684515/205619301-6db3a946-4811-4f41-8fc3-0fb0142b06c4.png">

In Follow track mode there is an arrow in reverse direction
<img width="200" alt="Screenshot 2022-12-05 at 15 52 34" src="https://user-images.githubusercontent.com/35684515/205620712-518c00aa-d15b-4611-b70c-74aebbb2c58a.png">

[Mon 05 Dec 2022_(4).gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10153459/Mon.05.Dec.2022_.4.gpx.zip)

**Comment by Zirochkabila** [comment]
4.4.1.4
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/207868675-7f21127e-0ec2-46bd-85ce-e7730c1ea471.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
