### ISSUE TITLE
 Follow gpx track issue

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd-iOS#2352]
Follow track with this gpx.

[Track.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10153518/Track.gpx.zip)

Android - OK
<img width="200" alt="Screenshot 2022-12-05 at 16 04 38" src="https://user-images.githubusercontent.com/35684515/205621261-48a6afe7-c012-4447-9421-d53a16a96518.jpeg">

IOS - Skips first segment
<img width="200" alt="Screenshot 2022-12-05 at 16 04 38" src="https://user-images.githubusercontent.com/35684515/205622177-39520aaf-a366-436e-b93b-4f2e08c93a99.png">

**Comment by Zirochkabila** [comment]
4.4.1.1
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/206708185-ef9d4801-bb4f-4239-8b0b-a5c2d148c867.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by PaulStets** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/pull/116
https://github.com/osmandapp/OsmAnd-core/pull/437
https://github.com/osmandapp/OsmAnd-iOS/pull/2391
