### ISSUE TITLE
OSM Editing suggestions jumps on every tap

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2396]
Tested on 4.3 version
<video source src="https://user-images.githubusercontent.com/9365308/208107063-62d70762-4fa5-4d88-9c1a-1a037053c042.MP4"  width="300" height="auto"/>

**Comment by Zirochkabila** [comment]
4.4.4.2
Done


https://user-images.githubusercontent.com/104760013/212968328-bcc19903-4990-4433-8ae8-942f4ecef1b8.mp4

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2420
