### ISSUE TITLE
Favorites: Open Files fir "Import", "Export" don't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2397]
## Review
- [x] https://github.com/osmandapp/OsmAnd-iOS/issues/2457
- [ ] #2507

## Import favorites
- [x] #2477
<table style="width:100%">
  <tr>
    <th>Current alert</th>
    <th>**Restore from file**</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/208129679-ea762a97-c275-420b-9980-780fd441de00.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/208129686-7a8e721d-51b2-4b75-923c-41fdb2f122ec.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>   

## Export favorites action don't work
* Open **Menu** > **My Places** > **Favorites**
* Scroll down to **Import/Export** group
* Tap on **Export favorites**
* Share sheet will open, but trying to send it somewhere don't do anything, if you try to select AirDrop it will show **Failed** message. 
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/208129979-456fa649-d246-4fc2-a505-48d414ca86fb.png"  width="300"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/208130668-50c52796-839b-484b-88ba-4c831b20b637.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.4.3
Done

**Comment by vshcherb** [comment]
Follow up task, it doesn't work on some devices https://github.com/osmandapp/OsmAnd-iOS/issues/2507
