### ISSUE TITLE
Crash after activating weather contour lines

### ISSUE THREAD

**Issue by pedrohazevedo** [osmandapp/OsmAnd-iOS#2398]
Step by step:
- [ ] Open app
- [ ] Activate the contour in the Weather settings
- [ ] Zoom out

After that, the app will crash.

OsmAnd 4.4.0.40
iPhone 14 Plus - iOS 16.2

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/41340982/208183590-8ac632bf-807a-4861-8446-c3d7fe483dfc.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by juliusvaart** [comment]
Experienced the same issue when testing.

**Comment by Zirochkabila** [comment]
4.4.1.5
Not reproduced

@juliusvaart @pedrohazevedo Try to check it on TestFlight version


https://user-images.githubusercontent.com/104760013/208306290-2b8b9322-26d8-4006-b97c-37c30f0be292.mp4

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/2747e0036e80b1d9bc030125cd57fcc0ba75bc6d

**Comment by juliusvaart** [comment]
TestFlight same issue as i stated. Please don’t close issues without proper testing.

**Comment by Zirochkabila** [comment]
4.4.3.1
Done
