### ISSUE TITLE
OsmAnd Pro subscription not working when older subscription active

### ISSUE THREAD

**Issue by juliusvaart** [osmandapp/OsmAnd-iOS#2399]
App store 4.3 version and testflight 4.4.0.40 version.

I have a subscription to “All inclusive” that ends in 10-09-2023 and subscribed to OsmAnd Pro. I now have two active subscriptions.

![30B6ED31-CF6D-4F36-BC3A-F9C85E5DDF2F](https://user-images.githubusercontent.com/764084/208286055-e5403e54-87d2-4c27-b709-71640c7fbdbe.jpeg)

But in OsmAnd i now have no subscriptions.

![60E251D8-F360-4E5B-BF5B-25A61E16B983](https://user-images.githubusercontent.com/764084/208286071-82bba2ea-224a-406f-ab25-5010c76bb27f.jpeg)

Restore purchases doesn’t work.

When trying a resubscribe from OsmAnd it says I already have the subscription (that’s is logical, i paid for the Pro one and is listed in my Apple subscriptions).

![B3AC604A-0C93-456D-B019-A7E483E0660E](https://user-images.githubusercontent.com/764084/208286152-796240b9-c3f5-41a6-9aea-3f22b4925911.jpeg)

When I press OK, the app hangs or crashes.

![35185E22-8A65-43B1-9B59-C0FDADE9A8F1](https://user-images.githubusercontent.com/764084/208286168-34b9c9b6-d5a5-4b33-a4f4-ec0d62f78448.jpeg)

**Comment by juliusvaart** [comment]
Alright, completly removing and reinstalling seems to have fixed the issue.

**Comment by juliusvaart** [comment]
Reinstalling made everything worse. When trying to download synced data the app says "no active subscription" but it's now showing the two subscriptions...

Feels really buggy.

**Comment by vshcherb** [comment]
We're fixing "Restore purchase" now, what do you see in Purchases.

**Comment by juliusvaart** [comment]
![72ECF940-7A6D-47A7-8CF4-ED485CB8357C](https://user-images.githubusercontent.com/764084/208484728-deb2de78-9296-4def-af40-651c71e0d7af.jpeg)

And then nothing. Will try reinstalling again.

**Comment by juliusvaart** [comment]
I see this with a clean install (app store version):

![F944F057-6A5E-40FD-BB52-F452F0E0D50F](https://user-images.githubusercontent.com/764084/208485711-5ed796f7-4f6b-4fd1-842f-82447220c2e2.jpeg)

Then i entered my cloud account e-mail and the app crashes.

**Comment by juliusvaart** [comment]
Now i’ve got a crash on every sync attempt.

**Comment by juliusvaart** [comment]
And purchases are gone again.

![BE9482DA-8056-46D0-95E4-4FE927857AD2](https://user-images.githubusercontent.com/764084/208486287-e3c977ee-02bc-4c4f-8037-0bd453e815c3.jpeg)

**Comment by mpavsic** [comment]
Hi, the same problem here. I had an active OsmAnd subscription with expiry date 2023-08-26, and I have recently I subscribed to the OsmAnd Pro (expires 2023-12-17).

Checking for purchases does nothing, and trying "Restore purchases" results in a crash.

iOS version 16.2, OsmAnd version 4.3 (as reported in App store, in app is says 4.4.1 as reported here: #2400 ).

**Comment by PaulStets** [comment]
Should be fixed in https://github.com/osmandapp/OsmAnd-iOS/pull/2406/files. Please install the next build once it's available and tap the ```Restore purchases``` button

**Comment by anastasiia936** [comment]
OsmAnd 4.4.2 subscription is still doe not displayed in the Purchase menu.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/80623554/209322103-d02b7256-e03f-4c91-9232-768e1d916f56.jpeg"  width="300" height="auto"/> </td>
<td><img src="https://user-images.githubusercontent.com/80623554/209321805-2bf02f3f-d9e3-4966-9d42-1afab5af0ec4.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/80623554/209321877-150c5d77-a5d6-489d-8a5f-78758358dc12.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by mpavsic** [comment]
> OsmAnd 4.4.2 subscription is still does not displayed in the Purchase menu.

Also for me nothing changed after installing the new app version, Pro purchase not visible in the app after trying to restore purchases.

**Comment by juliusvaart** [comment]
Still same issue.

**Comment by PaulStets** [comment]
Have you installed a TestFlight build in the past? If so, you may need to completely reinstall the app from the AppStore for it to work.

**Comment by mpavsic** [comment]
> Have you installed a TestFlight build in the past? If so, you may need to completely reinstall the app from the AppStore for it to work.

No, I have never had the Testflight version, just the regular one from the AppStore.

**Comment by juliusvaart** [comment]
Removed everything, reinstalled app store version, bur after enabling plugins, downloading maps and setting up osmand cloud, subscriptions are gone again…

**Comment by juliusvaart** [comment]
Seems like all Pro-functionality is working, but the purchases don’t show.

**Comment by vshcherb** [comment]
The original issue **is fixed**, now if you purchase PRO you can use all feature eligible for PRO subscription.

The **remaining issue**, Purchases screen and Restore all purchases still doesn't display all purchased information. Going to be fixed this week (hopefully will be reviewed soon) with 4.3.3

**Comment by mpavsic** [comment]
Great, the 4.3.3 update fixed the issue!
