### ISSUE TITLE
Feature request: configure default angle for 2.5D view 

### ISSUE THREAD

**Issue by rbsns** [osmandapp/OsmAnd-iOS#2405]
Hi! Please let the user change the default “angle” of 2.5D view in settings.

Although it’s possible to use two-finger scroll to change it, every time that the map is centered it comes back to default inclination, that’s to low in the new app version.

Tks!

**Comment by vshcherb** [comment]
We have another issue where we need to change angle for different zoom to make it more comfortable so this setting will be even more complicated to configure

**Comment by rbsns** [comment]
> We have another issue where we need to change angle for different zoom to make it more comfortable so this setting will be even more complicated to configure

Could be 2 options in settings: “fixed angle” (defined by user) or “automatic according to zoom level”.

But if the angle is adjusted, this setting could be unnecessary. The real problem is the very low angle in some scenarios.

**Comment by vshcherb** [comment]
Related issue https://github.com/osmandapp/OsmAnd/issues/16027

**Comment by rbsns** [comment]
The issue with angle at certain zoom levels was resolved in latest version and now this feature seems to be unnecessary.
