### ISSUE TITLE
Add additional data to the route when generating GPX

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2408]
### Description

- [x]  Add additional data to the route when generating GPX such as <extensions>, <osmand:route> and <osmand:types>

When generating GPX with the same route and coordinates of points - in the [Android ](https://github.com/osmandapp/OsmAnd/issues/14331#issuecomment-1354517530)version the [elements](https://github.com/osmandapp/OsmAnd/pull/15872) indicated in the screenshot are displayed, and in the iOS version, they aren't - need to add.
![photo_2022-12-20 20 28 50](https://user-images.githubusercontent.com/104760013/208739761-ecebf2ca-6644-4476-9c75-60eb10ddffd5.jpeg)

**Comment by PaulStets** [comment]
They were already present for quite some time.
![telegram-cloud-photo-size-2-5267255481754305589-y](https://user-images.githubusercontent.com/20681525/208906573-6bc343c0-79ee-4404-8c56-e23e6d14cc9f.jpg)

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-iOS/pull/2409

**Comment by Zirochkabila** [comment]
Done in master branch

<img width="975" alt="Screenshot 2023-01-16 at 16 12 33" src="https://user-images.githubusercontent.com/104760013/212698164-ba91b825-63e7-470f-a73e-0923b577027d.png">

**Comment by PaulStets** [comment]
Added to r4.3

**Comment by dmpr0** [comment]
## Review
- [ ]  iOS doesn't add `time` tag to `metadata`
```
  <metadata>
    <name>Tue 14 Feb 2023</name>
    <time>2023-02-14T08:57:09Z</time>
  </metadata>
```
- [ ]  
Android: `<osmand:split_interval>0.0</osmand:split_interval>`
iOS: `<osmand:split_interval>0</osmand:split_interval>`
