### ISSUE TITLE
Coordinates info for Favorites

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#2414]
There is no coordinates info for Favorites on Details:
![image](https://user-images.githubusercontent.com/44466116/209154154-eb7aa249-b27d-40f4-9e23-bf3889a1e92c.png)

OsmAnd 4.4.2 Testflight version

**Comment by Skalii** [comment]
[Context menu - Favorite/waypoint - Add coordinates r4.3](https://github.com/osmandapp/OsmAnd-iOS/pull/2456)

**Comment by Zirochkabila** [comment]
4.4.4.2
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/213214791-9671ecfa-cf7e-419d-84bc-98dc7bb4d442.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
