### ISSUE TITLE
Pop-up after downloading maps

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#2418]
After each downloading map, OsmAnd sends pop-up message about Nautical maps, but we installed an ordinary map of a region.
OsmAnd 4.3.1 

![image](https://user-images.githubusercontent.com/44466116/209556136-b8a60c5b-15a4-4e4c-8e00-19d9599ff1df.png)

**Comment by Zirochkabila** [comment]
Done in master branch


https://user-images.githubusercontent.com/104760013/212674699-2aa22b65-7331-452d-a4c2-34bc068ad314.mov
