### ISSUE TITLE
“Send Anonymous Data” switched on automatically 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2419]
Tested on 4.3.1

### How to reproduce
* Run OsmAnd
* Open **Menu** – **Settings** – **OsmAnd Settings**
* Turn off **Send Anonymous Data**
* Restart **OsmAnd**
* Open **Menu** – **Settings** – **OsmAnd Settings**
* **Send Anonymous Data** will be turned on again

### ToDo
- [ ]  Switch status change should be saved.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/209656245-7e34c92e-2ce5-48a0-a81e-2bfbb44caccc.MP4"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by EugeneZmeuk** [comment]
https://user-images.githubusercontent.com/44466116/209662833-eb6abe51-1cda-4eaf-b15c-3b4ebfd61e7e.mov

**Comment by Zirochkabila** [comment]
4.4.3.1
Done
