### ISSUE TITLE
iOS logs

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2422]
Freeze while opening Maps and resources. OsmAnd 4.3

[Dez. 25, 2022 01_11.log](https://github.com/osmandapp/OsmAnd-iOS/files/10319913/Dez.25.2022.01_11.log)
[Dez. 25, 2022 01_16.log](https://github.com/osmandapp/OsmAnd-iOS/files/10319914/Dez.25.2022.01_16.log)
[Dez. 25, 2022 01_17.log](https://github.com/osmandapp/OsmAnd-iOS/files/10319915/Dez.25.2022.01_17.log)
[Dez. 26, 2022 23_37.log](https://github.com/osmandapp/OsmAnd-iOS/files/10319916/Dez.26.2022.23_37.log)
[Dez. 27, 2022 18_44.log](https://github.com/osmandapp/OsmAnd-iOS/files/10319917/Dez.27.2022.18_44.log)

**Comment by anastasiia936** [comment]
[dic 26, 2022 07_43.log](https://github.com/osmandapp/OsmAnd-iOS/files/10319964/dic.26.2022.07_43.log)
[dic 26, 2022 13_32.log](https://github.com/osmandapp/OsmAnd-iOS/files/10319965/dic.26.2022.13_32.log)
[dic 26, 2022 18_58.log](https://github.com/osmandapp/OsmAnd-iOS/files/10319966/dic.26.2022.18_58.log)
[dic 26, 2022 20_10.log](https://github.com/osmandapp/OsmAnd-iOS/files/10319967/dic.26.2022.20_10.log)
[dic 28, 2022 18_40.log](https://github.com/osmandapp/OsmAnd-iOS/files/10319968/dic.28.2022.18_40.log)

**Comment by vshcherb** [comment]
No valuable information present probably it's related to purchases which were just fixed
