### ISSUE TITLE
Filter subtypes include type in name

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2423]
## How to reproduce
* Open OsmAnd,
* Open **Menu** select **Search**
* Select **Categories**, select **Cafe and restaurants**
* On the screen with search results, tap on filter icon

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/209967302-dc83a782-5ceb-44f0-9aa4-b3b3ea7e4527.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/209967308-5e9f0a68-d6e1-4e4f-bbf6-ec090eab806e.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Android supports with translation and without any duplication

![telegram-cloud-photo-size-4-5880001492163869972-y](https://user-images.githubusercontent.com/1042025/210250790-5644871e-233f-4330-9850-95128d8347ce.jpg)

![telegram-cloud-photo-size-4-5880001492163869971-y](https://user-images.githubusercontent.com/1042025/210250802-4be8d6b2-87b6-4c0e-bc91-b918b31df001.jpg)

**Comment by Zirochkabila** [comment]
4.4.4.2
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/213219916-60596ac7-d8b5-444c-a6ed-0edd4425356c.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
