### ISSUE TITLE
Unit of length and 'Nautical miles/feet', rename 'Nautical miles'

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2424]
Android task https://github.com/osmandapp/OsmAnd/issues/15724

## ToDO
We need to add new **Unit of length** option to display Nautical miles with feet and rename current **Nautical miles** to **Nautical miles/meters**.
- [x]  Rename **Nautical miles** to **Nautical miles/meters**
- [x] Add **Nautical miles/feet**

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/201691129-6d69bcee-af84-492c-b111-1ca9e4e3cddb.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.4.2
Done

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/213218030-08b69a93-d61a-4c31-93c6-b179ec75aef6.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2461/commits
