### ISSUE TITLE
OsmAnd 4.3.3 crashes during open Edit track menu

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2430]
OsmAnd 4.3.3

In the log was only this:
libc++abi: terminating with uncaught exception of type std::invalid_argument: Locations index: 444 out of bounds.

**Comment by EugeneZmeuk** [comment]
[Sun 01 Jan 2023.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10338464/Sun.01.Jan.2023.zip)

**Comment by EugeneZmeuk** [comment]
[Jan 03, 2023 18_20.log](https://github.com/osmandapp/OsmAnd-iOS/files/10338537/Jan.03.2023.18_20.log)

**Comment by Zirochkabila** [comment]
4.4.4.2
Done
