### ISSUE TITLE
Add Favorites search

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#2431]
**Request**
Add My Places / My Favorites search. In the Android version, this option is realised.

**ToDo**
- [x] Add Favorites search.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/210370241-0b864c9a-9a2b-4069-a260-8f5171b3a271.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/210370261-9a1d979c-d5da-4c79-b6b1-5471fe366b9c.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
# ToDo

<table style="width:100%">
  <tr>
    <th>Default state</th>
    <th>Pull down</th>
    <th>Search screen</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/220636520-e4ffb184-472f-4d0b-bfb7-319e09541626.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/220636526-175ed87b-1abc-47a7-a865-956f6e3a3eae.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/220636503-8c2c9bef-a0c9-4187-9ed5-49672d989d19.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2612/files

**Comment by Zirochkabila** [comment]
03.03 master 
Done

**Comment by dmpr0** [comment]
# Review
Large appBar is appears on scroll down with black text.
- [ ]  Fix text color or don't show large NavBar.
<img src="https://user-images.githubusercontent.com/9365308/222766356-2621ca32-d56b-4eae-9850-c89a307496e0.jpg"  width="300" height="auto"/>

**Comment by Skalii** [comment]
[Fix favorites navbar](https://github.com/osmandapp/OsmAnd-iOS/pull/2644)

**Comment by Zirochkabila** [comment]
4.4.6.6
iPad
13.03 
master branch Xcode
Not reproduced - Done
