### ISSUE TITLE
Dialog suggests to download already downloaded maps

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#2434]
I downloaded all maps for Netherlands by "Select all"  in the "Map" folder :
![image](https://user-images.githubusercontent.com/44466116/211031716-2e5c6f79-023f-43f1-9148-59d2400bde46.png)

All maps were downloaded and shown on Global map, and the "Map" folder is green:
![image](https://user-images.githubusercontent.com/44466116/211032000-3f55e990-f4ce-4e52-97a0-b93e52f5d329.png)
![image](https://user-images.githubusercontent.com/44466116/211032062-d254720b-79e7-45cb-8bc4-d30fad84cbe8.png)

But when I click to "Map" , it propose me to download all maps again:
![image](https://user-images.githubusercontent.com/44466116/211032283-4d6b70f4-2671-49bf-978b-41287e6b38d2.png)

**Comment by kuiperonline** [comment]
Is this solved?

**Comment by EugeneZmeuk** [comment]
For the last release (4.3.3), this issue is not fixed yet.

**Comment by DmitryAlexei** [comment]
OsmAnd 4.4.5.4
Reproduced.
You can download already downloaded map of Netherlands. 

<details><summary>You can download already downloaded maps</summary>
<video src="https://user-images.githubusercontent.com/116079541/220418289-c87eecdd-7628-42a6-ac7d-4882422d6513.mp4"></video>
</details>


<details><summary>Error on the second download</summary>
<video src="https://user-images.githubusercontent.com/116079541/220425617-ed7053e6-75ae-4ea1-914d-904a6c531302.mp4"></video>
</details>

**Comment by Zirochkabila** [comment]
25.02
Done

**Comment by dmpr0** [comment]
Done it TestFlight 4.4.6.1, will be a part of 4.4 release.
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/221912351-7b0e8b11-6350-4861-8ed4-cc7f8a3f4c22.PNG"  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by kuiperonline** [comment]
Can I download the testflight version? I have testflightVincentOn 28 Feb 2023, at 19:16, Dmytro Prodchenko ***@***.***> wrote:﻿
Done it TestFlight 4.4.6.1, will be a part of 4.4 release.

**Comment by dmpr0** [comment]
@kuiperonline Yes, of course https://testflight.apple.com/join/7poGNCKy
