### ISSUE TITLE
OsmAnd freezes while closing 'follow track' in navigation settings menu

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#2435]
Open Navigation > Settings > Follow track and swipe this menu down > OsmAnd freezes (see video)
When you choose "Cancel" instead of swiping, everything works fine

https://user-images.githubusercontent.com/116079541/211054702-2ea724be-8e0c-492b-8d13-bc4dcef16892.MP4

**Comment by Zirochkabila** [comment]
@DmitryAlexei Can you add log file, please: Files (Device) > On My Device > OsmAnd Maps > Logs > The last one

**Comment by DmitryAlexei** [comment]
[Jan 09, 2023 15_59.log](https://github.com/osmandapp/OsmAnd-iOS/files/10373337/Jan.09.2023.15_59.log)

**Comment by Zirochkabila** [comment]
4.4.3.1
Not reproduced

**Comment by Zirochkabila** [comment]
4.4.4.3
Done
