### ISSUE TITLE
Searching objects with special characters - use collator

### ISSUE THREAD

**Issue by mguaylambert** [osmandapp/OsmAnd-ios#244]
When you search objects with the search menu, special characters are considered "as is" making search in latin languages hard.

It is sometime called : Variations in User Input

For example, searching : "Plongee" (for convenience or lack of knowledge on how it is written) might want to return : "Plongée" results.

Example of character sets that might want to be matched :
A = À, Â, Á, Ä, Ã, Å, Ā
AE = Æ
E = É, È, Ê, Ë, Ę, Ė, Ē
I = Î, Ï, Ì, Í, Į, Ī
O = Ô, Ö, Ò, Ó ,Õ , Ø, Ō
OE = Œ
U = Û, Ù, Ü, Ú, Ū
Y = Ÿ
C = Ç, Ć, Č
N = Ñ, Ń

Commas : ´,' (and other special characters)

Search result example :
![image](https://user-images.githubusercontent.com/16389438/55281894-d171f780-5310-11e9-8fe0-ac30cd719f6e.jpeg)
![image](https://user-images.githubusercontent.com/16389438/55281895-d171f780-5310-11e9-965d-a443383bd8df.jpeg)

**Comment by crimean** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-core/commit/f9012393b68eecf94dd1fbaf3a7a1474ecf6ecae
