### ISSUE TITLE
The sync button doesn't work when you click on the sync icon (the one on the right)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2448]
### Description
The sync button doesn't work when you click on the sync icon (the one on the right) - works only after clicking on Sync now 

### Steps to reproduce
Menu > Settings > OsmAnd cloud 

### Actual result
The sync button doesn't work when you click on the sync icon

https://user-images.githubusercontent.com/104760013/211828211-c1c8f409-3226-4d46-b098-014226e20167.mp4

### Expected result
Synchronization starts both after clicking on Sync now and on the icon on the right

### Your Environment
OsmAnd Version: 4.4.3.1
Android/iOS version: iOS 15.7.1
Device model: iPad mini 4

**Comment by Skalii** [comment]
[Cloud - fix pressing sync button r4.3](https://github.com/osmandapp/OsmAnd-iOS/pull/2473)

**Comment by Zirochkabila** [comment]
4.4.4.3
Sync now button is work
But

- [ ] Cancel button doesn't work
- [ ] if start synchronization > exit and re-enter the page > the synchronization progress is constantly spinning, doesn't stop


https://user-images.githubusercontent.com/104760013/213682101-d25d94ba-6158-4a32-bdae-eae588f54e78.mp4


https://user-images.githubusercontent.com/104760013/213682126-99a706b6-6acf-475a-a5e4-5cbeb981b77a.mp4
