### ISSUE TITLE
POI overlay not working for all POIs beyond ~174.3746E degrees of longitude (for instance New Zealand North Island, Fiji island).

### ISSUE THREAD

**Issue by scit2010** [osmandapp/OsmAnd-iOS#2449]
Hi, 

the POI overlay in the map of New Zealand only highlights POIs on the west side of North Island with a round, orange handle.

Environment
------------
I'm using OsmAnd 4.3.3 on iOS 16.2.

Steps to reproduce
------------------
1. Download the map of New Zealand
2. In the main menu select "Configure map"
3. Select menu item "POI overlay"
4. Activate one or all POI types
5. Return to the map

Expected result
-----------------
OsmAnd highlights all POIs on New Zealand's North island with a round, orange handle, i. e. also on Coromandel Pensinsula or in Gisborne.

Actual result:
-------------
OsmAnd highlights only POIs on New Zealand's North Island west side, see attached screenshot.

I have tried this many times and also deleted and reloaded the map. The result stays the same. 

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/2828370/211907459-71b2cf24-0d7f-47fd-826f-f9cb038efbf9.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.4.0


https://user-images.githubusercontent.com/104760013/212364945-40901dab-ecb2-446e-bd64-baff77f923d3.mp4

**Comment by vshcherb** [comment]
Algorithm is not designed to search on such base levels - Android search only on zoom 8, so here it won't be a problem if we limit slightly more or fix the base algorithm

**Comment by scit2010** [comment]
Some more information from my side:

1. It seems a problem of the iOS version only. I just tried with OsmAnd 4.3.6 on Android. It shows the POIs on the east side of NZ Northern Island, which are missing in the iOS version.
2. On iOS: It is not only a problem of the NZ map, but also other maps that are beyond ~174,3746 East degrees of longitude. You can see it at Fiji island of the Ozeanian map or with the far east of Russia (Chukchi county, Kamchatka).

**Comment by Zirochkabila** [comment]
POI are displayed on Android, but not on iOS
OsmAnd~ 4.4.0#14173mqta, Released: 2023-02-13
4.4.5.5

<details><summary>Fiji</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/218498366-ab292308-a7ca-4a3a-af97-dac73bf37abe.jpeg">
<img width="240" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/218498395-a87f39e7-e39f-4ef2-8ec9-17f47a254a92.jpeg">
</details>

<details><summary>NewZealand</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/218499019-ff2c80fb-adc0-4f84-bd3f-20da282a4f49.jpeg">
<img width="240" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/218499023-7c3580e7-4003-4389-8829-0c2a0c352b85.jpeg">
</details>

**Comment by DmitryAlexei** [comment]
4.4.5.4
POI overlay set to show _Nearest POIs_
New Zealand, Oceania and Papua New Guinea maps are downloaded

- POI are not shown on Oceania map within about 500 kilometer zone from its incorrectly displayed borders. This partially affects New Zealand, Fiji, Tuvalu, Kiribati.

<details><summary>No POI Fiji</summary>
<video src="https://user-images.githubusercontent.com/116079541/220435442-b78dcb2b-a7de-4055-aff1-25384e42a2ed.mp4"></video>
</details>

<details><summary>No POI New Zealand</summary>
<img width="300" alt="2023-02-21_22-12-47" src="https://user-images.githubusercontent.com/116079541/220437508-204cbb8a-b720-47d7-9d3d-f35d2581effb.jpg">
</details>

<details><summary>No POI Tuvalu, Kiribati</summary>
<img width="300" alt="photo_2023-02-02 12 23 12" src="https://user-images.githubusercontent.com/116079541/220436652-0a0ff42e-a080-46d4-9c23-64945083a7a7.jpg">
</details>

Possible cause:
- Borders of downloaded Oceania map are displayed incorrectly: Cook Islands, Tokelau, Samoa, Tonga, Niue aren't shown in green. When you move the map to the east, borders of downloaded map (green color) disappear. 

<details><summary>Incorrect borders of Oceania</summary>
<img width="300" alt="photo_2023-02-21_21-43-38" src="https://user-images.githubusercontent.com/116079541/220432314-1bbb71d5-8343-4593-941b-1e1883a65eb0.jpg">
</details>

<details><summary>Borders disappear</summary>
<video src="https://user-images.githubusercontent.com/116079541/220433605-c1b45f54-6572-4a92-ac1f-0243d26f0d70.mp4"></video>
</details>

**Comment by DmitryAlexei** [comment]
Alaska map and POIs on some islands also incorrectly displayed.

<details><summary>Incorrect borders of Alaska and absence of POIs on some islands</summary>
<video src="https://user-images.githubusercontent.com/116079541/220451951-8fe42e6c-2268-4b67-af55-2ffbfa0a9111.mp4"></video>
</details>

For comparison. Android shows some POIs on west Aleutian Islands, but not all from the OSM.

<details><summary>51.99728° N, 178.16598° E </summary>
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/220458023-49d3b2cc-8cf5-4361-82ab-fb44d945eb12.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/220456252-a9a6441e-0fed-4454-bebc-27d5063ed5a6.jpg"  width="300" height="auto"  width="300" height="auto"/> </th>
  </tr>
</table>

</details>

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/488

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-iOS/issues/2449#issuecomment-1445393562

**Comment by Zirochkabila** [comment]
28.02 master
Done

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/491
