### ISSUE TITLE
OsmAnd navigation routes on linear distance

### ISSUE THREAD

**Issue by scit2010** [osmandapp/OsmAnd-iOS#2450]
Sometimes the navigation feature proposes routes along the linear distance which are impossible to use. 
This is especially misleading and annoying when travelling through unknown territory, trying to find a POI, trusting OsmAnd and just to end up stuck in a forest. 
I explain by example of finding a car route. 

Environment
-------------
OsmAnd 4.3.3 on iOS 16.2., but this also occurred in earlier versions.

Steps to reproduce
-------------------
1. Choose a target which is not reached by a street, e.g. a mountain top or lookout in the wilderness.
2. Select "Navigation" and then the Car icon. 
3. Tap "Start" and wait until OsmAnd has found a route.

Expected result
============
OsmAnd routes the car to a point closest to the target, where the user can park the car and continue by another transportation or by foot. If the target is unreachable by any transportation or foot, then behave somehow intelligent, for instance route to the closest point and tell the user about it or propose a parking ground close to the target.

Actual result
=========
OsmAnd routes to the point, which is closest to the target, and continues with the linear distance. But the linear distance is not a usable way (except the transportation is an air taxi, which is usually not the case).
See attachment for an example:

![Bugreport navigation along direct line](https://user-images.githubusercontent.com/2828370/211917400-ffc91efa-4345-434a-9755-4fefa9eda823.png)

**Comment by vshcherb** [comment]
As I see it's not reproducible with latest maps https://osmand.net/map?start=54.215241%2C10.722485&end=54.210787%2C10.723665&mode=car#16/54.2118/10.7243
