### ISSUE TITLE
Lane guidance ignores “none”

### ISSUE THREAD

**Issue by made2k** [osmandapp/OsmAnd-iOS#246]
While navigating with land guidance, if an intersection is approached with some lanes with right or left turn restrictions, the app will show those restrictions but will not show the additional lanes if those are marked as none.

The OSM feature I’m talking about is indicated here https://wiki.openstreetmap.org/wiki/Key:turn

I would say, with the example of a road with the key value `turn:lanes=left|||right` the results would be as followed.

Expected result:
Lane guidance shows 4 lanes, left most lane shows a left turn, two middle lanes show straight, right most lane shows a right turn. 

Actual result:
Lane guidance shows 2 lanes, left lane shows a left turn, right lane shows a right turn.

**Comment by vshcherb** [comment]
By default words: none or straight are supported.

**Comment by made2k** [comment]
It must be the implicit none then (when you have lanes marked without any characters and just the pipe character to split another lane), I can check the raw OSM data at some intersections around me and report back if that’s the case. Thanks for the heads up on what is supported already!

**Comment by made2k** [comment]
I found some intersections that had explicitly labeled "none" instead of the shorthand (`left|none|right`). And those appeared correctly in the app showing a `left arrow, straight arrow, right arrow`. 

I also drove through some intersections that used the implicit none where the word is left out and the delimiters only are used  (`left||right`). This did not appear correctly in the app. Instead it showed `left arrow, right arrow` and ignored the middle lane.

From a usability perspective, I would expect that the implicit none is handled in the same way that `none` is handled for turn lanes. Maybe this issue can be used to help track this and keep an eye on it for a future update if you guys think this would be the desired behavior. Thanks!

**Comment by vshcherb** [comment]
The issue is not reproduced anymore
