### ISSUE TITLE
Custom profiles get disabled after restart

### ISSUE THREAD

**Issue by juliusvaart** [osmandapp/OsmAnd-iOS#2460]
Custom profiles won’t persist. Settings stay but the profiles are disabled when restarting the app.

V4.3.2 AppStore

![998562E4-2CC9-4D9A-AAC8-DA4E690EC280](https://user-images.githubusercontent.com/764084/212267147-66f73da9-ee42-4d70-9b73-ddf70f723248.jpeg)

After closing and reopening app:

![7F00A975-B00F-46CE-A9F1-5095BBB2173C](https://user-images.githubusercontent.com/764084/212267281-652b8d12-ee75-4fa6-b40c-e1fe31bfadc8.jpeg)

**Comment by EugeneZmeuk** [comment]
I reproduced this bug

**Comment by Zirochkabila** [comment]
4.4.4.0

[Volvo XC70.osf.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10412364/Volvo.XC70.osf.zip)


https://user-images.githubusercontent.com/104760013/212344317-55a65a57-f0cb-43fd-aa69-45f4f0ae0e43.mp4

**Comment by Skalii** [comment]
[Custom profiles - fix list of active on app start r4.3](https://github.com/osmandapp/OsmAnd-iOS/pull/2467)
