### ISSUE TITLE
Missing Speedlimit signs in Carplay when in profil enabled

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd-iOS#2462]
### Description
Speed Limit Option enabled in Car profile option
Set Carplay to car profile

no speedlimits are showing on the screen while driving.

### How to reproduce?
enable speedlimit and drive with carplay screen

### Your Environment
OsmAnd Version: 4.3.3
iOS version: 16.2
Device model: 14 Pro

**Maps used (online or offline):**   
online and offline map with 1h update

**Comment by vshcherb** [comment]
It's not present in application itself, so it's a missing widget itself and not car play issue.

**Comment by Zirochkabila** [comment]
Speed limit warning has already been added to CarPlay (4.4.4.0) but now the [issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2464) with empty warnings is being solved

**Comment by dmpr0** [comment]
Speed limit sign is working, issues with empty sign should be fixed.

**Comment by vshcherb** [comment]
We have separate issue for widget displaying the current speed
