### ISSUE TITLE
Overspeeding sign is empty

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd-iOS#2464]
### Description
when overspeeding carplay is showing an empty 250 sign instead of the real speed limit

![IMG_0966](https://user-images.githubusercontent.com/35132439/212334509-a2ff07e5-e9e1-4c35-9fd0-1353beae3e0c.PNG)

### How to reproduce?
drive faster than allowed ;)

### Your Environment
OsmAnd Version: 4.3.3
iOS version: 16.2
Device model: 14 Pro

**Maps used (online or offline):**   
online and offline map with 1h update

**Comment by Zirochkabila** [comment]
4.4.4.0

![photo_2023-01-13 17 46 56](https://user-images.githubusercontent.com/104760013/212360944-151b30fe-46ef-4517-827a-8c6210c1ffc0.jpeg)

**Comment by Zirochkabila** [comment]
05.02.2023 Master branch - Done

<details>
  <summary>Speed limit</summary>
  <p><img width="690" alt="Screenshot 2023-02-05 at 17 36 35" src="https://user-images.githubusercontent.com/104760013/216829037-27016bf4-ed7b-4259-9779-1c34f57110f5.png"></p>
</details>

**Comment by dmpr0** [comment]
Done
<img src="https://user-images.githubusercontent.com/9365308/217571588-90e73e75-e0f5-4e84-8cf3-1521c08aa071.PNG"  width="800" height="auto"/> 
<img src="https://user-images.githubusercontent.com/9365308/217571610-a384a551-a5aa-4d50-b297-b497ed9bc8ae.PNG"  width="300" height="auto"/>

**Comment by WizoneDE** [comment]
Is it still only overspeeding or permanent speed sign?

**Comment by dmpr0** [comment]
> Is it still only overspeeding or permanent speed sign?

It shows max speed on current part of the road.

**Comment by WizoneDE** [comment]
Than it is broken in 4.4.5.4
Sign only appears when overspeeding

**Comment by vshcherb** [comment]
It shows max speed when overspeeding, for constant max speed it's not being implemented at all - only design phase (so it was never working android / iphone)

**Comment by WizoneDE** [comment]
Any chance to see the concept to maybe give feedback ? 🙈

**Comment by vshcherb** [comment]
@WizoneDE here is a discussion for your issue - so it's offtopic here https://github.com/osmandapp/OsmAnd/issues/13413
