### ISSUE TITLE
CarPlay: Search only works for addresses 

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd-iOS#2466]
### Description
There is currently no way to search for a POI based on its name like in the phone search. (or in every other routing app)

### How to reproduce?
try to search for a poi name in carplay.

### Your Environment
OsmAnd Version: 4.3.3
iOS version: 16.2
Device model: 14 Pro

**Maps used (online or offline):**   
online and offline with 1h update

**Comment by Skalii** [comment]
Included in issue https://github.com/osmandapp/OsmAnd-Issues/issues/1816

**Comment by Zirochkabila** [comment]
05.02.2023 Master branch
POI search is working

https://user-images.githubusercontent.com/104760013/216829493-97a7f017-4cb9-4d5c-aea1-3a03a996a4b6.mov



But Favorites search **doesn't** work


https://user-images.githubusercontent.com/104760013/216829619-07656f70-a35e-4770-aaa8-5d4a457a61f1.mov
