### ISSUE TITLE
Sqlitedb bug

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd-ios#247]
Hi. Please tell me how to install new sources of online maps on the IOS version of the Osmand application. I do the following:

1. I downloaded the map sources in sqlitedb format. I tested them on Android and they work well. Here are some of these files.  https://yadi.sk/d/0kwWqvhrA9SfVQ
2. I downloaded files from my computer to my phone via iTunes.  But I was advised to add them not to Osmand, but to some File Manager. I chose the Documents app for this purpose.
3. From my smartphone, I opened these files in the Documents app. In the pop-up menu, I selected Copy to Osmand.
4. The Osmand app started and showed me a text message.

For some maps, for example, "TopoMap (marshruty)", there is a error message. In this case, nothing appeared in the map list .

For others - "Yandex_Sat" - a message appears about the successful import.  After that, the imported map really appears in the list with the overlays. However, when I open this new map nothing happens: the map tiles are not loaded.

And this happens with all Sqlitedb files. On Android everything works fine, and on IOS - absolutely not.

Maybe I'm doing something wrong. Or maybe they need to be installed somehow differently? Tell me if you know. Or is it just a bug of IOS version?

Just in case, here are screenshots of all my actions and error messages. https://yadi.sk/d/quOkqO5Di_yUqQ

(IOS 12.1.4  Osmand 2.62)

**Comment by PaulStets** [comment]
@nnngrach Could you please upload the files to Google Drive or Dropbox? Unfortunately, the links you provided aren't available for me.

**Comment by nnngrach** [comment]
Ou. That’s it 

Sqlitedb files

https://www.dropbox.com/sh/06ukluiwvjfy0ki/AAAW3kUEny77XfxF-hOHaEaXa?dl=0



Screenshots

https://www.dropbox.com/sh/yseqa9x1ann570y/AADOTY5fQ7fp_7wApbNNP2O0a?dl=0

**Comment by PaulStets** [comment]
@nnngrach Thanks, I'll take a look.

**Comment by PaulStets** [comment]
Hi, @nnngrach. I have added online Sqlite support with https://github.com/osmandapp/OsmAnd-ios/pull/472 and https://github.com/osmandapp/OsmAnd-core/pull/97. You can now use the SQLite files from your collection. Please note, however, that you cannot use the BeanShell Sqlite maps, as there is no way to run BeanShell on iOS. Instead, I have added support for the ```rnd``` URL tag placeholder. You can use it like this: ```http://mt{rnd:0,1,2,3}.google.com/vt/lyrs=t@130,r@206000000&hl=ru&x={1}&y={2}&z={0}&s=Galileo&scale=1&hl=en";```. You can test it in the TestFlight build 3.08, which will be out soon. Let us know if you have any issues.

**Comment by nnngrach** [comment]
Hi, @PaulStets . Thank you all for implementing this feature!

I installed Test Flight, tested the beta and noticed a few bugs.


First.

Here is example of map without any scripts. Work correctly. 
https://anygis.ru/api/v1/Tracks_Strava_All_HD/{1}/{2}/{0}

Here is an example URL with a script that accepts numbers. Work correctly. 
https://m{rnd:1,2,3,4}.mapserver.mapy.cz/base-m/{0}-{1}-{2}

Here is an example URL with a script that accepts letters. Does not work.
http://{rnd:a,b,c}.tile.openstreetmap.org/{0}/{1}/{2}.png

Can be it is possible to make so that function rnd accepted on an input only letters? For example:
{rnd:'1','2','3','4'}
{rnd:'a','b','c'}


Second.

Here is a map of an elliptical projection. The ellipsoid field is set to 1. But tiles are displayed with an offset.
http://sat0{rnd:1,2,3,4}.maps.yandex.net/tiles?l=sat&x={1}&y={2}&z={0}&lang=ru


That's all I've noticed so far. Thanks again!

**Comment by PaulStets** [comment]
Hi, @nnngrach. Thank you for the feedback. I have fixed the ```rnd``` issue. However, I cannot access the ellipsoid map from the example, because Yandex services are blocked where I live. Could you please provide another map with elliptical projection?

**Comment by nnngrach** [comment]
Hi, @PaulStets. In this case, I'm afraid that other similar maps may be blocked too. 

Try using this URL. It allows you to download map tiles via proxy.

https://anygis.ru/api/v1/Yandex_sat_clean_WGS84_proxy/{1}/{2}/{0}

Or here is a ready sqlitedb file with this URL.

https://www.dropbox.com/s/cmuudpay1hmba0w/ellipsoid_map__yandex_proxy.sqlitedb?dl=0

**Comment by PaulStets** [comment]
@nnngrach Thanks for the link, I will check it soon.

**Comment by nnngrach** [comment]
@PaulStets, do you know, will this `rnd` script work on Android too?

**Comment by PaulStets** [comment]
It is not supported at the moment, but I'm sure it will be ported pretty soon.

**Comment by max-klaus** [comment]
> @PaulStets, do you know, will this `rnd` script work on Android too?

Should work now in the nightly build.
