### ISSUE TITLE
Track recording issue

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2472]
I started recording a track and when I lock the device, record stopped and drew a straight line to the finish point.
OsmAnd 4.3.3
Location permission tested with the Always allow and while using the app. 

![image](https://user-images.githubusercontent.com/80623554/212640014-838a7be7-a755-48dd-9a25-91a7f7b2322f.png)
[2023-01-14_18-30_Sat.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10424157/2023-01-14_18-30_Sat.gpx.zip)

<trkpt lat="50.4480840" lon="30.5057290">
                <ele>98.1</ele>
                <time>2023-01-14T16:36:01Z</time>
                <extensions>
                    <osmand:speed>1.8</osmand:speed>
                </extensions>
            </trkpt>

not filtered - and it has no hdop
```
  <trkpt lat="50.4480840" lon="30.5057290">
<trkpt lat="50.4480840" lon="30.5057290">  
```

without hdop should have filtered out

**Comment by Zirochkabila** [comment]
4.4.5.3 
Done

**Comment by dmpr0** [comment]
Tested for 70 hours, all works well.
