### ISSUE TITLE
Feature request: Add a keybinding to switch to next profile

### ISSUE THREAD

**Issue by joostbijl** [osmandapp/OsmAnd-iOS#2476]
When you are riding on your motorcycle you have different needs (for Osmand) at different moments. A typical day for me would be that I start riding on an offroad trail using the osmand offroad map with very little detail other than tracks and hills. At some point I need fuel or food so i want a view that shows me fuel & supermarket PoI. At the end of the day I'm on the lookout for a camp site and like to see where they are, preferably on a regular street map so that i can quickly go there. 

Osmand already has profiles that can be set up pretty much to suit each of these preferences described above. 

I'm using a keyboard to control Osmand from the handlebars (https://jaxeadv.com/barbuttons/) and I'd like to be able to cycle through the different profiles. I'd be very happy if Osmand would go to the next profile when i hit 'P' on the keyboard. 

Thanks for considering!

**Comment by joostbijl** [comment]
Hi @vshcherb, thanks for considering this request. You added the label next-iOS, but this potential feature should also apply to Android i think?

**Comment by dmpr0** [comment]
Added as part of the https://github.com/osmandapp/OsmAnd-iOS/issues/2698.
Can be tested on TestFlight https://testflight.apple.com/join/7poGNCKy

**Comment by Zirochkabila** [comment]
4.4.8.4
When opening Configure map, the profile icon does not change - it seems that switching profiles changes in the background


https://user-images.githubusercontent.com/104760013/236237656-fbfd9b02-5231-43f7-9a63-c3dcc7140642.mov

**Comment by Skalii** [comment]
[External input - fix ui update after profile change](https://github.com/osmandapp/OsmAnd-iOS/pull/2871)
