### ISSUE TITLE
Hanging on tapping a bus icon

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd-ios#248]
When tapping on a local bus icon in Germany/Saxonia/Pirna, the app freezes.
OsmAnd Maps 2.6, iPhone X with current iOS.

**Comment by PaulStets** [comment]
No longer reproducible. Tested in Pirna and Dresden. Perhaps it was connected to the route color issue that was already fixed. In case the issue persists, please send the coordinates of a bus stop where it happens.
