### ISSUE TITLE
Some poi’s shows Name brand and operator

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd-iOS#2480]
### Description
On some poi’s the map is showing the name, operator and brand which is way too much information on the map.

If a name is set only this should show up.
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/35132439/213105040-0793dec2-b5ea-49b4-b627-016fd1e75241.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/35132439/213105058-d6c7e4ff-317c-4912-894e-3ed8408f13ad.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/35132439/213105065-cbde9d80-1c40-4bb1-b2a7-6072680a441d.png"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: ios16.2
Device model: 14Pro

**Maps used (online or offline):**   
Online and offline

**Comment by vshcherb** [comment]
There is a public beta where issue with map updates was fixed it's probably related that map update is not working correctly, it was recently fixed in Android cause it was not 100% reproducible

**Comment by xmd5a2** [comment]
Dev notes: this only affects OpenGL.
Legacy:
![Screenshot_2023-01-30_17-03-06](https://user-images.githubusercontent.com/5829014/215498519-20345755-ede9-48ae-80dd-bb3b0d906c45.png)
OpenGL:
![Screenshot_2023-01-30_17-02-54](https://user-images.githubusercontent.com/5829014/215498562-08c659ff-083e-47cb-b245-1a0d4a22596e.png)
[Style code](https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L5852) should try `name` tag first, if it is not found then `brand` and then `operator`
This works in legacy but not in OpenGL. OpenGL renders all of name tags and behaves differently than legacy engine. I don't know how to fix it in rendering style.

**Comment by ivanPyrohivskyi** [comment]
Need check this fix on syntetic test rendering

**Comment by Zirochkabila** [comment]
Live updates Done too

<details><summary>OsmAnd~ 4.4.0#14194mqta, Released: 2023-02-22</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/220661223-0402a9df-44d0-4d81-b6da-98be14d6ca3a.jpeg">
</details>

<details><summary>22.02.23 master</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/220661405-7f8d513d-48d1-4d41-9172-92517a1ac16a.png">
</details>
