### ISSUE TITLE
personal favorite folder broken (outside of english users)

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd-iOS#2487]
### Description
"personal" favorite folder is broken, (maybe only out of english users)

- have home set via personal favorit
- added another poi as normal favorite
- added now another personal favorite and marked it to the folder "personal/Persönlich"

app created a second "Persönlich" folder within the app. 
on carplay you can see a difference between the new and the old folder:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/35132439/213459708-0cfebd57-c13a-42ce-826a-0e9a7a44e7dd.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/35132439/213459713-4bcaf49c-17c3-4bf6-8b3c-ff4d0ab1b57c.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/35132439/213459714-1ffe3317-ab40-4c68-8a47-2e30af8f3fb9.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/35132439/213459718-4b309b9d-24d8-4f0c-8521-92732d500dfe.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/35132439/213459758-d5d76ca4-df48-4e99-bdd7-c261d3ac4060.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/35132439/213459762-74062b63-3c82-4e8d-b28b-1d6c74d0a33c.png"  width="300" height="auto"/> </th>
  </tr>
</table>   

### How to reproduce?
set language to german
save a poi as favorite in your personal "Persönlich" folder

### Your Environment
OsmAnd Version: 4.3.3
Android/iOS version: ios16.2
Device model: 14 pro

**Maps used (online or offline):**   
Online and offline map with 1h update

**Comment by WizoneDE** [comment]
I don’t know if it is only happening in iOS but ok. Will now create issues I find in the iPhone only in the iOS sub area 👍

**Comment by Zirochkabila** [comment]
Master branch
With the Personal folder - **can't reproduce**

https://user-images.githubusercontent.com/104760013/213912925-23fd2c15-6383-4bcd-b17f-b457f583f862.mov



With the Persönlich folder, the folder could not be created to test. **But this may be the cause of the problem** @PaulStets 


https://user-images.githubusercontent.com/104760013/213912937-68b53579-8d2a-4af5-968a-000ed68e14aa.mov

**Comment by WizoneDE** [comment]
Don’t create a new folder. Just use the two existing. 

Add home address to favorites (personal folder)

than add a normal favorite and select personal
Folder too. The normal Favorit will be created into a second folder if the name of both differ by language.

looks like the home favorite is fix set to local lang personal and the normal fav mapping to personal is using the device Lang for personal which Is not existing so it will create a normal favorite folder names Persönlich in German lang

**Comment by WizoneDE** [comment]
added more information in post before

**Comment by Skalii** [comment]
[Fix favorite - personal group](https://github.com/osmandapp/OsmAnd-iOS/pull/2526)

**Comment by Zirochkabila** [comment]
05.02.2023 Master branch - Looks like it's fixed

**Comment by dmpr0** [comment]
Available in TestFlight 4.4.6.1
