### ISSUE TITLE
Edit menus is flying from the top left side of the screen

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2488]
## How to reproduce
* Select any point on the map
* In context menu tap on **Details**
* On section with coordinates, tap on **arrow**
* Tap on any button with coordinates
* Edit menu will fly over from the left side of the screen

## Expected
Popup should appear in place

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/213499047-b4f0a607-7856-4521-bebf-baadaae1a37b.MP4"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
OsmAnd 4.4.5.4
Did according to the guide from above. Not repoduced.

<details><summary>Video Tap on coordinates</summary>
<video src="https://user-images.githubusercontent.com/116079541/220404484-38c3995f-9803-494a-adaf-f2d98f3d54e2.MP4"></video>
</details>

**Comment by Zirochkabila** [comment]
03.03 master
Done
