### ISSUE TITLE
Functionality request: Export route as GPX file

### ISSUE THREAD

**Issue by TheAquaMan** [osmandapp/OsmAnd-ios#249]
Hello,
I would like to ask you to add functionality which would allow user to save calculated routes to "My Trips" and export them as GPX files.
This functionality will make your app really outstanding.
Thank you for you work :)
Regards, Vladimir

**Comment by pqhf5kd** [comment]
Agreed, this would be very useful

**Comment by andreas-boger** [comment]
I would appreciate such functionality too, particularly if the turn-by-turn cue list were embedded into the gpx file. It would be very useful for the Wahoo ELEMNT bike computer.

**Comment by natolh** [comment]
I believe this issue should still be open, pull request #412 is probably fixing #294 rather than this one (#249) ?

**Comment by PaulStets** [comment]
@natolh You are correct, it was a typo.

**Comment by PaulStets** [comment]
Added in https://github.com/osmandapp/OsmAnd-ios/commit/1c19dbd90fa9e70c84bccbc699381d2b264ca896
