### ISSUE TITLE
Empty public transport POI

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2495]
Tested on 4.4.4.3
Taping on the same POI, on iOS there is no public transport stops is shown.

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/213694991-fb021603-9af8-4098-9a59-c2133cb010a6.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/213694965-01258baa-5393-4674-b95c-e6b4f2fad764.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.5.2
Done
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/215806853-c7e516a6-be85-47bb-9a72-26fc7b8f428f.jpeg"  width="500" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/215806861-bfdefe56-18cf-4a9d-8ee5-4ebcaba90fc0.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>
