### ISSUE TITLE
Crash when trying to change Default speed

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2499]
## How to reproduce
* Open OsmAnd
* Go to Menu – Settings – Driving profile - Navigation settings – Vehicle parameters
* Tap on Default speed, OsmAnd will crash
Tested on TestFlight 4.4.4(4.4.4.3). Crash should be visible in Organizer.

![Screenshot 2023-01-23 at 12 29 00](https://user-images.githubusercontent.com/9365308/214017715-381ae7bb-b295-46bf-9a75-e9906d991af0.png)

**Comment by Zirochkabila** [comment]
Tested on TestFlight 4.4.5.3 and 05.02.2023 Master branch - Done
