### ISSUE TITLE
Hide "Default speed" parameter from Public transport profile

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#2501]
### Description
Public transport profile in **Android** doesn't have **Vehicle parameters**, this section is empty.
In **iOS** version, you can configure at least public transport default speed (see screenshot). Although the average speed of metro and trolleybus may differ significantly.

### How to reproduce?
* Go to **Settings** > **Public transport profile** > **Navigation settings** > **Vehicle parameters**

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/116079541/214057261-d878cf4a-dfe2-4b4b-9482-17b2a3a976fd.jpg"  width="300" height="auto"/> </td>
    <td><video source src="https://user-images.githubusercontent.com/116079541/214057021-3d4289c1-e690-419a-b5ae-22d19c99f97d.mp4  
"  width="300" height="auto"/>  </td>
  </tr>
</table>   

### Your Environment
OsmAnd Version: 4.3.8
Android/iOS version: 13
Device model:

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2702/commits

**Comment by Zirochkabila** [comment]
4.4.6.11
A blank page is displayed - maybe we should add the same message as in Android?

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/227714674-feda3fa8-13b5-4bd4-b0cb-f7a4d14058de.jpeg"  width="500" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/227714676-56760a1e-7311-4524-983d-2b4e3ebd4c78.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
We should fix both Android iOS empty message, but that should be a separate task for 4.5!
