### ISSUE TITLE
When selecting tracks from the folder Tracks on the map, no tick is placed

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2504]
OsmAnd 4.3.3
When I try to select tracks (from folder Tracks on the map) for Share or delete then, application does not put the tick, so I cannot understand if they are already selected or not.

https://user-images.githubusercontent.com/80623554/214312639-128aede9-c523-4730-ac11-67e79093cb0c.mp4

**Comment by DmitryAlexei** [comment]
OsmAnd 4.4.5.4
Works fine

<details><summary>Selecting tracks from the folder Tracks on the map</summary>
<video src="https://user-images.githubusercontent.com/116079541/220392554-26d758c2-786a-4f10-ae09-0ce441bd0e07.MP4"></video>
</details>
