### ISSUE TITLE
Add Catalan TTS

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2505]
## Review
- [x]  Sounds like English

## ToDo
- [x]  Add Catalan TTS

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2525

**Comment by Zirochkabila** [comment]
05.02.2023 Master branch - Done

**Comment by PaulStets** [comment]
Can be fixed only by Apple in the future iOS versions
