### ISSUE TITLE
Check list of available TTS between iOS and Android

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2508]
## ToDo
We need to check list of TTS available on Android vs iOS, with list of voices support on iOS and added missed. Languages supported by VoiceOver https://support.apple.com/en-us/HT206175

- [x]  https://github.com/osmandapp/OsmAnd-iOS/issues/2505
- [x] Ukrainian
- [x] Bulgarian
- [x] Indonesian
- [x] Slovenian

**Comment by Zirochkabila** [comment]
**+** Speech is present in Android TTS and VoiceOver, but not in iOS
**-** Speech is present in Android TTS, but not present in iOS and VoiceOver

Bulgarian +
Indonesian +
Slovenian +
Ukrainian +

Belarusian -
Chinese (Traditional) -
German (Casual) -
Guarani -
Latvian -
Sardinian -
Serbian (Cyrillic) -
Swahili -

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2589

**Comment by Zirochkabila** [comment]
25.02
Done
