### ISSUE TITLE
Crash when synchronizing data from cloud

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2511]
### Description
When synchronizing data from the cloud, at about 55% of the progress, the application crashes
[Jan 26, 2023 15:24.log](https://github.com/osmandapp/OsmAnd-iOS/files/10511355/Jan.26.2023.15.24.log)

User workaround - managed to solve the problem after having to delete all content in the cloud and reinstall OsmAnd several times

### Steps to reproduce
Menu > Settings > OsmAnd Cloud > Sync now

### Actual result
Crash

### Expected result
Data is synchronized

### Your Environment
OsmAnd Version: 4.4.5.1
Android/iOS version: iOS 15.7.2
Device model: iPad mini 4

**Comment by vshcherb** [comment]
As it not reproduced, it will be checked with other exceptions
