### ISSUE TITLE
GPX track isn't displayed as selected

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2512]
### Description
When selecting a GPX track in the Track on map section, the track is not displayed as selected. However, the total number of selected tracks increases, and this track is also displayed as selected in the Import folder (In the video, selecting the Lomka 2 track in the Track on map folder)

### Steps to reproduce
Menu > My places > Tracks > ... dots in the upper right corner > Select track

### Actual result
GPX track isn't displayed as selected

https://user-images.githubusercontent.com/104760013/214898289-92205142-bda9-427a-becd-92fd542c3eac.mp4

### Expected result
GPX track is displayed as selected like in Import folder

### Your Environment
OsmAnd Version: 4.4.5.1
Android/iOS version: iOS 15.7.2
Device model: iPad mini 4

**Comment by vshcherb** [comment]
Done needs to be clicked
