### ISSUE TITLE
With enabled Vegan filter POI does not display on the map

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2515]
While searching if I enable Diet filter (Vegan) for Cafe and restaurants POI won't be displayed on the map. They are displayed in the list (that means there are a lot of places in the required area), but they do not display as orange circles on the map. 

Map: Oslo, updated 1 Jan 2023
OsmAnd 4.3.3 (displayed in Apple App store)/ 4.3.4 (displayed in OsmAnd -> Help).

https://user-images.githubusercontent.com/80623554/215120732-ebc9007e-1d92-438c-a2a4-4095e4e9cc63.mp4

**Comment by Zirochkabila** [comment]
25.02
Done
