### ISSUE TITLE
"Analyze on map" track does not show blue ball when moving through the altitude graph

### ISSUE THREAD

**Issue by jumate** [osmandapp/OsmAnd-iOS#2518]
Version: iOS 4.3.4
When analyzing a track in My Places - Routes - Trace - Analyze on the map when scrolling through the altitude graph, it does not show the blue ball of each point.

**Comment by Zirochkabila** [comment]
4.4.5.5
Reproduced

**Comment by vshcherb** [comment]
Duplicate https://github.com/osmandapp/OsmAnd-iOS/issues/2093
