### ISSUE TITLE
During trip recording there is a gaps in the track

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2519]
# ToDo
We can try to add support of `startMonitoringSignificantLocationChanges `.

> If you leave the significant-change location service running and your iOS app is subsequently suspended or terminated, the service automatically wakes up your app when new location data arrives.
https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/LocationAwarenessPG/CoreLocation/CoreLocation.html#//apple_ref/doc/uid/TP40009497-CH2-SW1

## Issues
When I record track and lock my device, track was not recorded. The record has a gap or a straight line between start and finish point. 
The issue happens when the screen is locked or when I use another application.

# How to reproduce
1. Open OsmAnd -> start route with the Walking profile->Start trip recording
2. Lock the device or open another app (for example Telegram)
3. Open OsmAnd and you will see that OsmAnd made gaps in the record 
4. Tested with the Location permission - While using the app and Always.

<table style="width:100%">
  <tr>
    <th>While using the app (Location permission)</th>
    <th>Always allow</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/80623554/215485442-b0ee11d7-6d9d-4090-9a53-1e0bf4318c94.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/80623554/215484899-55567798-9437-47a5-898c-4f150db8418f.jpeg"  width="300" height="auto"/> </td>
  </tr>
</table>   

OsmAnd 4.3.4 (4.3.3)
Device: iPhone X
[2023-01-26_20-54_Thu.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10534383/2023-01-26_20-54_Thu.gpx.zip)

**Comment by vshcherb** [comment]
Looks like we can only warn users but nothing can be done in this ticket

**Comment by Zirochkabila** [comment]
4.4.5.2
Reproduced
[Jan 31, 2023 14:59.log](https://github.com/osmandapp/OsmAnd-iOS/files/10546848/Jan.31.2023.14.59.log)

**Comment by vshcherb** [comment]
@Zirochkabila There is no required analysis , why it's not reproduced on other iphone devices i.e. mine.

**Comment by anastasiia936** [comment]
Tested with the Browse map profile and the track also was recorded with gaps. 
OsmAnd 4.3.5
I started trip recording -> After around 5 minutes device locked (the track was recorded and displayed on the map) -> I walked for around 10 minutes and when I unlock the device I found that part, when the screen was off, did not record. 

Location permission - Always allow.

**Comment by EugeneZmeuk** [comment]
I tested the Recording track with a 5sec interval. I received a gap after the first 300m switching off my device screen.
<img width="379" alt="image" src="https://user-images.githubusercontent.com/44466116/216058177-d119cdc0-af52-43b8-9ed3-358a75e5b886.png">

But with Logging interval - Minimum (1sec)  I recorded a track without gaps. But I suggest that when we change Logging interval to 10 sec this problem will be more obvious.

**Comment by Zirochkabila** [comment]
4.4.5.5
When the interval is increased by 10 seconds, about 400m
In general, the result is similar to the one shown in @EugeneZmeuk  screenshot

**Comment by vshcherb** [comment]
Tested a lot and it works ok starting IPhone XS  with permission always allow access location. Probably we need to document

**Comment by PaulStets** [comment]
@anastasiia936 @EugeneZmeuk @dmpr0 @Zirochkabila Please test the next ```master``` build (4.4) and see if it improves.

**Comment by Zirochkabila** [comment]
4.4.6.1
Done
