### ISSUE TITLE
Include heading continues to be activated after reset plugin settings to default

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2524]
### Description
After resetting plugin settings to default (Walking, for example), the Include heading setting remains enabled

### Steps to reproduce
Menu > Settings > Select profile > Track recording > Include heading > Back > Reset to default or Reset plugin settings to default button in Track recording (After logging in again, the Include heading is displayed activated again)

### Actual result
Include heading continues to be activated

https://user-images.githubusercontent.com/104760013/216025430-513864a3-8708-40a4-9c12-b03d544eb6c5.mp4

### Expected result
Include heading will be deactivated too

### Your Environment
OsmAnd Version: 4.4.5.2
Android/iOS version: 15.7.3
Device model: iPad mini 4

**Comment by vshcherb** [comment]
it's ok, we include heading by default. I guest it's not a problem?
