### ISSUE TITLE
(Beta) Broken Orientation and position

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd-iOS#2527]
Updated to 4.4.5.2 today and now orientation and position is a mess 

Current position is now screen centered and the orientation of the map is no longer driving based but based on the iphone gyroskop.

since my iPhone is just put in the middle
Console and I have a pop socket on the back it is slide and turn a little.

Screen reflect this with going crazy incl turn around the map 🤪 

![ED6C99A1-9B80-47C3-BDCD-A9CB79103A4A](https://user-images.githubusercontent.com/35132439/216144740-383a1057-82ff-42ae-be69-8caf5a563329.png)
![EDC6FDFF-5C61-48DD-94F6-F5788627C61D](https://user-images.githubusercontent.com/35132439/216144746-b3e0e173-cde9-44fc-ba2f-78415d4caa4e.png)
![8684F32D-CE85-4157-B125-C3DA0B217310](https://user-images.githubusercontent.com/35132439/216144750-ea759c1a-ed69-4e3a-9e0f-0600594eb0b1.png)
![328B02FE-617E-4F25-B5AF-E3622371F550](https://user-images.githubusercontent.com/35132439/216144754-9c6b49e0-e920-422e-8a9d-8ab7e07acea7.png)
![DCD0818C-C045-4BC1-8F53-107B5DB07847](https://user-images.githubusercontent.com/35132439/216144759-74dd0e36-7633-46c2-b44f-73d81572b6d0.png)
![44B1AD20-AFC4-4311-9944-255CA6C504A8](https://user-images.githubusercontent.com/35132439/216144765-14de1e04-0f21-4522-991a-74d8f241e151.png)
![18EC0B3A-7B71-4A26-9B64-8E4200FA9604](https://user-images.githubusercontent.com/35132439/216144767-5cf04102-bd7f-410a-a60e-bd5fb974f2d0.png)
![F7111508-0E04-4428-BC71-AE7D50EB51B5](https://user-images.githubusercontent.com/35132439/216144768-3fb0f112-1390-4112-b108-f27b4ad2568c.png)

**Comment by PaulStets** [comment]
Hi, could you please check which map orientation setting you have in the General settings of the profile you use in CarPlay? Also, please note that you can toggle between the 3D and 2D view directly in CarPlay by pressing the location button.

**Comment by WizoneDE** [comment]
… was set to „direction of movement“ but after update compass was set.. 

Changed it will check again
