### ISSUE TITLE
Route details: uphill/ downhill show altitude range on route card

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2541]
Route card shows Uphill/Downhill(Ascent/Descent) icons but values are from altitude range, see **Route details** screenshot.

## ToDo
- [ ]  Show proper values for Uphill/Dowhill on **Route card**.
<table style="width:100%">
  <tr>
    <th>Route card</th>
    <th>Route details</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/216943207-c0ce1a6c-9a5b-4372-a6c5-c3d1a043e0ba.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/216943203-b367cd61-853f-458a-abd3-e6b617459be2.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by shurasmiling** [comment]
- https://osmand.net/docs/user/navigation/setup/route-details#elevation-info

- To add to the documentation task [Article - Track context menu #1110](https://github.com/osmandapp/OsmAnd-Issues/issues/1110) as well - https://osmand.net/docs/user/map/track-context-menu#altitude--speed-graphs
