### ISSUE TITLE
Contour lines switch doesn't work

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2553]
### Description
The Contour lines switch doesn't work in Configure map

### Steps to reproduce
Configure map > Contour lines > Enabled or disabled

### Actual result
Switch does not work

https://user-images.githubusercontent.com/104760013/217212909-d4ce676a-011d-4c2c-8659-3e258dd0b43d.mp4

### Expected result
4.4.5.3
Switch is working

https://user-images.githubusercontent.com/104760013/217213088-544113a4-a1c2-4ee4-a1be-08ff02e8f739.mp4

### Your Environment
OsmAnd Version: 07.02.2023 Master branch
Android/iOS version: iOS 13.7
Device model: iPhone 11

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/5223d562d6f4f77a0185a9c961a5604f46ea8be1

**Comment by Zirochkabila** [comment]
07.02.2023 Master branch 17:40 build - done

https://user-images.githubusercontent.com/104760013/217293898-e0a6c3a2-9f3b-4153-b87b-7078f54effe9.mov
