### ISSUE TITLE
Exit number abbreviated

### ISSUE THREAD

**Issue by pnoll1** [osmandapp/OsmAnd-iOS#2561]
### Description
Exit number rendered as 15.. instead of 154A
![2E604CCE-745A-4CA3-A34A-7B25A26A4BD8](https://user-images.githubusercontent.com/8444617/217409856-229c3a00-09e8-41c0-929d-2e0810c1c504.png)

### How to reproduce?
Route from I5 south to 405 north via exit 154A

Exit is located at 47.46301 -122.26575

### Your Environment
OsmAnd Version: 3.4.4
Android/iOS version:16.2
Device model:iPhone 11 pro max

**Maps used (online or offline):**   Custom map files, only address data added

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2598

**Comment by Zirochkabila** [comment]
25.02
 <details><summary>Done</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221366836-d38a8862-dfa0-4bf4-9820-1991d2fe7e83.png">
</details>

**Comment by pnoll1** [comment]
I had an issue with the entire exit number being truncated last week. I believe this was version 3.4.5. Is this also going to be fixed when this commit is released? ![5132C1CB-417F-41B4-A668-65F1109F29FF](https://user-images.githubusercontent.com/8444617/222876644-0a5822a9-69dc-4879-bd3a-a733ffec344a.png)

**Comment by Zirochkabila** [comment]
@pnoll1 Most likely, yes
