### ISSUE TITLE
Route line almost disappears after switching map style (map type)

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#2567]
The route line becomes almost invisible (very thin) after switching the map style. Also appears arrows in circles, that displays direction of movement.
How to reproduce: In navigation mode, change map style (Menu > Configure map > Map type) from OsmAnd style to another one. 
Then go back to OsmAnd map style.
User image:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/218086274-7c401c2a-a1bd-4201-bb92-3b5e596c26a8.png"  width="300" height="auto"/> </th>
  </tr>
</table>
Actual result:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/218088142-c1827a73-910d-43f5-a534-9c8aae0bf54d.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

Test flight version 4.4.5.4
IOs version 15.7.1

**Comment by DmitryAlexei** [comment]
This behavior with changing map stile isn't stable. Reproduces from time to time: sometimes you need to switch map style more than 3 or 4 times. Sometimes every time you change map style, route line is still very thin.
Route line almost disappears in following map styles:
- UniRS
- Touring view
- CycloRoute.Olivier
- Snowmobile
- Osm-carto

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/116079541/218414106-39bac723-7df9-43a8-8d11-82e7c6440d72.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218414110-877c2fae-b932-4077-91d3-34ec2f74f887.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218414111-58283139-1c54-4318-8ff5-16b4a507611a.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218414116-6a6b929a-520c-4463-82b7-7a929a2787e4.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218414118-6154b9cf-ade0-44ee-85f5-d0b5f9b0959e.jpg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/116079541/218414121-fe7536d0-679d-45b7-8a28-86ca93e0b22a.jpg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
26.02 master
Done
