### ISSUE TITLE
Search results of poi’s should include city name if set

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd-iOS#2570]
since distance in search is useless after first click (next distance is based on current screen position not real position) it would be really helpful to see the city name next to
The distance information. 

![64B21CC5-6D37-4DF5-926C-8513E953C0F4](https://user-images.githubusercontent.com/35132439/218248627-034969b3-250e-45a0-9a71-acbe82937511.jpeg)

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/2993
