### ISSUE TITLE
Add <time> tag to <metadata> block

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2574]
## ToDo
GPX files generated by OsmAnd on Android using Plan a Route tool included <time> tag in <metadata> block, we need to support that in iOS.

- [x]  Add `<time>` tag to `<metadata>` group

* GPX Android - [Tue 14 Feb 2023-Android.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10730727/Tue.14.Feb.2023-Android.gpx.zip)
* GPX iOS – [Tue 14 Feb 2023-iOS.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10730728/Tue.14.Feb.2023-iOS.gpx.zip)

```
  <metadata>
    <name>Tue 14 Feb 2023</name>
    <time>2023-02-14T08:57:09Z</time>
  </metadata>
```

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2872

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2873
