### ISSUE TITLE
Crash if clicking on on any item in Voice prompts menu

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2590]
### Description
If clicking on Voice guidance (prompts in 4.4) - crash
[Feb 20, 2023 11:30.log](https://github.com/osmandapp/OsmAnd-iOS/files/10782935/Feb.20.2023.11.30.log)

```
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Application tried to present a nil modal view controller on target <OAVoicePromptsViewController: 0x10a7583b0>.'
*** First throw call stack:
(0x181718c80 0x198f3dee4 0x183e64bec 0x183c65eb4 0x183c06e2c 0x183d6d34c 0x183c89738 0x100908464 0x100de7a10 0x1849a46d0 0x1849a4050 0x1849a494c 0x183ccd234 0x183be8764 0x183b16ea4 0x183b17570 0x183b1773c 0x1816c478c 0x1816959b4 0x181690f3c 0x1816a4194 0x1a1fcf988 0x183ea6a88 0x183c3ffc8 0x100dfe4ec 0x102c644d0)
libc++abi: terminating with uncaught exception of type NSException

```

### Steps to reproduce
Navigation > Settings > Navigation settings > Voice prompts > Сlick on any item in this menu

### Actual result
Crash

https://user-images.githubusercontent.com/104760013/220069630-93d651a8-890e-40cf-8e54-d25551b81778.mp4

### Expected result
 Voice guidance/prompts menu is open

### Your Environment
OsmAnd Version: 4.4.5.8 / master 19.02.23
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2606

**Comment by Zirochkabila** [comment]
25.02 master
Done
