### ISSUE TITLE
CarPlay: my places show folders first

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2595]
List item quantity on CarPlay limited from 12 or 24 items. 
* Currently when selecting **Favourites** or **Tracks** on CarPlay we show all points and tracks as one list divided by group name, so only 12 or 24 first items are visible. 
* We need to show folders first, so we can show first 12 or 24 folders and the same amount on favourites points or tracks in each folder.

## Tracks
- [x]  Show folders list
- [x] Taping on folder > open folder with the list of included tracks
<table style="width:100%">
  <tr>
    <th>Folder list</th>
    <th>Open folder</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/220369813-a0173982-d064-4729-a142-ffa1f8cc4087.png"  width="400" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/220382415-5e085470-4b00-462f-89d8-89f9eb4cc247.png"  width="400" height="auto"/> </td>
</table>   

## Favorites
- [x]  Show folders list
- [x]  Show **Last modified** as a first item
- - [x] Should include favourites from all folders sorted by last modified on top
- [x] Taping on folder > open folder with the list of included favourites
- [x] Favorite icon:
- - [x] Show proper icon with shape, colour, icon if we can
- - [x] If not, show selected icon with proper colour 
<table style="width:100%">
  <tr>
    <th> Tracks </th>
    <th> Favorites </th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/220395737-d9e46dca-83b3-4627-8712-348c9f92617c.png"  width="400" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/220394516-b03a35de-44f7-4563-80ce-9986ca7a1fa2.png"  width="400" height="auto"/> </td>
  </tr>
</table>

**Comment by Skalii** [comment]
[CarPlay - add folders to my places](https://github.com/osmandapp/OsmAnd-iOS/pull/2621)

**Comment by Zirochkabila** [comment]
03.03 master 
Done

**Comment by dmpr0** [comment]
## Review
- [ ] Lag after tap on Navigation > Favorites. One of the folder consist 9568 points.
- - [ ] File [2014 - LIDL Europe.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10898551/2014.-.LIDL.Europe.gpx.zip)
- [ ]  Favorites **Last modified**, show real quantity (12 or 24?) of items visible in the list.
- [ ]  Tracks **Last modified**, show real quantity (12 or 24?) of items visible in the list.

**Comment by Skalii** [comment]
[Fix CarPlay - favorite/track maximum items count](https://github.com/osmandapp/OsmAnd-iOS/pull/2651)

**Comment by Zirochkabila** [comment]
15.03 master
Looks like Lag is still present. But need to check in CarPlay app
[2023-03-15 17:13:17.064962+0200 OsmAnd Maps[38965:.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10982198/2023-03-15.17.13.17.064962%2B0200.OsmAnd.Maps.38965.zip)
