### ISSUE TITLE
Parking show 'type' on second line and proper icon

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2596]
Proposed by [WizoneDE](https://github.com/WizoneDE) in https://github.com/osmandapp/OsmAnd-iOS/issues/2468
Parking POI can be filtered **Type**. We can show type on second line in search results and context menu, current list of parking POI in search looks empty.

## Icon
We recently fixed https://github.com/osmandapp/OsmAnd-Issues/issues/1231 Parking POI icon in context menu, but orange POI and search results always show default "P" parking icon.
<table style="width:100%">
  <tr>
    <th>POI Map</th>
    <th>POI from search (orange)</th>
    <th>Search results</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/220929096-5421716e-9fe3-490e-b21a-362b9518f5ed.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/220929102-817dab94-e025-471d-8e62-2a9451bcde3a.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/220929111-9851d277-8da7-4b4e-afb6-be0ac8496b3d.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Type

- [ ]  Show **type** on second line for Parking POI
<table style="width:100%">
  <tr>
    <th>Stores</th>
    <th colspan=2>Parking</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/220409557-4c4b0d0d-2805-4831-9beb-c80b8b69329e.PNG"  width="240" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/220409579-2f004de0-3a59-425f-89e0-78b448d2b7a6.PNG"  width="240" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/220410908-0c8c1a28-742a-4239-bd38-74da5397b467.PNG"  width="240" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Duplicate
