### ISSUE TITLE
POI Saved to Favorites - Data missing

### ISSUE THREAD

**Issue by drtbyk** [osmandapp/OsmAnd-iOS#2597]
With the last v4.3 update when a POI is saved to Favorites all of the POI data was supposed to be saved.  This is not happening with all POI's and I have no way of telling what the cause is. Here is an example:

![IMG_1168](https://user-images.githubusercontent.com/8745955/220497424-17b995db-6868-4ba8-a890-342ffda8f86c.png)

![IMG_1169](https://user-images.githubusercontent.com/8745955/220497469-0d3d6c9d-55a4-48a8-8bd7-690d85e574ee.png)

**Comment by drtbyk** [comment]
Still do not know why but for this one POI OsmAnd is now saving most of the POI-OSM data. It still does not show the locations Address when saved to Favorites.

![IMG_1170](https://user-images.githubusercontent.com/8745955/220811504-9bff2955-1050-4e7b-ad92-b3316c1aa7e9.png)

**Comment by Zirochkabila** [comment]
All information except the address is not displayed
For example - on Android, the address is displayed, and the address in the neighboring Favorites is also displayed
[OSM](https://www.openstreetmap.org/node/9925967697#map=17/48.56594/10.16499)
[OSM neighboring ](https://www.openstreetmap.org/node/427590708)
[Map](https://drive.google.com/file/d/1PmYurkeMgOcEzIAfajLmRLrKhxre2MW4/view?usp=sharing)

<details><summary>26.02</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221422888-5ff6720a-3f1c-4375-a459-3e583ee3ffb2.png">
<img width="350" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221423570-7f5b3207-beb3-4e7a-b686-693338d017c8.jpeg">
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/221423542-3106b36f-8038-4a3f-9bf4-1d4632e786d6.png">
</details>

**Comment by Zirochkabila** [comment]
4.4.6.7
Done

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>POI</th>
    <th>Without offline map</th>
    <th>With offline map</th>
  </tr>
  <tr>
  <td><img src="https://user-images.githubusercontent.com/9365308/226388889-f2ed2008-f748-49f7-94c7-3c313bd94d79.jpeg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/226388493-c38435e9-5c94-432a-b0ab-fced02bbce55.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/226388503-03729da2-2dc7-4f9f-92c0-c792db5eec91.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by PaulStets** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2711

**Comment by Zirochkabila** [comment]
4.4.6.11
Still present


https://user-images.githubusercontent.com/104760013/227724524-2ea291d0-213e-46fa-b16f-a91b40497b68.mp4
