### ISSUE TITLE
Map style addons is visible as Map styles

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2617]
## ToDo
- [x]  Don't show map style addons 

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/221920065-1b49ae05-75eb-4c84-a6ed-98e3c921be14.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
03.03 master
Done
