### ISSUE TITLE
Snap to road title has been moved to the right

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2620]
### Description
Snap to road title has been moved to the right

### Steps to reproduce
Menu > Settings > Select any profile > Navigation settings > Map during navigation 

### Actual result
Snap to road title has been moved to the right
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/222179263-775f3ae9-ba55-46b3-9189-7152aa9ac471.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
Snap to road title is on the same level as other titles

### Your Environment
OsmAnd Version: 28.02.23 master

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2723

**Comment by Zirochkabila** [comment]
4.4.6.11
Still present

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/227726782-cfc7004c-ffb5-45d7-8a0f-53ec74f37298.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>
