### ISSUE TITLE
The download icon is shifted to the left in downloaded maps

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2622]
### Description
The download icon is shifted to the left in downloaded maps

### Steps to reproduce
Menu > Maps & Resources > Europe > Ukraine > Kyiv

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/222383215-64ce324e-b8ed-4332-a230-263cd9f379e7.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
The download icon is in line with other download icons

### Your Environment
OsmAnd Version: 4.4.6.2
Android/iOS version: 15.7.3
Device model: iPhone X

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2646

**Comment by Zirochkabila** [comment]
4.4.6.6
iPad - Done
15.03 master
Xcode - Done too
