### ISSUE TITLE
Speedometer widget

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2627]
## Description
We have speed limit alert, but we have requests to add single widget that will show current speed + speed limit.

> Should be done in the following order:
> 1. https://github.com/osmandapp/OsmAnd-iOS/issues/3652
> 2. https://github.com/osmandapp/OsmAnd-iOS/issues/3664
> 3. https://github.com/osmandapp/OsmAnd-iOS/issues/2627
> 4. https://github.com/osmandapp/OsmAnd-iOS/issues/3668

# Driving mode without Navigation

- [x] Speed limit should work without navigation by attaching to the road with appropriate profile (see Android). Only for Driving profiles based on Car
- [x] Optional (+20 value) similar should be implemented for Lanes / Street name / Max speed widget 

# Configure Screen

## Other group
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/0ebcbc09-f534-4e47-8fef-818233079cda"  width="375" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new item **Speedometer**, to **Other** group
- - [x] Icon, On state – `widget_speed`
- - [x] Icon, Off state – `ic_custom_speedometer_outlined`
- - [x] Tap, should open separate screen with widget settings

## Speedometer, [Figma](https://www.figma.com/file/ARnU6oUzxzcKWkTNR8bgTd/Configure-Screen?type=design&node-id=1207%3A87778&mode=dev)

<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <th>Off</th>
    <th>On</th>
    <th>Speed limit warning</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/39faf345-fcb6-48b1-a507-9cd35286d060"  width="260" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c55b772c-0937-4559-86af-5eaad3f8066d"  width="260" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/32d2af4b-6651-47ad-bbf6-9f50f8694fea"  width="260" height="auto"/> </td>
  </tr>
</table>  

</details>  
 
- [x] Show switch to Enable / Disable speedometer on the map
- [x] Show widget preview, should react on size change and settings
- - [x] Frame should have fixed height

**Settings**
- [x] Add group **Settings**
- [x] Add option **Speed limit warning**, to control visibility of speed limit warning, with two parameters:
- - [x] **Always**, speed limit sign should be always shown
- - [x] **When exceeded**, speed limit sign visibility should be depend on **Speed limit tolerance** option

# Widget

## Speedometer, [Figma](https://www.figma.com/file/kA99qiWKbDUN3C4n9SKQUV/Widgets?type=design&node-id=1210%3A33494&mode=dev) 

![Screenshot 2024-05-02 at 17 55 40](https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1a11e09a-7e15-4707-8372-2ba652aa29d7)

|**Current speed** | S | M | L |
|---|---|---|---|
| Width ↔︎ | 56 pt | 72 pt | 96 pt |
| Height ↕︎ | 56 pt | 72 pt | 96 pt |
|**Corner radius** | | |
| iOS | 6 pt | 6 pt | 6 pt  |
| CarPlay | 10 pt | 10 pt | 10 pt |

## Text

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Text size</th>
        <th>Max</th>
        <th>Fit to width</th>
      </tr>
      <tr>
        <th>L</th>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/470c910a-d8e8-4042-9cbe-06f34cb4c945"  width="auto" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d7307fba-3e00-499c-a2b3-7daab21a9af2"  width="auto" height="auto"/> </td>
      </tr>
      <tr>
        <th>M</th>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/5e1bae0d-961b-4e18-af4b-3599a22c359b"  width="auto" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d3146f85-df48-4b6f-bb56-08eae227c191"  width="auto" height="auto"/> </td>
      </tr>
      <tr>
        <th>S</th>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/5cb12ffa-541d-48d7-aeeb-ee15f5bab8a9"  width="auto" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/fdcd91ce-2ed7-4161-8596-cef79d36d710"  width="auto" height="auto"/> </td>
      </tr>
    </table>   
</details> 

- [x] Text color
- - [x] Value  – `widgetValueColor`
- - [x] Units – `widgetUnitsColor`
- [x] Align text in the middle of the fill area
- [x] Set max. and min. text size for widget **value**:
- - [x] **L**, max – `50 pt`, min  = `17 pt`
- - [x] **M**, max – `33 pt`, min  = `17 pt`
- - [x] **S**, max – `22 pt`, min  = `17 pt`
- [x] Units, text size – `11 pt`

## Limit icon

<table style="width:100%">
  <tr>
    <td>Size</td>
    <th>L</th>
    <th>M</th>
    <th>S</th>
  </tr>
  <tr>
    <th></th>
    <th>96 x 96</th>
    <th>72 x 72</th>
    <th>56 x 56</th>
  </tr>
  <tr>
    <th>Icon</th>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/15b3346d-2beb-481d-8886-311e530906e0"  width="auto" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a6f33fb7-fe0d-406f-81e2-277dd315135b"  width="auto" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c8a7fd76-1eb7-4bed-84e7-700c85421d47"  width="auto" height="auto"/> </td>
  </tr>
</table>   

- [x] Text color  – `widgetValueColor`
- [x] Align text in the middle of the fill area
- [x] Set max. and min. text size for widget **value**:
- - [x] **L**, max – `50 pt`, min  = `17 pt`
- - [x] **M**, max – `33 pt`, min  = `17 pt`
- - [x] **S**, max – `22 pt`, min  = `17 pt`
- [x] Icon
- - [x] EU – `img_speedlimit_eu`
- - [x] USA, Canada – `img_speedlimit_nam`

**Comment by anastasiia936** [comment]
Request from customer: 

The speed limit should show all of the time on CarPlay instead of just when you are speeding.

**Comment by WizoneDE** [comment]
Posted my feedback Here
https://github.com/osmandapp/OsmAnd/issues/13413

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3723

**Comment by dmpr0** [comment]
# Review

- [ ] Units – use text style similar to Top/Bottom widget (Uppercase)

**Comment by shurasmiling** [comment]
1. [speed-limit](https://osmand.net/docs/user/navigation/guidance/voice-navigation/#speed-limit)
2. [speedometer info widget](https://osmand.net/docs/user/widgets/info-widgets#speedometer)
3. [Speedometer widget – CarPlay #3668](https://github.com/osmandapp/OsmAnd-iOS/issues/3668)

**Comment by dmpr0** [comment]
# Review 2 
- [ ] Size should be Small by default
