### ISSUE TITLE
UI doesn't update after changing settings in Trip recording plugin

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2629]
## How to reproduce
* Make sure that **Trip recording** plugin is On, in **Menu** - **Settings** – **Plugin**
* Open Menu – Settings – Select any profile, 
* **Configure profile** – **Trip recording**
* Try to change **General logging interval** 
* Value on Trip recording setting screen, stay the same, but it will be changed.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/222716532-cb507201-0570-4065-921d-d1df281a820b.mov"  width="300" height="auto"/>  </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.6.7
Done
