### ISSUE TITLE
"Back" option in "Customise route line" menu does not lead back

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#2630]
## ToDo
- [x]  Back button should open previous screen.
* If **Customise route line** opened from Settings - Navigation settings –, back to it
* If **Customise route line** opened from Navigation – Settings, back to it

## Description
*Back* option in *Customize route line* menu instead of leading back (to the navigation settings) leads to the main screen.

How to reproduce:
1. Main menu > Settings > One of profiles (except Browse map) > Navigation settings > Customise route line and tap "Back" in the top left corner of the screen.
2. Tap Navigation button on the main screen > select profile > Settings > Navigation settings > Customise route line and tap "Back" in the top left corner of the screen.
3. Choose Navigation section in the Main menu (Main menu > Navigation) > select profile > Settings > Navigation settings > Customise route line and tap "Back" in the top left corner of the screen.

<details><summary>Back lead to the main screen </summary>
<video src="https://user-images.githubusercontent.com/116079541/222794864-5182c5e5-e9f4-4779-bf86-59e831514b3e.mp4"></video>
</details>

TestFlight 4.4.6.2

**Comment by Skalii** [comment]
+

**Comment by Zirochkabila** [comment]
4.4.6.15
Main request is resolved
But, there is a delay when displaying the route line and returning from the Customize route line screen - only plays on iPad mini 4


https://user-images.githubusercontent.com/104760013/229479418-e55adecc-4bd3-4bf5-8e25-f2a6dd829de3.mp4
