### ISSUE TITLE
Quick action - RTL (iOS)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2631]
### Description

- [x] Arabic in Quick action, but the system language of the application is English
- [x] The Quick action arrow is shown in the opposite direction 

### Steps to reproduce
Menu > Configure screen > Quick action 
Quick action 

### Actual result

<details><summary>Arabic in Quick action </summary>
<video src="https://user-images.githubusercontent.com/104760013/222956448-be764337-41a7-40b2-b915-180e5c89973c.mp4"></video>
</details> 

<details><summary>Arrow</summary>
<img width="400" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/223101572-24c634ec-5482-44a6-95e4-d3f8e258a393.jpeg">
</details> 

### Expected result
System language in Quick action 
The Quick action arrow is shown in the opposite direction (to the right)

### Your Environment
OsmAnd Version: 4.4.6.3
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by Chumva** [comment]
Fixed in android - https://github.com/osmandapp/OsmAnd/commit/0191ba5a34def3bc31ec8ff577e911e9aa10af7d

**Comment by Zirochkabila** [comment]
4.4.6.10
Done
