### ISSUE TITLE
Freeze-Crash - Resolving Conflicts Cloud

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2632]
### Description

- [x] Cloud status freeze after conflict resolution
- [x] Crash

[Mar 06, 2023 16:15.log](https://github.com/osmandapp/OsmAnd-iOS/files/10899279/Mar.06.2023.16.15.log)
[cloud.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10899281/cloud.zip)

### Steps to reproduce
Menu > Settings > OsmAnd Cloud > Last sync > Conflicts > Select one > Upload local version > Go to Cloud, Local and back to Conflicts

### Actual result

<details><summary>Freeze and crash</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/223139348-5e2514aa-8221-4f9b-83d9-4a03e5b62a07.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/223139933-bfb15b36-3c57-4a7a-accb-b3c056fef856.mov"  width="300" height="auto"/> </td>
  </tr>
</table> 
</details> 

### Your Environment
OsmAnd Version: 4.4.6.3
Android/iOS version: 15.7.3
Device model: iPad mini 4 / iPhone 14 pro

**Comment by Zirochkabila** [comment]
4.4.6.7
Still present

https://user-images.githubusercontent.com/104760013/225703549-043fe50a-7f3f-467b-b556-df182343d76e.mp4

**Comment by dmpr0** [comment]
# Review
TestFlight 4.4.6.10
- [ ]  Crash, resolving conflicts

**Comment by PaulStets** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2748
