### ISSUE TITLE
Widgets: No "un-Collapse" button on screen.

### ISSUE THREAD

**Issue by drtbyk** [osmandapp/OsmAnd-iOS#2633]
OsmAnd v4.3.5 AppStore release version.
iOS v16.3.1
iPhone 14 Pro Max

**_Help Documentation: iOS Widgets
Right panel is the part of the screen with Widgets. You can choose the next parameters for each widget: Show/Hide/Collapse. Collapse add special button near widget for collapsing widgets._**

When setting Widgets on the Right Side of the screen to "Collapse" view, there is no "un-Collapse" button displayed. Widget(s) can not be returned to display without changing Settings back to "Show". In the screenshots below the WEATHER Widgets were set to Collapse.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/8745955/223277332-9826adbc-5910-4c10-88d0-bd5b00b5a784.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/8745955/223277179-3207696b-107c-4f65-8283-41a20bd05dc9.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.6.5
In Collapse mode, widgets aren't displayed on the screen
But, since we are planning to make the widget display similar to that of Android, it is most likely necessary to remove the Collapse function for now
