### ISSUE TITLE
Waypoint with alpha color issue

### ISSUE THREAD

**Issue by anastasiia936** [osmandapp/OsmAnd-iOS#2635]
After importing a track with waypoints, the color of the points is displayed in different colors in different menus. Also, the color of the points cannot be changed. 

## How to reproduce the bug
1. Create track with waypoints on Android device
2. Share track
3. Import it to OsmAnd on iOS device
4. Display on the map and try to change color for waypoints

**File** [2023-03-07_10-33_Tue.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10908159/2023-03-07_10-33_Tue.gpx.zip)
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td valign=top><img src="https://user-images.githubusercontent.com/80623554/223387167-2f368567-aed3-41fb-a6af-c2653660eac5.png"  width="300" height="auto"/> </td>
    <td valign=top><img src="https://user-images.githubusercontent.com/9365308/223392356-f70fa8d1-7efa-4fdd-a940-4ceec3c4129b.png"  width="300" height="auto"/> </td>
    <td valign=top><video source src="https://user-images.githubusercontent.com/80623554/223387258-4b432e28-195f-488d-98c8-af635570f353.mp4"  width="300" height="auto"/>   </td>
  </tr>
</table>   

Tested on
Android, OsmAnd 4.3.5
iOS, TestFlight 4.4.6.3

##Expeted result
The color of the waypoints are displayed the same color as in the gpx file.
Change color is available

**Comment by Zirochkabila** [comment]
4.4.6.5
The color of the Waypoints on the map is indeed different from the color in the context menu.
When editing the color, you can change the color

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/224673998-0f2f6e74-96ea-4bd0-9b2b-e4cf4de78a55.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
@Zirochkabila I don't think it's an issue. In context menu icon on purpose doesn't support transparency, so there is no bug that it's transparent on the map, user meant something related to import.

**Comment by Zirochkabila** [comment]
@vshcherb What the user meant was that when imported into the Android version, the icons are displayed in red.
But, in addition to this, there is also what was described above
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/224770998-7505271c-a197-456c-9618-d333105240ca.jpeg"  width="200" height="auto"/> </th>
<th><img src="https://user-images.githubusercontent.com/104760013/224771408-cbb7913b-2049-4970-906b-d2fd53178adb.png"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
```#b4d00d0d``` is red https://www.w3schools.com/colors/colors_picker.asp

**Comment by Zirochkabila** [comment]
In Android, icons are displayed in red - as they should be
On iOS, the icons are transparent + color of the Waypoints on the map is indeed different from the color in the context menu.
If editing the color, you can change the color

**Comment by PaulStets** [comment]
![image](https://user-images.githubusercontent.com/20681525/229112088-c2621366-6f10-4e05-8f1f-09fb7f24824b.png)

**Comment by Zirochkabila** [comment]
4.4.6.15
Сolor of one Waypoint is different
`49.5933852, 34.5680129` - `b4d00d0d`

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/229494083-e8ba9ceb-2e87-460b-ada1-7b5531673207.jpeg"  width="500" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/229494116-4e921e26-ef7c-40a0-a4a3-1afb3b9e4dd0.png"  width="650" height="auto"/> </th>
  </tr>
</table>
