### ISSUE TITLE
Import of Garmin GPX Tracks: Track Extensions are attributed to the wrong Track.

### ISSUE THREAD

**Issue by drtbyk** [osmandapp/OsmAnd-iOS#2640]
OsmAnd Maps: v4.4.6.3
iOS/iPadOS: v16.3.1

Issue: 
Importing GPX file of GPX Tracks with Garmin Extensions: Track Extensions are attributed to the next Track (n+1) in the file.

GPX File Example: [PostM2M.zip](https://github.com/osmandapp/OsmAnd-iOS/files/10926420/PostM2M.zip)

<table style="width:100%">
  <tr>
    <th>Screenshot of original track color:</th>
    <th>Screenshot of OsmAnd Maps Import:</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/8745955/223882145-7c7e6c0e-72a5-4b70-93d4-15af9751e352.png"  width="400" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/8745955/223882179-21f964bb-f735-410d-9e37-c6bf06217827.png"  width="400" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
- Day 1 - Tue, Jun 13, 2023 - Red
- Day 2 - Wed, Jun 14, 2023 - Blue
- Day 3 - Thu, Jun 15, 2023 - Red
- Day 4 - Fri, Jun 16, 2023 - Blue
- Day 6 - Sun, Jun 18, 2023 - Red
- Day 7 - Mon, Jun 19, 2023 - Blue
- Day 8 - Tue, Jun 20, 2023 - Black [https://www.openstreetmap.org/#map=15/45.9824/9.2678 https://www.openstreetmap.org/#map=15/47.4026/8.4057 ]
- Day 9 - Wed, Jun 21, 2023 - Red

**Comment by drtbyk** [comment]
I think we are seeing the same issue. OsmAnd is coding the Tracks as follows:

Day 1 - Tue, Jun 13, 2023 - Red - OsmAnd Default
Day 2 - Wed, Jun 14, 2023 - Blue - OsmAnd used the previous Extension - Red
Day 3 - Thu, Jun 15, 2023 - Red - OsmAnd used the previous Extension -Blue
Day 4 - Fri, Jun 16, 2023 - Blue - OsmAnd used the previous Extension -Red
Day 6 - Sun, Jun 18, 2023 - Red - OsmAnd used the previous Extension -Blue
Day 7 - Mon, Jun 19, 2023 - Blue - OsmAnd used the previous Extension -Red
Day 8 - Tue, Jun 20, 2023 - Black - OsmAnd used the previous Extension -Blue [Route](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=45.9873%2C9.2613%3B47.4024%2C8.4056#map=8/46.670/9.707) 
Day 9 - Wed, Jun 21, 2023 - Red - OsmAnd used the previous Extension -Black
Day 10 - Thu, Jun 22, 2023 - Black - OsmAnd used the previous Extension -Red[Route](https://www.openstreetmap.org/directions?engine=graphhopper_car&route=47.805214%2C8.189003%3B47.805214%2C8.189003) - round trip
Day 11 - Fri, Jun 23, 2023 - Blue - OsmAnd used the previous Extension -Black
Day 13 - Sun, Jun 25, 2023 - Red - OsmAnd used the previous Extension -Blue
Day 15 - Tue, Jun 27, 2023 - On Extension Color - OsmAnd used the previous Extension

**Comment by Zirochkabila** [comment]
OsmAnd~ 4.4.0#14228mqta, Released: 2023-03-10 - Track color is displayed in accordance with the original color
4.4.6.4 - bug confirmed

**Comment by PaulStets** [comment]
![image](https://user-images.githubusercontent.com/20681525/228467512-547024b3-df7a-482f-8590-96cf34c1bdb0.png)
Fixed in https://github.com/osmandapp/OsmAnd-iOS/pull/2743
