### ISSUE TITLE
Crash when activating Terrain

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2645]
### Description
Crash when activating Terrain (provided that Terrain maps are not downloaded)

### Steps to reproduce
Configure map > Terrain > Enable

### Actual result
Crash

https://user-images.githubusercontent.com/104760013/224037826-9614bbc0-5050-48cf-8663-d6c35af9f620.mp4

### Expected result
Terrain enabled

### Your Environment
OsmAnd Version: 4.4.6.4
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by Skalii** [comment]
[Refactoring Terrain settings screen](https://github.com/osmandapp/OsmAnd-iOS/pull/2696)

**Comment by Zirochkabila** [comment]
4.4.6.10
Done
