### ISSUE TITLE
Change Object's position does not accurately place icon

### ISSUE THREAD

**Issue by kit4short** [osmandapp/OsmAnd-iOS#2654]
### Description 
'Change Object's position' command does not accurately place icon

### Steps to reproduce
Select POI / Marker, choose Change Objects Position, move marker circle over new position, click done

### Actual result
Icon for POI / Marker is placed approximately 15mm below chosen location

### Expected result
POI / Marker icon to be located in selected position

### Your Environment
OsmAnd Version: 4.3.4
Android/iOS version: iOS 16.1.2
Device model: iPhone Pro 12 / Model No: MGMN3X/A

**Comment by PaulStets** [comment]
Should be fixed now.

**Comment by Zirochkabila** [comment]
@PaulStets Most likely, it needs to be reopened and refined - we managed to reproduce the user's primary request (**4.4.6.7** version in the video - **OsmAnd on Mac M1**).

- [ ] Favorite is hidden behind the context menu

- [ ] Location is not saved after reopening 

**But in version 4.4.6.8 of iPad**, we can only reproduce the fact that the location of the Favorite is not saved after reopening the application (perhaps the first item cannot be reproduced on the iPad. but it is also present).


https://user-images.githubusercontent.com/104760013/226121040-5bd6d005-44e2-4991-bc45-ce1240a35a5f.mov

**Comment by Zirochkabila** [comment]
4.4.6.10
Done
