### ISSUE TITLE
Wrong active icon color – Trip recording plugin

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2670]
### Description
Incorrect display of the icon "Auto-record track during navigation" status
Blue when disabled and gray when enabled

### Steps to reproduce
Menu > Settings > Select profile > Trip recording > Enable/disable "Auto-record track during navigation" button

### Actual result
Blue when disabled and gray when enabled

https://user-images.githubusercontent.com/104760013/225691502-5aff5466-bf55-47d6-abcb-bc074c6ee24d.mp4

### Expected result
Grey when disabled and blue when enabled

### Your Environment
OsmAnd Version: 4.4.6.7
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2772/files

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2772/files
