### ISSUE TITLE
CarPlay: history doesn't include points that was used in navigation or search

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2677]
## How to reproduce
* Connect iPhone to CarPlay Simulator
* Launch OsmAnd, tap on Navigation
* Select POI Categories, pick any type
* Choose one of the listed POI  /  this should be counted as search history item
* Chose one of the listed POI > tap Start / this should be counted as last route

### Expected result:
* Tap on POI in the search list should be counted as search history item
* Start navigation to the POI should be counted as last route

**Comment by Zirochkabila** [comment]
@dmpr0 we need an additional check on how gestures (screen responsiveness to touch) work in CarPlay

**Comment by dmpr0** [comment]
> @dmpr0 we need an additional check on how gestures (screen responsiveness to touch) work in CarPlay

In this task? Is it related to logging history?
