### ISSUE TITLE
Cropped image in "Arrival announcement" dialog

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2686]
### Description
Image partition in Arrival announcement is cropped when the screen is rotated

## Steps to reproduce
* Reproduce on iPad
* Open Navigation > Settings > Navigation settings > Voice prompts > Announcement time >

### Actual result
* Image is cropped in both Portrait and Landscape mode

## ToDo
- [x]  Image should be scaling by Width to fit the scree width.

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td valign=top><img src="https://user-images.githubusercontent.com/9365308/226945671-8654d854-0719-4ad2-8132-4ada0c624709.png"  width="400" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/226945684-33397f93-5512-4a75-9a84-7289d89611b8.png"  width="400" height="auto"/> </td>
  </tr>
</table>   

### Expected result
Image partition is displayed fully

### Your Environment
OsmAnd Version: 4.4.6.8
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2782
