### ISSUE TITLE
Issues with regions selection

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2693]
Android task https://github.com/osmandapp/OsmAnd/issues/16090.

## Steps to reproduce
1. Zoom on level 5-6 (world wide scale)
2. Click on Lienz (or on Insbruck)
3. Region Tirol should be selected as on provided link

https://nominatim.openstreetmap.org/ui/search.html?q=tirol

## Actual result
Only Insbruck area is highlighted, Lienz area is not highlighted

## Expected result
Bot Insbruck and Lienz area are highlighted

## Testing Note
To test other regions represented as multipolygon Philipines, Greece, Australia Coral Islands

**Comment by PaulStets** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2734
https://github.com/osmandapp/OsmAnd-core/pull/512

**Comment by Zirochkabila** [comment]
4.4.6.13
The main issue is fixed
But, each newly selected region is highlighted with a yellow color, the previously selected region continues to be highlighted as well


https://user-images.githubusercontent.com/104760013/228184392-a0893029-1301-4bb7-bcad-7da0f412ed64.mp4
