### ISSUE TITLE
Context menu actions, redesign to properly fit two lines of text.

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2695]
### Description
In context menu of point, icons are raised and cropped (**Ukrainian language**)

### Steps to reproduce 
Set Ukrainian language > Find this place `17.68583° S, 178.80358° E` > Set a point

<table style="width:100%">
  <tr>
    <th>Actual result</th>
    <th>Expected result</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/104760013/226713576-99993ab1-ee83-4da7-a1c5-44863571c70e.jpeg"  width="500" height="auto"/>> </td>
    <td><img src="https://user-images.githubusercontent.com/104760013/226713662-2b2c99d8-f81f-4c70-91cd-8c34eb726527.jpeg"  width="500" height="auto"/> </td>
  </tr>
</table>   

### Your Environment
OsmAnd Version: 4.4.6.9
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by dmpr0** [comment]
## ToDo
I propose to redesign action button, to use the same as we added to track context menu.

<img src="ttps://user-images.githubusercontent.com/9365308/229751878-c8bcf6a1-411a-4b18-8aaf-6cbeeaa2a125.png"  width="300" height="auto"/>

**Comment by alex-osm** [comment]
- [x] Fix direction arrow https://github.com/osmandapp/OsmAnd-iOS/commit/44977fd476eb3eee768ad81b0736e7a638a35e5f

**Comment by dmpr0** [comment]
## Review
- [ ]  Use `ic_custom_edit` for **Edit favorite**
