### ISSUE TITLE
Crash on re-opening from loading weather maps in the background

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2699]
### Description
Crash on re-opening from loading weather maps in the background (first re-opening takes more than a minute, after which the crash is performed, and to speed up the crash, you need to make a second re-opening)
This may be due to the fact that downloading the weather uses a lot of memory and the device does not have enough resources

### Steps to reproduce
Menu > Maps & Resources > Weather forecast download > Close OsmAnd > Reopen > Close > Reopen > Crash

### Actual result

https://user-images.githubusercontent.com/104760013/226944016-e3903320-a17d-4172-bab6-2254e48a159b.mp4

### Expected result
No crash - weather continues to load up

### Your Environment
OsmAnd Version: 4.4.6.9
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by PaulStets** [comment]
This crash is not related to weather download. It is a known rendering crash.

**Comment by Zirochkabila** [comment]
4.4.7.1
Сrash - done
But, weather stops loading after closing
