### ISSUE TITLE
Quick action is transferred to the My Location button after changing the screen orientation

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2707]
### Description
Quick action button is transferred to the My Location button after changing the screen orientation

### Steps to reproduce
Change the screen orientation to landscape

### Actual result

https://user-images.githubusercontent.com/104760013/227237140-97d2d78d-0d25-47f0-a7b9-9bd58ad5d141.mp4

### Expected result
Must remain in place

### Your Environment
OsmAnd Version: 4.4.6.10
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by vshcherb** [comment]
Location is configured for each orientation separately
