### ISSUE TITLE
Navigation icon blinks during navigation

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2713]
### Description
The navigation icon blinks during navigation

### Steps to reproduce
Starting navigation (or simulation)

### Actual result

https://user-images.githubusercontent.com/104760013/227494430-a274d536-2422-4826-9c35-b38f05ff3e34.mp4

### Expected result
<img width="592" alt="Screenshot 2023-03-24 at 12 18 38" src="https://user-images.githubusercontent.com/104760013/227494859-ec4029cd-94da-4b17-9abd-799045f61063.png">

### Your Environment
OsmAnd Version: 4.4.6.10
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by PaulStets** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2747
