### ISSUE TITLE
Crash when synchronizing data from cloud

### ISSUE THREAD

**Issue by jjfidalgo** [osmandapp/OsmAnd-iOS#2716]
**Description**

When synchronising data from the cloud the application crashes

**Steps to reproduce**
Menu > Settings > OsmAnd Cloud > Sync now

**Actual result**
Crash

**Expected result**
Data is synchronised

**Your Environment**
OsmAnd Version: 4.3.5
Android/iOS version: iOS 16.3.1
Device model: iPhone 13 Pro Max

**Related with** 
https://github.com/osmandapp/OsmAnd-iOS/issues/2511

@Zirochkabila @vshcherb

**Comment by Zirochkabila** [comment]
@jjfidalgo Most likely, this bug has already been fixed - please download the TestFlight version and check the behavior

**Comment by jjfidalgo** [comment]
@vshcherb why this is issue has been closed?. Until I can download a version with the fix and confirm the fix is OK in my device, I don't think the issue should be closed. Even for the proposed TestFlight version, it's not even clear if it fixes the issue. Am I missing something?

**Comment by vshcherb** [comment]
Issue is closed once the code is fixed, the tracker is for developers where users can track the progress.
