### ISSUE TITLE
Distance is cropped is search result list with increased text size

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2717]
Distance is cropped if user increase text size in iOS settings.

## How to reproduce
* Open device **Settings** – **Display & Brightness** – **Text size**
* Set to maximum
* Open **OsmAnd** – **Menu** – **Search** - **Categories**
* Choose any category
* Scroll the list, you will notice cropped text with distance 

### Expected result
* Cell height should change dynamically follow the text size
* Text shouldn't be cropped.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/227504364-b5a47582-46d9-4757-a1d6-7e305a0ce6a2.png"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/227504378-de309396-5a08-45b4-b808-b226fc878bf9.png"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2757

**Comment by Zirochkabila** [comment]
Text is not cropped
But, in some POI, the distance is transferred to the third line, although the description takes two lines

<img width="334" alt="Screenshot 2023-04-15 at 16 34 27" src="https://user-images.githubusercontent.com/104760013/232227385-e7e11c43-3fa8-493e-88d4-244a96e4682e.png">

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2879

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2913/files

**Comment by dmpr0** [comment]
Done
<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/63dcd867-cd2c-4212-9ee4-34f3459f7459"  width="300" height="auto"/>
