### ISSUE TITLE
Сar profile is set by default, even if it is deactivated

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2718]
### Description

When clicked on the Navigation button, the Car profile is displayed as active

When calculating the route, no profile is displayed (although the route is calculated in the Car profile), and when starting navigation, the Car profile is activated
**Car profile is disabled**
It seems that the profile remains active even after it is turned off

### Steps to reproduce
* Open **OsmAnd** - **Settings**
* Disable **Driving** profile
* Leave only the Bicycle, Pedestrian and Public transport profiles active >
* Open **Navigation** > Set start point > Set finish point (route calculated using the Car profile)
* Start (navigation starts in the Car profile)

### Actual result
* Noe of the profile is selected in **Navigation**
* Route calculated using **Car** profile, navigation starts in the Car profile too
* Start (navigation starts in the Car profile)

<table style="width:100%">
  <tr>
    <th>Second profile is displayed as active</th>
    <th>Route calculated with the profile Car that is deactivated</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/227501399-670491b8-dadd-4984-ad2b-17031f13fc97.mp4"  width="300" height="auto"/></td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/227498809-b2f10f09-6ef9-4632-8444-0bad57c73388.mp4"  width="300" height="auto"/> </td>
  </tr>
</table> 

### Expected result

- [x] When clicking the Navigation button, the profile that is first in the list of profiles is displayed as active **(Video 1)**
- [x] Route is calculated only with active profiles **(Video 2)**

<table style="width:100%">
  <tr>
    <th>Video 1</th>
    <th>Video 2</th>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/104760013/227505415-613cdfac-b4e1-4bcb-8576-ce617c141a32.mp4
"  width="300" height="auto"/>  </td>
    <td><video source src="https://user-images.githubusercontent.com/104760013/227505452-606249fc-eee8-4708-8165-33cdc89167c4.mp4
"  width="300" height="auto"/>  </td>
  </tr>
</table>   

### Your Environment
OsmAnd Version: 4.4.6.10
Android/iOS version: iOS 15.7.3 / iOS 16.3.1
Device model: iPad mini 4 / iPhone 14 Pro

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2749

**Comment by Zirochkabila** [comment]
Still present

https://user-images.githubusercontent.com/104760013/232227658-6e2f11d5-9f66-4f89-b7e0-df992094ce93.mov

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2800
