### ISSUE TITLE
The search bar is partially displayed

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2727]
### Description
In some places, the search bar is partially displayed when you switch to a region

### Steps to reproduce

- Menu
- Map & Resources
- Antarctica, Australia and Oceania, North America, Russia, and South America

### Actual result
Search bar is partially displayed

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/227710545-f68451ba-ad92-4668-83d1-a1348146fc90.jpeg" </th>
<th><img src="https://user-images.githubusercontent.com/104760013/227710490-518e08d1-c4f6-4ce8-b309-08142890d303.jpeg" </th>
<th><img src="https://user-images.githubusercontent.com/104760013/227710466-4dd707c9-472f-4cac-98a6-26f671cb0c03.jpeg" </th>
<th><img src="https://user-images.githubusercontent.com/104760013/227710544-7d8ca08c-ba14-4516-8266-b8344fa06475.jpeg" </th>
<th><img src="https://user-images.githubusercontent.com/104760013/227710543-eddae49c-e878-4d95-bc87-d90f9b0082be.jpeg" </th>
  </tr>
</table> 

### Expected result

- [x] The search bar is not displayed until the list of regions is dragged down

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/227710644-7a0c7a01-3a44-4426-9d79-fa25cd3cf251.jpeg" </th>
<th><img src="https://user-images.githubusercontent.com/104760013/227710646-09912aeb-52e4-44f5-9224-a97217841ea5.jpeg" </th>
<th><img src="https://user-images.githubusercontent.com/104760013/227710648-4f49cc21-5bf2-444d-880e-668c8ddd22be.jpeg" </th>
<th><img src="https://user-images.githubusercontent.com/104760013/227710649-5ed95936-6123-4bee-9e5f-f38f3126e67e.jpeg" </th>
  </tr>
</table> 

### Your Environment
OsmAnd Version: 4.4.6.11
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2809
