### ISSUE TITLE
Can't zoom out in Apple CarPlay

### ISSUE THREAD

**Issue by akkana** [osmandapp/OsmAnd-iOS#2729]
Related to the now closed issue #2008 : the speed-dependent zoom is working in CarPlay, but sometimes we need to zoom much farther out for whatever reason, like to see how far it is to the next town, to see what that big highway is up ahead, or just get a view where we are and how far along in the trip. Currently, you can zoom out by tapping the - button repeatedly, but in a few seconds it zooms right back in. Could it please honor a user-initiated zoom in or out, and not override it with the next display update?

**Comment by akkana** [comment]
Thanks, but we already have that pref set to "No auto zoom" and it still auto zooms.

This might have something to do with buggy versions of CarPlay on some cars. My husband says he saw it work yesterday in the Chevy Volt, but today it failed every time (we'd zoom out two or three steps, but after a few seconds it zoomed back in. And in the Toyota Rav4 it always zooms right back in almost immediately.

There are other prefs that aren't being honored either. For instance, the car profile is set to show a little car instead of the blue arrow for current position, but most of the time it shows a blue arrow. On the few occasions when it's shown the car, the no auto zoom pref seemed to be working too. And the map type is set to Offroad, but the displayed map always looks like the default style. So maybe it's just not setting the profile reliably in CarPlay?

This is 4.3.5 on an iPhone SE, which seems to be the latest version on the Apple store.

**Comment by dmpr0** [comment]
@akkana 
You can try to install TestFlight version, https://testflight.apple.com/join/7poGNCKy, it will be available as release in a few weeks.

I have re-tested again mentioned issues with No auto zoom and location icon. I couldn't reproduce it. 
Maybe the issue appeared because OsmAnd doesn't switch to CarPlay profile #2745

**Comment by akkana** [comment]
Confirming that this is due to #2745. When we set the default profile (instead of the CarPlay profile), zooming and follow car both work fine. And I see that issue is marked fixed -- that was fast, thanks! OsmAnd rocks (as always).
