### ISSUE TITLE
Missing cities in the "select city" search

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-ios#273]
Some cities are impossible to find in the "select city" option of the search by address menu.
For example
- Oullins, France : https://www.openstreetmap.org/relation/186363
- Sainte-Foy-Lès-Lyon, France : https://www.openstreetmap.org/relation/192369
- Brignais, France : https://www.openstreetmap.org/relation/192382

**Comment by max-klaus** [comment]
Works with downloaded map of the region.
