### ISSUE TITLE
Feature request: delete all GPX tracks at once

### ISSUE THREAD

**Issue by alyonapinchuk** [osmandapp/OsmAnd-iOS#274]
Currently, it is possible to delete only individual tracks. Please add the feature to delete all trips at once.

**Comment by rschaeuble** [comment]
I'd like to second this request. Deleting many tracks one-by-one certainly isn't the end of the world, but it is a bit inconvenient/annoying, so a bulk delete option would be appreciated.

**Comment by dmpr0** [comment]
Done, available in the latest TestFlight builds.
