### ISSUE TITLE
Swipe to delete

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-iOS#277]
Would it be possible to implement swipe to delete action in (1) favourite and in (2) search history. This action is already implemented to manage installed maps. 
I know that both in search history and favourite screen there is already the possibility to delete item through long press & edit button respectively. But it would be a more natural behaviour to have this feature I think. But you should keep the actual behaviour as well for mass edit.

**Comment by natolh** [comment]
Could also be implemented in : Favourite > Trips

**Comment by AnnBibyk** [comment]
Fixed by @AnnBibyk 
https://github.com/osmandapp/OsmAnd-iOS/pull/654/commits/9abae7b36972a9477de9886e96b12abc02e38186
