### ISSUE TITLE
Cell values doesn't fill free space

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2771]
### Description
In some items of the system, the text is displayed in two lines

### Steps to reproduce

- Menu > Maps & Resources > Updates > Weather forecast > Chose some country
- Menu > Settings > OsmAnd settings 
- Menu > Settings > Select some profile > Navigation settings > Voice prompts > Go down
- Menu > Settings > Select some profile > Wikipedia

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/230090690-521a96ae-7f57-4267-a9dc-1c0d54ecf9e0.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/230090701-4ca568d2-2ec7-44af-a858-e53cd4175981.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/230090704-368364eb-5e2d-4f8d-81ed-fdcbdebd82a5.jpeg"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/104760013/230090705-9234d47d-af15-44c7-9d7b-57030d3aadb7.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
Text is displayed in one line

### Your Environment
OsmAnd Version: 4.4.6.15
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by Zirochkabila** [comment]
A similar behavior occurs if you increase the text size to the maximum  https://github.com/osmandapp/OsmAnd-iOS/issues/2717#issuecomment-1509833122

For example, the second arrow indicates that there is no third line, although the information about POI is displayed as on the first arrow, which has three lines of information

- [ ] It may be possible to display information in two lines

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/232283273-9b1eb5f1-ff8d-48ae-bb66-b9a43d0e2932.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2828

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2833

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2842

**Comment by Zirochkabila** [comment]
4.4.8.15

- [ ] Text in a line takes up two lines - after changing the screen orientation, the text takes up one line (can be reproduced in the 1st, 2nd, and 4th places on the screenshots in the task)

https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/b1c5b241-af9d-40d8-8b6f-7ba9b1963dd5

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f96b0664-4de3-420d-b7cb-c710465f8749"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4d1dcff0-a7e1-4277-af8d-6e6bb689bdc5"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2978

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3062

**Comment by dmpr0** [comment]
# Review 
<table style="width:100%">
  <tr>
    <th>Розташування на екрані</th>
    <th>Компас</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/36028bba-c7b4-4be5-bf52-ab485591fff7"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/99e00240-e5ca-4dbd-aba8-e481bde8387b"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
@dmpr0 2nd name description won't be longer than 50% of the width due to technical limitations (so mentioned screenshots are acceptable), so we need to retest on tablet and see if it takes space enough.

**Comment by dmpr0** [comment]
> @dmpr0 2nd name description won't be longer than 50% of the width due to technical limitations (so mentioned screenshots are acceptable), so we need to retest on tablet and see if it takes space enough.

Each of OsmAnd user need to test in on the tablet even if they don't have it?
