### ISSUE TITLE
"Khikhani Fortress" missed article - Wikipedia

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2775]
## Description
Article about [Khikhani Fortress](https://www.openstreetmap.org/way/547497894#map=19/41.54140/42.56534) is missed in Wikipedia for Georgia. Looking it online, it seems it has coordinates. [Wikipedia](https://ka.wikipedia.org/wiki/%E1%83%AE%E1%83%98%E1%83%AE%E1%83%90%E1%83%9C%E1%83%98%E1%83%A1_%E1%83%AA%E1%83%98%E1%83%AE%E1%83%94)

### How to reproduce
* Open **OsmAnd** – **Menu** - **Maps & Resources** – **Asia** – **Georgia**
* Download **Standard** and **Wikipedia** maps
* Open **Search** - **Address** – **Coordinates search**
* Search `41.54137° N, 42.56541° E`
* Select **Khikhani Fortress** on the map, tap **Details**
* Tap on Wikipedia link

<table style="width:100%">
  <tr>
    <th>Online Wikipedia</th>
    <th>OsmAnd</th>
  </tr>
  <tr>
    <td valign=top><img src="https://user-images.githubusercontent.com/9365308/230327151-695192c9-1ed6-4cef-9c10-78c1cfa1873f.png"  width="300" height="auto"/>  </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/230327410-3a2e59c8-7ec3-4ce7-b6d7-2149b9385e98.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
OSM parsing without relation
1. Save ALL nodes to DB
2. Process way (filter by tag) using saved nodes

OSM parsing with relation
1. Save relations (filter by tag) with consist of info ways and nodes.
2. Second parsing. Using first parsing:
2.1 Save ALL nodes to DB
2.2 Process way (filter by ids + filter by tag) using saved nodes
2.3 Calculate common way for relation based
-------------------

3. Calculate coordinates
