### ISSUE TITLE
URL field is duplicated in Context Menu

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2776]
## Description
Object on OSM [Khikhani Fortress](https://www.openstreetmap.org/way/547497894#map=19/41.54140/42.56534)

### How to reproduce
* Open **OsmAnd** – **Menu** - **Maps & Resources** – **Asia** – **Georgia**
* Download **Standard** map
* Open **Search** - **Address** – **Coordinates search**
* Search `41.54137° N, 42.56541° E`
* Select **Khikhani Fortress** on the map, tap **Details**

## Expected result
* URL field will be shown as one item

## Actual result
* URL field is shown as two items

<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/230329499-3ea5f33d-cd81-43bd-8287-6cfe842e474c.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
Android too

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/230396659-091db7f2-5a4a-4aca-ae3c-208e905c09f8.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Not too bad
