### ISSUE TITLE
Pushnotification works for everyone

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#2783]
There is a restriction on displaying a push notification banner if subscriptions or in-apps are purchased. 
But OsmAnd shows push notifications always. 
![telegram-cloud-photo-size-2-5296360709887739922-y](https://user-images.githubusercontent.com/44466116/230641410-a0f0e50f-0f7a-4d20-a2b8-b7f1abe0c30c.jpg)

**Comment by alex-osm** [comment]
Bad json
