### ISSUE TITLE
When external input device is set to WunderLINQ UP/DOWN Arrows Keys should Zoom In/Out

### ISSUE THREAD

**Issue by blackboxembedded** [osmandapp/OsmAnd-iOS#2785]
A recent change to the iOS app now has all External Input Controllers UP/DOWN Arrow keys mapped to Pan Up/Down.  When set to WUNDERLINQ_EXTERNAL_DEVICE it should map Up/Down to Zoom In/Out respectively.

**Comment by Zirochkabila** [comment]
Merge with https://github.com/osmandapp/OsmAnd-iOS/issues/2698
