### ISSUE TITLE
Subscription Promo Pro doesn't activate without internet connection 

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#2787]
My use-case:
I have Promo Pro subscription and OsmAnd 4.4.6. I use iPhone XS without sim-card (I have only Wi-Fi connection at home).
When I didn't start OsmAnd app at home and go out from Wi-Fi zone, I see the next pictures: 
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/44466116/231137848-116a96cc-a0e2-4b03-a89b-ee93a3704831.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

My purchase screen try to connect and find my puchases.
At that moment I have all paid features except Pro:
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/44466116/231137917-2d728ae6-8ad3-42c5-b35e-dfcc2482027e.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/44466116/231138031-33998e06-88dd-49a3-9e6c-38a4d480eee4.png"  width="300" height="auto"/> </th>
  </tr>
</table>  

My proposal is to save the status of purchasing and not find it each time. 

My Purchases screen with wi-fi connection:

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/44466116/231138413-873b1e48-a787-49a5-926a-cb7585ee64c3.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.8.11
**Bug still present**

If disconnected internet data - subscription is still active and all paid features work, and the plugins appear activated
But if you **opened  Cloud or Restore purchases menu,** - paid features stop working.
