### ISSUE TITLE
Map opens automatically when try to enter building number in Address search

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2790]
### How to reproduce
* Open **OsmAnd** – **Menu** – **Search** – **Address**
* Tap on **Select street in `City name`**
* Enter street name, select it from the search results
* Try to enter building number

#### Actual result
* OsmAnd will automatically close Search and open Map screen somewhere in the middle of selected street

#### Expected result

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/231427339-1d8454db-50ae-431e-9d6e-1e5232c05dd8.MP4"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by Skalii** [comment]
[Fix search for non-existing building](https://github.com/osmandapp/OsmAnd-iOS/pull/2862)
