### ISSUE TITLE
custom render on ios no place names

### ISSUE THREAD

**Issue by marticigor** [osmandapp/OsmAnd-iOS#2791]
Hi, my custom render theme works fine on android but on ios there is no place names (towns, villages...)
Also, there is no custom color option for contour lines, like there is on android.
Can you please check.

Thanks in advance,

Igor.
https://github.com/marticigor/osmand-cartographia

**Comment by marticigor** [comment]
> Hello! Places names are missing both on iOS and Android with **Map rendering engine** set to **Version 2 (OpenGL).**
> iOS 	Android
> <img alt="" width="300" height="auto" src="https://user-images.githubusercontent.com/9365308/231681969-04236f8d-5a68-444c-94cf-e33d052785e6.jpg"> 	<img alt="" width="300" height="auto" src="https://user-images.githubusercontent.com/9365308/231681994-b80366fc-f20a-4a72-bd9c-b8f40e6eaed0.jpg">
Hi,
thanks for the hint, but I simply can't find the culprit in the theme. I tried to remove switches for engine_v1, but still I can't see place and water name texts.
[Cartographia.hu.render.txt](https://github.com/osmandapp/OsmAnd-iOS/files/11231820/Cartographia.hu.render.txt)

**Comment by Zirochkabila** [comment]
City and country names are displayed in V1 rendering

**Comment by xmd5a2** [comment]
Rendering style seems to be correct. Unable to find issue. Need OpenGL debugging.

**Comment by cepprice** [comment]
@marticigor `renderingConstant`s should be in `<renderingStyle>`, not in `<text>`

https://github.com/marticigor/osmand-cartographia/blob/main/Cartographia.hu.render.xml#L2666-L2669

**Comment by marticigor** [comment]
Thanks @cepprice for finding this, works now, I have place names.
However, there is still incorrect displaying of hiking and cycling paths, and no custom color option for countour lines:
this lines seem to have no effect on ios(opengl):
https://github.com/marticigor/osmand-cartographia/blob/443e4ab8ac0f423ce3431b5828f5d1ed2479d491/Cartographia.hu.render.xml#L7719 path effect and color
https://github.com/marticigor/osmand-cartographia/blob/443e4ab8ac0f423ce3431b5828f5d1ed2479d491/Cartographia.hu.render.xml#LL7556C9-L7556C9 ->patheffect and color
https://github.com/marticigor/osmand-cartographia/blob/443e4ab8ac0f423ce3431b5828f5d1ed2479d491/Cartographia.hu.render.xml#LL953C10-L953C10 -> no countour color option

Thanks.

**Comment by Zirochkabila** [comment]
@xmd5a2 please review this information - can we fix it?

**Comment by vshcherb** [comment]
@Zirochkabila @marticigor it could be time consuming let's wait for releases. Android / iOS should be functioning the same

**Comment by marticigor** [comment]
> Thanks @cepprice for finding this, works now, I have place names. However, there is still incorrect displaying of hiking and cycling paths, and no custom color option for countour lines: this lines seem to have no effect on ios(opengl): https://github.com/marticigor/osmand-cartographia/blob/443e4ab8ac0f423ce3431b5828f5d1ed2479d491/Cartographia.hu.render.xml#L7719 path effect and color https://github.com/marticigor/osmand-cartographia/blob/443e4ab8ac0f423ce3431b5828f5d1ed2479d491/Cartographia.hu.render.xml#LL7556C9-L7556C9 ->patheffect and color https://github.com/marticigor/osmand-cartographia/blob/443e4ab8ac0f423ce3431b5828f5d1ed2479d491/Cartographia.hu.render.xml#LL953C10-L953C10 -> no countour color option
> 
> Thanks.

Hello, anything regarding this? Hi can I make this work? I tested on android latest nightly and works as expected, but on ios still the same. Can I do something on my side?

Thanks in advance.

Igor.

**Comment by marticigor** [comment]
Based on this [thread](https://github.com/osmandapp/OsmAnd/discussions/16699) looks like this is fixed on android but not on ios.
