### ISSUE TITLE
Change zoom to show layers – Weather

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2795]
# Description 
Weather layers not helpful on close zoom levels, we can add automatic zoom out when Weather screen is opens.

## ToDo
- [x] Change zoom level to `10`, if it was bigger than `10` when **Weather** screen is opens.
- [x] Revert zoom level, to value used before **Weather** screen was opened (if user was not interact with map).
* For example, if zoom level was 16 > user opens Weather screen > zoom level changes to 10
* * Not interaction with map and tap back = zoom level revert to 16
* * Interact with map and tap back = zoom level leaves the same as was in Weather screen

**Comment by Skalii** [comment]
[Weather - zoom in toolbar](https://github.com/osmandapp/OsmAnd-iOS/pull/2826)
