### ISSUE TITLE
Don't add World Overview map to downloads on Start screen.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2796]
## Description 
On first launch, OsmAnd on iOS is still automatically add WorldOverview map to list of downloads if user is start to download proposed map on start screen.

- [x]  Don't add World Overview to downloads list on Start Screen.

**Comment by Zirochkabila** [comment]
4.4.7.2 Still present

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2847
