### ISSUE TITLE
GPX import issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-iOS#280]
OsmAnd offers to import a track as Favourites even if the track does not contain waypoints.

**Comment by vshcherb** [comment]
The name of file should be checked and only "favorites.gpx" or "favourites.gpx" should be suggested.

**Comment by AnnBibyk** [comment]
Fixed by @AnnBibyk 
https://github.com/osmandapp/OsmAnd-iOS/pull/655

**Comment by AnnBibyk** [comment]
Fixed by @AnnBibyk
https://github.com/osmandapp/OsmAnd-iOS/pull/655
