### ISSUE TITLE
Restore from file leads to unnecessary duplicates in /backup/ folder

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2802]
## Description 
After restoring data from OSF file, OsmAnd creates backups for each profile, I guess? Each file size is equal to original backup OSF file.

### How to reproduce
**Create backup file** or using example [Export_17-04-23-Map-Profiles.osf.zip](https://github.com/osmandapp/OsmAnd-iOS/files/11250021/Export_17-04-23-Map-Profiles.osf.zip)

* Open **Menu** – **Settings** – **Backup as file**
* Select all **Settings** 
* Select one **Offline Map** 
* Tap Continue, save file in **Files** app.

**Import file**
* Open Menu - Settings - Restore from file
* Select file from previous step using Files app
* On Import screen Select all – tap **Import**
* On the screen **Some items already exist**, select **Replace all**

#### Expected result
* All selected items will be imported into OsmAnd
* Backup files for custom profiles should include only settings. Currently all data (GPX, OBF) is backup.

#### Actual result
* Mostly all items is imported
* OsmAnd created backup file in` /OsmAnd Maps/backup/ `for each profile, each file size is equal to Restored file.

<table style="width:100%">
  <tr>
    <th>Before restore</th>
    <th>After restore</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/232482701-2d780d22-69c7-4e26-a591-0337450ede76.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/232482734-2eb3a889-1fa9-45c8-a6aa-91cb2eb5df9a.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2864
