### ISSUE TITLE
Contour lines doesn't restore from file

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2803]
## Description
Contour lines doesn't restore from `.OSF` but they present in archive and visible on Import state. Tested on 4.4.7.2

### How to reproduce
* Download file [Export_17-04-23-Andora.osf.zip](https://github.com/osmandapp/OsmAnd-iOS/files/11250298/Export_17-04-23-Andora.osf.zip)
* Import file to OsmAnd
* Contour lines is missed, but they present in OSF

<table style="width:100%">
  <tr>
    <th>Import/Export screen show all maps</th>
    <th>"Local" before backup</th>
    <th>"Local" after restore</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/232488529-f824444f-e9cf-44dc-90f1-b28ca898e330.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/232488834-9cfd46cf-0815-40ca-b44a-fdc6933530a3.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/232488774-fefb4412-3525-4e10-bdb2-7d7a62240425.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2867
