### ISSUE TITLE
Plugin and Profiles status doesn't import back from OSF

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2804]
## Description
Status On or Off of profiles and plugins is not imported or not exported back from local OSF backup

* File [Export_17-04-23-Plugins.osf.zip](https://github.com/osmandapp/OsmAnd-iOS/files/11250400/Export_17-04-23-Plugins.osf.zip)

<table style="width:100%">
  <tr>
    <th colspan=2>Plugins</th>
  </tr>
  <tr>
    <th>Before restore</th>
    <th>After restore</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/232489834-01ab9eae-9738-44bf-9d5b-18c4ff986676.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/232489513-dcffbfa1-386b-475a-ae90-6e36ec19bf03.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>   

<table style="width:100%">
  <tr>
    <th colspan=2>Profiles</th>
  </tr>
  <tr>
    <th>Before restore</th>
    <th>After restore</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/232490799-e3d78677-8ecb-481e-93d7-9f81aca1d138.PNG"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/232490804-f2c7b390-2847-4305-b0b3-09070eed9b88.PNG"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src=""  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>   

![image](https://user-images.githubusercontent.com/9365308/236433569-e3782eca-6da9-4fcb-ae38-23948162aec5.png)

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2881
