### ISSUE TITLE
Allow to use Emoji in user point names 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2808]
## Description
Core team have fixed displaying emoji on the map https://github.com/osmandapp/OsmAnd-Issues/issues/1250, but in the past we was added code that don't allow to use emoji as one or first symbol in the favorites/waypoint name.

### How to reproduce
* Select any point on the map
* Open **Context menu**, tap **Add favorites**
* Tap on **Name** field, clear proposed name if present
* Enter emoji as first or last symbol in the name

#### Actual result
* OsmAnd will show alert
* OsmAnd will remove all emoji's from the name 
<img src="https://user-images.githubusercontent.com/9365308/232803508-3c5c9b89-e280-4db5-bd5d-d8814da2699c.png"  width="300" height="auto"/> 

#### Expected result
* OsmAnd allows to use emoji symbol in any place while entering name for favorite/waypoint

## Todo
- [ ] User can use emoji in the favorite/waypoint name

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/e2237f0

**Comment by Skalii** [comment]
[Favorites - show emoji](https://github.com/osmandapp/OsmAnd-iOS/pull/2825)

**Comment by dmpr0** [comment]
* Work on UI
* Doesn't work on Map https://github.com/osmandapp/OsmAnd-Issues/issues/1250
<img src="https://user-images.githubusercontent.com/9365308/235452046-1917ae6a-f6cc-4d76-8c24-a3a8b8789d4a.jpeg"  width="300" height="auto"/>
