### ISSUE TITLE
Progress bar is missing – Upload GPX to OpenStreetMap

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2810]
### To Do

- [x] Display information (like in Master branch):

1. Unloading - on the left
2. Interest - on the right

### Description
No information is available in the track loading bar - when uploading a track to OSM
Original issue https://github.com/osmandapp/OsmAnd-iOS/issues/1132#issuecomment-1509754607

### Steps to reproduce

- Select track
- Actions
- Upload to OSM
- Enter a description
- Upload

### Actual result

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/232221742-aac03b43-db84-4559-a033-a135af502258.jpeg"  width="470" height="auto"/> </th>
    <td><video source src="https://user-images.githubusercontent.com/104760013/232221751-ee05b864-1318-41fe-b6db-8397873b09a8.mp4"  width="300" height="auto"/> </td>
  </tr>
</table> 

### Expected result
<img width="334" alt="Screenshot 2023-04-19 at 12 34 32" src="https://user-images.githubusercontent.com/104760013/233034582-06e0eef6-c94b-431c-858a-e8ee4c1a3683.png">

### Your Environment
OsmAnd Version: 4.4.7.2
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by DmitrySvetlichny** [comment]
https://user-images.githubusercontent.com/111898301/234805936-972c926d-9f7c-4062-9fdd-f487abde55a5.mp4
