### ISSUE TITLE
Profile icon is updated only after the page refreshes

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2817]
## ToDo
Profile icon doesn't changes back (if it was changed) after profile settings was reseted to default
> Android task https://github.com/osmandapp/OsmAnd/issues/16750

### How to reproduce
* Open **OsmAnd** – **Menu** - **Settings** – **Driving** 
* Select **Profile appearance** 
* On **Select icon** group, change icon to any other, **Taxi** for example
* Tap **Save**
* You will be back to **Configure profile**, scroll down to **Actions** group
* Tap on **Reset to default** – **Reset**

#### Expected result
* Profile icon and color will be changed after reseting will be done

#### Actual result
* Profile icon and color changed only after scrolling back or other interactions with the screen

<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/233600063-3ad92aa4-7dc7-42cf-8548-d5ef602bbb43.png"  width="300" height="auto"/> </td>
    <td><video source src="https://user-images.githubusercontent.com/9365308/233600009-05295b8f-4398-4ad9-9700-d076e047ce27.MP4"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2950
