### ISSUE TITLE
Pages for Widgets

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2820]
## ToDo
* Allow to add pages for Left/Right panel. (Implemented on Android)

**Comment by DmitryAlexei** [comment]
https://docs.osmand.net/docs/user/widgets/configure-screen
we need to describe how to create pages for widgets

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/widgets/configure-screen.md#pages-for-widgets

**Comment by vshcherb** [comment]
Структура непонятна.
- Кнопки не являются виджетами, они являются часть HUD.
- Слово дубликаты не употреблять. Никому дубликаты не нужны нужно правильно подобрать слова.
- Actions panel (Android) / Three-button menu - вообще не понял что за раздел и про что это
- Список виджетов сомнительная идея, но если и делать то отдельным списком, а лучше не делать вообще
- Buttons нет ссылки на кнопки какой-то ограниченный список. А нужен ли тут список или он должен в статье Map Buttons? А здесь должна быть именно про настройки кнопок

Возможная структура:
```
- Overview
- Buttons
- Top / Bottom Panel
   * Rows
- Left / Right Panel
   * Pages
- Widget settings
- Actions (? нужно ли вообще)
  * Swich profile
  * Удалить виджет
  * Reset to default
```

**Comment by EugeneZmeuk** [comment]
Reviewed
- (Pages for widgets Section)[https://docs.osmand.net/docs/user/widgets/configure-screen/#pages-for-widgets]

**Comment by EugeneZmeuk** [comment]
18.03.2024 Review: next task for adding and re-write (release 4.7) [here](https://github.com/osmandapp/OsmAnd-Issues/issues/2302#issuecomment-2004766985)
