### ISSUE TITLE
Checkbox not correctly displayed - My Places / Tracks

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#2827]
In OsmAnd 4.4.1 in French, when I select displayed tracks, the displayed tracks below are not individually checked (left blue checked button)
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/59312735/233850757-fd31d3c3-07fd-47eb-907e-6baad46d95a3.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by nabilys** [comment]
Also, if we individually select ont of the tracks belonging to « displayed tracks », the top bar increment, but we still don’t see what’s selected 
![IMG_3352](https://user-images.githubusercontent.com/59312735/233851127-ab91d0fc-e525-427d-9e55-844ce137cf2c.jpeg)

**Comment by Zirochkabila** [comment]
4.4.7.2 - similar behavior. Tracks are not displayed as selected

https://user-images.githubusercontent.com/104760013/233996997-32ac56bb-ede7-4dfa-ba78-760013653dd9.mp4
