### ISSUE TITLE
Map is very busy with Public Transport stops

### ISSUE THREAD

**Issue by mguaylambert** [osmandapp/OsmAnd-ios#283]
There is no option to disable labels of the public transport stops. We did the import and since then, the map became extremely busy, trying to show all names (like in the picture)
I am not sure what is the best approach here. Either it should not show the labels before a very high zoom level and / or to have an option to disable it. (Still show the bus stops icons, without labels).
Thank you for you hard work! 🤗
![IMG_1145](https://user-images.githubusercontent.com/16389438/57172729-db948380-6df1-11e9-9340-a6549e9751f2.jpeg)

**Comment by vshcherb** [comment]
The icon size will be increased, so it might give more room and less text.

**Comment by mguaylambert** [comment]
@vshcherb sadly, it has not got better even with new settings. 🙁
![IMG_1368](https://user-images.githubusercontent.com/16389438/58386465-2444f400-7fce-11e9-8ad7-b496d5ec1f7f.png)

**Comment by mguaylambert** [comment]
At a lower zoom level, there is the same with parks names.
![IMG_2015](https://user-images.githubusercontent.com/16389438/60399863-a37f9780-9b39-11e9-8ccf-a945308e18cd.png)

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/80490141-38713e00-8961-11ea-951c-5d3110db95ba.png)
![image](https://user-images.githubusercontent.com/1042025/80490157-3c9d5b80-8961-11ea-83f9-60784d884243.png)

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/80490183-458e2d00-8961-11ea-874c-e124f320e9b0.png)

**Comment by louxyy** [comment]
I disabled all options on the map, including the transportation option, but I still see the bus stop icons on the map. 

Are there plans to add an option to hide bus stops on the map? Or is it possible to hide them using a custom render? All these points of interest are slowing down the loading time of the map.
My OSMand version : 4.9.6

![image](https://github.com/user-attachments/assets/d8c076b4-b95a-4685-9242-21760e5b58b4)
