### ISSUE TITLE
Wrong title for Transporting of hazardous materials

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2830]
## ToDo
`Hazmat category is wrong`, `Transporting of hazardous materials` is should be used for the option.
Proper Android string https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd/res/values/strings.xml/#L474

- [x]  Use `Transporting of hazardous materials` 
<table style="width:100%">
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/233976212-1d18da52-3d01-491f-921f-d440a541cc68.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2945

**Comment by yuriiurshuliak** [comment]
The English title has been successfully changed. However, for other languages (Ukrainian, German, Russian), it remained preliminary.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/e0ace777-3c38-4e5a-896c-8c6ad27f9d63"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/2a04330b-b53e-4d97-9437-262faeec3062"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/6de05682-f2b9-44fa-9d8c-ea57e9943d06"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/a1466da8-48ed-4003-a713-154be506aca9"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/f84b9efe-df11-44a2-9db8-5e4d59800ebd"  width="300" height="auto"/> </th>
  </tr>
</table>
