### ISSUE TITLE
Sunrise widget - Time left formatting

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#2838]
## Review
 Time left: show the time left to sunrise, example 05:25 **h**
- [x]  **"h"** for hours and **"m"** for minutes is missing to **Time left** mode.

_Originally posted by @dmpr0 in https://github.com/osmandapp/OsmAnd-iOS/issues/233#issuecomment-1485072957_

**Comment by Zirochkabila** [comment]
4.4.8.2

- [ ] Display "хв" instead of "m" when selecting the Ukrainian language 

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/235210045-456c8e51-9624-4236-99c0-69239ad47102.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>
