### ISSUE TITLE
“Road” and “undefined” are both white in navigation information 

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#2846]
Road” and “undefined” are both white in navigation information, which make difficult to know if we will face a road or something undefined, in OsmAnd 4.4.1
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/59312735/234823366-c31ec316-cf4a-457a-a5bd-bd725203854a.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
@nabilys Cannot be reproduced - please download the nightly version (or an available update) and try again.
If the behavior repeats, please send your route coordinates and profile settings.

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/234964934-37652a91-ac0a-4f8c-803d-b794e7f84383.png"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by nabilys** [comment]
Unfortunately I have limited data (traveling) so I can’t 
Doesn’t seems to happen with dark mode, same version 
![IMG_3382](https://user-images.githubusercontent.com/59312735/234966636-5ef30d99-f8ec-49b8-82f4-ecbe37758dad.png)

**Comment by Zirochkabila** [comment]
4.4.8.2
Can be reproduced only in Day mode
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/234969464-62929112-a993-48ab-89a4-f77bfa87a0b1.png"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
This colors or even they presence are depends on Map style. Judging from colors on first screenshot, @nabilys use LightRS.

**Comment by nabilys** [comment]
I am using OsmAnd offline
![IMG_3519](https://user-images.githubusercontent.com/59312735/235429208-3f89c0c8-b787-42d1-a1a9-cde11d832382.png)

**Comment by xmd5a2** [comment]
Color added. Please test when new OsmAnd will be available.

**Comment by yuriiurshuliak** [comment]
OsmAnd~ 4.5.0#209m, released: 2023-06-14
Colors are fixed on the latest nightly version. 
|<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/7d0a34d2-cd5e-46b2-b9a4-8668652c939a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/92acd47b-dc26-4b5d-8dc2-f08b9e169feb"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
OsmAnd~ 4.5.0#209m, released: 2023-06-14
OsmAnd 4.4.10

In day mode on iOS, the color difference was not corrected.

In night mode on iOS, the colors are correct.
The colors are also correct in Android day and night mode.

|<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/85b254f2-8091-45b0-92ff-1c95dac84250"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/c68f80b5-a78e-4852-bbbe-a3a4206af788"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/90e2b8a4-4ea6-472c-b860-e610dba3736a"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Android:
![изображение](https://github.com/osmandapp/OsmAnd-iOS/assets/5829014/3d547673-c50e-493c-bf30-fb1338e5ebd2)
