### ISSUE TITLE
Check tunnel simulation

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-ios#285]
https://www.openstreetmap.org/#map=14/64.5368/-21.9024 - track could be attached

**Comment by crimean** [comment]
Works ok

**Comment by MagielBruntink** [comment]
Is tunnel simulation supposed to work automatically? I just had a poor experience in a (Prague) tunnel where position simply didn’t update any further upon entering the tunnel. Updates only resumed after exiting the tunnel.

App version 4.2.4.
