### ISSUE TITLE
Can't tap a track on the map

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#2850]
I attached my track to the roads.  After that, I can't tap this track on the map.

[2023-04-23_16-36_Sun.zip](https://github.com/osmandapp/OsmAnd-iOS/files/11351862/2023-04-23_16-36_Sun.zip)

OsmAnd version:  4.4.8.2 Testflight

**Comment by Zirochkabila** [comment]
4.4.8.3
Cannot be reproduced
@EugeneZmeuk  Please add a video that shows all the steps to reproduce
