### ISSUE TITLE
Tabbar in Favorites doesn't displayed after cancel search

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2852]
### To Do

- [x] Displayed tabbar  in Favorite as in Tracks

### Description
Tabbar in Favorites doesn't displayed after cancel search

### Steps to reproduce
Menu > My Places > Favorites > Tap in Search line > Cancel

### Actual result

https://user-images.githubusercontent.com/104760013/235159269-cd551909-631b-4fe2-b1a8-9537af1433ea.mp4

<table style="width:100%">
  <tr>
    <th>before search</th>
    <th>after</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/68b92ee8-5940-420a-a3f2-95efdf8858e5"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/f8b41cac-d2ad-4d92-aaed-13aa98e7748a"  width="300" height="auto"/> </th>
    <td><video source src="  width="300" height="auto"/> </td>
  </tr>
</table> 

### Expected result

https://user-images.githubusercontent.com/104760013/235159495-43ca32c9-4708-4d05-aa6f-f5f1795a573c.mp4

### Your Environment
OsmAnd Version: 4.4.8.3
Android/iOS version: iOS 15.7.3
Device model: iPad mini 4

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2886
