### ISSUE TITLE
Crash after taping on Wikipedia link in context menu

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2858]
### How to reproduce
* Go to `52.37315, 4.89103`
* Tap on **Koninklijk Paleis**
* In context menu tap Details
* Tap on wikipedia link

> Tested on current master build.

<table style="width:100%">
  <tr>
    <td><video source src="https://user-images.githubusercontent.com/9365308/235702370-43ca338e-1c0b-4c26-8e98-3179126910b7.mov"  width="300" height="auto"/>  </td>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.4.8.5

<details><summary>Behavior was checked at 52.37340° N, 4.89280° E</summary>
<img width="600" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/236689978-5554fe11-9fef-4cec-8ca1-294849e2152f.jpeg">
</details> 


<details><summary>This place 52.37315, 4.89103 doesn't have Wiki link</summary>
<img width="600" alt="Screenshot 2023-01-31 at 11 19 41" src="https://user-images.githubusercontent.com/104760013/236690078-524edccf-9b20-4f95-abfa-447737fdb701.jpeg">
</details>
