### ISSUE TITLE
[BUG] Lagy map selection & app freezing

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-ios#286]
Device : iPhone 5S (ME432F/A)
OS : iOS 12.2
Build : 2.64 (Beta) with OsmAnd Live

Problem
The app is responding extremely slow to POI selection and freeze until the detail screen is shown. While this problem was also existing in the previous versions the app was still usable.

Steps to reproduce
- Select a feature on the map
- Wait (you can try to drag the map)

Attempts to fix the problem
- Restarting the app did not change anything.
- Reinstalling maps did not change anything.

Here are some home mesured times :
- 44 seconds (https://www.openstreetmap.org/node/5968545369)
- 40 seconds (https://www.openstreetmap.org/node/5109013740)
- 21 seconds (https://www.openstreetmap.org/node/6367654518)
- 45 seconds (https://www.openstreetmap.org/node/5343218934)
- 45 seconds (https://www.openstreetmap.org/node/2326863062)
- 3 seconds (https://www.openstreetmap.org/way/242947592)
- 13 seconds (https://www.openstreetmap.org/node/475875488)
- 9 seconds (https://www.openstreetmap.org/node/3067355027)
- 7 seconds (https://www.openstreetmap.org/way/317427599)
- 31 seconds (https://www.openstreetmap.org/node/1628920558)
- 2 seconds (https://www.openstreetmap.org/node/6037627225)
- 2 seconds (https://www.openstreetmap.org/node/3514374361)
- 5 seconds (https://www.openstreetmap.org/node/6421906898)
- 1 second (https://www.openstreetmap.org/node/4500780205)
- 2 seconds (https://www.openstreetmap.org/way/485074014)
- 2 seconds (https://www.openstreetmap.org/relation/166988)

Hypothesis : it seems that longer times are obtained in dense urban areas.

**Comment by crimean** [comment]
This is known issue in 2.64 version. Will be fixed in the next version. Thanks for reporting!
