### ISSUE TITLE
graduation between elevation and road type does not match

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#2860]
In OsmAnd 4.4.1, the graduation between elevation and road type does not match
<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/59312735/235839402-4208977d-09b5-49c4-be7e-29dcb1c857b7.jpeg"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
@nabilys If we are talking about displaying graphs at the same level, then these are different graphs and display data differently.
For example, in the screenshot below, you can see that the scale is placed in the same way on the graphs of the same type.
If the graph does not correspond to the actual route, please provide the start and finish coordinates of the route

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/104760013/235865788-8b747079-a46f-4b93-b822-b2e6024dd77e.jpeg"  width="500" height="auto"/> </th>
  </tr>
</table>

**Comment by nabilys** [comment]
I have the same behavior than your screenshot. The data may have different intervals for the kilometer (in your example, first grad each 30 km, others each 40km) but shouldn’t 120km appear at the same place in both graduations?

**Comment by Zirochkabila** [comment]
@nabilys These are different types of graphs, so they have different scales

**Comment by vshcherb** [comment]
We're going to update documentation and algorithm, as you see green graph will indicate how much counts uphill (> 0). On your graph  you see that even as graph goes uphill there are values green < 0 it means uphill will be bigger than "Max - Min altitude"
