### ISSUE TITLE
POI information is not available if Wikipedia data is downloaded

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2866]
# Description
Found by @Zirochkabila in #2858.

## How to reproduce
* Open `52.37315° N, 4.89103° E`, download standart offline map for North Holland
* Tap on **Koninklijk Paleis** standart data for POI from OSM will be shown https://www.openstreetmap.org/relation/3580875
* Tap on Wikipedia link, in dialog, select Download Wikipedia data
* Close the context menu, tap again on **Koninklijk Paleis** icon on the map, new context menu will be shown for Wikipedia point. Wiki plugin and layer is disabled.

<table style="width:100%">
  <tr>
    <th>Without Wiki data</th>
    <th>With Wiki data</th>
  </tr>
  <tr>
    <td><img src="https://user-images.githubusercontent.com/9365308/236783683-9635fa17-d146-40cf-b2b7-257ecd93960b.jpg"  width="300" height="auto"/> </td>
    <td><img src="https://user-images.githubusercontent.com/9365308/236783769-a4835a1f-37dc-4d81-b609-e18ebb62f0fe.jpg"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by Skalii** [comment]
[fix open poi exclude categories](https://github.com/osmandapp/OsmAnd-core/pull/597)

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-core/commit/af79d945e793c4f18b530f13c31b118495be9c55
