### ISSUE TITLE
Wrong  icon for Appearance saving hiking route

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2875]
# Description
Navigation icon is shown instead of appearance.

## How to reproduce
* Open Configure Map, enable Hiking routes
* Go to `46.93489° N, 8.12519° E`
* Tap on any hiking route
* In context menu, tap **Save**
* New action icons will be shown

### Result
* Navigation icon is shown for Appearance until re-selection GPX from the map

<table style="width:100%">
  <tr>
    <th>After saving</th>
    <th>After menu re opening</th>
    <th>Video</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/0996c51c-a1f4-451e-933f-c7f811c75327"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/be7a3ad5-b4f6-465b-8cb1-26fc378a7412"  width="300" height="auto"/> </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d49f9de4-39b7-408e-b960-5ae84a9b18cc"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2890
