### ISSUE TITLE
Avoid unintended "Manually rotated" orientation 

### ISSUE THREAD

**Issue by nvardi** [osmandapp/OsmAnd-iOS#2882]
The "manually rotated" orientation mode is activated automatically by a two finger gesture. This can happen when the user only intends to zoom by pinching. Add a setting option that disables the rotation activation, so that the "north up" orientation remains active even when the user inadverently  rotates the map while zooming. This option may also be toggled by a long press on the compass icon in "north up" state.

**Comment by nvardi** [comment]
Yes, it is a duplicate. Sorry, I missed the other issue when I searched. I
will close our delete mine. Thanks for letting me know.

Nitsan

**Comment by nvardi** [comment]
Why reopen? This is a duplicate, and all the arguments for and against are already stated in https://github.com/osmandapp/OsmAnd/discussions/16836

**Comment by dmpr0** [comment]
> Why reopen? This is a duplicate, and all the arguments for and against are already stated in [osmandapp/OsmAnd#16836](https://github.com/osmandapp/OsmAnd/discussions/16836)
Android and iOS are different. If we wan't to fix it we will need to do it separately for iOS.

**Comment by Zirochkabila** [comment]
4.4.8.14
Confirmed
To reproduce, needed to change the zoom level using a two-finger swipe
