### ISSUE TITLE
Borders of downloaded maps displayed while Weather enabled

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2888]
### To Do

- [x]  Hide borders downloaded maps while Weather enabled

### Steps to reproduce

- Configure map
- Show borders of downloaded maps
- Menu
- Weather

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/4faa1046-eaaf-4338-9314-23274fd9ca93"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result

https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/d3bdb21e-ab83-4dd8-a923-3c75427a8e1c

### Your Environment
OsmAnd Version: 4.4.8.11
Android/iOS version: iOS 15.7.5
Device model: iPad mini 4

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2955/files
