### ISSUE TITLE
Add to a track function doesn't work

### ISSUE THREAD

**Issue by zipav** [osmandapp/OsmAnd-iOS#2893]
### Description

When trying to merge several imported tracks into one using **Add to track** function it doesn't work. 
On Android, the merging happens as it should.
* Tracks [tracks.zip](https://github.com/osmandapp/OsmAnd-iOS/files/11541048/tracks.zip)

### Steps to reproduce

* Import tracks
* Go to Menu – My Places – Tracks – Tap one of the track
* In Context menu tap on Actions - Edit track
* In Edit track tap on Options – Add to a track
* Select second track

### Actual result
* Tracks aren't merged, the selected track length remains the same
* Track is saved dialog doesn't show track name

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/69b08ff2-88c3-4e26-ba91-54153d880a6c"  width="300" height="auto"/>   </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/67b0f326-289b-4cf2-98a0-70ee4c52c38c"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result
Tracks are merged into one like in the Android version

### Your Environment
OsmAnd Version: 4.4.8.11 TestFlight \ OsmAnd 4.4.7 Android
Android/iOS version: iOS 16.0 \ Android 10
Device model: iPhone 12 \ Nokia 5.4

**Comment by Zirochkabila** [comment]
This cannot be reproduced with the latest version of TestFlight

**Comment by zipav** [comment]
OsmAnd TestFlight 4.4.10.18

As before tracks are not added to each other, their length does not change

https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/9351aad8-4a08-414c-b60f-a6372bd44c56

**Comment by zipav** [comment]
OsmAnd TestFlight 4.5.1.8

As before **third-party** tracks are not added to each other, their length does not change.
Tracks created in OsmAnd are merged successfully. 

On Android, merging happens as it should, both with third-party tracks and with tracks created in OsmAnd.
<table style="width:100%">
  <tr>
    <th>OsmAnd tracks - success </th>
    <th>third-party tracks - failure </th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/ba4476b8-c12c-4d9b-912b-c28258763a6d"  width="200" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/7c5e844c-b422-4393-95e7-4b930360c73b"  width="200" height="auto"/></td>
  </tr>
