### ISSUE TITLE
Show track name as it is

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2895]
## Description
Currently iOS version is trimming underscore `_` symbol while displaying track names on UI. 
Original track name `2023-05-03_09-31_Mi.`, iOS UI > `2023-05-03 09-31 Mi.`
* Example track [2023-05-03_09-31_Mi..gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/11541186/2023-05-03_09-31_Mi.gpx.zip)

### ToDo
- [x]  Don't trim track names on UI. Sync code with Android.

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/9f738403-c4de-4c31-a7a3-63b3639780ad"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/763ffcc2-217d-4f1a-bc6e-db8d56c840dd"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2959

**Comment by Zirochkabila** [comment]
Still present

<table style="width:100%">
  <tr>
    <th>OsmAnd~ 4.5.0#283m, Released: 2023-06-23</th>
    <th>4.4.10.8</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/1d6b6488-1b60-4cdd-b5c4-b26b82f5329f"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/4b873661-62dd-4c93-bbf3-c3d4f8609698"  width="530" height="auto"/> </th>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
Check again on the branch master

https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/1dd6f8f3-81eb-4423-ae9c-5e6bf1ebf0ba
