### ISSUE TITLE
Unable to tap on point in Plan a Route if 3D Relief is On

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2900]
## Description
Tested on TestFlight 4.4.8.15

### Step to reproduce
* Enable 3D Relief in OsmAnd Development plugin
* Enable Terrain in Configure Map
* Download HeightMap for viewed area

<table style="width:100%">
  <tr>
    <th>3D Relief – Off</th>
    <th>3D Relief – On</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/131b9f45-8fc8-448a-9fc3-01d4f49453e9"  width="300" height="auto"/>  </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/477d5e3b-cc56-49f8-a181-d191642bf9ad"  width="300" height="auto"/>  </td>
  </tr>
</table>

**Comment by Andrewschenko** [comment]
Looks like it's already fixed.
