### ISSUE TITLE
Don't change zoom level and map center position after tap on Edit track 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2901]
## Description
On iOS opening Edit track, change map zoom level to show the whole track on the screen, it is not helpful when you zoom in to needed part and start editing from it. 

### ToDo
- [x]  Don't change zoom level after opening Edit track.

### How to reproduce
* Find track on the map
* Zoom in to any part of the track
* Tap on track
* In context menu tap on Options – Edit track

#### Actual result
* Map zoom level will be changed to show the whole track on the screen.

#### Expected result
* Map zoom level wan't be changed without user iteration. Android version work as expected.

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c70ec5f7-d812-4b66-ad29-3490a920ed2c"  width="300" height="auto"/>  </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/3c29ea38-20f0-41d2-a8ea-85d8bcf43f82"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2962
