### ISSUE TITLE
Fixed screen rotation while navigating (Android feature parity)

### ISSUE THREAD

**Issue by habitoti** [osmandapp/OsmAnd-iOS#2906]
### 🚀 Feature request

With the new SmartphoneGrip from Bosch, a lot of bicycle users will be forced to using OSMAND in landscape mode while navigating or following a predefined track. Being fixed almost horizontally, the phone's sensors don't detect any specific orientation now. If you quickly checked another app and return to OSMAND, you usually end up again in portrait mode. So you have to unmount the device, lift it up and rotate it to force it to landscape again.

**Solution**

A profile setting should allow for forcing a certain rotation setting while navigating. So I can set it to "Landscape" and have it always rotate into landscape orientation, no matter what the position sensors think (or actually just don't know...).

**Alternatives**

At least for iOS the standard system device orientation lock can't be used, as it forces the device to portrait mode only. You can't lock a phone in landscape (works only for iPads).
I read something about a screen orientation feature for Android, however I couldn't find anything similar for iOS.

**Comment by dmpr0** [comment]
## ToDo
We need to investigate if it possible to add **Screen orientation** option to iOS, similar to [Android](https://docs.osmand.net/docs/user/personal/profiles#general-settings).
* Allow to set Landscape or Portrait orientation for different profiles 
* If Landscape is set for Default profile, OsmAnd should launch in Landscape orientation 

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>General settings</th>
    <th>Screen orientation</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ad37a0d9-45b8-4760-9c8c-887da0b311d8"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/494b4509-d48b-4186-8cc7-f87f0f902080"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>

**Comment by dmpr0** [comment]
Doc:
* Doesn't available on iPad
* Doesn't redraw on the map screen

**Comment by dmpr0** [comment]
Available to test with the latest TestFlight 4.6.1.3, https://testflight.apple.com/join/7poGNCKy

**Comment by shurasmiling** [comment]
https://docs.osmand.net/docs/user/personal/profiles#appearance

**Comment by EugeneZmeuk** [comment]
**16-04-2024 Review**
