### ISSUE TITLE
[OSM Edit] Allow search and set of POI type without setting a POI category

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-ios#291]
Current workflow for creating a new POI
- User has to set a POI category
- User has to set a POI type
If the user doesn't set a POI category he can't define or search for a POI type.

I don't see any use case where setting a category before defining the POI type could be useful. But perhaps it's just me ? On the other hand it adds a extra step for the user who needs to determine what is the category of the POI he wants to map (which can be tricky sometimes). The only use case I see is to shorten the list of POI types, but there is a search feature so that's not really a use case. There is a high chance that, like in iD, users will use the search function to get what they are searching for instead of scrolling the list.

Suggestion: remove the "category" and just keep the "POI type" field.

**Comment by PaulStets** [comment]
@natolh This was added in 2.82. You can now search for a poi type without selecting the category.

**Comment by natolh** [comment]
Nice ! But we still have a category field, what's the use case ? Maybe it can be deleted to simplify the UI ?

**Comment by PaulStets** [comment]
The category field serves mainly for informational purposes (e.g. to display the category of the selected type). Moreover, the field can be used to show only types belonging to a specific category. This can be useful for selecting the most suitable type from the specific category.

**Comment by natolh** [comment]
- For Informational purposes: I'm not really interest in how OSM is ordering all the stuff inside, the only thing I want to be sure is to select the correct feature.
- For selection: I'm not sure it's usefull, when you have access to a search mechanism you don't need to bother about all the access tree down to the thing you're looking for.
Thousands of OSM contributors use iD which does not have a similar mechanism to define features, yet no trouble to edit/add things on OSM. Perhaps you're overthinking the interface. I think OSMAnd will really benefit from simplifying this (and also a lot of other things but that's not the matter). 😊
