### ISSUE TITLE
Line to the next point is attached to the touch finger on the map (Plan a route)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2910]
### Description
When creating a track, the line to the next point is attached to the place where finger touches the map

### Steps to reproduce

- Menu
- Plan a route
- Create new route
- Try to add a second point

### Actual result

https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/236dba59-f9cb-4764-b85a-fcaa366723ad

### Expected result

https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/efff0fee-72cf-493d-97d3-6a5e6d8125d7

### Your Environment
OsmAnd Version: 4.4.8.16
Android/iOS version: iOS 15.7.5
Device model: iPad mini 4

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/1b3a96b7eeeb4e5f99d0a9f1fa4d0504c1b63038
