### ISSUE TITLE
Routing ignores access:conditional restrictions

### ISSUE THREAD

**Issue by WizoneDE** [osmandapp/OsmAnd-iOS#2912]
Example:
https://www.openstreetmap.org/way/1176871058

`access:conditional=no @ (2023 Apr 26-2023 Sep 22)`

With the current map build incl. hourly updates the  app is still planning its route via the closed parts. 

Tested on latest production version and the current beta build

**Comment by WizoneDE** [comment]
![IMG_2678](https://github.com/osmandapp/OsmAnd-iOS/assets/35132439/bc393669-01cc-4a7d-af89-f23db875bc14)
![IMG_2679](https://github.com/osmandapp/OsmAnd-iOS/assets/35132439/eeec90b5-ab6e-48b4-b6a9-ae6d1bf08d1d)
![IMG_2680](https://github.com/osmandapp/OsmAnd-iOS/assets/35132439/ecea3bc3-8653-4f63-9ae6-7c1f90ed7ffa)

**Comment by Dima-1** [comment]
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/31807095/d01657e2-e281-4010-a3cf-1d61ee42ad3f)"  width="300" height="auto"/> </th>
  </tr>
</table>
