### ISSUE TITLE
Fix description "Select track" in Simulate location

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2919]
# Description

- [x] Remove description `route_between_points_add_track_desc` from the track selection view.

### Steps to reproduce
* Go to **Menu** – **Plugins** – **OsmAnd Development**
* Tap on Settings icon in NavBar (top right)
* Tap on **Simulate your position** – **Track**

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/54e61cb3-2f05-4cba-8899-e686ab16e2cf"  width="375" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
To do: 
- Change description for simulation "Select track to simulate location with it."
- Double check that original description is used in original place

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/2946
