### ISSUE TITLE
IOS - Bug Data Formatting instead of 1.35 km (1347 km displayed)

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2920]
# Description

**Camera elevation**
| Zoom level | 9 | 5 |
| -  | - |  -  | 
| iOS | 235 km | 3797 km  | 
| Android  | 280 km |  4236 km |

**Distance from camera to target**
| Zoom level | 9 | 5 |
| -  | - |  -  | 
| iOS | 235 km | 3,8 km  | 
| Android  | 280 km |  4236 km |

<table style="width:100%">
  <tr>
    <th colspan=2>Zoom level: 9</th>
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6356fd1b-3a8b-4623-8e2f-fddc88e55c43"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a89bbd60-8f0a-4599-b649-fb3928ccb007"  width="300" height="auto"/> </td>
  </tr>
  <tr>
    <th colspan=2>Zoom level: 5</th>
  </tr>
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/5382b43e-730c-40e5-a4d4-b794ffe3fc5c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b545a583-ea19-480a-92fa-2355cb990a57"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] **Distance to target** displayed km and same data as a **Camera Elevation** widgets (like in Android)

https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/5cc7a715-a792-422e-b2d7-59bb7763c403

### Description
When working with zoom, there is a data mismatch in the **Distance to target** and **Camera Elevation widgets**. 
Distance to target changes to **meters**, while Camera Elevation still displays **km**

### Steps to reproduce

- **Menu** > **Configure screen** > **Add Distance to target and Camera Elevation widgets**
- **Change zoom level**

### Actual result

https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/a91b4dcd-7092-4961-abc4-378e7ae79c55

### Your Environment
OsmAnd Version: 4.4.10.1
Android/iOS version: iOS 15.7.5
Device model: iPad mini 4

**Comment by vshcherb** [comment]
To do fix formatting " IOS - Bug Data Formatting instead of 1.35 km (1347 km displayed)"

**Comment by Skalii** [comment]
[Fix widget - Distance to target](https://github.com/osmandapp/OsmAnd-iOS/pull/2947)
