### ISSUE TITLE
Custom extensions aren't visible – GPX

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2927]
Tested file – [custom_extenstion.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/11677591/custom_extenstion.gpx.zip)

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<gpx version="1.1" creator="OsmAnd" xmlns="http://www.topografix.com/GPX/1/1" xmlns:osmand="https://osmand.net" xmlns:test="https://test.net" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
    <wpt lat="37.5460870" lon="-77.4532843">
        <time>2023-06-07T12:31:35Z</time>
        <name>Test</name>
        <type>SOTM</type>
        <extensions>
            <osmand:address>Floyd Avenue (The Fan) 907, Richmond</osmand:address>
            <osmand:icon>place_town</osmand:icon>
            <osmand:background>circle</osmand:background>
            <osmand:color>#ff4e4eff</osmand:color>
            <test:country>United States</test:country>
            <test:state>Virginia</test:state>
            <test:telephone>(804) 828-0100</test:telephone>
            <test:postcode>23284</test:postcode>
            <test:start_date>Thursday, June 8, 2023</test:start_date>
        </extensions>
    </wpt>
</gpx>
```

<table style="width:100%">
  <tr>
    <th colspan=2>Imported as Track</th>
  </tr>
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1f7efec6-3e54-41b7-beb3-c4d45e9d624f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d7e0f4d9-dd3d-481a-b05c-69b2872ed58b"  width="300" height="auto"/> </td>
  </tr>
</table>   

<table style="width:100%">
  <tr>
    <th colspan=2>Imported as Favourites</th>
  </tr>
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/74a734f0-f654-476b-8453-7b81608c79c2"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/01c93ed0-eb51-4020-9619-0f915533e3b6"  width="300" height="auto"/> </td>
  </tr>
</table>   

Previous task https://github.com/osmandapp/OsmAnd-Issues/issues/1666

**Comment by Skalii** [comment]
[fix display of custom extensions](https://github.com/osmandapp/OsmAnd-iOS/pull/2976)

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3035

**Comment by dmpr0** [comment]
# Review - 2
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a07a80f1-6ebf-4eaf-998b-ac1ae40e48d3"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ]  Custom extension is missed after waypoints group is copied to favorites. On Android, custom extensions converted to `<osmand:>` extensions.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3055
