### ISSUE TITLE
Unable to change weather forecast temperature format

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2929]
## Description 
It seems that OsmAnd on iOS have two set of Weather settings: 

**First** 
* In **Menu** – **Plugin** – **Weather**
* Applies on widgets in map browser mode

**Second** 
* in **Configure Map** – **Weather** – **Temperature,**
* Applies only on widgets visible on **Weather** screen.

## Expected 
* Weather format settings, can be accesible thru few places (Plugin settings, Configure Map)
* Affect all places in Application.

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e2fc7194-75c3-42ae-ba20-bc1d00691959"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/0cadab14-3c18-45b9-9908-4fb3d1a27c5e"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
All widget numbers / values should be consistent with Weather Plugin Settings.
2 way of changing Settings should be consolidated.
