### ISSUE TITLE
Missing strings for translation

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-ios#293]
iPhone 5S
iOS 12.3
OsmAnd 2.65, 2.7

Here is a list of strings that appears untranslated in the application (french) and that seems to be not accessible to translation on Weblate.
- Map > Details > Depth contours
- Map > Details > Hide house numbers
- Map > Details > Hide map icons
- Map > Details > Hide overground objects
- Map > Details > Hide POI labels
- Map > Details > Hide proposed objects
- Map > Details > Hide undeground objects
- Map > Routes > Horse routes
- Map > Routes > Show MTB routes
- Map > Routes > Whitewater sports
- Map > Public transports > Transports stops
- Map > Contour lines color scheme
- Map > Contour lines density
- Map > Contour lines density > high
- Map > Contour lines density > low
- Map > Contour lines density > medium_w
- Map > Contour lines width
- Map > Contour lines width > medium
- Map > Contour lines width > thin
- Favourite > Trips > (select a trip) > Show on map
- Map & Resources > OsmAnd Live > (select a map) > Downloaded updates size

**Comment by PaulStets** [comment]
Hi, @natolh. I've added the missing strings. You can translate them now. Thank you for reporting this.

**Comment by natolh** [comment]
Thanks, I'll try to do that.
