### ISSUE TITLE
Zooming/unzooming provoke inconsistent display of beginning/end of tracks

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#2932]
In osmand 4.4.5, the start and stop of tracks appears at a certain level of speed, but dissipera at another lever of zoom. That provoke inconsistent display if we have multiple tracks displayed on a map
to reproduce : 
Put traces on différents parts of world map
Zoom on some of them until you see they’re beginning and end icons
Unzoom
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/4d88e6b2-5595-407f-8eb1-eb1159d67ffe"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by zipav** [comment]
### Steps to reproduce:
Put tracks on different parts of world overview map
Zoom until 200 km scale
Unzoom until 500-2000 km scale

TestFlight 4.4.10.2

https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/b0e340ab-1e92-46e7-aa88-d60763ef5e5e

**Comment by vshcherb** [comment]
That's ok we try to reduce icons visible

**Comment by Zirochkabila** [comment]
@vshcherb Why then do they continue to appear on some tracks and disappear on others?

**Comment by vshcherb** [comment]
specifics are not clear to me, you can ask devs how it's implemented. I don't see an issue here to fix
