### ISSUE TITLE
Unable to update maps due to wrong free space calculation

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2934]
# Description 

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b0b51748-2152-4951-b3e1-1d3546e0dc91"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7448fc32-2499-4090-b0fa-81b33de0b5af"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
To do Calculate free space necesary for maximum 1 file unzip extra space.

**Comment by Skalii** [comment]
[fix free space check for map update](https://github.com/osmandapp/OsmAnd-iOS/pull/2967)
