### ISSUE TITLE
voice navigation repeats the destination:ref tag twice when entering an onramp

### ISSUE THREAD

**Issue by tensleepslav25** [osmandapp/OsmAnd-iOS#2937]
Using version 4.4.9 on an iPhone 13 Pro (iOS 15.4.1) with a custom driving profile

Any time I am about to turn onto an onramp (slip road for those outside the US), the TTS voice will repeat the destination:ref tag twice followed by the destination tag once. This sounds especially clunky when there are multiple destination:ref values.

To reproduce, create a route from 42.26615,-71.21468 to 42.26076,-71.20988 using the "English" TTS voice.

**Comment by zipav** [comment]
TestFlight 4.4.10.5

### Steps to reproduce:
- Create a route
- Navigation
- Start: `42.26615,-71.21468`
- Finish:` 42.26076,-71.20988`
- Enable English voice prompts
- Run Navigation Simulation in Realistic Mode 



https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/35f9ed16-d381-4f84-b5e8-39ada279e983

**Comment by DmitryAlexei** [comment]
Testflight 4.5.1.8
Cannot reproduce with fresh United States Indiana map and provided coordinates:
- Start: 42.26615,-71.21468
- Finish: 42.26076,-71.20988


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/9f03971b-d77c-43f8-becb-1388769c2761"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/a7088b66-1fa0-4858-ab9a-a3039899782f"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by tensleepslav25** [comment]
@DmitryAlexei I think you may have entered the destination coordinates incorrectly. The correct route should take you onto the motorway link leading to I 95 South where the destination:ref tags are

**Comment by DmitryAlexei** [comment]
@tensleepslav25 thanks for noticing

Start and end points are entered manually, so that the destination:ref tag from  https://www.openstreetmap.org/way/175115136 is sounded (enable sound in video)

Actual result:
- tag destination:ref= I 95 South;MA 128 South  **pronounced twice**

https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/65a144a0-46d4-4d2a-b2ed-a21eb312a126

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#881m, released: 2023-10-17


https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/bf77537d-e412-4d8b-a13a-c3edba24aac6
