### ISSUE TITLE
Information about house numbers on Solomianska Street cannot be opened

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2939]
### Description
After displaying the results in the search, it is not possible to open the information about the house numbers of Solomianska Street
[OSM](https://www.openstreetmap.org/relation/1415920#map=15/50.4256/30.4858) 

### Steps to reproduce

- Search
- Cоломʼянська вулиця
- Select first result

### Actual result

<table style="width:100%">
  <tr>
    <th>4.4.10.4</th>
    <th>OsmAnd~ 4.5.0#209m, Released: 2023-06-14</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/5d1d9352-64c1-464a-817c-ed02413526e5"  width="300" height="auto"/></td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/89b82d56-c161-4b40-a8f4-0c8acae0e429"  width="300" height="auto"/> </td>
  </tr>
</table> 

### Expected result

https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/b82e6893-e99c-4b1a-ae0a-b3237ebf9c4d

**Comment by vshcherb** [comment]
Investigation on data level is needed to identify the cause.

**Comment by xmd5a2** [comment]
Address data:
```
			'Солом'янська вулиця (Солом’янка)' [562], 81 building(s), 11 intersections(s)
				Buildings:
				1/2
				2-А postcode:03110
				3
				3-А
				3-Б
				3-Б
				4/2
				4/2
				5
				6-В
				7
				7
				7-А
				8
				10 postcode:03110
				11
				11
				11
				11
				11
				11-А
				11а
				13
				14 postcode:03110
				14 postcode:03110
				15-А
				15-А
				16 postcode:03110
				16
				16 postcode:03110
				16-А postcode:03110
				16-Б postcode:03110
				16-Б postcode:03110
				17 postcode:03110
				17 postcode:03110
				17 postcode:03110
				17
				17
				17
				18-А postcode:03031
				19
				19-А
				20 postcode:03110
				20-А postcode:03110
				20-Б postcode:03110
				20-В
				20-В
				21
				21-Ж
				22 postcode:03110
				23
				23-А postcode:03110
				23-А postcode:03110
				24
				24
				24
				27
				28
				28/30
				29
				30
				31
				32
				33
				33 postcode:03141
				33
				33 postcode:03141
				33
				33-А
				34
				34-А
				35
				35-А
				36
				37 postcode:03141
				38
				39
				40-А postcode:03069
				40/4
				41 к1
				41 к2
```
Clicked on building 20 ("Where am I?" in Map Creator):
![Screenshot_2023-06-21_09-34-55](https://github.com/osmandapp/OsmAnd-iOS/assets/5829014/d5b2bd15-d2e9-4c9e-828f-eefe12b15b2b)
Clicked on building 18-А:
![изображение](https://github.com/osmandapp/OsmAnd-iOS/assets/5829014/b1d9f76f-fdad-40b5-b0c5-31beadd6fa9f)

OSM data looks like correct. May be this is related to apostrophe type?

**Comment by DmitryAlexei** [comment]
android done
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/635cdab8-1949-4489-ab69-3f84fc97b4b2"  width="300" height="auto"/> </th>
  </tr>
</table>
