### ISSUE TITLE
Truncated back button

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-ios#294]
iPhone 5S
iOS 12.3
OsmAnd 2.7, language: french

Back buttons are cropped and the label is truncated as you can see on screenshots attached below. Truncation is something understandable when there is a lack of screen space like on screenshot n°2. But on n°1 there is plenty of space to get the back button label displayed correctly.

![IMG_1821](https://user-images.githubusercontent.com/30546417/57567749-67e40f00-73cd-11e9-9179-4831e78fdd45.png)
![IMG_1823](https://user-images.githubusercontent.com/30546417/57567750-67e40f00-73cd-11e9-8730-4a1c03a1b20a.png)

This behaviour seems to happen in every OsmAnd menus but I can make an exhaustive list of cases if you want.

**Comment by PaulStets** [comment]
Fixed via 9666af1930737b2d40fc176a6fa4e6ca8d530dc6
