### ISSUE TITLE
Description and On/Off button is missing for Custom Plugins

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#2949]
## Description
Custom plugin settings screen is empty, description is not visible and as On/Off button.

### How to reproduce
* Import plugin https://t.me/c/1265587788/12352
* Open **Menu** > **Plugins** > **Plugin** > **Settings**

### Actual result
* Screen is empty

### Expected result
* On/Off button and description should be visible

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/77a59867-80c0-44c1-b880-00901dba08fb"  width="300" height="auto"/>    </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/abff283a-8c66-42a4-98fb-18d2dd819e24"  width="300" height="auto"/> </td>

  </tr>
</table>

**Comment by Skalii** [comment]
[fix plugin details screen](https://github.com/osmandapp/OsmAnd-iOS/pull/2964)
