### ISSUE TITLE
4.4.10.7 crashes

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2952]
### Description
Systematic crashes during use

![photo_2023-06-20 16 53 12](https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/ceb40f2d-1cf3-49e0-b656-e119786ca4c1)

### Steps to reproduce

- Start the navigation simulation, download the map (everyday actions)
- Close OsmAnd and use another application

**Comment by Skalii** [comment]
[fix crash mappers](https://github.com/osmandapp/OsmAnd-iOS/pull/2963)
