### ISSUE TITLE
Data in the Lanes widget and the Road name have moved apart

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#2953]
### Description
During the navigation simulation, sometimes the route is recalculated (although there is no reason for this), and after the recalculation, the data in the widget is divergent
Probably related to https://github.com/osmandapp/OsmAnd/issues/17238#issuecomment-1598907765

### Steps to reproduce
Simulate navigation (realistic) from `53.83908, 27.53308` to `53.83607, 27.52985`

### Actual result
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/07ab04b8-cad2-4fd7-b722-c1bf4cbe8147"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/af0d91f7-4b69-4eda-b49c-a8c4fe4984a4"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/104760013/6f16990b-ffd0-487e-ba21-87786fb3a77c"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.4.10.7

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/acf5b3e8-702e-421d-a4d0-5a9dfd744284"  width="300" height="auto"/> </td>
  </tr>
</table>
