### ISSUE TITLE
Add "Read article" button to context menu of Wikipedia POI

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#2954]
In the iOS version of the OsmAnd app, **there is no "Read Article" button** in the context menu of the Wikipedia POI, unlike the Android version.

As of now, compared to Android you need to do two additional actions to open an article:
- tap *Details* (or just pull the context menu up) > Tap on text of the extract of an article.

<table style="width:100%">
  <tr>
    <th>iOS 1</th>
    <th>iOS 2</th>
    <th>Android 1</th>
    <th>Android 2</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/88b76286-4b0b-4834-bc87-97acc30ada402"  width="188" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/d5152ffb-b444-4117-96a3-c5beb30ba3a0"  width="188" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/c2382f5d-cc0c-4860-8cdb-0933f19d9cb3"  width="188" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/13fbe66b-c7a1-4ed7-b512-3a1e221339ec"  width="188" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
## ToDo
* Add Read article button for Wikipedia points context menu
* It should look similar to download map buttons in context menu
