### ISSUE TITLE
Address search lag while loading street list

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2984]
## Description
Loading list of streets for Berlin in search address is lagging.

## How to reproduce
* Open **Menu** – **Search** – **Address** 
* **Select city**, search for Berlin

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/deff1311-99f6-4829-9c47-888601ecf29f"  width="300" height="auto"/>  </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a0e23942-b41a-4586-a893-0898129f5ef0"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Combined with https://github.com/osmandapp/OsmAnd-iOS/issues/2986
