### ISSUE TITLE
Loading list of streets for Berlin in search address is lagging

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#2986]
## Description
- Loading list of streets for Berlin in search address is lagging.
- Loading list of streets for Berlin in search address is lagging.
## How to reproduce
* Open **Menu** – **Search** – **Address** 
* **Select city**, search for Berlin
* Select Berlin, wait until list of streets are loading.

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/71119286-526a-4550-bcdc-044196b420ba"  width="300" height="auto"/>  </td>
  </tr>
</table>   

## How to reproduce
* Open **Menu** – **Search** – **Address** 
* **Select city**, search for Berlin

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/deff1311-99f6-4829-9c47-888601ecf29f"  width="300" height="auto"/>  </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a0e23942-b41a-4586-a893-0898129f5ef0"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by zipav** [comment]
TestFlight 4.4.10.12

On Android, there is no empty line in the results and no delay in the search, on iOS there is both a delay in the results and an empty line in the search results.

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/fedc8993-4e9f-481e-ab30-7047f0c9249c"  width="300" height="auto"/>  </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/40d9bb56-433e-4857-819a-8940fdfd4e69"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by ivanPyrohivskyi** [comment]
Need to check empty street in the search index

**Comment by xmd5a2** [comment]
Address data for Berlin:
```
3 Address data Germany_berlin_europe - 39095845 bytes
	3.1 Address part size=12254987 bytes
	3.3 Address part size=11476734 bytes
	3.2 Address part size=13825613 bytes
	Cities/Towns section, 4 group(s):
		'Berlin' [240109189], 14055 street(s) size 12064300 bytes:
			'<Berlin>' [27752], 5 building(s), 0 intersections(s)
				Buildings:
				Building D postcode:12529
				Building E postcode:12529
				V - Zentrale Abstrichstelle postcode:14467
				X postcode:14467
				16-24 (all)  postcode:16548
                                ...
```
https://www.openstreetmap.org/way/241290828

**Comment by xmd5a2** [comment]
[Building C](https://www.openstreetmap.org/way/82281160) is in [Altglienicke](https://www.openstreetmap.org/node/161618720#map=16/52.4113/13.5489) suburb while [Building D](https://www.openstreetmap.org/way/241290828) is not (see previous comment)
```
			<Berlin> (Altglienicke) [29000], 6 building(s), 0 intersections(s)
				Buildings:
				Building A postcode:12526
				Building B postcode:12526
				Building C postcode:12526
				32 postcode:12524
				42 postcode:12524
				77A-D postcode:12526
```
Too little address data? Not clear what to do with such addresses.

**Comment by vshcherb** [comment]
Probably here with debug or logs is much simpler to understand, Android problem is not reproduced. 
By section data no empty street I see. Don't confuse buildings attached to city with empty streets

**Comment by Dima-1** [comment]
Empty string is absent now
<table style="width:100%">
  <tr>
    <th>iOS</th>

  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/31807095/204fc2c4-a5ca-4b92-a316-6c73727b376e"  width="300" height="auto"/>  </td>

  </tr>
</table>

**Comment by Dima-1** [comment]
While testing this issue, I found a slight difference in the sorting of the results.
<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/31807095/83e59a67-c437-4ad2-ba2f-0e359558c899"  width="300" height="auto"/>  </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/31807095/53bb9dfd-ed90-42c0-8cb3-9b89bd6851ac"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Actually all searches are significantly slow and crash (OOM ?) - 
- Click on any POI category (Cafe) - results on top devices are very slow comparing to Android
- Click on any City 
- Sometimes leads crash

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/5d1ec52cb67e8230f6572baf99aa9bfa4be24e9c
