### ISSUE TITLE
Build Error: Prepare.sh times out with builder.osmand.net to download World_basemap_mini_2.obf

### ISSUE THREAD

**Issue by OWL4C** [osmandapp/OsmAnd-iOS#2993]
Following the instructions from https://osmand.net/docs/technical/build-osmand/how-to-compile-the-ios-version/ errors out because it cannot reach the server to download the World_Basemap from within the `download-shipped-resources.sh`

**Comment by vshcherb** [comment]
I think it was fixed already https://github.com/osmandapp/OsmAnd-iOS/commit/19ff3230ad7bba9d3ee0c9c02afee4a53d705867
