### ISSUE TITLE
Destination > Select on map doesn't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3008]
# Description
Trying to select destination or start position on the map is impossible.

## How to reproduce
* Open **Menu** – **Navigation** – **Select destination** – **Select on map**
* New screen with map will be opened

## Actual result
<table style="width:100%">
  <tr>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/431c4790-cadc-400d-83c3-b410b8223fb1"  width="300" height="auto"/>  </td>
  </tr>
</table>   

* Taping on map doesn't do anything

## Expected result
* Taping on map should add this point as destination or start position

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/36a372063369ea2bd92f07589d6efc94bf51b154
