### ISSUE TITLE
No such module Charts.Swift in GpxUIHelper.swift

### ISSUE THREAD

**Issue by OWL4C** [osmandapp/OsmAnd-iOS#3014]
Followed https://www.osmand.net/docs/technical/build-osmand/how-to-compile-the-ios-version and re-downloaded ios today, all the other gits a week ago.
After prepare.sh i open the xcodeproject, switch to OSMAnd Maps and compile to iPhone 14 Simulator. It starts building and then fails at Charts.Swift. Charts without swift seems to get found, but .swift errors out. Could not find any relevant (or working) fix

**Comment by OWL4C** [comment]
<img width="1127" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/124401812/a4637802-3249-449c-a651-78f9a143b0d1">
XCode is 14.2
I repulled everything, ran prepare again, built again and same error.

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/ee34fa1376efc6730ac6d1dd566b812bcbabda85

**Comment by tigrim** [comment]
You need to open the OsmAnd.xcworkspace file, it looks like you have opened OsmAnd.xcodeproj
