### ISSUE TITLE
Topo and Offroad map styles are lacking option to hide house numbers

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#3020]
Please consider to add an option to hide house numbers for the Topo map style (which is brilliant).

**Comment by MagielBruntink** [comment]
Also for the Offroad map type.

**Comment by DmitryAlexei** [comment]
Tested in OsmAnd~ 4.6.0#634m, released: 2023-08-18
- Topo and Offroad map styles have an option *Hide house numbers* in Configure map > Hide menu
when this option is toggled, house numbers are not shown as expected
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/a23fb160-f14f-45df-abab-c5b45196d222"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
The most recent release of TestFlight now includes a feature that allows to hide the house numbers.
OsmAnd 4.5.1.6

<table style="width:100%">
  </tr>
  <tr>
    <th>Topo</th>
    <th>Offroad</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/4b58c556-eeb7-4f8f-8ed0-06f03a4063f7"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/b56e2f8b-956d-486d-9e54-71d04d5d9d41"  width="300" height="auto"/>   </td>
  </tr>
</table>
