### ISSUE TITLE
Slash in inscription tags are treated as link

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3021]
## ToDo
[`inscription`](https://wiki.openstreetmap.org/wiki/Key:inscription) and other tags needs to be checked if they start with  `http://` or `https://`.

Place to check – https://www.openstreetmap.org/node/5504782341
> Android task https://github.com/osmandapp/OsmAnd/issues/17466

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/68d25249-514b-4d6c-8ff2-ccd8dbfd5408"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7c441877-6fdb-420d-bc4c-f1b94eb16c34"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3049
