### ISSUE TITLE
Topo and Offroad map styles lack road numbers

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#3025]
Please consider adding road number display to these awesome map styles.

**Comment by yuriiurshuliak** [comment]
In the new update of TestFlight, road numbers are now shown for Topo and Offroad styles.
OsmAnd 4.5.1.6

<table style="width:100%">
  </tr>
  <tr>
    <th>OsmAnd</th>
    <th>Topo</th>
    <th>Offroad</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/88a44bed-a391-4944-b177-e35d06e599a8"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/8db21d06-e020-4f5c-aaae-c324e410f0e7"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/86cce9a4-d4f6-48df-87e8-d5916e7461ed"  width="300" height="auto"/> </th>
  </tr>
</table>
