### ISSUE TITLE
Development setup: Multiple Errors around OAuth - WebAuthenticationSession in scope

### ISSUE THREAD

**Issue by OWL4C** [osmandapp/OsmAnd-iOS#3027]
<img width="258" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/124401812/49e1a2c1-265c-44b3-9e09-ed5261814dc7">
Pulled all gits recently, ran prepare.sh and opened the xcode workspace

**Comment by vshcherb** [comment]
Development setup: Multiple Errors around OAuth - Cannot find type WebAuthenticationSession in scope, EnvironementValues has no member webAuthenticationSession

**Comment by vshcherb** [comment]
OAuth requires newest version of xcode which might not be present on old macos
