### ISSUE TITLE
Crash when adding point to existing route / track

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#3032]
In 4.4.9 if new route points are added to this track and “Save changes” or “Done” is pressed, app crashes. I have tried various alternatives: adding new point between existing ones, all crash.

[Rondje Radkow.zip](https://github.com/osmandapp/OsmAnd-iOS/files/12196115/Rondje.Radkow.zip)

(I have some other perhaps related crash observations with creating multiple new tracks in the same session. Sometimes new tracks don’t appear until the app is restarted. And editing one track actually changes another one. Hard to say exactly.)

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/commit/f66756fe8efebb9d40c650700974c423085c7332
https://github.com/osmandapp/OsmAnd-core-legacy/commit/121e28db6253033de226ea2ec6884bd630ecefb2
https://github.com/osmandapp/OsmAnd-iOS/commit/b4d2489faa492426542fca496e517339abc7210f
https://github.com/osmandapp/OsmAnd-iOS/commit/374077afb6a3eaa143113fc807acece8880254f7

**Comment by vshcherb** [comment]
I don't think they went to 4.5 branch so they can't be tested with 4.5 version

**Comment by alex-osm** [comment]
All changes are in two branches already

**Comment by zipav** [comment]
OsmAns TestFlight 4.5.1.3

After adding points and clicking Done, the app does not crash, it displays as it should, with changes.

https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/4da99a18-c34d-46d4-bd5b-c9295c29cee3
