### ISSUE TITLE
Navigation uses roads that were removed by live map update

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#3033]
Just experienced this hard to reproduce issue. I removed a road that no longer existed in reality from OSM using GoMap (another app). After some minutes the edit was downloaded as a live update on OsmAnd. The road was indeed gone on the map in OsmAnd. But when creating a new navigation, it still used the road which was now gone on the map! 

Is the navigation graph properly updated after a live map update?

**Comment by DmitryAlexei** [comment]
Have you enabled *OsmAnd live data* in Navigation settings?
For more information see https://osmand.net/docs/user/navigation/guidance/navigation-settings#development-settings

**Comment by MagielBruntink** [comment]
Yes, indeed. The live update happened and the road I removed from OSM seemed also gone from the OsmAnd map. But then navigation in OsmAnd still used the road that was no longer shown on the map. The navigation line followed exactly where the road used to be.

**Comment by MagielBruntink** [comment]
I'm not sure I have options to enable live data in the Navigation setting. This is on iOS with the Pro subscription.

**Comment by DmitryAlexei** [comment]
Oh, I see. 
As of now, live updates for routing works in a test mode for Android (when development plugin is enabled). 
In general, it is necessary to wait for the generation of new maps (at the beginning of the month) for updates to take effect.
