### ISSUE TITLE
Radius ruler and weather indicator follow finger position instead of map center

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#3034]
Not sure if intended functionality, but it's somewhat confusing. If dragging the map, widgets like the radius ruler and weather indicators reflect values for the finger touch location on the map. Expected is that the widgets follow the map center (crosshair).

**Comment by DmitryAlexei** [comment]
Please add short video or screenshots of your issue.
Updating to the latest version of the app may help.

**Comment by MagielBruntink** [comment]
https://github.com/osmandapp/OsmAnd-iOS/assets/3635696/1524bf05-9838-48da-ada4-cd1e386b4768

#In the beginning of the video, the map center (crosshair) is 278 m away from me. Look at the radius ruler widget in the top right. Then I start finger dragging the map and the center moves very little away. But the radius ruler indicates 433 meter away during the dragging. It is using the location where I put my finger, instead of the map center.

**Comment by zipav** [comment]
OsmAnd Nightly 4.6.0#525m, released: 2023-08-01
OsmAnd TestFlight 4.4.10.17

### Steps to reproduce:
- Menu
- Configure screen
- Right panel
- Enable Radius ruler widget 
- Hide Distance circles
- Menu
- Settings
- Choose profile
- General settings
- Display position: Center
- Place a finger above the ruler radius marker
- Smoothly drag the map with the finger without taking it off the screen

https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/bf4d5378-3d82-4c7f-a9e5-b3e63809cd6c

https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/1e0fcfe8-5092-448a-b5dc-2830295b51da
