### ISSUE TITLE
Crash when clicking Import tracks while tracks are selected

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#3038]
In the My Places -> Tracks menu, select a track and then click import at the bottom -> crash.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/3635696/7d82323f-5d82-415d-a14e-758ddc589bd5"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
Upon accessing OsmAnd, go to Menu, then navigate to My Places and choose Tracks. Next, click on the three dots located in the upper right corner and scroll down to select "import tracks." As a result of this action, the application experiences a crash.

OsmAnd 4.4.10.7

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/8db418b2-fb6f-4950-bae0-6f6259423998

**Comment by dmpr0** [comment]
# ToDo
- [ ]  Hide **Actions** group in Edit mode

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3084

**Comment by EugeneZmeuk** [comment]
**12-04-2024**
- preparing [_Tracks_ article](https://osmand.net/docs/user/personal/tracks)
