### ISSUE TITLE
Does the iOS app have a crash log?

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#3042]
Yesterday during normal (track following) navigation I experienced frequent crashes. It's very hard to pin down what caused them however. I suspect it's related to either the tracks displayed on the map, or their number of points. Is there a crash log stored somewhere?

**Comment by DmitryAlexei** [comment]
iOS has some kind of crash logs, see 
https://osmand.net/docs/user/troubleshooting/crash-logs#send-logs-from-ios-devices
