### ISSUE TITLE
Crashes with several recorded tracks on map

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#3043]
With attached recorded tracks shown on map I am experiencing frequent crashes. It happens when just panning and zooming the map around where the tracks are shown.

There are no logs generated.

The crashes don’t happen without the tracks shown.

Profile: walking, with hiking trails shown. Also hill shade and contour lines.
Map type: touring.

[Several recorded tracks.zip](https://github.com/osmandapp/OsmAnd-iOS/files/12249434/Several.recorded.tracks.zip)

**Comment by yuriiurshuliak** [comment]
To replicate this issue, I followed these steps: I brought in the three designated tracks that were provided by the user and showcased them on the map. Following that, I obtained the map for the northeastern part of Czechia along with the Hillshade and Contour Lines. Next, I adjusted the settings to Pedestrian mode and, in the Map Configuration, activated Hiking routes while also altering the Map style to Touring view. After incorporating all the requested visual preferences, I attempted various actions like zooming, tilting, and rotating the map from different perspectives, and observed consistent functionality.

iOS 16.4.1
OsmAnd 4.4.10.7

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/e39f0007-2f02-48f7-a891-a9a7e88438ed

**Comment by MagielBruntink** [comment]
Thanks for replicating. To be sure, do you mean you also observe the crashes?

**Comment by MagielBruntink** [comment]
Thanks for replicating. Here is my screen recording of a crash.

https://share.icloud.com/photos/061_gMj4XqxcBKSKlWR6-6GhQ

App version 4.4.9
iOS 16.5.1

**Comment by yuriiurshuliak** [comment]
We made another attempt to recreate the bug, but regrettably, we couldn't replicate the issue demonstrated in your video. Could you please consider updating the maps for the location where you established the routes and linking the tracks to the roads as described here: https://osmand.net/docs/user/plan-route/create-route#attach-to-the-roads

**Comment by MagielBruntink** [comment]
For all three tracks I attached to the roads with the Walking profile. No crashes occurred. What do you want me to do? Save the new tracks?

**Comment by vshcherb** [comment]
We suspect it's related to rendering of track arrows, this bug is fixed and new version should be tested. Let's wait for next build
