### ISSUE TITLE
Allow to access OsmAnd Cloud settings while checking status

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3046]
# Description
Settings button is blocked while status of changes is checked. it's a obstacle while testing.

## ToDo
- [x]  Don't block Settings button

<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/5544bd85-d14c-491b-93e8-d6a27211c4fa"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3074

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3078
