### ISSUE TITLE
Configure Screen NavBar RTL issue

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3047]
# Description
App Profile icon should be on the left side if app language is set to RTL

## ToDo
- [x]  Fix application profile icon position

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td width="300" height="auto"><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4bcd27f2-ea09-4c33-bd92-1ba937267978"  /> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d4ae4c47-a01a-4f97-baad-331be83c0ac7"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b29b3171-f7eb-4888-9f0e-40e6a8c6fb1c"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3068
