### ISSUE TITLE
Don't update all list after resolving one conflict

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3048]
## Description
When user resolve conflicts in OsmAnd Cloud, all list is updates after each change and scroll position is reseted to the top.

## ToDo
- [x] Don't update all list after resolving one conflict
- [x] Remember scroll position after resolving conflict

## How to reproduce
* Open **Menu** – **Settings** – **OsmAnd Cloud** – **Conflicts**
* Tap on last item in the list, choose any action
* Whole list will be updated 

### Expected result
* After choosing the action, upload/download process should be indicated on one list item
* After upload/download process is done, this one item should be removed from the list
* OsmAnd Cloud can check status an if for some reason there is changes wither other items, only this items should be removed from the list

### Actual result 
* Whole list is updates
* The list returns to the beginning

- - - - 
Android task https://github.com/osmandapp/OsmAnd/issues/16795

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3077

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3083

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/55d973e8-1f73-4ac2-9eca-a875c3efb3ba"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c522037e-06e3-464c-9c7e-60743d1dd744"  width="300" height="auto"/> </td>
  </tr>
</table>   
After resolving few conflicts rest of items are disappear and main screen show error message.

```
2023-09-08 15:29:50.966 OsmAnd Maps[20751:24390656] downloadFileList END (518.674850 ms) 0 Total files: 174 Total zip size: 12,6 МБ Total file versions: 424
2023-09-08 15:29:50.966 OsmAnd Maps[20751:24390636] collectRemoteItems END (519.124985 ms) 
2023-09-08 15:29:50.967 OsmAnd Maps[20751:24390636] Failed to collect items for backup: Error downloading items info
```

**Comment by vshcherb** [comment]
Separate testing for ioS cloud + crashes needed, not related to this issue
