### ISSUE TITLE
Make all links tappable in POI details

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3053]
# Description
Instagram and Facebook links doesn't work in POI details.
* Example POI https://www.openstreetmap.org/node/2620108524

## 
- [ ]  All links should be tapable 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b676374a-14e4-45d8-8cf4-585511a3309e"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Probably this should be fixed first https://github.com/osmandapp/OsmAnd/issues/17811

**Comment by vshcherb** [comment]
Related https://github.com/osmandapp/OsmAnd-iOS/issues/3728 ?

**Comment by DmitryAlexei** [comment]
TestFlight 4.8.0.3
Now Facebook and Instagram links are tappable in POI details both in iOS and MacBook versions of the app

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/bce745d9-f54c-49d7-b430-e3741afefa51"  width="300" height="auto"/> </td>
  </tr>
</table>
