### ISSUE TITLE
Make it possible to open hiking link’s website 

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#3065]
Hi, everything is on the title. In OsmAnd 4.4.5 I can’t open links from hiking itinerary details 
![IMG_8743](https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/e40cd282-32af-4759-b8b3-0b4617b0aefa)

**Comment by alex-osm** [comment]
Should be fixed already - https://github.com/osmandapp/OsmAnd-iOS/issues/2944
