### ISSUE TITLE
Map jumping when trying "Change object position" to waypoint

### ISSUE THREAD

**Issue by zipav** [osmandapp/OsmAnd-iOS#3071]
## Description
Our user claims when trying to Change object position, map is jumping and position of waypoint also
### How to reproduce
* Create a waypoint – Tap on it – **Actions**
* Select **Change object's position**
* Try to move the map as in the direction
* Check the result

### Actual result
Map and waypoint on it jumping when you move the map
### Expected result
Smooth movement of the waypoint

**Environment**
OsmAnd Version: OsmAnd TestFlight 4.5.1.3
iOS version: iOS 16.0
Device model: iPhone 12

https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/973641c7-93d8-42f9-a78a-85f0161e5f47

**Comment by vshcherb** [comment]
More important that object is not center

**Comment by zipav** [comment]
OsmAnd TestFlight 4.5.1.7

Moving the waypoint is now smoother, the waypoint moves to the position marked by tapping the screen.

https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/6125ad1b-7539-4800-8d30-4691b4b41f59
