### ISSUE TITLE
Quick action button in unavailable if 3D Mode button is On

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3075]
## Description
Quick action button is don't visible on the map screen if 3D Mode button in visible.

### How to reproduce
* Open **Menu** – **Configure Screen** – **3D Mode** – set to **Visible**
* Go back to map screen, 3D mode button is visible
* Get back to **Configure Screen** – **Quick action** – set to enabled
* Get back to Map screen, **Quick action** button is don't visible

### Actual result
* Quick action button don't visible if 3D Mode button was enabled first
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ba8cda7b-8304-475f-b84b-cb4b86833876"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b5a7f2b8-6cf3-49ff-a034-4c8d62cfcf6b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d7e1d38d-a304-46b1-9498-7eb5b6866c4e"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result
* Both **3D Mode** and **Quick action** buttons should be available.

**Environment**
OsmAnd Version: `4.5.1.13 (TestFlight)`
iOS version: `16.6`
Device model: `iPhone XS Max`

**Comment by Skalii** [comment]
[fix visibility of quick action button r4.5](https://github.com/osmandapp/OsmAnd-iOS/pull/3122)

**Comment by dmpr0** [comment]
# Review - 1

<details>
    <summary>Screenshot</summary>

    <p>Detailed content goes here …</p>

</details>  

<table style="width:100%">
  <tr>
    <th>Before Restart</th>
    <th>After Restart</th>
    <th>After Moving</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/efe3c03f-9ca6-4cca-baf1-0477d4da4d7f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/44128f59-5329-4dab-88e6-6c59d67cd909"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d272896a-82c4-46f7-acd9-f4c7f6b4b40e"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ]  Button position is changed to default, get back to user setted position only after taping.

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/c93150f6998fc3a6f881cca99504e7180121a386
