### ISSUE TITLE
OsmAnd Cloud Main screen RTL issues

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3081]
## Description 
<table style="width:100%">
  <tr>
    <th>OsmAnd Cloud</th>
    <th>Correct example</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/03dd09fa-322b-43b6-b3db-654694f7f290"  width="200" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/38303346-4540-46f4-931d-4c1ec19f983d"  width="200" height="auto"/> </td>
  </tr>
</table>   

- [x]  Use native NavBar
- [x] Change direction on chevron in Cloud Status tabelcell

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3082

**Comment by dmpr0** [comment]
# Review – 1

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e7ce9c45-f962-4ea4-9b62-0c9ed1581002"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ]  Change direction on chevron in Cloud Status tabelcell

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3086

**Comment by dmpr0** [comment]
# Review 2

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e567addb-8aae-47e7-9694-b9eb10182ae9"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ]  Use native back action

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3103
