### ISSUE TITLE
Map animations doesn't work on devices with high screen refresh rate

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3089]
## Description
Map animation doesn't work on new devices with devices with high screen refresh rate.

<table style="width:100%">
  <tr>
    <th>iPhone 14 Pro</th>
    <th>iPhone XS Max</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/836ad8a6-1b0f-4140-8c7e-b461fa0f391e"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4fa8ffab-d47f-4772-b736-4d724e4dddce"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review
- [ ]  Don't skip animation

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/52633d50bc838268820a7c64af05c9a7562647e7
