### ISSUE TITLE
Redesign Upload POI / Note / Open OSM Note UI

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3095]
# Description
We need to redesign Upload POI / Note UI because old UI use login / password as one available method of authorisation. 
Mostly all UI changes are identical to new Upload GPX dialog.

## Upload POI, [Figma](https://www.figma.com/file/tFOVdxhVgFAPI3D194lusr/OpenStreetMap?type=design&node-id=802%3A14320&mode=dev) 
<table style="width:100%">
  <tr>
    <th>Current</th>
    <th>Upload POI</th>
    <th>Login to OpenStreetMap </th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b2b94ba0-cb61-4bf6-8348-b23ce900fefc"  width="250" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/efbcbb00-9586-43c2-8e8a-5e00452876bc"  width="250" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/214b43a9-5a25-4f69-a968-100c6c164353"  width="250" height="auto"/> </td>
  </tr>
</table>   

- [x]  Show **Upload POI** view after tap on Upload button
- [x]  Show login screen if user don't logged in to OpenStreetMap

## Open OSM Note
<table style="width:100%">
  <tr>
    <th>Current</th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/11950494-9888-4b89-9db4-58f154458235"  width="250" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/9096efe4-a959-4cec-aaa7-a9057f395619"  width="250" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/83512c40-1ce3-430d-8eb3-1a4e5280cf76"  width="250" height="auto"/> </td>
  </tr>
</table>   

## Upload OSM Note
<table style="width:100%">
  <tr>
    <th>Without login</th>
    <th>Upload anonymously</th>
    <th>Using user login</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/70337fe5-2b81-4a22-a049-220d824e7973"  width="250" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/842c79f9-3982-42ff-adfa-9b17338200d1"  width="250" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d7aa3390-b7e0-439a-a5c2-3a62f39a4337"  width="250" height="auto"/> </td>
  </tr>
</table>   

- [x]  Show Upload OSM Note view after tap on Upload button, login doesn't required

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3137

**Comment by dmpr0** [comment]
# Review

**Open OSM Note**

 <details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Current implementation</th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d1a61b56-5e15-47c8-941d-458de340a263"  width="300" height="auto"/> </td>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [ ]  Open with Keyboard

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3198

**Comment by dmpr0** [comment]
# Review - 2

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d8df7f40-87d9-42d5-ac10-3524ab8d9266"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d8837f83-d3b7-41d0-aa60-8e8748660d33"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [ ] Flying Keyboard glitch on Upload, if it was open before taping Upload

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3212
