### ISSUE TITLE
iOS Interstate Exit Numbers

### ISSUE THREAD

**Issue by NickKatchur** [osmandapp/OsmAnd-iOS#3098]
I'm running into issues with interstate on/off ramps and exit numbers using the iOS app and additionally when using carplay.

When using the iOS app I get the following, which does include the exit number, but does not include the "destination name" but instead uses the interstate that I'm already on. As shown below.

I don't have a screenshot of the carplay interaction, but from history carplay doesn't display the exit number or the destination name, it simply just states take a right in x miles.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/97560029/deb3116e-7700-4555-8127-2009d5d89c66"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/97560029/183a4b4c-708c-4264-b581-ec42e98133e8"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
testflight version 4.5.1.7
- starting point 39.92400° N, 86.22172° W
- end point 39.92663° N, 86.22941° W 
- Way https://www.openstreetmap.org/way/1098555701 is tagged ref=I 465 and it is shown in street name widget

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/74fce00e-9c57-4dfd-9c8e-b9ec5e0ee35c"  width="300" height="auto"/> </td>
  </tr>
</table>

- if you continue along the route, the street name widget will display the information from OSM (https://www.openstreetmap.org/way/415747121 and https://www.openstreetmap.org/way/437516453)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/9a19151c-27bc-441f-9874-9a95163b4026"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/77085ffc-98f5-4410-883e-1d49216d2f6e"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by NickKatchur** [comment]
Yes, but that’s once you’re already on the exit ramp which is just signifying the road you’re turning onto. The benefit would be knowing what road you need to exit onto while still on the interstate. “Exit XX - Street Name”

**Comment by vshcherb** [comment]
This road contains information about destination / ref https://www.openstreetmap.org/way/415747121 "US 421 North" I think while approaching to turn we display next street name

**Comment by NickKatchur** [comment]
That is the correct name, but that name doesn't show up until you're on the off ramp of the interstate. The benefit would be for that name to pop up while approaching the exit, before actually getting on the exit.

**Comment by vshcherb** [comment]
As 4.5 release is out the issue could be double checked if it's fixed cause on 4.5 it's not reproducible

**Comment by NickKatchur** [comment]
I am on iOS 4.5.2 and the problem still persists for me.

![IMG_2053](https://github.com/osmandapp/OsmAnd-iOS/assets/97560029/65ddd40f-d302-477c-95ab-0e3b40b967d4)

**Comment by yuriiurshuliak** [comment]
The ref tag in OSM should be visible in the street name widget, but currently, the street name widget only shows information from OSM. There is no destination:ref=* tag on the road, it only appears at the convention.

TestFlight OsmAnd 4.6.1.3

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/1347a874-70b2-4918-a25c-1343b98f19e4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/443d8ddd-16c7-4c6c-8378-a3e8a6f619c4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/b4f5be8e-82df-4bbc-aed3-c9edd2a2e721"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by NickKatchur** [comment]
I believe that's the issue though, an interstate isn't going to have a destination tag. The destination tag of the ramp IS the important information and should be what is pulled BEFORE you get on the ramp.

When approaching an exit it should be pulling the junction reference and destination reference BEFORE you get on the ramp. This is how every other navigation software does it so you can correspond the number and name to real life signage. For example Valhalla on the osm website shows it properly, exit number and destination name:

![image](https://github.com/osmandapp/OsmAnd-iOS/assets/97560029/2ac650eb-199b-4425-a411-4d91427e7bb2)

**Comment by yuriiurshuliak** [comment]
Currently, the sign US 421North, Michigan road is displayed before the turn. However, it is worth noting that the shield 465 in the upper panel on the left is covered.

OsmAnd~ 4.7.0#1655m, released: 2024-02-23

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/29082b21-2078-4dd6-a088-66d38f97d1b0"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/15e9890c-7dfc-42db-842d-962dcf38956a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/9a41c06f-fa4b-4197-b226-7acddb51a2c1"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by NickKatchur** [comment]
All, appreciate your all's effort on this. This seems to be working in most scenarios, but I have a few remaining observations:

(These are based off of iOS Testflight 4.7.1)
1. Exit numbers and the appropriate destination tagging is still not showing up in Carplay, example provided below.
2. In cases where a highway exit further splits dividing into one exit ramp into two separate exit ramps with each it's own destination tags. OsmAnd is still pulling the original exit's destination tag rather than the next roads destination tag, example provided below.

Reference of the exact example location:
https://www.openstreetmap.org/way/283196244#map=17/39.99439/-86.12644

You can see in the example below no information is being shown in the Carplay view other than lane guidance. Additionally, to recreate the scenario:

1. While on North Meridian Street (Way: North Meridian Street (117994379)) properly displays to take Exit 129A (Node: 129A (2870978853)) with the proper destination tags 151st Street, 146th Street (Way: 283196244)
2. **After taking Exit 129A, the ramp further divides and incorrectly states the destination tags.** OsmAnd should show the destination tag 146th Street (Way: 283196244), although it still shows the previous destination tag.

![73558559-D914-4C84-AB0F-8DEED72DA74A](https://github.com/osmandapp/OsmAnd-iOS/assets/97560029/acbfc2c6-03fc-499b-82e4-fbebe69ab113)
![BC80E347-A01A-448C-A790-F8C01A2F9296](https://github.com/osmandapp/OsmAnd-iOS/assets/97560029/b471bd88-6cc8-4e53-b671-e532d94de405)

**Comment by vshcherb** [comment]
Yes for 2nd we need to create a new issue to not merge.
```After taking Exit 129A, the ramp further divides and incorrectly states the destination tags. OsmAnd should show the destination tag 146th Street (Way: 283196244), although it still shows the previous destination tag.
```
For Car play information we already know that something is  not consistent across car play versions and our implementation, so no text is visible.
