### ISSUE TITLE
App crashes immediately on startup on macOS

### ISSUE THREAD

**Issue by EmmEff** [osmandapp/OsmAnd-iOS#3107]
I installed latest version from the App Store on my M1 Mac mini running Ventura 13.5.2 (22G91). I proceeded to download North America/Canada/Ontario mapset with no issue. Once map download was complete, I closed those screens, the app crashed and now when restarting it immediately crashes on startup.

I ended up deleting the app and reinstalling from the App Store and now it just crashes on startup every time.

Is this a known issue? Can I provide any more info for troubleshooting/debugging? Is there a publicly accessible TestFlight build that I could try? The version in the App Store is about 3mo old IIRC.

**Comment by DmitryAlexei** [comment]
@EmmEff 
please provide crash logs (see https://docs.osmand.net/docs/user/troubleshooting/crash-logs#send-logs-from-ios-devices)

**Comment by EmmEff** [comment]
Thanks. I sent an email to crash@osmand.net

**Comment by EmmEff** [comment]
This is still an issue. I know the app isn't reported to be supported on macOS but it'd be awesome if it was.

**Comment by EmmEff** [comment]
Possibly a duplicate of https://github.com/osmandapp/OsmAnd-iOS/issues/2425

**Comment by EmmEff** [comment]
The TestFlight build is working for me! Thank you
