### ISSUE TITLE
Crashing importing GPX tracks from WorkOutDoors

### ISSUE THREAD

**Issue by zipav** [osmandapp/OsmAnd-iOS#3115]
## Description
During an attempt to import a GPX tracks, the application crashes. [Downloads.zip](https://github.com/osmandapp/OsmAnd-iOS/files/12612815/Downloads.zip).
Track was exported from [Workoutdoors](https://apps.apple.com/app/workoutdoors/id1241909999?ls=1) app 

### How to reproduce

* Download the tracks
* Open OsmAnd – Menu – My Places – Tracks - Import track

Or download the track, and open it from a file manager using OsmAnd.

### Actual result
* The track is not imported, it crashes while trying to import.

### Expected result
* The track is imported without crashing the OsmAnd app.

**Environment**
OsmAnd Version: OsmAnd TestFlight 4.5.1.10
iOS version: iOS 16.0
Device model: iPhone 12

https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/bc3776ee-e385-4fef-97ff-7ac922351702

**Comment by dmpr0** [comment]
## ToDo
The tracks file is broken.
- [ ]  OsmAnd should not crash
- [ ] Show Alert with error, with line number where it occurs.

**Comment by ahrorkosimi** [comment]
> ## ToDo
> 
> The tracks file is broken.
> 
>     * [ ]   OsmAnd should not crash
> 
>     * [ ]  Show Alert with error, with line number where it occurs.

How is it broken when I can import and open this file in other map apps in iOS, like Organic Maps, or Strava for that matter. Strange.

**Comment by alex-osm** [comment]
Please look at the beginning of `Friday Morning Run.gpx`:
...
`<trk><name>Friday Morning Run</name><type>running</type><trkseg>
<wpt lat="38.2659382" lon="72.6069177">
<name>Start</name>
<ele>3301</ele>
<time>2023-09-08T05:59:26.125Z</time>
<type>user</type>
</wpt>`
...

`trkseg` contains `wpt` points inside, but it not conforms to https://www.topografix.com/GPX/1/1/#type_trksegType
That is why those gpx are broken. Looks like some apps can import broken gpx(s). That's it.

**Comment by vshcherb** [comment]
Not planning to fix for now

**Comment by ahrorkosimi** [comment]
@alex-osm thank you so much for pointing out to the problem. I have contacted the app developer and he plans to release an update with the fix.
