### ISSUE TITLE
customized display of favorites and tracks (Android feature parity)

### ISSUE THREAD

**Issue by abdullahO2** [osmandapp/OsmAnd-iOS#3117]
### 🚀 Feature request
Is it feasible to develop a feature that allows for a customized display of favorites/tracks/POI on the map, resembling the functionality available in the Android version of Osmand? Specifically, the ability to manage the display of specific favorites items and control the visibility of tracks through map settings would be highly beneficial

Favorites on Android:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/61907628/f92244db-5ca2-484f-9b22-b922440690ff"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/61907628/30b50be8-5ba5-4ad9-a055-2b16551c3974"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/61907628/c9a9735e-75e2-430b-972e-b75c5a98b18d"  width="300" height="auto"/> </td>
  </tr>
</table>

On iOS:
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/61907628/d912d540-5011-41ce-8faa-15a6a76d1de0"  width="300" height="auto"/> </td>
  </tr>
</table>

<table style="width:100%">
  <tr>
    <th>Tracks on Android</th>
    <th>Tracks on iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/61907628/02fe4bc3-3aba-4078-aa75-93949ea35435"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/61907628/2d062ae5-92fa-461b-95ca-e823c5a7f1cb"  width="300" height="auto"/> </td>
  </tr>
</table>

![image](https://github.com/osmandapp/OsmAnd-iOS/assets/61907628/0d309ef3-dc7a-44d4-9451-6f7074e27f20)

**Comment by dmpr0** [comment]
## Summary 
**Favorites** 
* Context menu for folders will be implemented in this task https://github.com/osmandapp/OsmAnd-iOS/issues/2902, but **Show on map** still missing.

**Tracks**
* Tracks view in Configure Map will be redesigned as part of this task https://github.com/osmandapp/OsmAnd-Issues/issues/1913

**POI Overlay**
* Redesign currently not planned

**Comment by vshcherb** [comment]
Merged to other tasks
