### ISSUE TITLE
Follow location mode is switched off after tap on map

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3123]
# Description 
Taping on map for example with Distance to tap enabled leads to loose map following location mode, map isn't moves at all but tap on location button is needed to get back to Follow location mode

### How to reproduce

* Enable **Distance by tap** in **Menu** – **Configure Screen**
* Get back to map, tap on **My location** button, map is set to Follow location mode
* Tap on empty place on map
* **Distance by tap** will be shown, map isn't moving but **Follow location** mode is off

### Actual result
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f287d78b-b833-414b-8672-d695543f036b"  width="300" height="auto"/> </td>
  </tr>
</table>  

### Expected result
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b83d4121-44ce-463e-b0ae-72a64f855126"  width="300" height="auto"/> </td>
  </tr>
</table>  

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3151
