### ISSUE TITLE
Animated TabelCells – Search

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3125]
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1813d3f3-433c-4b54-8802-2196720ad4b0"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
how to reproduce this bug

https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/445a5a69-042d-456c-93b8-7e35d7f7422d

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3144
