### ISSUE TITLE
Show Temporary Access Restriction

### ISSUE THREAD

**Issue by NickKatchur** [osmandapp/OsmAnd-iOS#3131]
Currently temporary access restrictions are not being displayed on the map. Only permanent access restrictions when enabling show access restrictions and tolls.

I think it should recognize temporary restrictions in rendering the map. Such as the example below. The ramp indicated is currently closed and has a temporary access restriction, but is rendering the same as any other normal road.

I’m unsure if it would be best to create a separate option to show temporary access restrictions with its own render type or include that in the current setting.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/97560029/91c24924-2f1a-46d2-9d81-e360278b3e10"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by vshcherb** [comment]
Merged to https://github.com/osmandapp/OsmAnd/issues/10983
