### ISSUE TITLE
Weather screen widgets is broken

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3135]
## Description
After introduction new Configure Screen, we broken up Weather screen.
 
### How to reproduce
* Open Weather screen

### Actual result

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6a167a07-9319-4ab3-9d1b-3f48fae33cd9"  width="300" height="auto"/> </td>
  </tr>
</table>
</details>  
  
* Widgets from Left and Right panels are shown

### Expected result

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6c0550e2-133f-4e2a-8f52-7a137312a5a7"  width="300" height="auto"/> </td>
  </tr>
</table>
</details> 

- [x]  Only Weather widgets should be shown on the Right panel:
- - [x] Temperature
- - [x] Pressure
- - [x] Wing
- - [x] Clouds
- - [x] Precipitation 

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d05f6f49-627e-4ab2-8092-d129a08e318d"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  


- [ ]  Only left panel width limited list of weather widgets should be shown

- - - - - - - - - - 

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e39f5afc-17a4-4ac7-aa07-5d34a2ef375d"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>

- [ ]  Wrong order of Time marks on slider using RTL. Should be `00 - 21 - 18 - 15 - 12 - 9 - 6 - 3 - 00`

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/9903cc831494309a520e7cc3ec05975f25962ee3

**Comment by dmpr0** [comment]
# Review – 2
