### ISSUE TITLE
Coordinates widget toast –  RTL issue 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3136]
## Description
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b0e34379-417d-4971-86ba-73b61af5090a"  width="400" height="auto"/> </td>
  </tr>
</table>

Using RTL widget in default coordinates format, Coordinates widget and context menu show coordinates in format: 
`30.5213° E 50.4378° N`

### How to reproduce
* Switch OsmAnd app language to Arabic in Settings - OsmAnd Maps
* Add Coordinates widget to the top or bottom panel 

### Actual result
   <details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th>Context menu</th>
    <th>Coordinates widget and toast</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/29e1b29d-5bd2-46b7-9b9f-9c2c92eed0b3"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/89c28f8e-0d51-4406-9df5-7f6a893684c7"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

* Widget show: `30.5213° E, 50.4378° N`
* Toast show: `N, 30.5213° E 50.4378° `
* Clipboard: `50.4360° N, 30.5064° E`

### Expected result
- [x] Format in widget and toast should be the same, fix text in toast.

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3319
