### ISSUE TITLE
Crash: closing color palette

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3146]
## Description
OsmAnd crash when try to change track colour by adding new one by using color palette.

### How to reproduce
* Tap on **Menu** – **My Places** - **Tracks**
* Select any track, tap on **Appearance**  
* Scroll to **Coloring**, switch to **Solid**
* Tap on **Add** (+)
* Colour palette will open, tap on close

### Actual result
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ad21c748-d5ca-4ea0-9746-0dd1c332a4bc"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result
* Close without crash

**Environment**
OsmAnd Version: 4.5.2.2
iOS version: 17.1 beta
Device model: iPhone XS Max

**Comment by Skalii** [comment]
[fix crash after closing color palette r4.5](https://github.com/osmandapp/OsmAnd-iOS/pull/3150)
