### ISSUE TITLE
Add OSM link with pin into context menu

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3153]
## Description 
Follow Android team, we need to add OSM Link with Pin into Coordinates section of context menu.

> Android task Share button to openstreetmap.org with marker on map #16386

## ToDo
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4d8034e3-7626-4509-a9b0-9d3025383c73"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x]  Add OSM Link to context menu Coordinates section
- [x] Visible if OpenStreetMap editing plugin is On.

**Comment by DmitryAlexei** [comment]
Docs updated
https://osmand.net/docs/user/map/map-context-menu#coordinates

**Comment by EugeneZmeuk** [comment]
**16-04-2023 Review**
- added links for [this section](https://osmand.net/docs/user/map/map-context-menu/#coordinates]
