### ISSUE TITLE
Wrong coordinates applied for points after swipe – Plan route

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3167]
## Description
Points added right after map was moved, will added to previous location of screen center. It seems that issues in 
`void OsmAnd::MapAnimator::animateFlatTargetWith`

### How to reproduce
* Open **OsmAnd** - **Menu** – **Plan a Route**
* Move map and tap on **Add point**

### Actual result
<table style="width:100%">
  <tr>
    <th colspan=2>Swipe iOs</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/9c00f306-5780-4845-b950-98511ea9851c"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e029bbb9-9696-47fb-b95f-688cf97e6eb9"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/5f886dde-41ba-4a23-87b4-a91ecb18c1b2"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result
* Points will be added below screen center, marked by special crosshair icon

**Environment**
OsmAnd Version: 4.5.4.1
iOS version: 17.1 Beta 3
Device model: XS Max

**Comment by Andrewschenko** [comment]
> # Review
> Tested on TestFlight 4.6.2.1
> 
>  PlanARoute.mov 
> * [ ]  Still reproduces

This behavior is observed during the free “sliding” of the map after dragging. Unfortunately, determining the location of the screen center on the terrain in each frame is quite expensive computationally. This leads to a general drop in FPS and doesn't give the desired result.
