### ISSUE TITLE
4.5.1 Topography setting inaccessible

### ISSUE THREAD

**Issue by valynor** [osmandapp/OsmAnd-iOS#3169]
iPhone 13 Pro Max, iOS 17.0.3

Just installed 4.5.1 and noticed that in configure map "Topography" is now inaccessible, it's in the same menu cell as "Road style" but overwritten by it. 

![image](https://github.com/osmandapp/OsmAnd-iOS/assets/23384233/db786f80-9df0-4b4d-a9bb-3c5be4fe555e)

Weirdly, on an iPad Mini 5 Topography shows as expected.

**Comment by vshcherb** [comment]
You probably need to install new terrain maps, we're working to understand the cause of the issue

**Comment by valynor** [comment]
@vshcherb 
Turning on the contour lines plugin - without even downloading the terrain map - fixed it. Thanks!
