### ISSUE TITLE
4.5.4 hillshading and 3D terrain not working

### ISSUE THREAD

**Issue by tomislav** [osmandapp/OsmAnd-iOS#3170]
I’ve just updated to 4.5.4 and hill shading is no longer working. Also, 3D terrain is not working. I have downloaded the 3D terrain data. I am an Pro subscriber. 

Am I missing something?

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/656/5f2e7c9b-d73e-438f-ad90-a23a1ebd890f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/656/250a0b44-df1d-48f8-b5a6-4723a431fde4"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by MagielBruntink** [comment]
Same issue here. In some maps hillshade is working (like Netherlands) but not on others (like Czechia). 3D relief is never working. All maps downloaded. Pro subscription.

**Comment by DmitryAlexei** [comment]
To fix this issue, please follow these steps:
- enable *Test heightmap* in Development plugin (go to menu > plugins > development > settings), see screenshot. Make sure, that other options in Terrain map (3d) are also enabled.
- download heightmaps of needed regions
- configure visibility and zoom levels of hillshade/slopes in Configure map menu 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/2cabe5f2-f672-4b5f-85ae-7bab36f50abe"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by MagielBruntink** [comment]
Thank you, that works. The change log suggests the 3D relief is a finished feature, which is why it's confusing that the development plugin is still needed.

**Comment by dmpr0** [comment]
The issue will be fixed in the next update https://github.com/osmandapp/OsmAnd-iOS/commit/b80f0d065ac18fbbba51a9d36874c11c6114606a
