### ISSUE TITLE
4.5.1 hillshades/slopes not displayed on iPad 

### ISSUE THREAD

**Issue by valynor** [osmandapp/OsmAnd-iOS#3172]
iPad Mini 5, iOS 17.0.3

Hillshades or slopes are not displayed on my iPad. 

What I tried to fix this:
-toggled Contour Plugin off and on again
-switched Terrain off and on again 
-switched between hillshades and slopes
-killed and restarted the app multiple times
-deleted and redownloaded the terrain map

... all of this with zero effect, unfortunately. 
Hillshades do work fine on my iPhone 13 Pro Max though, same account, exact same settings. 

<img width="768" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/23384233/df0796e9-42d1-465a-bc22-56ba37a065fe">

**Comment by DmitryAlexei** [comment]
Could you please enable *Test heightmap* option in Development plugin (Menu > Plugins > Development > settings) and download heightmaps of needed regions? (see comment https://github.com/osmandapp/OsmAnd-iOS/issues/3170#issuecomment-1763518083)
Is it working for you?

**Comment by dmpr0** [comment]
Will be fixed with the next update https://github.com/osmandapp/OsmAnd-iOS/commit/b80f0d065ac18fbbba51a9d36874c11c6114606a
