### ISSUE TITLE
OpenStreetMap fields old_name, alt_name, full name list

### ISSUE THREAD

**Issue by abdullahO2** [osmandapp/OsmAnd-iOS#3173]
In one of the previous versions of OsmAnd on the Android system, the feature was added to display all the names available for the feature, and the ability to search in them. Is it possible to add this feature to OsmAnd on iOS?
https://github.com/osmandapp/OsmAnd/issues/17486

**Comment by Dima-1** [comment]
For [Clayton Hotel Düsseldorf](https://www.openstreetmap.org/node/3176636861)
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/31807095/b1d20219-51a6-48e9-a646-805f10c37c19"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by abdullahO2** [comment]
Thank you very much @vshcherb @Dima-1

**Comment by DmitryAlexei** [comment]
OsmAnd TestFlight 4.7.2.11
New functionality successfully added to the iOS version of the app. Old_name=* tag tested on [this](https://www.openstreetmap.org/node/4726658599) POI (see screenshots), alt_name=* tested on [this](https://www.openstreetmap.org/node/10824078498) and [this](https://www.openstreetmap.org/node/1340656195) POI and [this](https://www.openstreetmap.org/relation/130921) city, all worked.
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/1d198dbd-78c5-4e24-a4b9-50500cac492d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/116079541/7a6a4223-3cec-4ac2-a911-fb1c7fe7a7d4"  width="300" height="auto"/> </td>
  </tr>
</table>
