### ISSUE TITLE
Exit number is truncated if it is more than two digits 

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd-iOS#3178]
### Description

See picture below, where the highway exit number was greater than 100

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/609677/9698505f-7c55-4d0c-b489-828ea0c3c921"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

See picture 

### Actual result

See picture

### Expected result

Exit number is a key piece of information and should not be truncated.

### Your Environment (required)

```
OsmAnd Version: 4.5.4
iOS version: 16.7
Device model: iPhone XR
Crash-Logs: 
```

**Comment by vshcherb** [comment]
New release is just out

**Comment by kevinp2** [comment]
@DmitryAlexei , here is an exit on I-15 southbound in Nevada:

https://www.openstreetmap.org/node/137642982

And this is what is displayed on my iPhone XR , which may well be specific to certain screen sizes:

![IMG_3233](https://github.com/osmandapp/OsmAnd-iOS/assets/609677/67c394a2-9ac8-4275-9658-a168c672da5f)

**Comment by DmitryAlexei** [comment]
@vshcherb you are right, the issue is text-size specific

Steps to reproduce:
- Increase text size in the System settings
- enable street name widget in the configure screen settings
- simulate navigation using mentioned above .gpx file or coordinates 

Actual result:
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/8bd72cd5-e946-40b2-8846-2534ebcda564"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/e31bc268-769a-4439-aac6-c1772a35424a"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3199

**Comment by zipav** [comment]
OsmAnd TestFlight 4.6.1.3

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/4b050b5f-e5d3-4351-bc09-5dd0d9508c1f"  width="300" height="auto"/> </td>
  </tr>
</table>
