### ISSUE TITLE
CarPlay - bug  of the location icon with navigation + underlay  mode

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#3181]
###  Description

- [x] The location icon moves to the left (non-right place) during Navigation + underlay (overlay?) is switched on. After the underlay is switched off, the icon is not moved to the right place.

|Navigation and Underlay on| Navigation and Underlay off|
|--------|----------|
|<img width="419" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/f2a7cbe8-a1d6-497e-bc30-9a6a59060e3a">|<img width="552" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/24f5bfdb-68f8-4714-9c7c-118ec93b565f">|

### Steps to reproduce

Switch on underlay (overlay?) for navigation mode.

### Actual result

The location icon moves to a non-right place. The actual result is right for non-navigation mode (the centre screen for icon location).

| Navigation and Underlay mode |
|---|
|<img width="619" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/ed403610-df87-4ae9-aedd-ad9ce216df01">|

### Expected result

the location icon must be in the centre for navigation mode:

|Navigation mode|
|----|
|<img width="1036" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/29021379-8391-4332-90d8-f0bc3ca02ff8">|

Your Environment (required)
OsmAnd Version: 4.5.5.1
Android/iOS version: iOS 17
Device model: XS

**Comment by dmpr0** [comment]
Need to be retested on 4.6 version

**Comment by Skalii** [comment]
fix location icon after opening gpx track
fix location icon after opening navigation settings
fix location icon after opening route line appearance
