### ISSUE TITLE
CarPlay - location lag during navigation mode

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#3191]
###  Description

- [ ] During navigation mode the location has a lag of 3-5 sec of the real location.

In this video you can see:
4s - I droved through an intersection
12s - CarPlay shows my location at this intersection, but already I was near a bus stop (120 m. on forward).

My speed was about 40-50 km/h

https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/5b054265-0ec0-472f-914c-0bfdf10c39fa

### Steps to reproduce

Starting of navigation on CarPlay

### Actual result

The lag location is 3-5sec. Navigation is not actual

### Expected result

The lag location needs to be no more than 0.5sec

Your Environment (required)
OsmAnd Version: 4.5.5.1
Android/iOS version: iOS 17
Device model: XS

**Comment by alex-osm** [comment]
Waiting for @EugeneZmeuk retest

**Comment by vshcherb** [comment]
Animation related issue

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/11327832a82be1c3988263ede7c94dbb8b617de2

**Comment by vshcherb** [comment]
Needs to be retested with latest version
