### ISSUE TITLE
Crash remove color 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3207]
## Description
Crash when trying to remove a color.

<details>
    <summary>Crash</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7f57cfb3-67f3-4c12-95c3-f0493fd38866"  width="auto" height="auto"/> </td>
  </tr>
</table>   
</details>  

### How to reproduce
* Select any point on the map
* Tap Add favourite in content menu
* Scroll down to **Color** group
* Tap on **All colors** item
* Tap `+` Add new color in NavBar
* In palette UI select new color, tap close
* Long tap on new color, context menu will open
* Tap **Delete**

### Actual result

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/61970141-44b9-44a1-add0-92cd4fd568fd
"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

* Crash

### Expected result
* Color will be removed

**Environment**
OsmAnd Version: 4.6.1.1
Android/iOS version: 17.2
Device model: iPhone XS Max

**Comment by Skalii** [comment]
fix crashes on group create/edit screen
fix crash after select "duplicate"
fix selected item after deleting another item
fix default color duplication when creating the first favorite

**Comment by dmpr0** [comment]
<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1644da0d-1f08-4b58-8543-fa38d466a0ed"  width="600" height="auto"/> 

> _User feedback:_
> Not possible to launch the app. Crash systemically

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d650ca8b-36b9-4f50-addc-7ae04bc00b61"  width="300" height="auto"/> </td>
  </tr>
</table>   
</details>  

- [ ] Crash, on Change default appearance for folder.

**Comment by Skalii** [comment]
fixed creation of favorites folder on first launch
