### ISSUE TITLE
OSMAnd iOS does not render natural=shingle in a way that is easy to see

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd-iOS#3217]
### Description

Here is a test area: https://www.openstreetmap.org/way/1223388250

In the Driving Profile:

In the night view, this area is rendered, but is just barely visible:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/609677/1857b506-39be-456e-be3b-52aca349ff1b"  width="300" height="auto"/> </td>
  </tr>
</table>

In the day view, the area is there but even less visible.  

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/609677/478594c2-f136-4445-bf2b-d43b32de012c"  width="300" height="auto"/> </td>
  </tr>
</table>

I think that the area is rendered in the Browse Map and Walking profiles, but so faintly that no one would notice.

### Steps to reproduce

Open OSMAnd iOS and go to this location: 36.19651,-114.68880

Switch the profile between Driving, Browse Map and Walking profiles
Switch the day/night mode between day and night.

Compare to OSM's rendering: https://www.openstreetmap.org/#map=18/36.19635/-114.68881

### Actual result

The shingle area is barely visible and would not be noticed unless you already knew it was there.

### Expected result

The shingle area should be shown consistently across all profiles and day/night modes.

The shingle area covers a dry wash which is prone to flash floods.  **It is helpful in hiking and driving navigation to be aware of the dry wash / flash flood area.**

The OSM Carto rendering would be a good compromise - enough to be noticed, but not enough to distract:

https://wiki.openstreetmap.org/wiki/Tag:natural=shingle

https://www.openstreetmap.org/#map=18/36.19635/-114.68881

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.5.5
Android/iOS version:  16.7
Device model: iPhone XR
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
Visibility is quite low I agree

**Comment by xmd5a2** [comment]
Shingle visibility was improved
![Screenshot_2023-11-22_10-12-22](https://github.com/osmandapp/OsmAnd-iOS/assets/5829014/63ea107f-29df-490a-801e-5da56625af98)
![Screenshot_2023-11-22_10-11-41](https://github.com/osmandapp/OsmAnd-iOS/assets/5829014/73ab3b67-98a5-47f1-9b3d-d713cad69453)

**Comment by zipav** [comment]
OsmAnd TestFlight 4.1.6.4

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/90d881d8-e4b2-4864-a83b-324f49321e47"  width="300" height="auto"/> </td>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/d1a3d50d-7152-4afb-9e8f-f9a089e67d5d"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by xmd5a2** [comment]
![изображение](https://github.com/osmandapp/OsmAnd-iOS/assets/5829014/88013ae7-5c39-419e-99d9-fd3c944b1152)
