### ISSUE TITLE
App freezes when having multiple tracks

### ISSUE THREAD

**Issue by Dimi1911** [osmandapp/OsmAnd-iOS#3218]
### Description

i have switched from an android to iphone. i have installed the osmand app on my new iphone. because i did not want to lose all my tracks, i have copied them on my old phone, send them to my email and downloaded all the tracks on my new phone. 
before downloading the tracks, the app worked just fine on my iphone. but as soon as i downloaded the tracks on my new phone. the app kept freezing. i deleted the app and did the same all over again, but everytime i downloaded the tracks, the app kept freezing and i couldnt use it at all. 
so what can i do now to not lose all my tracks i have recorded for the past three years??

### Steps to reproduce

copy tracks on old phone. send it per mail to yourself, download tracks on new phone

### Actual result

app freezes, could not be used at all

### Expected result

i would like to have all my tracks (around 400) on my new phone without the app freezing

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```

**Comment by DmitryAlexei** [comment]
@Dimi1911 
- what is the version of the OsmAnd app and iOS? what device do you use?
- how much space do your tracks take?
- have you got freezes when all the tracks shown on the map? or even when they are not shown?

**Comment by Dimi1911** [comment]
Hi
I use iPhone 14

I am Not Site how much Space the Tracks use But ist around 400 Tracks i Rhinozeros maybe even more
The device also freezes when the Tracks are Not shown

**Comment by zipav** [comment]
OsmAnd TestFlight 4.6.1.3
iOS 16.0 
iPhone 12

The application does not allow to import a file with tracks (70) to reach the number of 400+, the application crashes instantly, sent 2 reports with crash logs to the developer at 0:57 by Kyiv.

**Comment by Dimi1911** [comment]
hi

so in order to get all my 400 tracks on my new phone, do i need to copy the tracks in packages of 70 per import? will it work then? 

i dont want to lose all my 400 tracks

 
 

Gesendet: Sonntag, 19. November 2023 um 23:51 Uhr
Von: "zipav" ***@***.***>
An: "osmandapp/OsmAnd-iOS" ***@***.***>
Cc: "Dimi1911" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [osmandapp/OsmAnd-iOS] app freezes (Issue #3218)


 

OsmAnd TestFlight 4.6.1.3
iOS 16.0
iPhone 12

The application does not allow to import a file with tracks (70) to reach the number of 400+, the application crashes instantly, sent 2 reports with crash logs to the developer at 0:57 by Kyiv.

**Comment by DmitryAlexei** [comment]
@Dimi1911 you can either wait for a fix or try Cloud backup (https://osmand.net/docs/user/personal/osmand-cloud) available with a Pro subscription.

**Comment by DmitryAlexei** [comment]
@Dimi1911 you can try with new TestFlight version (when ready, see https://osmand.net/docs/versions/nightly_versions#testflight) or wait for the next release.
From our side, we will continue testing.
