### ISSUE TITLE
Missing « hide selected tracks » option

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#3228]
In osmand 4.5.2, in the tracks submenu, there is a button to display all selected tracks (the one at the right of the sharing icon) but no option to hide all selected tracks. The only possibility I found to hide tracks is to manually to so with the switch at the right of the tracks in the list
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/8c049400-9b46-45d6-96f8-cf6725bc32b2"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
Merge to https://github.com/osmandapp/OsmAnd-Issues/issues/1913

Will be available with the next TestFlight build 4.7.1.3, https://testflight.apple.com/join/7poGNCKy
