### ISSUE TITLE
Slow app while having sereval displayed tracks

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#3229]
In osmand 4.6.1.3 with an iPhone 14 Pro, the app seems to be slowed down a lot when having multiple tracks displayed on the map. It also takes longer to load it

https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/065c6bb5-cd41-45b9-924b-2b24027efe86

**Comment by DmitryAlexei** [comment]
Duplicate of https://github.com/osmandapp/OsmAnd-iOS/issues/3218
