### ISSUE TITLE
Shader Relief should be always enabled when 3D Relief is on

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#3235]
![Screenshot 2023-11-22 at 13 50 12](https://github.com/osmandapp/OsmAnd-iOS/assets/1042025/87a9f808-3127-4ebe-ab7f-d06965ba5cc0)

Observed:
- Currently it's always off and you can see the picture above. If you change zoom levels for hillshade or enable Slope
Expected:
- It should be always on

**Comment by dmpr0** [comment]
# Review 
* What result should be expected?

**Comment by vshcherb** [comment]
Hillshade is automatically enabled when relief is on
