### ISSUE TITLE
Invisible symbols on speed limit alert

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3239]
## Description
Digits with road speed limit isn't visible if App theme set to Dark and Map mode set to Light.

### How to reproduce
* Switch **App theme** to **Dark** in Menu – Settings - Profile – General settings
* Set **Map mode** to **Light,** in Menu – Configure Map – Map mode
* Build a route from `50.440882,30.508432` to `50.447202,30.522122`
* Set Simulate navigation to Fixed speed, 90 km/h

### Actual result
<table style="width:100%">
  <tr>
    <th> CarPlay</th>
    <th colspan=2>iPhone</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/42e060a2-d903-496d-b8a6-7552784d063e"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/0a02dd91-76a0-4ec3-935e-cc35a32b720d"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e180187e-8391-4e84-8a6a-647afa9911e9"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result
* Visible symbols 

**Environment**
OsmAnd Version: 4.6.2.1
iOS version: 17.2
Device model: iPhone XS Max
 

> Part of https://github.com/osmandapp/OsmAnd-Issues/issues/1958

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3252
