### ISSUE TITLE
Map ruler center point is mismatch with map center

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#3251]
## Description

**Radius-ruler widget**
- [x] After the App restart the centre point is not visible and showed after switching on/off all circles for the Radius-ruler
- [x] The center point has a white color, but it will have a black color

<details>
    <summary>Screenshots</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img width="362" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/c007249f-c665-4286-80b3-bd48ae2baa14"> </td>
    <td><img width="376" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/82a62fe0-2c76-48cf-acd1-cb79848320e9"> </td>
  </tr>
</table>   
</details>  

- [x] Sometimes the centre point is not centred with My Location

<details>
    <summary>Screenshots with not centred point</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img width="362" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/5d11b43b-e43c-4e7e-b68d-4b0d5470133b"> </td>
    <td><img width="376" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/933df196-d773-4a84-b7c5-da42dc001c07"> </td>
  </tr>
</table>   
</details>  

**Weather widgets**
- [x] the centre point is not centred with My Location (always)

<details>
    <summary>Screenshots with not centred point of the weather widget</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img width="362" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/9c2c7c75-15b7-46cc-ab8b-de11b291cc21"> </td>
    <td><img width="376" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/7b7c929e-a385-4323-b02d-64fabe0b7f65"> </td>
  </tr>
</table>   
</details>

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/19f20cdc77e4647d1d2e167bfbfa46a21a0f8a0f
https://github.com/osmandapp/OsmAnd-iOS/commit/408a50d75323f17d1136cc56a0d894413d5ca2c1
