### ISSUE TITLE
Symmetric color space for GPX slope 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3261]
## Description 
We need to follow Android changes, and provide the same gradient for GPX Slope colorisation.

> Android task https://github.com/osmandapp/OsmAnd/issues/12336

## ToDo
- [x] Use new gradient for GPX slope (transfer from Android)
- [x] Use `img_track_gradient_slope` from assets for legend
- - [x] Remove previous raster resource

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3284
