### ISSUE TITLE
Nakhchivan region download unavailable 

### ISSUE THREAD

**Issue by Bootgrease** [osmandapp/OsmAnd-iOS#3279]
### Description

Hello. The option to download the Nakhchivan region of Azerbaijan is nowhere to be found, so that it is impossible to have offline maps of this area. I live not far from here, and I know it is politically complicated because historically this region belonged to Armenia, but can you guys make this region available to download?
P.S. If you choose to make this place downloadable under the jurisdiction of Armenia I and many others will be most pleased, but unfortunately you would be severely insulted by the larger Turkic population, so really save yourself the trouble and do what Wikipedia says is “true” of these contested lands. I just want to be able to have this region downloaded. Thanks. 
<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/153181689/c39b53d7-bda7-45fd-9f36-2803785a77f4"  width="300" height="auto"/> </td>
  </tr>
</table>

### Steps to reproduce

Open the app. Go to map resources/downloads. Go to Asia. Go to Azerbaijan or Armenia. Observe Nakhchivan is missing. Go to Wikipedia. Observe Wikipedia says Nakhchivan belongs to Azerbaijan history even though Azerbaijan is younger than the Coco-cola company. Go to airport and fly to Turkey. Go to bus terminal and drive to Nakhchivan. Observe ancient Armenian crosses carved into stones that predate the age of gun powder. Decide who’s land this really belonged to. 

### Actual result

No download available for Nakhchivan. 

### Expected result

Nakhchivan should be available to download. 

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version:
Android/iOS version:
Device model:
Crash-Logs: ?
```
I don’t know what this means, I’m just making this bug report because some dude in your app support said do this after I emailed y’all. I’m not a computer guy, I’m a hobo living in Armenia.

**Comment by zipav** [comment]
OsmAnd TestFlight 4.6.2.4

When downloading the map of Azerbaijan, Nakhchivan is displayed, although there is not much data.
However, if you enter the coordinates of Nakhchivan and navigate to them, OsmAnd recognises the region when entering the coordinates, but when navigating to the coordinates it cannot identify the map needed to download this region, and it can only be downloaded via Menu → Maps&Recources → Asia → Azerbaijan

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/123936521/cf6afafb-f60b-41e7-a8f4-216d6cd827e9"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/f5316d1d-8b04-4f9a-a5e9-6afdf9ba115d"  width="300" height="auto"/> </th>
  </tr>
</table>
