### ISSUE TITLE
GPX display extra tags on waypoints and metadata

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#3297]
## Description 
Add support for listed tags. 
Example GPX file – [GPX_Example.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/13673063/GPX_Example.gpx.zip)

### New tags

- [x] Link 

<details>
    <summary>Example</summary>

```
    <link href="https://osmand.net/">
      <text>OsmAnd.net</text>
    </link>
```

</details>  

- - -

- [x] Copyright

<details>
    <summary>Example</summary>

```
    <copyright author="OsmAnd B.V">
      <year>2023</year>
      <license>https://github.com/osmandapp/OsmAnd/blob/master/LICENSE</license>
    </copyright>
```

</details>  

- - -

- [x] Author

<details>
    <summary>Example</summary>

```
   <author>
      <name>Author Name</name>
      <email id="your" domain="email.com"/>
      <link href="https://yourwebsite.com" />
    </author>
```

</details>  

- - -

- [x] Keywords

<details>
    <summary>Example</summary>

```
    <keywords>gpx, osmand, hiking</keywords>
```

</details>  

- - -

### Supported tags:
* OsmAnd Extensions 
* Custom extensions

> Current Android task https://github.com/osmandapp/OsmAnd/issues/18342
> Previous tasks:
> https://github.com/osmandapp/OsmAnd-iOS/issues/2039
> https://github.com/osmandapp/OsmAnd-iOS/issues/2063

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/30fb2ae1-1895-47b3-8479-81858569534b"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Email links should work as `malilto:` links, tap on its should open Mail app.

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e03740a1-28ac-4885-8147-17a86c1e0827"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] Link cell padding

**Comment by DmitryAlexei** [comment]
Docs: 
- https://osmand.net/docs/user/map/track-context-menu#description-and-info
- https://osmand.net/docs/user/map/track-context-menu#waypoints-folder

**Comment by dmpr0** [comment]
Correct example file [GPX_ExampleV2.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/14011398/GPX_ExampleV2.gpx.zip)

**Comment by EugeneZmeuk** [comment]
**04.04.2024 Review**
- [ ] [Track Context menu > Overview tab](https://osmand.net/docs/user/map/track-context-menu#description-and-info)
