### ISSUE TITLE
iOS 64GB memory limit 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-ios#330]
https://github.com/osmandapp/Osmand/issues/7053
iOS version of OsmAnd map downloads limited to 64GB?

Version is OsmAnd iOS latest as at 19-Jun-2019.
Device is iPhone 6S, 128GB, latest version of iOS (12.3.1)
Do you use the offline maps offered within the OsmAnd app for download. Yes.

Map download shows Device memory as Free: 1.59 GB.
Actual Device memory shows as 61.4 GB free of 128 GB, (ie 66 GB free approximately).

Error message: "Not enough space to update Netherlands - Map. 2.49 GB is needed. Please free up some space."
I deleted another app to free up memory, and the map downloaded successfully.

I have screen images if you need them.

**Comment by WilfForrow** [comment]
OK, I didn't realise about the iOS project, thank you.

The bug in iOS OsmAnd app is that it thinks my 128GB iPhone is only 64GB.

So the top 64GB of my phone is unusable, and I can't download any more OsmAnd maps without deleting other apps to get me below 64GB.

Many thanks

Images of OsmAnd app error message and iPhone storage attached.

![image](https://user-images.githubusercontent.com/2242419/59760488-5fafa700-928a-11e9-8a9a-75611f9ea512.png)

![image](https://user-images.githubusercontent.com/2242419/59760520-6ccc9600-928a-11e9-9c51-9f1fa7150bc2.png)

**Comment by crimean** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-ios/commit/30e374dfd3a5e6d02fb964295d50b0a045996eba
