### ISSUE TITLE
CarPlay - reset of 3D from Dashboard to full screen (navigation mode) and lag

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#3300]
## Description

The 3D navigation mode is reset when going Full Screen > Dashboard > Full Screen and there is location lag (icons displacement and My location for Full screen)  for Dashboard > Full Screen.

## Steps to reproduce

Start navigation > Full Screen > Dashboard > Full Screen

https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/63953f9f-dd23-4118-80ce-b06d3f6d0ed4

## Actual result

- Reset 3D  (Navigation mode) from Dashboard to Full Screen
- In this video you can see lag from Dashboard > **Full Screen (lag of Full Screen ~5sec)**

## Expected result

3D mode should not be reset when switching from the dashboard to full screen (for Navigation mode) and lag no more than 1 second.

## Your Environment 

OsmAnd 4.6.2.9
iOS version 17.1.2

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/518cb413dd3374f54f65bf1763c5f1d7238dd528

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Video</th>
        <th>Before navigation</th>
        <th>Screen with route</th>
        <th>After Start</th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/fa2b9b85-aaeb-48cb-b1fb-e7592f236a46"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/dfe71cf1-257e-4320-9645-9a1be52938fc"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e1c632b3-47b6-47fe-9731-707cf5086062"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/708d2b5c-c6de-4c35-8787-645fef7e2807"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Navigation started in 2D mode, even if 3D Mode was turned on before
