### ISSUE TITLE
Use Approximate bearing when "Snap to road" is On

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#3310]
## Description

- [ ] Bearing for location icon should be approximated from road curve
- - [ ] Should work only if **Snap to road** is On.

Approximate bearing is internal setting (implemented in Android by @cepprice) which approximates bearing from the road curve and ignores sensor bearing.

<table style="width:100%">
  <tr>
    <th>Observed</th>
    <th>Expected</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/cdcb5d20-016e-4eee-bec8-e237484ebaf8"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd/assets/127092082/cd4f3cab-239d-41b6-8f77-5eb3c94d5c13"  width="300" height="auto"/>   </td>
  </tr>
</table>   

----------------
**Technical Plan** 
- https://github.com/osmandapp/OsmAnd/pull/18680/files
- https://github.com/osmandapp/OsmAnd/commit/9574cdd7f8465f7d1f663da61a5f94edab0101e3 Android (Remove setting approximate bearing - use by default with snap to road)
- https://github.com/osmandapp/OsmAnd/issues/18817

**Comment by yuriiurshuliak** [comment]
The location icon moves smoothly around the roundabout. However, unexpected behavior is noticeable when approaching turns.

TestFlight OsmAnd 4.7.1.10
iOS version: IOS 16.4.1

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/0669fb08-6602-49e7-acff-8b48a8ec09f8
