### ISSUE TITLE
Pinch to zoom not working on Mac

### ISSUE THREAD

**Issue by tomislav** [osmandapp/OsmAnd-iOS#3331]
I'm using the new v4.6 version on an Apple Silicon Mac and with this version the pinch to zoom trackpad gesture stopped working. Zooming with on screen buttons works. Can anyone reproduce?

(Latest macOS)

**Comment by gy-mate** [comment]
I've also just encountered this issue on my Apple silicon Mac—can confirm.

**Comment by dmpr0** [comment]
On my Mac:
* Pin to zoom didn't work not on 4.5.2 nor on 4.6
* Move map with two finger works
* Rotate map doesn't work

**Comment by dmpr0** [comment]
# ToDo
Support listed gestures on Mac OS.

- [ ] Pin to zoom 
- [ ] Map rotation

**Comment by tomislav** [comment]
Please also add support for two finger swipe to tilt the map.

**Comment by dmpr0** [comment]
# Review 
- [ ] Doesn't work
