### ISSUE TITLE
Auto zoom animation for navigation

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3340]
## ToDo
Add auto zoom for navigation animation.
* Consult with OpenGL team about commits to transfer and how to test

> Android & Core tasks
> https://github.com/osmandapp/OsmAnd-Issues/issues/2056
> https://github.com/osmandapp/OsmAnd-Issues/issues/2330

**Comment by vshcherb** [comment]
- Crash (lanes)
- Auto-rotate is blocked by auto-zoom so navigation doesn't follow bearing mode
