### ISSUE TITLE
Exit Number Misrendered

### ISSUE THREAD

**Issue by pnoll1** [osmandapp/OsmAnd-iOS#3341]
Exit number in upper left rendered out of position and text doesn't fit background

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/8444617/20bca80f-3562-4669-92fe-cd1cf79a11c7"  width="300" height="auto"/> </td>
  </tr>
</table>

Reproduction:
Route from I5 north to 405 north via exit 154A

Exit is located at 47.46301 -122.26575

Osmand Version 3.5.X 
Issue seen on Nov 1, 2023

**Comment by DmitryAlexei** [comment]
This issue should have already been resolved. Try to update to 4.6
The initial issue was https://github.com/osmandapp/OsmAnd-iOS/issues/3178
