### ISSUE TITLE
Wrong icons selected when adding a new favourite place

### ISSUE THREAD

**Issue by fortysix2ahead** [osmandapp/OsmAnd-iOS#3348]
When adding a new favourite place, the icon of the place is not respected, but an old, previously selected icon is chosen. This worked in previous versions, but seems to be broken in a least the most recent version. See attached screenshots for illustration: select a well as a new favourite (icon is the well icon). The icon is shown on the map and and in the details pane. But after adding the well as a favourite, an icon from the collection of previously used icons (the last one used???) is chosen.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/40423757/e57f7bc3-8b8e-4df6-be27-ce53e5b499b6"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/40423757/9f9618c4-54b8-42be-b772-8a2d6a79a60c"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by zipav** [comment]
OsmAnd TestFlight 4.6.4.4

On the latest version of TestFlight is not reproduced, saving Favorites keeps the icon that is listed in the Map Legend.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/72f7968b-0e48-4c4f-8c05-8ab457e4f16a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/dc1df40e-14d9-4cd7-89c0-43ed28151905"  width="300" height="auto"/> </th>
  </tr>
</table>
