### ISSUE TITLE
Live “Place removed” string not finished

### ISSUE THREAD

**Issue by tohaklim** [osmandapp/OsmAnd-ios#335]
When searching for a poi on a Live-enabled device, some poi nodes displayed in search results on the map are duplicates of an existing node. They have an “OsmAnd Change Delete” line in the poi pop up, which is inactive and not localized.

При поиске пои с использованием Live из меню поиска (категория «key_cutter» в данном случае) и выводе результатов на карту, в некоторых случаях выводятся дубликаты существующих точек (2 дубля в примере). В окне с деталями точки отображается непереведенная и неактивная строчка OsmAnd Change Delete. 

![156BE4C8-8321-41BC-A617-E8DE783C25CD](https://user-images.githubusercontent.com/7071423/59941397-c76e1980-9465-11e9-971a-0e6434ee30e6.jpeg)
![B6F5894A-3FA8-4749-9261-EE02C6A9BFB6](https://user-images.githubusercontent.com/7071423/59941398-c806b000-9465-11e9-8022-3091c691ba56.jpeg)

Above: only the northernmost node is operational/open.

**Comment by vshcherb** [comment]
2 issues:
1. Search by category shouldn't display deleted objects!
2. Deleted object should be displayed properly in context menu
