### ISSUE TITLE
Truncated text labels on Add favourites screen

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3352]
### How to reproduce
* Switch app language to Ukrainian, Dutch or German 
* Tap on any POI or long tap on map
* Add favourite screen will be open

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Ukrainian</th>
        <th>Dutch</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/122c33ee-65f9-407e-a87d-1f4a14e0d208"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/aff3c200-6c33-4acd-8f67-997f8ec6d7fe"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Back and Save labels are truncated, but visyaly there is a lot of space for them

### Expected result
* Labels will use more free space 

**Environment**
OsmAnd Version: 4.6.4.4
iOS version: 17.2
Device model: XS Max

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. However, it is worth noting that in my case, when selecting a POI and adding a Favorite, the names "Save" or "Cancel" are displayed in full. Yet, when I long-press on the map to add a favorite, these buttons aren't fully visible.

OsmAnd 4.6.2

<table style="width:100%">
  </tr>
  <tr>
    <th>Ukrainian</th>
    <th>German</th>
    <th>Dutch</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/bc3e83f7-8899-4064-8273-24b8f25da5e7"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/043bebae-38c4-4844-9e9f-97bbac2ef74d"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/31f28814-c2a5-428e-9ce7-fcc33c577216"  width="300" height="auto"/>   </td>
  </tr>
</table>
