### ISSUE TITLE
Fix Night theme for point menu in Plan a Route 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3355]
### How to reproduce
* Launch **OsmAnd** – **Menu** - **Plan a route**
* Select **Create new route**
* Add few point on the map
* Tap on points

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Current</th>
        <th> Expected </th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/543c45e3-7a0a-4290-8d13-4d199f14f488"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/97d8d42c-0a76-4b6c-8e9d-ce9dc7c91fda"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Text and icon color is wrong for some labels 

### Expected result
* Fix text and icons color, [Figma](https://www.figma.com/file/DyC3BkWuaDb5pFvLvYnr8k/Plan-a-route?type=design&node-id=102%3A6488&mode=dev)
- [x] Disabled item
- - [x] Text color = `textColorSecondary`
- - [x] Icon color = `iconColorDisabled`

**Environment**
OsmAnd Version:
Android/iOS version:
Device model:

**Comment by tigrim** [comment]
<img width="412" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/17082167/efdb0a1a-6d1c-4a54-86f0-0c1cce087688">

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3362
