### ISSUE TITLE
render style addons overwriting custom render rules

### ISSUE THREAD

**Issue by marticigor** [osmandapp/OsmAnd-iOS#3363]
There is still incorrect displaying of hiking and cycling paths, and no custom color option for contour lines and contour font:
this lines seem to have no effect on ios(opengl):
https://github.com/marticigor/osmand-cartographia/blob/443e4ab8ac0f423ce3431b5828f5d1ed2479d491/Cartographia.hu.render.xml#L7719 path effect and color
https://github.com/marticigor/osmand-cartographia/blob/443e4ab8ac0f423ce3431b5828f5d1ed2479d491/Cartographia.hu.render.xml#LL7556C9-L7556C9 ->patheffect and color
https://github.com/marticigor/osmand-cartographia/blob/443e4ab8ac0f423ce3431b5828f5d1ed2479d491/Cartographia.hu.render.xml#LL953C10-L953C10 -> no countour color option

Based on this thread, it seems to be fixed on android but not on ios:
https://github.com/osmandapp/OsmAnd/discussions/16699#discussioncomment-5541795
addon.render rules are overwriting rules in custom render.

Here is the custom render:
https://github.com/marticigor/osmand-cartographia

Thanks.

**Comment by yuriiurshuliak** [comment]
I compared the map on iOS and Android by installing your custom rendering Hiking.render.xml. Here are the steps to reproduce:

- Import the Hiking.render.xml specified above
- Download the map, at these coordinates 46.940983005419845, 16.283155423406438
- Set the settings specified in this link: https://github.com/marticigor/osmand-cartographia?tab=readme-ov-file
- Compare the same places on the map on Android and iOS

For my part, I can see the difference in colors. However, please provide more specific information about this bug.
Please provide screenshots where we can see what the specific problem is.

OsmAnd~ 4.7.0#1356m, released: 2024-01-12

<table style="width:100%">
  </tr>
  <tr>
    <th>iOS</th>
    <th></th>
    <th>Android</th>
    <th></th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/403d60d0-f960-4f41-92fc-0282e4110a99"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/c63fed37-7e1c-43ab-a9f6-a8b0d864e16f"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/1d11aaa8-7045-4f1f-a502-6d0605a37f5f"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/2b7ca629-8d7e-46ac-a25a-35d18bf1281b"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by marticigor** [comment]
Hi, you took the wrong xml, That one in your screenshots is not mine. This is mine:
https://github.com/marticigor/osmand-cartographia/blob/main/Cartographia.hu.render.xml
The problem is hiking paths, cycling paths, contour lines and countour numbers font is not rendered according to rules in my xml. On android it works but on ios not.

**Comment by vshcherb** [comment]
It's hard to understand how did it happen. As Android and IOS already have same rendering engines and should be identical. That's what we need to certainly reproduce however fixing rendering style might be a complicated task

**Comment by marticigor** [comment]
looks like and also it is mentioned here https://github.com/osmandapp/OsmAnd/discussions/16699#discussioncomment-5541795
that addon.render.xml rules are overruling the rendering style.

**Comment by yuriiurshuliak** [comment]
This time I installed the rendering you mentioned in the comment.
I used identical exported profiles, at the same places and the same zoom and selected several moments indicated by arrows. Do you mean it?

<table style="width:100%">
  </tr>
  <tr>
    <th>iOS</th>
    <th>Android</th>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/b4754d78-8279-4a88-953b-d914d9d6c952"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/77afea8c-1b6b-480d-8855-a3804b1e3cd6"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/2cb95fb1-10df-4930-8796-27216fc8700f"  width="300" height="auto"/> </th>
  <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/6ff6e007-8cbc-4e98-8283-752b9ac7cc7d"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by marticigor** [comment]
Hi, pretty much, yes. My hiking path are red with option to make them slight transparent. Also try to switch on bike paths and compare how that renders. Contour lines are also not rendered according to my style, in contour lines options there is no my custom color for contours to select. There are also some additional switches I use to hightlight gravel tracks and hide stuff I don’t need:
![IMG_0633](https://github.com/osmandapp/OsmAnd-iOS/assets/51922092/74a0b84c-17bc-47ab-9a87-1640e32f15a2)
![IMG_0634](https://github.com/osmandapp/OsmAnd-iOS/assets/51922092/a1e7328c-622d-4621-819b-4c1c9b30277d)

**Comment by vshcherb** [comment]
Now I recall the issue, we decided (as I remember) for some issues that overwriting addon should be possible with addon itself. As addon is a plugin itself for rendering style. Let's double check with @xmd5a2 what's the right approach.

**Comment by xmd5a2** [comment]
@vshcherb Why are you talking about some addon while topic starter mentioned standalone rendering style? This issue is not related to rendering style addons. Some fixes should be made in iOS.

**Comment by vshcherb** [comment]
@xmd5a2 I didn't understand much. Please summarize what needs to be fixed and what the difference Android / iOS

**Comment by xmd5a2** [comment]
Rendering style addons ([example 1](https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/contourlines.addon.render.xml), [example 2](https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/routes.addon.render.xml)) should be applied **after** custom rendering styles that user can put into _rendering_ folder on device.

**Comment by marticigor** [comment]
I have quickly created addons and pushed into new branch ios:https://github.com/marticigor/osmand-cartographia/tree/ios
It seems to be working for hiking and cycling paths but not for contourlines

**Comment by DmitryAlexei** [comment]
- need to check order of initialization of render styles and add-on styles in iOS
