### ISSUE TITLE
Wikipedia POI missing for New Zealand north island from 6 zoom level

### ISSUE THREAD

**Issue by ae-s** [osmandapp/OsmAnd-iOS#3374]
hi,

i was referred here from the osmand support email folks.  please refer to the attached screenshots. [image 1](https://github.com/osmandapp/OsmAnd-iOS/assets/172920/7bf8ac9c-7189-4af2-85eb-b8fdcd5e1d4f) [image 2](https://github.com/osmandapp/OsmAnd-iOS/assets/172920/4272b23f-8ac3-4a76-a230-737a315c5ef4)

new zealand's north island appears to be missing most of its wikipedia poi's when zoomed in. by my guess it was cropped to the east side of the south island bounding box.

when i zoom out, article icons do cover the whole nation & are clickable.

i just re-downloaded all my map data (it's fresh). i'm pretty sure it downloaded correctly, i didnt see any error messages.

thank you!

**Comment by zipav** [comment]
OsmAnd testFlight 4.7.1.9

<table style="width:100%">
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/d7c83fbd-845e-4444-a6f8-b92f4e187da5"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/896417c5-227d-4982-b288-e98252f95ebd"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by ae-s** [comment]
It's been a month, how can I get some attention to this issue?

**Comment by dmpr0** [comment]
## ToDo
- [ ] Fix issue with missing Wikipedia POI in the part of the country


## Additional
Wikipedia POI on Android displaying from 9 zoom level. On iOS from 5 zoom level

**Comment by Dima-1** [comment]
Not only wikipedia poi missing and not only for New Zealand, it seems like poi tile doesn't clear after min zoom
![photo_2024-03-15_10-45-39](https://github.com/osmandapp/OsmAnd-iOS/assets/31807095/04e09263-ac8f-4c19-8b25-7b1881f135ac)

**Comment by zipav** [comment]
OsmAnd TestFlight 4.7.2.10

<table style="width:100%">
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/8e39cca7-82ef-4cd6-bbff-07992c38b9cb"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/d6c1e17c-139d-4710-8ee0-a0b64c14c7d4"  width="300" height="auto"/> </td>
  </tr>
</table>
