### ISSUE TITLE
Help follow Docs structure 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3375]
## Description 
To generate proper structure for Help this file should be used (https://osmand.net/help-structure.json) now instead of old sitemap.xml

> Backend task https://github.com/osmandapp/OsmAnd-Issues/issues/2341
> Previous task #3161

**Popular articles:**
- [x] Use `ios": { "popularArticles":` to get list of popular articles
- - [x] Order of appearance similar to the file

**User guide**
- [x] Use `"level": 2,` to get list of items
- - [x] Order of appearance similar to the file

**Troubleshooting**
- [x] **Troubleshooting** Article should be excluded from list and put into separate section **Troubleshooting**

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3447
