### ISSUE TITLE
Crash after moving widget

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3380]
## Description
App crash after moving first widget bellow the screen center

### How to reproduce
* Open **Menu** – **Configure Screen** – **Left panel**
* Tap on **Edit**
* Move first widget bellow screen center and release

### Actual result
<details>
    <summary>Crash</summary>
<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/2f2faa99-90d4-4d10-998e-751252002052"  width="300" height="auto"/> 
</details>  

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a6bf9411-b9ef-4c2d-8e75-7e03bcaf6d26"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

* Crash

### Expected result
* Widget moves to the new place

**Environment**
OsmAnd Version: 4.7.1.2
iOS version: 17.3
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3411

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3414
