### ISSUE TITLE
Empty point info on transport stop layer

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3387]
## Description

> Previous task, probably related https://github.com/osmandapp/OsmAnd-iOS/issues/2495

### How to reproduce
* Open OsmAnd, go to `52.51742° N, 13.39598° E`
* Open **Configure Map** - **Transport**
* Turn on **Transport stops**
* Tap on stop from Transport stops layer than on Transport stop POI

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Transport layer</th>
        <th>POI</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d06c135a-c97e-4d42-ac31-2bac8fb2055d"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/624c036b-dd0c-4f28-8128-e9dca550f0ab"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

### Expected result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Transport layer</th>
        <th>POI</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c7ccccc6-2d24-4566-8b25-4397e1253292"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b9cd0531-124c-422a-b13e-f164740646a6"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>

**Comment by nnngrach** [comment]
finding points in radius
https://github.com/osmandapp/OsmAnd-iOS/blob/b3c51e5d3dca2c5adca80829c6a4a573c44afb12/Sources/Controllers/Map/Layers/OAContextMenuLayer.mm#L438

filtering points by name and type
https://github.com/osmandapp/OsmAnd-iOS/blob/b3c51e5d3dca2c5adca80829c6a4a573c44afb12/Sources/Controllers/Map/Layers/OAContextMenuLayer.mm#L474
