### ISSUE TITLE
Please help me. QtExtensions.h not found

### ISSUE THREAD

**Issue by Davaajargal** [osmandapp/OsmAnd-iOS#3389]
#include <OsmAndCore/QtExtensions.h> 

<img width="1317" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/5964368/f7a27070-3444-4a2e-a558-529b958c84ce">

**Comment by yuriiurshuliak** [comment]
Please describe the problem and a step-by-step reproduction so we can check. Moreover, such questions are usually discussed in the discussions section: https://github.com/osmandapp/OsmAnd/discussions

**Comment by vshcherb** [comment]
Probably rerun ./prepare.sh and check if there are any errors - https://docs.osmand.net/docs/technical/build-osmand/how-to-compile-the-ios-version
