### ISSUE TITLE
Open proper History type screen on long tap 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3391]
## Description
Currently on **Search** – **History** screen OsmAnd show list of items for Search and Navigation, long tap on any of the item opens Edit mode with old UI. 

We need to open proper screen:
* For navigation items > Navigation history 
* For search items > Search history.

> Android task https://github.com/osmandapp/OsmAnd/issues/18053

### Search history

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Current</th>
        <th>Proposed</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/249f8290-1c8c-448e-a5c1-53a3d5c85b6b"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c77a1823-9a33-4d07-b570-c83ab726b3c3"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Open **Search history** screen after long tap on search history item
- [x] Taping **Cancel**, should open previous screen 

### Navigation history

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Current</th>
        <th>Proposed</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/249f8290-1c8c-448e-a5c1-53a3d5c85b6b"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/75e7940a-f9ff-4755-ac56-77eba727ca05"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Open **Navigation history** screen after long tap on navigation history item
- [x] Taping **Cancel**, should open previous screen

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3452

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Settings > History</th>
        <th>Search – History</th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7eacadd3-528e-464d-b970-1362d2e7e1f8"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f9ef94f4-83d7-4850-9388-63e975b1ea87"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Export doesn't work
