### ISSUE TITLE
Coma after remaining kilometers stays even if there are no decimal to display

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#3393]
Occurs in osmand 4.7.1.3 in navigation mode, the coma is always displayed in the widget of remaining kilometers

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/8d345bf0-b362-4f00-9d32-72c074c3cf23"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/a9ee6f8d-a1de-4cb1-9da7-15eb3ffa9397"  width="300" height="auto"/> </th>
  </tr>
</table>

In comparaison, current speed hide it when there are no decimals

**Comment by vshcherb** [comment]
To do: formatting distance should be fixed (so all widgets will be fixed). **Expected**: ```60 km```

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3440
