### ISSUE TITLE
Flight Metrics (Glide Ratio) – Widget

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3395]
## Description

> Android task https://github.com/osmandapp/OsmAnd/issues/16968

# To Do 
> Glide ratio is the horizontal distance divided by change in altitude. I. For example, if my handglider has a glide ration of 7:1 (7 to 1), then for each foot of altitude lost I travel forward 7 feet. 
https://en.wikipedia.org/wiki/Lift-to-drag_ratio#Glide_ratio

# Widget group

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4e542654-ad07-439c-9c81-09ca0f30ee96"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x]  Add new widget group **Flight Metrics**, with two widgets:

## Glide ratio to target, [Figma](https://www.figma.com/file/ARnU6oUzxzcKWkTNR8bgTd/Configure-Screen?type=design&node-id=1212-54653&mode=dev)

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Main screen</th>
        <th>Mode</th>
        <th>Map</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4bec680f-094e-43a7-8c96-448d4323079f"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/491ab9a9-ff0e-4019-be8c-43d6d9fdb844"  width="300" height="auto"/> </td>
        <td><img src=""  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>  

- [x] Name – `Glide ratio to target`, `glide_ratio_to_target`
- - [x] Icon `widget_glide_ratio_to_target`
- - [x] Description – `Shows the glide ratio needed to reach the target point.`, `map_widget_glide_target_desc`

### Modes

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c7271298-5b96-470f-8883-f38d18ce9812"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] **Glide ratio to target**
- - [x] Should show glide ratio to first map marker.
- - [x] Formatting: `7.4 : 1`. _(7,4 units of distance forward for each unit of descent)_
- - [x] If selected add description – `First map marker will be used as target.`

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a92b4aaa-f051-40d8-b50e-1f84dad1da24"  width="300" height="auto"/> </td>
  </tr>
</table>  

- [x] **Target elevation**
- - [x] Show elevation of target object, for example `320 m`
- - [x] Name on map – `Target elevation`
- - [x] If selected add description – `Terrain map (3D) is needed for retrieving elevation for target.`

## Average glide ratio, [Figma](https://www.figma.com/file/ARnU6oUzxzcKWkTNR8bgTd/Configure-Screen?type=design&node-id=1214-55951&mode=dev)

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Average glide ratio</th>
        <th>Mode</th>
        <th>Interval</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ce9cc7b8-07dc-4a75-ba8c-54a33b2300f8"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/77eab4a3-7b92-4b77-8a9a-38ab6adaf9fe"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/800ed964-8a31-4acf-9d62-6b5390337c0a"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Should show glide ratio over configurable interval
- [x] Description – `Shows the average glide ratio or vertical speed for the set interval..`

**Modes**
- [x] **Average glide ratio**
- - [x]  Show average glide ratio over configurable interval
- - [x]  Icon `widget_glide_ratio_average`
- [x] **Average vertical speed**
- - [x] Show average vertical speed over configurable interval
- - [x] Icon - `widget_vertical_average_speed`

**Interval**
- [x] The same set of values as for Average speed widget

**Comment by dmpr0** [comment]
# Review 
- [ ] **Target elevation** should work if Terrain maps is present, not depended on Terrain or 3D Relief options status

**Comment by vshcherb** [comment]
Special values
```
+-0:1 - You over/under the point destination
0:0 - You on the point of destination
+1:0 - You and target on the same altitude
```

**Comment by vshcherb** [comment]
- [ ] Wrong speed in simuation

**Comment by vshcherb** [comment]
- [ ] Wrong calculation = ```199000/(10999-382)``` = 18.74
![telegram-cloud-photo-size-2-5280538316657253070-y](https://github.com/osmandapp/OsmAnd-iOS/assets/1042025/747804b8-b052-4973-9936-419661ac3491)
