### ISSUE TITLE
Delete account – OsmAnd Cloud

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3396]
## Description 
Add ability to delete OsmAnd Cloud account with all data.

> Android task https://github.com/osmandapp/OsmAnd-Issues/issues/2045
> Backend https://github.com/osmandapp/OsmAnd-Issues/issues/1990

## Process 
* OsmAnd Cloud settings, user tap on **Delete account**
* Open **Verification screen** , where we ask to enter email address for this account
* Tap **Continue**
* ask user to enter one-time password that was send to the email address associated with the account
* If one-time password is correct we open **Delete account** screen, where we inform user about what will be done.
* Taping on **Delete account** button should show last warning dialog
* Taping **Delete** in dialog, should trigger account deleting process (no way back)
* Switch to next screen with progress bar
* Tap **Close** on previous screen, get user to OsmAnd Cloud main screen.

## Settings, OsmAnd Cloud. [Figma](https://www.figma.com/file/9ZeCSdZ4M3uU3VyHl3uKQg/Backup-%26-Restore?type=design&node-id=2235-30523&mode=dev)

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/258333d7-7b10-4af3-a790-98e05ca87769"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new item, text = `Delete account`
- [x] Tap should open **Verification** screen.

##  Verification, [Figma](https://www.figma.com/file/9ZeCSdZ4M3uU3VyHl3uKQg/Backup-%26-Restore?type=design&node-id=2244-15815&mode=dev)

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Email</th>
        <th>Code</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/20662225-4a6d-4cae-95a3-8c96e632d1a6"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4a459583-21ce-41db-884c-6ecc8f8162a4"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* We have this screen, they are used during Login/Registration process.
* We need to add new string on first one, for exactly this case
* We need to verify the user, for this we ask to enter account email address and one-time password, if both were correct we go to the next step.

- [x] First step: Ask for email 
- - [x] Check that the entered email address is the same as the current authorized account.
- [x] Second step: Ask for one-time password, if correct open next step 

##  Delete account 

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <th></th>
    <th>Deleting – In progress</th>
    <th>Deleting – Complete</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/825e3234-f832-4fc5-80bc-c55dd719ef42"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b10bb838-4cdd-49cd-b5a7-4b8db9c82eed"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/45c4c99c-26bd-4415-a6b2-fbdc2a5909b5"  width="300" height="auto"/> </td>
  </tr>
</table> 
</details>  

- [x]  "All data..", icon `ic_custom_file_delete`
- [x] "Your account and...", icon `ic_custom_user_profile_delete`
- [x] "Secondary devices...", icon `ic_custom_secondary_devices_disabled` 
- [x] Add hint "This will not cancel your OsmAnd Pro subscription. Manage subscriptions." Taping on this item should works as the same button on **Purchase** screen.
- [x]  Add **Delete** button, tap - open alert with last warning.

### Alert

<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/09b1bc9a-0a43-4d58-8fc8-6c19e7aea072"  width="300" height="auto"/> </td>
</table> 
</details>  

- [x] Alert title = `Delete account?`
- [x] Description - `Are you sure you want to delete OsmAnd Cloud account? This action can’t be undone.`
- [x] Buttons:
- - [x] **Cancel**, close alert, leave user on Delete account screen.
- - [x] **Delete**, trigger account deleting process, open next screen with progress.

**Comment by RZR-UA** [comment]
Please do not forget to add `lang` API parameter by the similar way:

https://github.com/osmandapp/OsmAnd/pull/19058/files

https://github.com/osmandapp/OsmAnd-iOS/commit/10a38ec6225b77bf0b8804556f54d8551d9a7945

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Settings</th>
        <th>Verification</th>
        <th>Video</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f7353813-9a0d-4300-bd51-d447d04c9291"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/951f659d-d9e7-40eb-9428-b5d1ba1543f7"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6246a957-817e-4e40-be93-0b5e98a716f8"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   


- [ ]  Check that the entered email address is the same as the current authorised account.
