### ISSUE TITLE
Show route type in What's here menu

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3405]
## Description 
When more than one type of route are enabled in Configure Map it's hard to distinguish one from another in What's here menu. We need to indicate route type on the second line, for example: `Route – Hiking`, `Route – Bicycle`.
* Example location 50.96628 10.98794

> Android task https://github.com/osmandapp/OsmAnd/issues/17163

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Android</th>
        <th>iOS</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/2758235f-2a31-491b-816e-39dce311dc15"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d597914c-3d2d-467a-b7eb-5df00fb0e0b1"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

## ToDo
- [x] Add route type to the second line

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3531

**Comment by vshcherb** [comment]
- [ ] https://github.com/osmandapp/OsmAnd/blob/ad6beb4d27537c28f2914d548056ba15935a40dc/OsmAnd-java/src/main/java/net/osmand/osm/OsmRouteType.java - full list is not implemented

**Comment by DmitrySvetlichny** [comment]
![IMG_3427](https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/2d63a279-60ac-4954-9d48-1a229a974ea8)
![IMG_3426](https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/4d3f6338-ba1a-453e-ae03-df098b20cf69)
![IMG_3425](https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/52fbe9f6-bc05-4630-9535-4da504589413)
![IMG_3424](https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/ffc7baf6-292b-4770-9033-7684e14ddb29)

**Comment by DmitrySvetlichny** [comment]
MTB:
![IMG_3427](https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/cedf1eba-def0-4751-ab42-fa8491180ec4)
![IMG_3426](https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/5cb9c8bb-9f42-434d-bd08-e29a744e2dbb)

**Comment by DmitrySvetlichny** [comment]
Horse:
![IMG_3429](https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/273ac389-cac3-4f3f-a877-22461d46c5ae)
![IMG_3428](https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/df65f285-58f4-4f82-adb7-c2c1a1a52659)

**Comment by vshcherb** [comment]
Migrate: https://github.com/osmandapp/OsmAnd/blob/master/OsmAnd-java/src/main/java/net/osmand/osm/OsmRouteType.java#L15
->  https://github.com/osmandapp/OsmAnd-core/blob/795b1e94cac1ed0c18757c340735fcf06e4b27f1/include/OsmAndCore/NetworkRouteContext.h#L19C16-L19C25

**Comment by dmpr0** [comment]
### MTB

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/96dcc031-fa51-4cb3-b47f-152fb305df58"  width="300" height="auto"/> </td>
  </tr>
</table>
