### ISSUE TITLE
Download map dialog should use Map mode as theme

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3406]
### How to reproduce
* Set **App theme** to **Light** in Menu – Settings – Profile – General settings 
* Set **Map mode** to **Night** in Menu – Configure Map – Map mode
* Move map above region without map
* Zoom in to 8 zoom

### Actual result
<table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/fbca4a1b-abf2-4728-8bb2-97d235db33ae"  width="300" height="auto"/> </td>
      </tr>
</table>

* Part of the data isn't visible

### Expected result

<table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/49ca639d-a1cb-445c-b6c0-e1f277ee0130"  width="300" height="auto"/> </td>
      </tr>
</table>

* Dialog theme should depend from Map mode

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3448
