### ISSUE TITLE
Crashs On scrolling the map and in navigation

### ISSUE THREAD

**Issue by michaelkrnac** [osmandapp/OsmAnd-ios#341]
iOS Reports me in my weekle  report  that OSMand is the Most used app on my phone. ☺️ Even though it crashes over and over Again. 

Scrolling the map -> Crash
Start Navigation -> Crash
Navigation Works for 5 minutes-> Crash
Start navigation again (While driving) -> Crash
Calculating alternative Route -> staled loading bar.

Iam very passioned and happy with the Progress of OsmAnd for iOS. But  it is sometimes very anoing 😤

I have no mac so i can Not Debug with Xcode. Is there another  way i can create Stack traces to help to make osmand more stable?

**Comment by vshcherb** [comment]
That looks like too many crashes, especially while scrolling the map. Please send the spec of your IPhone. I don't think we have these many crashes even on 5C. Also we could check App Analytics to find your crash in case it is enabled on your IPhone.

**Comment by michaelkrnac** [comment]
Its an iPhone 6 with iOS 12.3.1 and OSMAnd 2.8.

I have now enabled iPhone Analytics and also switched on "Share With App Developers.

Since than i produced 4 Crashes :-) Can you see that somehow with Analytics?

**Comment by PaulStets** [comment]
@michaelkrnac Unfortunately, there's no way to find out which crash reports were sent from your device. Could you please tell us which maps do you have installed? We would also appreciate if you could send a screenshot of the Map settings screen.

**Comment by michaelkrnac** [comment]
@PaulStets attached the screenshots hope it helps.

Under analytics I have also some log files for osmand. But I do not know if they are helpful. The content is like:

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x0000000000000001
VM Region Info: 0x1 is not in any region.  Bytes before following region: 4299784191
      REGION TYPE                      START - END             [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                 0000000100498000-000000010049c000 [   16K] r-x/r-x SM=COW  ...p/OsmAnd Maps

Termination Signal: Segmentation fault: 11
Termination Reason: Namespace SIGNAL, Code 0xb
Terminating Process: exc handler [12789]
Triggered by Thread:  0

Thread 0 name:  Dispatch queue: com.apple.main-thread
Thread 0 Crashed:
0   libGPUSupportMercury.dylib    	0x00000001e824cfe4 0x1e824b000 + 8164
1   AGXGLDriver                   	0x00000001ec8c5ed8 0x1ec8a1000 + 151256
2   libGPUSupportMercury.dylib    	0x00000001e824dfac 0x1e824b000 + 12204
3   AGXGLDriver                   	0x00000001ec8c7404 0x1ec8a1000 + 156676
4   GLEngine                      	0x00000001eda62234 0x1ed981000 + 922164
5   OpenGLES                      	0x00000001cf4b5aa4 0x1cf4ae000 + 31396
6   OsmAnd Maps                   	0x00000001004e40f8 0x100498000 + 311544
7   QuartzCore                    	0x00000001d0634f90 0x1d0624000 + 69520
8   IOKit                         	0x00000001cc5094b0 0x1cc504000 + 21680
9   CoreFoundation                	0x00000001cc218a8c 0x1cc195000 + 539276
10  CoreFoundation                	0x00000001cc23f690 0x1cc195000 + 698000
11  CoreFoundation                	0x00000001cc23eddc 0x1cc195000 + 695772
12  CoreFoundation                	0x00000001cc239c00 0x1cc195000 + 674816
13  CoreFoundation                	0x00000001cc2390b0 0x1cc195000 + 671920
14  GraphicsServices              	0x00000001ce43979c 0x1ce42f000 + 42908
15  UIKitCore                     	0x00000001f8a6f978 0x1f81b3000 + 9161080
16  OsmAnd Maps                   	0x000000010049d4d8 0x100498000 + 21720
17  libdyld.dylib                 	0x00000001cbcfe8e0 0x1cbcfd000 + 6368


![B5912FC4-3EA2-421C-A528-2161B6246A9C](https://user-images.githubusercontent.com/3944657/60560466-3eea5580-9d50-11e9-84af-16ef3f747e7f.png)
![87373F81-0B8F-4B48-AB9F-C76E78C7130B](https://user-images.githubusercontent.com/3944657/60560467-3f82ec00-9d50-11e9-962b-ae6226f46f89.png)
![455DE3C0-51AC-46AA-BC0A-143115C173F7](https://user-images.githubusercontent.com/3944657/60560468-3f82ec00-9d50-11e9-9da1-31ff165b8391.png)
![766BE96C-F4F5-4A8F-9971-F1D3B7F44ACC](https://user-images.githubusercontent.com/3944657/60560469-3f82ec00-9d50-11e9-93b1-7779ec96d8eb.png)
![B3E6AD62-A71D-4237-A268-AE0D656C7906](https://user-images.githubusercontent.com/3944657/60560470-401b8280-9d50-11e9-9630-1f7999f345b9.png)

**Comment by max-klaus** [comment]
@michaelkrnac could you please confirm it still crashes with 2.90?

**Comment by michaelkrnac** [comment]
Yes still crashes. But I guess there is some problem in combination with routing. On calculating the route OSM crashes a lot on my phone. If I am lucky and the route ist calculated I try to check if the route is correct. so i start to scroll following the route. Here I also get a lot of crashes.

**Comment by PaulStets** [comment]
@michaelkrnac Could you please test the 3.0 version. Let us know if the crashes still occur. According to the crash reports, this issue should not happen in 3.0.

**Comment by michaelkrnac** [comment]
@PaulStets Iam using 3.00 since it was released. I still have 3 scenarios when OsmAnd crashes.

1. scrolling - but this is rare
2. route calculation - always !! Only routes smaller 5 km work
3. when I store a favorite - sometimes

**Comment by PaulStets** [comment]
Does the app crash every time you calculate a longer route, or does it happen on specific routes? Could you please provide an example route coordinates and navigation profile that cause the app to crash?

**Comment by PaulStets** [comment]
@michaelkrnac Also, if you have any recent crash logs in the analytics, please attach them here.

**Comment by michaelkrnac** [comment]
@PaulStets it crashes always independently from route and location. Profile is car. There are recent logs in my analytics but none from osmand. Do i have to enable something ? I will attach a video showing the crash hopefully github can handle the video.



Von meinem iPhone gesendet

**Comment by PaulStets** [comment]
@michaelkrnac How many favorite points do you have at the moment?

**Comment by michaelkrnac** [comment]
Around 800

Von meinem iPhone gesendet

**Comment by PaulStets** [comment]
@michaelkrnac I’m almost completely sure this is why the app crashes. I’ll run a test with the favorites tomorrow and will see if we can do anything about it. In the meantime, please make a backup of your favorites and try reducing their number to at least a hundred. This should prevent the app from crashing.

**Comment by michaelkrnac** [comment]
@PaulStets no crash on scrolling since 3.1 and this with 1000 Favorites. Nice!
I think we can close this issue and focus on #443 because my osmand crashes all the time when i click the route button.

**Comment by PaulStets** [comment]
@michaelkrnac Glad to hear the app stopped crashing on the scroll. We indeed improved the rendering speeds in this update. As for the routing issue, I'm not sure that your issue is similar to #443, because that issue can be related to manual app build (e. g. not installed from the App Store). Please describe your exact actions when the app crashes in navigation.
