### ISSUE TITLE
Text on transparent widget

### ISSUE THREAD

**Issue by tatobox** [osmandapp/OsmAnd-iOS#3417]
When I set transparent widgets the text is displayed badly, both when the map is in day or night mode and whether the profile is light or dark

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/a12d4a01-8d39-4c8f-b927-fb4c638c6dc6"  width="300" height="auto"/> </td>
  </tr>
</table>    

> iPhone SE 1st gen
> iOS 15.8
> TestFlight 4.7.1.6

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. First, try to see the normal widgets, then try to enable the "Transparent widgets" option.
Menu → Configure screen → Widgets

OsmAnd TestFlight 4.7.1.6

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/02e95ea6-aaa4-45e2-9d2d-721c8f77e69a

**Comment by tatobox** [comment]
@vshcherb TestFlight 4.7.1.10 fixed this issue.
Thanks

**Comment by yuriiurshuliak** [comment]
Currently, if you enable the "Transparent widgets" option, the widgets are visible.

OsmAnd TestFlight 4.7.2.7

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/4121dbb7-16dd-4d1b-b4c5-ac46dd6c3aa6
