### ISSUE TITLE
Add syncing for map dark mode with iOS state

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd-iOS#3464]
Right now we have three settings for map mode:
“Sunrise/sunset”
“Day”
“Night”

I propose to add fourth mode: 
“Sync with IOS”. 

And make this mode as default. Because it is really logic app behavior: to sync dark mode with iOS by default.

<img width="1043" alt="Снимок экрана 2024-02-27 в 20 02 15" src="https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/ddb0a3b8-605e-45d7-b7ce-9220c7bc9762">

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd/issues/3384

**Comment by vshcherb** [comment]
https://github.com/osmandapp/OsmAnd-Issues/issues/2308
