### ISSUE TITLE
iPhone X position of elements in landscape mode

### ISSUE THREAD

**Issue by macagoule** [osmandapp/OsmAnd-ios#348]
Hi Osmand Team,

In regards of this issue https://github.com/osmandapp/OsmAnd-ios/issues/98, iPhone X(S/R) systems are now working fine in Portrait Mode. However when using in LandScape Mode, the notch still mask some elements when Navigation enabled for example.

![osmand_landcape_nav_issue](https://user-images.githubusercontent.com/29747870/60982728-fbd44780-a338-11e9-96ef-f6b85a36ccf1.png)

![osmand_landcape_nav_issue2](https://user-images.githubusercontent.com/29747870/60982752-055daf80-a339-11e9-9a98-2ee3ef1b90ac.png)

Is it possible to make the necessary changes to make it work as the Portrait Mode ?

Thanks !

**Comment by PaulStets** [comment]
Fixed with 01aeb8fcc8846710ba6ea31a483a55ace955a9cf
