### ISSUE TITLE
mac OS - App crashes at launch

### ISSUE THREAD

**Issue by matteoar1** [osmandapp/OsmAnd-iOS#3484]
The app doesn't open on my Mac mini with M2. It crashes at lunch.
[OsmAnd Maps-2024-03-06-122139.ips.zip](https://github.com/osmandapp/OsmAnd-iOS/files/14509111/OsmAnd.Maps-2024-03-06-122139.ips.zip)

**Comment by dmpr0** [comment]
## Crash at launch

<details>
    <summary>Screenshot</summary>

<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/9095114f-37ae-4202-afed-272d3514c91c"  width="auto" height="auto"/> 

</details>  

```
Device: MacBook Pro (14‑inch, 2021)
Version: macOS 14.2.1
App Version: 4.7.3 (4.7.3.5)
```

- -  -
> Related https://github.com/osmandapp/OsmAnd-iOS/issues/3107
