### ISSUE TITLE
Add context menu for tracks in Configure Map

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3488]
## ToDo
We need to show context menu after long tap on track item in Configure Map – Tracks.
- [x] Show context menu after long tap
- [x] Context menu similar to menu in My Places > Tracks
- - [x] Replace **Show no map** with **Open** action, icon – `ic_custom_overview
`
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/57e4b907-bae8-4e26-857b-04709d3df41b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/ab1a8199-443b-4a3d-9c29-30a617935172"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3987
