### ISSUE TITLE
Roundabout turn arrows is missing – CarPlay

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3489]
## Description
Roundabout turn arrows are does't while navigation in CarPlay. On CarPlay we use different and limited from iOS app set of turn arrows, but `map_turn_roundabout_left` and `map_turn_roundabout_right` is present in there. 

### How to reproduce
* Calculate route from `52.23996, 4.50341` to `52.23599, 4.50283`
* Turn on Simulation
* Connect OsmAnd to CarPlay
* Star Navigation

### Actual result

<details>
    <summary>Video</summary>

<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e37ed4c2-8bea-4823-a3dd-d77227272bf8"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>  

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>CarPlay Screen</th>
        <th>iPhone screen</th>
      </tr>
      <tr>
        <td valign=top><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/095ab88d-cdd1-492b-b180-0b8e0da6b283"  width="600" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/22c6ce87-0fa3-4e96-a6e2-8aeed6c05a43"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>  

### Expected result

* Generate turn arrows resources for CarPlay (the same as we do on iOS)
* * Include exit number
* Turn angle 

If generated resources won't work on CarPlay, inform @dmpr0
* Check why those two doesn't use `map_turn_roundabout_left` and `map_turn_roundabout_right`
* * Add few more resources

**Environment**
OsmAnd Version: 4.7.2.6
iOS version: 17.3
Device model: XS Max

**Comment by alex-osm** [comment]
We pass turn arrows as images. Entry point is `- (NSString *) imageNameForTurnType:(const std::shared_ptr<TurnType> &)turnType`

**Comment by dmpr0** [comment]
# Review 

<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d631c9f2-d83d-42ad-a695-16ad1412036c"  width="300" height="auto"/> 

- [ ] Round about turn arrows is missed
