### ISSUE TITLE
Direction arrows color is not adjusts to line color

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3492]
### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1c585824-addf-499d-b7f1-f67e1b70bb49"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1d8a9275-8ec8-4c9a-924f-af99c1a0e99c"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

### Expected result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Android</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1d8a9275-8ec8-4c9a-924f-af99c1a0e99c"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

**Environment**
OsmAnd Version: 4.7.2.6
iOS version: 17.3
Device model: XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/703

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3518

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3536
https://github.com/osmandapp/OsmAnd-core/pull/708

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3543

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Android</th>
        <th>iOS</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/69f24b65-d071-412c-92df-b69177172d0b"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/46c41433-dec2-4935-9f8b-af041e14a085"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [ ] Circle direction arrows should start to be drawn when Width < 9
