### ISSUE TITLE
French translation : missing space before « à »

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#3506]
In osmand 4.7.2.8, there is a missing space after the letter « à » in the following screens : 
Cartes & Ressources 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/74791b43-d0e3-4d1d-9733-9a63eef68056"  width="300" height="auto"/> </td>
  </tr>
</table>

« Misesà jour » should be « Mises à jour »

Paramètre -> any profile -> paramètres de guidage -> annonces vocales 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/0d0bf929-f306-4d5f-a457-58ddbba2f54b"  width="300" height="auto"/> </td>
  </tr>
</table>

« Favorisà proximité » should be « Favoris à proximité »
« POIà proximité » should be « POI à proximité »

Paramètre -> any profile -> paramètres de guidage -> personnaliser la ligne d’itinéraire

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/692f3afd-33e7-4caa-85ea-c114809cbee0"  width="300" height="auto"/> </td>
  </tr>
</table>

« Revenirà l’original » should be « Revenir à l’original »

Paramètre -> any profile -> Édition OpenStreetMap

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/85dcd2ac-2b07-4782-b39e-3118b834357b"  width="300" height="auto"/> </td>
  </tr>
</table>

« Misesà jour des cartes pour les contributeurs OSM » should be « Mises à jour des cartes pour les contributeurs OSM »

Paramètre -> any profile -> Édition OpenStreetMap -> Misesà jour des cartes pour les contributeurs OSM

same for the title and the label of the menu

the same issue may occurs in other places of the app

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback. 
We use Weblate for colaborative translations, you can change al mentioned places for example 
https://hosted.weblate.org/translate/osmand/ios/fr/?checksum=e4da514e2699a3e3
