### ISSUE TITLE
Reset to default for widget panel doesn't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3510]
### How to reproduce
* Open **OsmAnd**, switch to Driving profile
* Go to **Configure Screen** - **Right panel**
* Tap **Edit**, remove few widgets, tap **Done**
* Tap Menu in NavBar, select **Reset to default**

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Default state</th>
        <th>After editing</th>
        <th>After restoring</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/2100604e-a68b-4b9b-b064-30ea324c722f"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/bf250995-1b5e-45b9-850a-8e58a9d8e21b"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/286f7ba7-f055-4b3b-b3cb-cc7bb4a0e694"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

<details>
    <summary>Video</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/e2a0cb9f-0f66-4f0f-a192-98427cb4352e
"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

* Widget quantity remain the same

### Expected result

* Original list for widget would be restored

**Environment**
OsmAnd Version: 4.7.2.8
iOS version: 17.4
Device model: XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3602
