### ISSUE TITLE
Adopt user voice preferences

### ISSUE THREAD

**Issue by rachellawson** [osmandapp/OsmAnd-iOS#3511]
### Description

I have British Voice 3 (the slightly "generic northern” woman’s voice) selected in iOS 17.4 and that is automatically used in most apps but NOT in OsmAnd for some reason, where a man’s voice is used for navigation prompts.

### Steps to reproduce

Choose a voice in iOS other than the default, navigate and discover the voice doesn’t change in OsmAnd.

### Actual result

Voice is always the same voice, no matter what is chosen in iOS settings

### Expected result

Honour the iOS settings of voice to use.

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.6.1
iOS version: 17.4
Device model: 15 Pro
Crash-Logs: ?
```

**Comment by dmpr0** [comment]
# ToDo
User can select voice type and configure: speed, tembre, sentence pause. in iOS Settings – Accesibiblity Voice 

- [ ] Adopt all user voice preferences

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3669

**Comment by DmitrySvetlichny** [comment]
Currently, the AVSpeechSynthesizer API in iOS does not provide direct access to voice tone and pause length settings, which the user can configure in the system accessibility settings.
In order for an app to use custom tone and pause settings that iOS doesn't allow for direct control through the AVSpeechSynthesizer, the user will need to be able to configure these settings within the app and adjust them accordingly in the AVSpeechUtterance object.

**Comment by DmitrySvetlichny** [comment]
https://developer.apple.com/documentation/avfaudio/avspeechsynthesizer
https://developer.apple.com/documentation/avfaudio/avspeechutterance

**Comment by zipav** [comment]
OsmAnd TestFlight 4.7.6.2

The voice in OsmAnd voice prompts now matches the voice selected via steps:
iPhone > Accessibility > Spoken content

https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/0c6ea305-f75f-494b-af64-1b11cc8330d6

**Comment by dmpr0** [comment]
Docs:
* Voice should be selected in **iOS** – **Settings**  – **Accessibility** – **Spoken content** – **Voices**.
* Speaking rate should be changed on **Spoken content** screen, not on Voice screen.

**Comment by dmpr0** [comment]
@rachellawson Fixed, will be available in TestFlight build 4.7.7.1 version, https://testflight.apple.com/join/7poGNCKy

**Comment by rachellawson** [comment]
Ah great! I'll give it a try when that release turns up in my TestFlight!

**Comment by shurasmiling** [comment]
[Voice settings](https://osmand.net/docs/user/navigation/guidance/voice-navigation#tts-text-to-speech)
