### ISSUE TITLE
App crashed after started a navigation

### ISSUE THREAD

**Issue by LYHPandaKing** [osmandapp/OsmAnd-iOS#3534]
### Description
After started a navigation, app run normally for a while and crashed suddenly.

### How to reproduce
Open OsmAnd App
App pop up location permission > Only while using the App
Choose random places and start the navigation
Turn on simulate navigation
Wait for it to simulate

### Expected result
Normally finish whole navigation
App won't crash

### Environment
OsmAnd Version: 4.6.6.1
iOS version: 17.1
Device model: iPhone 12

### Extra
Log file: 
[3月 28, 2024 下午8:17.log](https://github.com/osmandapp/OsmAnd-iOS/files/14789539/3.28.2024.8.17.log)
[3月 29, 2024 下午12:50.log](https://github.com/osmandapp/OsmAnd-iOS/files/14799898/3.29.2024.12.50.log)

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced.  I attempted to reproduce the crash by choosing various destinations multiple times. Throughout the navigation simulation, the journey from beginning to end proceeded smoothly without any incidents.
Please test if you encounter these crashes on the TestFlight version: [link](https://osmand.net/docs/versions/nightly_versions#testflight).

OsmAnd TestFlight 4.7.3.1
iOS 16.4.1

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/fc10da0e-bfe1-4dac-8ce9-b0a6d40f869c"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/944d19a2-cb92-47b0-9bb8-d691a9089a4b"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by LYHPandaKing** [comment]
Thanks for reply. I have downloaded the TF ver and same problem happened again. I looked into the log file, the app crash after `OAAppDelegate applicationDidReceiveMemoryWarning` shown. I figured out that app crashed due to not enough memory.  But I still have at least 3GB space of storage in my IP12. Sadly, this problem made Osmand unusable on my phone.

When I try to search for solutions online, I find out that Osmand did offer "Memory Setting" for Android version but currently not for ios version. Hopefully this problem can be solved soon.
![250EB109-A3F0-42C4-8595-E7268C196F54](https://github.com/osmandapp/OsmAnd-iOS/assets/35364533/6259427c-4180-45d1-8c44-03ef2194e241)

**Comment by yuriiurshuliak** [comment]
Please attempt to use our TestFlight version, which incorporates the latest updates, and verify if the issue persists there. It's possible that the problem has already been resolved in this version. You can access the TestFlight version through this link: [TestFlight](https://testflight.apple.com/join/7poGNCKy)

**Comment by vshcherb** [comment]
Yes we didn't release it yet but new version will be not limited to memory during routing as much. So please consider TestFlight until it's fully released
