### ISSUE TITLE
New features not available

### ISSUE THREAD

**Issue by tatobox** [osmandapp/OsmAnd-iOS#3538]
In the current TestFlight 4.7.1.10 version some of the new features listed on the web page about the 4.7 iOS version are not available.
- Speedometer (no “Other” section)
- Track 3D visualization
- Round up numbers in navigation widget

See screenshots

iPad Pro 12.9 1st gen
iPadOS 16.7.5
TestFlight 4.7.1.10

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/ae243a96-4444-4c76-9eeb-9ef6e938798e)"  width="600" height="auto"/> </td>
  </tr>
<tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/aa73f4ed-e4e6-469a-a298-c680ae1df7c7)"  width="600" height="auto"/> </td>
  </tr>
<tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/31422681-8bec-4808-8949-1b7467eb34e6)"  width="600" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
Hi! Thank you for the feedback
**3D visualization** and **Distance during navigation** available in the latest 4.7.3.1 build.
Speedometer is a planned feature, but currently we are thinking about shifting to the 4.8 release.

**Comment by EugeneZmeuk** [comment]
I removed the "Speedometer" part from the article and rebuilt [the article](https://osmand.net/docs/versions/future-ios)
