### ISSUE TITLE
weather forecasts only work for 2 days

### ISSUE THREAD

**Issue by teox26** [osmandapp/OsmAnd-iOS#3540]
### Description

good morning, I would like to point out that the weather forecast only works for two days and not up to seven

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/165290566/6f266f5f-bc0d-4faa-939b-d97d73436dc4"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/165290566/1cf121cc-f8b6-4973-a4be-89a8282cadea"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd/assets/165290566/57cbd36a-65a8-481f-a59b-f5a76a49a71d"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

I simply activated the weather function but it only works on two days

### Actual result

two day weather forecast

### Expected result

seven day weather forecast

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.6.6.1
Android/iOS version: 17.3.1
Device model: iPhone 11
Crash-Logs: ?
```

**Comment by vshcherb** [comment]
Something similar was fixed 2 weeks ago, we need to check whether it's a release or testflight bug

**Comment by zipav** [comment]
OsmAnd TestFlight 4.7.3.2

On the latest version of TestFlight, it shows the entire week's weather forecast:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/c4a17d2e-a50e-41ed-b29e-a822c1f2f834"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/f3ecfa90-2ab2-4acc-a194-ff59866fe008"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/28669ef7-00dc-435f-8100-f064d9dd449b"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by vshcherb** [comment]
Already fixed looks like

**Comment by zipav** [comment]
OsmAnd Maps 4.6.6.1

It also not reproduced on the release version, shows the weather forecast for the whole week.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/3a832cdc-b35c-47eb-9ebc-6b6c4c251b5a"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/e2342efd-864e-490c-9f77-b2703eae488e"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/2cfcaa77-a817-43b0-b341-d95279e5b9a8"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by teox26** [comment]
On beta test work correctly, in standard versione doesn't work
