### ISSUE TITLE
Lag taping on Travel bookmark

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3542]
### How to reproduce
* Add article as bookmark
* Open **Menu** – **My Places** – **Travel**
* Tap on any bookmarked article

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/9559f672-853c-4fef-b92f-12244678c1e5
"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/8f391384-0314-483c-9a79-63ccdcc65df9
"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Lag

### Expected result

* Works without lag

**Environment**
OsmAnd Version: 4.7.3.1
iOS version: 17.4
Device model: XS Max

**Comment by dmpr0** [comment]
# Review
- [ ] More bookmarked article = loner time to open My Places > Travel

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/e7dd40c5198ae6f853637078bd9ec71613297c59
