### ISSUE TITLE
Disable automatic changing of map angle or zoom level

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3548]
### How to reproduce
* Change map tilt and orientation
* Go to map – tap on track

**Changing position**
* Hold and pull menu up
* Hold and pull menu down 

**Appearance**
* Tap **Appearance**

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Changing menu position</th>
        <th>Appearance</th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a8d02dd9-e99a-45ee-9db5-21daf7fe0558"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/a632fbfb-2702-4560-8c6f-7a403572ea42"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Map tilt / zoom level / orientation will be changed.

### Expected result

* Map tilt / zoom level / orientation will remain unchanged

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3581
