### ISSUE TITLE
Allow to add Waypoint if Track recording plugin is Off

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3549]
## ToDo
Currently, if the Trip recording plugin is off, user can't add a Waypoint to GPX track through context menu – actions. Add waypoint action is available only if the plugin is On. I propose to change this behavior.

- [x] Show **Add waypoint**  actions if plugin is off.

**Comment by vshcherb** [comment]
Why do we need it?
