### ISSUE TITLE
Sensor speed graph is missing

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3551]
### How to reproduce
* Import test track (recorded in Android) [HR-Cad-Speed-2024-04-01_14-20_Mon_SpeedFixed.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/14823580/HR-Cad-Speed-2024-04-01_14-20_Mon_SpeedFixed.gpx.zip)
* Go to **Track** – **Actions** – **Analyze on Map**
* Tap on Y-Axis (`Altitude / Slope`)

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d68e9bcb-685f-4f4a-a7fc-0951ba716c67"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/9df4660c-9fbd-4b3f-b787-d31dd819fa07"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* **Sensor speed** data isn't available as data type for graph axis

### Expected result

* **Sensor speed** data will be available as data type for graph axis

**Environment**
OsmAnd Version: 4.7.3.1
iOS version: 17.4.1
Device model: iPhone Xs Max

**Comment by DmitryAlexei** [comment]
Previous task https://github.com/osmandapp/OsmAnd-iOS/issues/3293

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3590
