### ISSUE TITLE
Allow to choose non-rotational icons for moving my location

### ISSUE THREAD

**Issue by kssi** [osmandapp/OsmAnd-iOS#3553]
### Version

OsmAnd 4.2.4 on iOS 15.6.1

### Problem

OsmAnd has (and has always had for as long as I can remember) a very hard time figuring out whether I'm standing still or not. This means that when I need the "Position icon at rest" the most, e.g. to know which direction my device is pointing toward, I will most likely get a barely usable "Position icon while moving" jiggling on the map. This happens in all conditions, even in open fields with strong GPS signal.

### Solution

I think this issue has been reported 4 years ago here: osmandapp/OsmAnd#6207, but it has yet to be solved.

In the meantime, it would be really nice to have a per-profile setting that allows one to disable _bearing_ arrows (aka. "Position icon while moving") altogether. Especially for those like me, who have always found this feature more troublesome than anything.

Please make it optional!

**Comment by limex** [comment]
this sounds promising!
But I'm afraid that they (again) only have motorists use cases in mind when solving the issue.
I mentioned my comment is this issue https://github.com/osmandapp/OsmAnd/issues/19230.

**Comment by vshcherb** [comment]
I think this issue was standing still for a while @kssi and recently being misused for another issue. 

I would like to close this topic as a for a problem mentioned in a topic start we don't have a solution. 
Arrow Icon is being displayed when speed > 0 reported by system. We can't hardcode any threshold as any practically low speed would make sense, so we can't filter locations. However it's possible to do once the track is recorded.

If you observe any other behavior than I described please mention.

**Comment by sonora** [comment]
It's a long running chipset issue also affecting several Android systems. I have investigated many times, but also failed to detect any reasonable way to fix this in an app.

**Comment by kssi** [comment]
@vshcherb why is it so difficult to get an answer on a feature request/workaround which was asked multiple times before: 

Can we please have an option to switch off entirely the "Position icon while moving"?

It **DOES NOT** mean "no icon" but simply have OsmAND keep showing the view direction of the device as explained by @syneoa [here](https://github.com/osmandapp/OsmAnd-iOS/issues/3553#issuecomment-2032380291).

**Comment by sonora** [comment]
Could perhaps simply under _Configure profile > Profile appearance > Position icon while moving_ also provide one of the 'neutral' ones from _Position icon at rest_ for selection... that may do the trick, not sure.

**Comment by sonora** [comment]
Bad wording on my behalf, I meant one of the isotropic ones.

**Comment by limex** [comment]
> Bad wording on my behalf, I meant one of the isotropic ones.

Why would you show an icon (like a static cycle or whatever) with no information at all, all the time? Please don't follow this path!

Listen: 
The original feature request (years ago stated and (I guess) still most important for most of us hikers (non motorists) is:

**Show the VIEW DIRECTION feature when no movement is detected.** 

Now: In the meantime we all know that there are fake movements that can't be filtered out. So instead: 

**Don't show MOVING icon at all, even in movement. Always show the view VIEW DIRECTION icon.**

Sorry for using bold, but it seems necessary to add a consensus about this feature. finally.

**Comment by sonora** [comment]
Think we're on the same page...  :wink: I was not talking about the viewing direction, but the movement icon. Simply: Under

![Screenshot_20240409-120646_OsmAnd~](https://github.com/osmandapp/OsmAnd-iOS/assets/845735/48085ad1-e891-4ab7-9676-ca748e3c55c3)

also offer one (or all) of these available for selection:

![Screenshot_20240409-120422_OsmAnd~](https://github.com/osmandapp/OsmAnd-iOS/assets/845735/97b5ced9-95e9-4170-bdf7-82197f3c5b52)

**Comment by limex** [comment]
@sonora Now we are really on the same page. Your suggestion is an EXTENSION to the "permanent viewing direction" feature.

**Comment by vshcherb** [comment]
> Show the VIEW DIRECTION feature when no movement is detected.

View direction represents device orientation and not the bearing.

Basically the request is to ignore bearing information on the map cause it  useless (by whatever reason).

**Comment by mnalis** [comment]
> Basically the request is to ignore bearing information on the map cause it useless (by whatever reason).

Yes, that is correct; thanks for reopening! 

BTW (seeing that this has been moved to OsmAnd-iOS) could we please have that option (_"ignore bearing"_) also in Android version?

**Comment by dmpr0** [comment]
## ToDo

> Android task https://github.com/osmandapp/OsmAnd-Issues/issues/2591

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/8cdde767-fb08-42fd-869e-4bd08e679c24"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/9f76bb5b-1436-442b-80ac-95926720024e"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/280f783d-7769-4e7e-8405-60a1d7e1260d"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c00d6776-c75a-4dc1-8db1-02559e306cbf"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/6b831c3f-ee2a-4a1d-98cc-4ba38d93febf"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review
- [ ] Separator height?
- [ ] Separator left padding is missed

**Comment by craigerl** [comment]
Yes, thank you.  I was backpacking this weekend and I couldn't tell which way I was facing on foot.   I had to estimate a bearing, then open GPS Essentials and use a working compass for navigation.   Getting rid of the "motion arrow" and forcing the use of compass-direction "cone" would make navigation easy and enjoyable.

**Comment by dmpr0** [comment]
# Review 

- [ ] Unable to change **Location radius** option
