### ISSUE TITLE
Vertical exaggeration – 3D Relief

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3560]
# Description 
Add UI for **Vertical exaggeration** option that should allow to upscale 3D relief.

> OpenGL Team task https://github.com/osmandapp/OsmAnd/issues/19443
> Android task https://github.com/osmandapp/OsmAnd/issues/19474

## Terrain

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Off</th>
        <th>On</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/56f61ab4-1921-497d-81bd-ffc1ede5bef0"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/540591f4-ecc0-46cb-b86f-303c44dbc36e"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

- [x] Add new item **Vertical exaggeration**
- - [x] Place below **3D Relief**
- - [x] Visible if **3D Relief** is on
- - [x] Icon – `ic_custom_terrain_scale`
- - [x] Show selected value on the right side
- - [x] Tap on item should open separate screen

## Vertical exaggeration
Separate screen to configure selected parameter, UI is similar to **Visibility** in **Terrain**.

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7790c357-97af-4ee1-a793-495a86f132e6"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Use slider to change parameter
- - [x] Available parameters: None / x1 / x2 / x3 
- - [x] Default – None
- [x] Add description – `By changing the scale value, you can emphasise the 3D relief.`
- [ ] Final formula for Track is ```((Alt - MinTrackAltitude) * TrackScale + MinTrackAltitude)*ReliefScale```

**Comment by wesleyverbruggen** [comment]
Would love to have this! I'm partaking in a trailrun race this May in an area with elevation between 200-800 meters. Being able to scale the 3D elevation would greatly enhance the ability to inspect the terrain and plan accordingly. Glad to see that this already got suggested. Thank you for making this platform better and better.

Something that comes to mind: would it make sense to add something like logarithmic scaling (scaling is larger for lower elevations than higher elevations)? That would obviously distort the relative elevations, but might be useful for plotting the elevation without obstructing the view. I have no clue how that would look, but maybe it looks better than we think. If it is not too, difficult, might be worth it to try and see.

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/aa752674-7126-42f9-aa07-9abdc9781468"  width="375" height="auto"/> </td>
  </tr>
</table>   

- [ ] If selected value = None, use `iconColorDefault` for icon color
