### ISSUE TITLE
Crash while downloading in the background

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3561]
* Log – [OsmAnd Maps-2024-04-04-140335.ips.zip](https://github.com/osmandapp/OsmAnd-iOS/files/14873768/OsmAnd.Maps-2024-04-04-140335.ips.zip)

**Comment by nnngrach** [comment]
Reprodused:

Opened all maps 
Clicked Update all to start updating 5-8 gb of maps.
Switch on map screen.
Open another app.
Wait a bit.
Crash occurs on returning to OsmAnd.

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3596

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3596/commits/d021891650dfa2974c6325f41ede3c54b7d847cf
