### ISSUE TITLE
Keep using location arrow icon while Driving in Snap to road mode

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#3564]
## To do: 
- [x] In snap to road mode (navigation) don't use circle (location at rest) icon and only use navigation
- [x] Use bearing from snapped road
```
if (bearingValid && (speedValid || isLocationSnappedToRoad())) {
				return hasBearing ? location.getBearing() : lastBearingCached;
			}
```

 Migrate this pull request to iOS https://github.com/osmandapp/OsmAnd/pull/19393

_Originally posted by @vshcherb in https://github.com/osmandapp/OsmAnd-iOS/issues/3553#issuecomment-2032380304_

**Comment by DmitryAlexei** [comment]
Related Android (OpenGL) task https://github.com/osmandapp/OsmAnd/issues/19706

**Comment by vshcherb** [comment]
I don't think it's related task probably another issue

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/44c21caff039e83dc881b912d0635bd0d6167aba

**Comment by dmpr0** [comment]
Done

<table style="width:100%">
  <tr>
    <th>With Navigation</th>
    <th>Without navigation</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/e90683d5-1013-430c-9866-93b161f47abb"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/97d62d8a-b390-4053-ac06-db23c57e3ba1"  width="300" height="auto"/> </td>
  </tr>
</table>
