### ISSUE TITLE
Invisible POI icons in Quick Action menu

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3567]
### How to reproduce
* Open **OsmAnd** - **Menu** – **Configure Screen** – **Quick action**
* Tap **Add** (+) in NavBar
* Add **Add POI** quick action

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1f44b61a-f9e6-43b4-a3e1-41b58190c855"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/868dc3a3-7e03-4448-a93f-2b47819e5845"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Icons invisible

### Expected result

* Visible icons

**Environment**
OsmAnd Version: 4.7.3.2
iOS version: 17.4.1
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3696
