### ISSUE TITLE
Zoom Search should vary for different objects

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#3569]
https://github.com/osmandapp/OsmAnd/issues/18901

**Implement algorithm**
- If search object could be visible with previous map center (before search) to extent of ZOOM - 2, then map just zooms out and center moves to search object. For example, my location is in center with zoom 16, nearby searched POI is in 300m but doesn't fit visible bbox of zoom 16 and fits bbox on zoom 14 so both my location and searched POI is visble.
- In all other cases when zoom out doesn't help to see previous map center and search POI default constants are used: 
   - POI / Building - 16
   - Street - 15
   - City - 14

**Comment by dmpr0** [comment]
## Review 
### Search for City

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Before search</th>
        <th>After search</th>
        <th>Video</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7af07dfd-39a9-48f3-bb24-39a7132a432d"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/694247ee-9c78-4e79-a05e-a1abec94f715"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/0de2c5ba-0eab-44cb-9acd-f0aa499b439a"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Expected: - 14
* Actual – 15
