### ISSUE TITLE
Direction from is lost if Navigation UI is closed

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3570]
## Description
WIP

### How to reproduce
* Select any point on the map, open context menu
* Tap **Actions** – **Direction from**

### Actual result

* When Navigation menu is closed, **Direction from** point is removed

### Expected result

* Direction from point stays on the map, allowing user to set Destinations.
* See how Android works

**Environment**
OsmAnd Version: 4.7.3.2
iOS version: 17.4.1
Device model: iPhone XS Max

**Comment by vshcherb** [comment]
Android point is stored for the app running (not in settings) however if you select target point for navigation then start point should be used for that route.

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.1.4927` - Fixed

The only difference from the behavior in Android is that in Android, the “Direction from” point as the starting point is saved only once for the next navigation, after closing the menu for selecting this point.
In iOS, the “Direction from” point is saved for all subsequent times until the starting point is changed manually (even restarting the application does not help to “cancel” the selected “Direction from” point)

**So, if we want to do it like in Android, then it needs to be finalized.**

**Comment by Zirochkabila** [comment]
# Testing 2
`4.9.1.4928` - Fixed
