### ISSUE TITLE
All shields background icons is missed

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3573]
## Description

<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/f6710b21-7822-4a6e-838c-694c634f0716"  width="300" height="auto"/> 

### How to reproduce
* Open OsmAnd
* Find any icon on the map

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
        <th>Android</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4b134e87-3ec1-4a1c-90c4-694f6a53d8e9"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/18e2c121-da86-4d1c-ac27-dcbbaf7159fe"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Road shields background icons is missed

### Expected result

* Road shields should be visible

**Environment**
OsmAnd Version: 4.7.3.3
iOS version: 17.4.1
Device model: iPhone XS Max

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/2e3fd0a0bddd95d6df0a34b17579f3fa801311d3
