### ISSUE TITLE
Missing tertiary turn arrow

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3574]
## Description

> Backend task https://github.com/osmandapp/OsmAnd/issues/19441#issuecomment-2042192064
> https://test.osmand.net/map/?start=43.141352,6.003782&end=43.142434,6.010696&profile=car#19/43.14269/6.00954

### How to reproduce
* Build a Car route from: `43.14135, 6.00378` to `43.14253 6.01055`. Destination should be placed into one of the middle road.
* Start navigation simulation

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Android</th>
        <th>iOS</th>
      </tr>
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7c84e353-085c-4150-96d3-bfb5c8f82f34"  width="300" height="auto"/> </td>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/23fa65a8-a2d0-45e4-a604-0c9f76eee1f4"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

<details>
    <summary>Video</summary>
    <table style="width:100%">
      <tr>
        <th>Android</th>
        <th>iOS</th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/cdda4538-2a58-456a-9ab5-c010279d3ad6"  width="300" height="auto"/> </td>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/070b513d-d06a-44e8-af15-58ad2c7d8d18"  width="300" height="auto"/> </td>
      </tr>
    </table>   
</details>   

* Tertiary turn arrow: `Turn right (+TR,C,TSLR)` is missed 

### Expected result

* Visible `Turn right (+TR,C,TSLR)` arrow

**Environment**
OsmAnd Version: 4.7.3.3
iOS version: 17.4.1
Device model: iPhone XS MAx

**Comment by DmitrySvetlichny** [comment]
https://github.com/user-attachments/assets/148e74d9-a563-4799-8723-976c3c26c9be
