### ISSUE TITLE
Bug during a boat trip

### ISSUE THREAD

**Issue by ApoMet** [osmandapp/OsmAnd-iOS#3588]
Doing a trip by boat the distance was 29.3 km and with an average speed of 15 km/h the program estimated a trip duration of 6 hours (8:47 current time, arrival at 14:40). Please look into it. I attach a screenshot!

<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/167064987/bd9c1ab8-77ad-49b9-89b7-e6b1ffb68a71"  width="300" height="auto"/>

**Comment by zipav** [comment]
OsmAnd TestFlight 4.7.3.9

Reproduced. The 29.8 km route calculates arrival time at 21:33, route calculation time 15:39 local time.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/5323d85b-164f-4e41-ae1f-67a097772121"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by zipav** [comment]
@ApoMet We have discussed this situation with the team again, please note that the Default speed parameter affects the route time, the default value of this parameter is 3 nautical miles per hour (about 5.5 km per hour), as the Default speed parameter value increases the estimated time of arrival decreases.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/06f1c3df-b45f-48b1-9039-c164bdc44916"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/6d70d7cd-3a5d-40c1-a9ae-e957ca0b2fc3"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by ApoMet** [comment]
So it calculates the time using the default speed and not the real speed? Ok. Thanks. It is not so important. I didn’t know!

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zipav** [comment]
OsmAnd TestFlight 4.7.3.10

When Default speed 15 km/h is set, the route time is 1h 52 min.


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/123936521/36667032-c971-408b-92bb-479090e9d0c3"  width="300" height="auto"/> </th>
  </tr>
</table>
