### ISSUE TITLE
Crashes 4.7

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-iOS#3599]
- [x] OsmAnd Maps: _dispatch_once(long*, void () block_pointer) + 16
- [x] OsmAnd Maps: SkISize::width() const
- [x] OsmAnd Maps: OsmAnd::GpxAdditionalIconsProvider::buildStartFinishSymbolsGroup
- [x] `cachedArticles` crashes because of concurrency

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/0b8dfdf3f43be4c4d99ce75e764cff2f5bcf70fc

**Comment by alex-osm** [comment]
Address lookup crash - https://github.com/osmandapp/OsmAnd-iOS/commit/bbf6de8b2206475e7a04bb7c710ca398c848492a

**Comment by alex-osm** [comment]
Fix buildActionArrows - https://github.com/osmandapp/OsmAnd-iOS/commit/ed44fab193011964ff3a638183cd5ab5c1f51bec

**Comment by alex-osm** [comment]
Fix getPairAt - https://github.com/osmandapp/OsmAnd-iOS/commit/35a89716c4188187f7c4faf1c3187fdb56e9dfa6

**Comment by alex-osm** [comment]
Fix getGroupElementCellForRowAtIndexPath - https://github.com/osmandapp/OsmAnd-iOS/commit/7c9cfa266ecfe71b533d9cd3afe54ea112f91757

**Comment by alex-osm** [comment]
Fix OAOsmEditsLayer getIcon - https://github.com/osmandapp/OsmAnd-iOS/commit/f3ad27b1ed537c4e6fa2e17fc05eedbf7cd1398d

**Comment by alex-osm** [comment]
Fix retain cycles / observers - https://github.com/osmandapp/OsmAnd-iOS/commit/d5c0a8b6626536c73cb908d8ecd8a133d12df346

**Comment by alex-osm** [comment]
Fix cachedArticles - https://github.com/osmandapp/OsmAnd-iOS/commit/fac3670990b8dad27ed752f76f218d9e18c6fe1e
