### ISSUE TITLE
Canceling navigation from any profile returns to the default profile

### ISSUE THREAD

**Issue by tatobox** [osmandapp/OsmAnd-iOS#3603]
# Description
My default profile is Car.
If I start from any profile (Bike, Cycle,...) and cancel the navigation the result is to return me to the default profile.

### How to reproduce
Go to any profile other than the default one
Go to Navigation
Cancel Navigation

### Actual result
<details>
<summary>Screenshoot</summary>
<table style="width:100%">
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/153958793/3925b84e-ea74-4866-b19c-abf94017c21f"  width="600" height="auto"/> </td>
  </tr>
</table>
</details>

It goes to the default profile

### Expected result
It remains in the selected profile

__My device__
iPad Pro 12.9 1st (ML0N2TY/A)
iPadOS 16.7.7
TestFlight 4.7.3.7

**Comment by dmpr0** [comment]
Hi! You can change this behavior by changing **Default profile** to **Last used**.

**Comment by vshcherb** [comment]
Yes, it's designed behavior that default profile is always used after navigation
