### ISSUE TITLE
Wrong profile name is shown on Cloud changes

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3605]
### How to reproduce
* Login to OsmAnd Cloud on Device 1, upload all changes
* Login on second Device 2, make changes in profile settings, upload them
* Sync changes on Device 1

### Actual result
<table style="width:100%">
  <tr>
    <th>Local</th>
    <th>Cloud</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/7b411c9d-6348-49d0-9ab5-c0a274d23460"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/639ccb61-2887-4fd5-8cb8-2313c8d1c32f"  width="300" height="auto"/> </td>
  </tr>
</table>   

* `Profile_Bicycle` is shown instead of **Cycling**

### Expected result

** Cycling should be shown on both tabs

**Environment**
OsmAnd Version: 4.7.3.8
iOS version: 17.4.1
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3646
