### ISSUE TITLE
Compass is broken

### ISSUE THREAD

**Issue by valynor** [osmandapp/OsmAnd-iOS#3614]
Just installed 4.7 on iPad Mini 5 and iPhone 13 Pro Max, IOS 17.4.1: 
on both devices the compass related functions are now completely inoperable. (Organic Maps & Apple Maps still work fine)

The "location dot viewing angle thingy" alway points north and with the map orientation in "compass view" the map does not rotate with you at all when you turn around.

**Comment by kevinp2** [comment]
I can confirm this behavior.  I wonder if it is related in some way to changes made to Map orientation in general.  See [Issue 19626](https://github.com/osmandapp/OsmAnd/issues/19626)
