### ISSUE TITLE
Impossible to use  ‘ in POI search

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-ios#362]
Names with  ‘  symbol cannot be searched.

**Comment by vshcherb** [comment]
![image](https://user-images.githubusercontent.com/1042025/61665816-4dd08200-acd6-11e9-9c0f-9ff58498a966.png)
Something is wrong comparing to Android

**Comment by PaulStets** [comment]
Not sure what the problem is. Perhaps we need specific cases when the search with the ' symbol doesn't work.
![image](https://user-images.githubusercontent.com/20681525/61693118-a8e69100-ad37-11e9-9db5-a846ac44e185.png)

**Comment by crimean** [comment]
Check with ‘

**Comment by PaulStets** [comment]
Checked POI search with ‘. Everything works as expected.
![IMG_0202](https://user-images.githubusercontent.com/20681525/63944921-290cbe80-ca7b-11e9-857b-d9ef7edcc050.jpg)
![IMG_0204](https://user-images.githubusercontent.com/20681525/63944922-29a55500-ca7b-11e9-92aa-5280065c90aa.jpg)
