### ISSUE TITLE
Pinch to zoom up to 25 zoom level

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#3625]
iPhone 13 mini, OsmAnd TestFlight 4.7.3.10, iOS 17.4.1

In Berlin, there is a possibility to zoom in up to 25 zoom level using pinch to zoom. Using -+ buttons you can only zoom up to 22 level.

Steps to reproduce
- go to Berlin (for me, issue appears when Germany-Brandenburg, Berlin map downloaded, I also have >100 other maps), terrain map disabled
- zoom in using pinch to zoom
- issue doesn't depend on used profile ([Browse map.osf.txt](https://github.com/osmandapp/OsmAnd-iOS/files/15061749/Browse.map.osf.txt) profile)

Actual result
- on the video you can see, that using pinch to zoom, the zoom level can be increased up to 25 zoom level. When using - + buttons, the zoom level can be increased only to 22 zoom.
- issue cannot be reproduced on iPhone 6s, iOS 15.7.7, and iPad (6th generation), iPad OS 17.2

https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/a88615d4-dcb4-408a-8ad2-2f48c8f6073d

**Comment by dmpr0** [comment]
## Review
- [ ] Todo is missed

**Comment by vshcherb** [comment]
- [ ] Spelling of missing is wrong
