### ISSUE TITLE
Favorites background is bigger than icon on external Full HD screen – Mac OS

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3641]
### How to reproduce
* Launch OsmAnd on Mac OS
* Add favorite point

### Actual result

<table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4f7398bb-5c13-4776-9e41-ea243e4a7357)"  width="600" height="auto"/> </td>
      </tr>
</table>

### Expected result
* Normal size icons

**Environment**
OsmAnd Version: 4.7.4.1
Mac OS version: 14.2.1 (23C71)
Device model: M1 with **Full HD** monitor

**Comment by dmpr0** [comment]
## Review


<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/67d30a8f-1e40-4a7e-9834-681972126a23"  width="600" height="auto"/> </td>
  </tr>
</table>   

- [ ] Fix icon sizes too, they looks bigger than any other icons

**Comment by Skalii** [comment]
- [ ] fix marker icons size;
- [ ] fix gpx start/finish icons size;
- [ ] fix avoid icons size;
