### ISSUE TITLE
Compass orientation not working on iOS

### ISSUE THREAD

**Issue by pixtur** [osmandapp/OsmAnd-iOS#3644]
Version: 4.7.3.10
iOS 16.7.7
iphoneX

I assume that the blue view region should update when I rotate the phone in my hand (at least this is what I expect from an indicator like this and how it works in Apple Maps and Google maps). On OSMAnd it always points north. This is even worse than showing no view indication at all.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/1732545/5c3257fc-136c-46ef-aebb-4dc952786f3c"  width="300" height="auto"/> </th>
  </tr>
</table>

I assume this is an issue with the magnetometer API. 

a quick side note: I personally find the user interface of OSMAnd bewilderingly complex. I now have used it more or less non stop for two weeks and I can still not remember the differences between map profiles, map configuration and app settings. I always thought myself to be somewhat of an app and maps nerd. But your app sure has the most complex UI I have ever seen in a mobile app. I can see why you need all those settings but I can also see that it makes the UI clunky, crowded and confusing. (Eg no other map still uses extra buttons for zoom in/out). So pinch zooming should be the default. Yet there is an option to show horse tracks but not to simplify the ui by hiding “legacy” features like this. Maybe that’s just an issue with the defaults. Or maybe it’s just me.

**Comment by vshcherb** [comment]
Yes, I think it's a bug in 4.7.3 release, we've already sent for review TestFlight Externals and Release 4.7.4 to get this fixed

**Comment by dmpr0** [comment]
Currently available thru TestFlight https://testflight.apple.com/join/7poGNCKy
