### ISSUE TITLE
OSMAnd crashes upon startup and won't open at all

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd-iOS#3650]
I have the latest version of OSMAnd iOS as of the moment.

It was working fine yesterday.  This morning, I opened the app when I was in a hotel elevator, possibly a poor Internet connection there.

The app crashed upon startup and since then simply won't open at all.  It crashes upon startup every single time.

I have rebooted the phone, closed other apps, made sure I have good Internet access, all to no avail.  It's basically unusable now. 

Any ideas?  Perhaps there was some network access upon startup that failed and left the app in an unusable state?

**Comment by vshcherb** [comment]
Did you have latest update? Latest testflight? What version if you remember

**Comment by kevinp2** [comment]
OSMAnd 4.7, installed through the App Store.

**Comment by kevinp2** [comment]
Same version as the one in which I reported this issue:

https://github.com/osmandapp/OsmAnd-iOS/issues/3617

**Comment by vshcherb** [comment]
We're are just waiting for approve for 4.7.4 which fixes very annoying  crash and you linked to 4.7.3

**Comment by vshcherb** [comment]
4.7.4 is available in testflight though https://testflight.apple.com/join/7poGNCKy

**Comment by kevinp2** [comment]
Not sure, then.  The App Store version history shows only 4.7, but perhaps a new version came through and I didn’t notice.

![image](https://github.com/osmandapp/OsmAnd-iOS/assets/609677/bf8886c6-60d2-4c64-820b-5c467fa41073)

**Comment by vshcherb** [comment]
just got reviewed & released today... let's see how fast it comes

**Comment by kevinp2** [comment]
Thank you for the super quick response!

**Comment by kevinp2** [comment]
I saw OSMAnd 4.7.4 in the app store this morning and updated it.  

Unfortunately, the same behavior:  the app crashes upon startup immediately, even after rebooting the phone.

Should I try to reinstall it?

**Comment by vshcherb** [comment]
Yes please try to reinstall and if possible share the crash with description if iOS suggested

**Comment by kevinp2** [comment]
OK, I did this:
1. Deleted the app, keeping the subscription.
2. Rebooted the phone for good luck.
3. App opened but without any settings, etc. I don't think I had a backup, so will have to recreate them all by hand, sigh.

Will report back on app stability over the next few days.

**Comment by vshcherb** [comment]
Let's keep watching
