### ISSUE TITLE
Move "Location position on screen" to Configure Screen

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3652]
## Description 

As part of unification and preparing for #2627, this task should be done. Android task https://github.com/osmandapp/OsmAnd-Issues/issues/2302

> Part of the "Speedometer #2627" task
> 1. https://github.com/osmandapp/OsmAnd-iOS/issues/3652
> 2. https://github.com/osmandapp/OsmAnd-iOS/issues/3664
> 3. https://github.com/osmandapp/OsmAnd-iOS/issues/2627

### Configure Screen
<details>
    <summary>Screenshot</summary>
<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4e1c05ed-7f7b-4cac-b7e7-d8f603a79764"  width="300" height="auto"/> </td>
  </tr>
</table>  
</details>  

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4e1c05ed-7f7b-4cac-b7e7-d8f603a79764"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new group **Other**
- - [x] Place below group **Buttons**
- [x] Move **Distance by tap** into Other group
- [x] Move **Display position** from **General settings** to **Other** group

### Location position on screen
We need to redo the bottom sheet using new half screen modal view, it looks and works better both on small and big screens.

<table style="width:100%">
  <tr>
    <th>Automatic</th>
    <th>Bottom</th>
    <th>Centre</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/c0af565c-7a05-4705-9120-a036a8f7f7f5"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/fae7055b-955c-49f4-9c3e-dd3d255d0a71"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/20126049-df8e-4f36-89b1-ff6e4045ef82"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Use new half screen modal view, similar to **Application theme** option
- [x] Add description to the footer if **Automatic** is selected.
- - [x] Description – `display_position_automatic_descr`

### Additionally 
- [x] Use icons from Assets, remove old raster versions
- - [x] **ic_action_ruler_line** for **Distance by tap**
- - [x] `ic_custom_display_position_automatic`, `ic_custom_display_position_bottom`, `ic_custom_display_position_center` for **Location position on screen**

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3684

**Comment by shurasmiling** [comment]
- [*General settings → Appearance*](https://osmand.net/docs/user/personal/profiles#appearance)
- [*Configure screen → Buttons*](https://osmand.net/docs/user/widgets/configure-screen#buttons)
- [*Configure screen → Other*](https://osmand.net/docs/user/widgets/configure-screen#other)
