### ISSUE TITLE
No Download Map or Update Map action available from context menu

### ISSUE THREAD

**Issue by StC-OSM** [osmandapp/OsmAnd-iOS#3657]
With iOS 17.4.1 / OsmAnd 4.7.4, when I long tap on the map then press the Actions button I find no action to download or update maps. See below. Same on iOS 15.4.1 / OsmAnd 4.0.5. Unfortunately I can't say when the problem has appeared. It works OK on Android.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/100076956/dfab8d7c-ed96-4510-9c9e-b9f8720c7e1f"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by StC-OSM** [comment]
> If you would like to download or update an online map, this map should be enabled as a map source. Go to menu > configure map > map type > online maps

Yes, thank you. This was tested on three different iPhones, three different OsmAnd versions, three different online maps with no overlay or underlay activated. Another French user reported the same problem too.

After more exploration, it seems that the problem is random (or rather, triggered by unknown causes). I rotated between 3/4 different online maps and was able to come back to working conditions, including with the original online map. Then the Download/Update map actions have disappeared again. In some cases, they were back, but other actions actions have disappeared. See below for examples.
![IMG_2285](https://github.com/osmandapp/OsmAnd-iOS/assets/100076956/b4c8705a-3239-4bdd-af34-4f0112e4b5df)
![IMG_2284](https://github.com/osmandapp/OsmAnd-iOS/assets/100076956/f1b9e2a4-73ee-484a-a78f-86a83b1a8b0b)

**Comment by pbalyx** [comment]
For personal reasons (not only SPO - Stop Programmed Obsolescence) I use a rather old version of OSMAnd 
OsMAnd 4.0 .7 Android 5.1.1. But online card download worked fine up to now.
I tried today using exactly the same methods and nothing works 
Online Map OSM vector maps, I tried to load a french department. I got the button "Bouches du Rhône" but nothing happens when I click
Online map OpenTopoMap, Long press in the center of a small zone, -> action/download map -> zoom choice -> even with a very low zoom (less than one Mo) nothing happens.
I insist, all this worked fine a few weeks ago.

**Comment by DmitryAlexei** [comment]
@pbalyx there was a different issue for android https://github.com/osmandapp/OsmAnd/issues/19575
it is already fixed in OsmAnd 4.7.10 from Google play. Please try if it is working for you and provide your feedback.

**Comment by DmitryAlexei** [comment]
@StC-OSM if you enable the OpenStreetMap Editing Plugin (go to menu > plugins), you will have more actions in the context menu. 
For your first device (with white context menu) you can also try to update OsmAnd to the latest version and reset profile settings (go to menu > settings > profile > reset to default)

**Comment by pbalyx** [comment]
"Version 4.7.10 (471003) - Ajouté le Apr 24, 2024
Cette version nécessite Android 6.0 ou ultérieur. "

As I said before, I use a phone with Android 5.1.1 which was very efficient up to now. So what can I do ? Put it in the garbage can ?   :(

**Comment by StC-OSM** [comment]
> @StC-OSM if you enable the OpenStreetMap Editing Plugin (go to menu > plugins), you will have more actions in the context menu.

Thanks, this probably explains why some actions are missing in some of my tests.

Coming back to the missing Download/Update actions, if I narrow the conditions of occurence of the bug are you interested in looking into it?  I have found when the actions disappear and how to make them come back on all three versions of OsmAnd-iOS that I use, so I can live with it now.

**Comment by DmitryAlexei** [comment]
@StC-OSM Yes, please. I am interested in your observations.

**Comment by dmpr0** [comment]
**Download** / **Update** actions are present if online tiles map is selected as **Map source**, if it selected as **Overlay** or **Underlay** the actions not available. 
Android was a task to add this functionality to Overlay / Underlay.

**Comment by StC-OSM** [comment]
I am a bit lost. I spend more and more efforts characterizing the precise conditions of occurence of the problem, and I keep receiving comments that suggest that the basic conditions for the proper behaviour are not met. So I'll say it again: yes, I am only talking about online map sources, and yes there is no overlay or underlay activated.

**Comment by DmitryAlexei** [comment]
@StC-OSM I didn't manage to reproduce the issue using provided steps on OsmAnd TestFlight 4.7.6.1:
- I switched from the profile with offline maps to another profile with online maps
- as you can see in the context menu, there is an option to download map data

https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/84f6eb09-c848-4348-9f37-5eebdc36137c

**Comment by StC-OSM** [comment]
Interesting. Meanwhile I had the opportunity to test this on a fourth iPhone with yet another OsmAnd version, and the results are consistent with my previous results.

I'll try to produce a video, but apart from sharing my observations there is only a low probability that it will help find why I can reproduce the issue and you cannot.  Maybe we need other testers to try and find a pattern?

**Comment by DmitryAlexei** [comment]
Video of the issue from your or anyone else's side would help developers to find and fix that bug.
Please try to reproduce it on the latest available in the App Store OsmAnd version. The bug could be fixed with the new release.

**Comment by StC-OSM** [comment]
https://github.com/osmandapp/OsmAnd-iOS/assets/100076956/cb675de6-411a-4ea5-9218-29973cc9408d

version 4.7.5.5

**Comment by DmitryAlexei** [comment]
OsmAnd TestFlight 4.7.6.3 
- download map option now works as expected

When testing found a bug partially related to that issue:
Multiple copies of the Configure map screen can be opened by misclick on iPhone 13 mini. To close the initial configure map screen, the app should be restarted.
### Steps to reproduce:
- open POI context menu
- open Configure map menu by tapping profile icon 
- tap slightly bellow Configure map header with the back button where the profile icon partially visible (see video)

### Actual result
- back button in the header closes only the second Configure map screen
- I didn't manage to close the first Configure map screen 
- once app crashed (see crash log)

[OsmAnd Maps-2024-05-23-215527.ips.txt](https://github.com/osmandapp/OsmAnd-iOS/files/15421628/OsmAnd.Maps-2024-05-23-215527.ips.txt)

https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/71986294-6229-4ba4-9846-05c1ab83c7b9

**Comment by dmpr0** [comment]
## ToDo

- [ ] Tap on any UI button with open context menu, should close the context menu
