### ISSUE TITLE
OsmAnd crashes when starting

### ISSUE THREAD

**Issue by jmendys** [osmandapp/OsmAnd-ios#366]
I was trying to use OsmAnd free and paid version on both iOS (iPhone 7S 64GB) and Android (Samsung Galaxy xCover4). In both cases, the app is unusable as it constantly crashes after startup.

On iOS it opens, loads maps then after 3-15 seconds crash!
On Android is crashes even before it opens. 

I am happy to provide more information if you only guide me on how to get it for you.

Thanks,

Jakub

**Comment by vshcherb** [comment]
Are we talking about versions which are in Google Play or the version that are manually built?

**Comment by jmendys** [comment]
Both versions were from Apple Store and Google Play

**Comment by jeremycherfas** [comment]
I just downloaded the version for iPhone (6+) from the App Store and paid for the first full year immediately. I have exactly the same problem. App crashes within minutes of opening, over and over again.

I'm a bit surprised, honestly.

**Comment by max-klaus** [comment]
@jeremycherfas sorry for the issue. Could you please tell how much maps did you install and what approx lat/lon/zoom of the place on map when app crashes? Do you use contour line / hillshade maps? Are they active? Also it would be good if you will share analytics with us, so we can see crash logs from your device. [https://support.apple.com/en-us/HT202100](url) Turn on Share With App Developers.

**Comment by jmendys** [comment]
It was already crashing without any map downloaded (using online maps only). It is crashing regardless of location or zoom and regardless if contour line / hillshades are used / active or not. 
I've turned on sharing analytics so hopefully you can get more info.

**Comment by jeremycherfas** [comment]
@max-klaus Global overview map and Lazio Italy (my home region) were downloaded automatically. I am not using contours or hillshading. Crash seems to happen after about 20 seconds, no matter what I am doing. Analytics is being shared.

I noticed also that when I press Home twice, to see all open apps after the crash, OsmAnd is still present with the purchasing screen visible.

**Comment by max-klaus** [comment]
Some issues related to app stability were fixed. Such crash should be fixed as well in the next release or testflight build. I am closing it now, but if you will face it again - please reopen the issue.
