### ISSUE TITLE
Separate "Speed limit" screen alert

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3664]
## Description 
We need to add separate control or **Speed limit** screen alert, currently it is part of **Traffic warnings** screen alert

> Part of the "Speedometer #2627" task
> 1. https://github.com/osmandapp/OsmAnd-iOS/issues/3652
> 2. https://github.com/osmandapp/OsmAnd-iOS/issues/3664
> 3. https://github.com/osmandapp/OsmAnd-iOS/issues/2627

## Screen alerts – Navigation settings 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/69958195-8dbd-4e8f-b5b4-e74e3c744b45"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] Add separate item –  **Speed limit**
- - [x] Regular icon – `list_warnings_limit`
- - [x] For USA region, – `list_warnings_speed_limit_us`
- - [x] For Canada region  – `list_warnings_speed_limit_ca`
- - [x] Turn off by default

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th>Speed limit</th>
    <th>Speed limit + Traffic warning</th>
  </tr>
  <tr>
    <td><video src=""  width="300" height="auto"/> </td>
    <td><video src=""  width="300" height="auto"/> </td>
  </tr>
</table>   

Uploading Speed+Traffic.mov…



- [ ] Doesn't work if Traffic warnings alert is disable.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3758

**Comment by shurasmiling** [comment]
https://github.com/osmandapp/OsmAnd/issues/13413#issuecomment-1952430864

**Comment by shurasmiling** [comment]
- https://osmand.net/docs/user/navigation/guidance/navigation-settings#screen-alerts
- https://osmand.net/docs/user/widgets/nav-widgets/#alert-widget
