### ISSUE TITLE
Speedometer widget – CarPlay

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3668]
## Description
Show speedometer from #2627 on CarPlay screen.

> Should be done in the following order:
> 1. https://github.com/osmandapp/OsmAnd-iOS/issues/3652
> 2. https://github.com/osmandapp/OsmAnd-iOS/issues/3664
> 3. https://github.com/osmandapp/OsmAnd-iOS/issues/2627
> 4. https://github.com/osmandapp/OsmAnd-iOS/issues/3668

## CarPlay

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/fdad0249-4c68-49d4-a03c-9f0bb6b9199e"  width="400" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/cebe695a-0477-4fd2-9987-65d5479a6c9b"  width="400" height="auto"/> </td>
  </tr>
</table>   

### Appearance:

<table style="width:100%">
  <tr>
    <th>Left</th>
    <th>Right</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/63554f15-1884-4a3d-b6a9-65f574ff2837"  width="auto" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/120fc868-d518-4dbe-bea5-e53aaa296797"  width="auto" height="auto"/> </td>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/cb3dc3af-5471-4a4a-b3a5-6532c5b8c448"  width="auto" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/0c667f88-3af5-4cb0-8380-c272a9a5e221"  width="auto" height="auto"/> </td>
  </tr>
</table>   

- [x] Widget theme should depend on CarPlay theme (not App MapMode)
- [x] Text align in Speedometer
- - [x] Screen side – Left, to the left side
- - [x] Screen side – Right, to the right side

**Speedometer:**
- [x] Background color – `widgetBgColor`
- [x] Stroke – `widgetAutoBgStrokeColor`
- - [x] Stroke should be outside main frame, in light appearance it has opacity 15%.
- [x] Value (current speed) – `widgetValueColor`
- [x] Units – `widgetUnitsColor`

**Visibility and placement**
- [x] Visibility of widget should be profile depend and depend on main Speedometer switch in Configure Screen.
- [x] Screen side left or right should depend on placement of Main navigation widget.

**Comment by dmpr0** [comment]
## Review 

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/3bc22718-2abd-4e4f-b1ce-6336b6c16464"  width="300" height="auto"/> </td>
 <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/b24d1af4-d02e-441d-a3b1-15f87e6412a6"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] Stroke should be drawn as shape below main shape to

**Comment by shurasmiling** [comment]
1. [Speedometer widget](https://osmand.net/docs/user/navigation/car-play/#speedometer)
2. [speed-limit](https://osmand.net/docs/user/navigation/guidance/voice-navigation/#speed-limit)
3. [speedometer info widget](https://osmand.net/docs/user/widgets/info-widgets#speedometer)
