### ISSUE TITLE
Adding POI - website label : disable autocorrect and maj first letter

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#3671]
Hi, when I try to fill the website label of the adding POI UI, the keyboard automatically add higher case for first letter and try to autocorrect. Should be disable

<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/97a5092e-c00b-4d59-adef-f8ce47e6c134"  width="300" height="auto"/> 

**Environment**
OsmAnd Version: 4.7.4
iOS version: 17.4.1
Device model: iPhone 14 Pro

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.  When editing a POI and adding a website in the contacts section, the suggested behavior is to enter the name in capital letters. However, this issue can be resolved by switching the keyboard from uppercase to lowercase and disabling autocorrect.

OsmAnd TestFlight 4.7.5.5

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/050ca2dc-e05d-4356-8d68-9bbe8edda26d

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3713

**Comment by nabilys** [comment]
Same problem by putting the name of POI
![IMG_0042](https://github.com/osmandapp/OsmAnd-iOS/assets/59312735/d9946930-1674-43ce-8724-534a15ec5d22)

**Comment by dmpr0** [comment]
@nabilys 

Try to disable Auto-correction in iOS settings https://support.apple.com/en-in/104995
