### ISSUE TITLE
Open on map button doesn't work – Travel guides

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3672]
### How to reproduce
* Open **Menu** – **Travel guides**
* Download file for Europe
* Search for **Berlin**, scroll to **See** section

### Actual result

<details>
    <summary>Video</summary>
    <table style="width:100%">
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/d013ce9f-e7b4-4cf2-b9bd-9f99dba2368f
"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

* Taping on **Open Map** button doesn't do anything

### Expected result

* Transition to map screen with context menu

**Environment**

OsmAnd Version:
iOS version: 17.4.1
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3676
