### ISSUE TITLE
build ios app show error in BRCybertron

### ISSUE THREAD

**Issue by A00001111** [osmandapp/OsmAnd-iOS#3673]
i did everything in [https://osmand.net/docs/technical/build-osmand/how-to-compile-the-ios-version/](url)
when build ios version using Xcode show me this error
`/Users/.../osmAnd/ios/Pods/BRCybertron/libxslt/libxslt/extensions.c:2287:37 Incompatible function pointer types passing 'void (void *, void *, xmlChar *)' (aka 'void (void *, void *, unsigned char *)') to parameter of type 'xmlHashScanner' (aka 'void (*)(void *, void *, const unsigned char *)')
`
on this line
`xmlHashScan(xsltModuleHash, xsltHashScannerModuleFree, 0);`

in libxslt -> extentions -> xsltCleanupGlobals()

**Comment by dmpr0** [comment]
Hello!
Fixed https://github.com/osmandapp/OsmAnd-iOS/pull/3661. 
You need to run `prepare.sh` script before build.
