### ISSUE TITLE
Cycling Route by GPX Recalculation not working

### ISSUE THREAD

**Issue by MatthijsH** [osmandapp/OsmAnd-iOS#3679]
### Description
Route recalculation for cycling in OsmAnd 4.7 and up isn't working 99% of the time. As mentioned in #3617 the issue might differ.

### Steps to reproduce
- Start a route and cycle it
- Deviate from the route somewhere along
- Notice that the route isn't recalculated
- Rejoin the route further along, notice that the route proceeds as normal
- Deviate again, sometimes the route is recalculated now

### Actual result
The route isn't recalculated almost always. When you are close to the calculated route, you can see the route line disappearing as if you are following it. If you rejoin the route, it proceeds as normal. Sometimes another deviation is recalculated, but I can't reproduce this reliably.
I've attached a track (renamed to .txt for uploading) where the route isn't recalculated at around 2.5km into it, after another km I rejoin the route that was calculated at the start.
[2024-05-06_17-42_Mon.txt](https://github.com/osmandapp/OsmAnd-iOS/files/15238579/2024-05-06_17-42_Mon.txt)

### Expected result
Route to be recalculated after the set deviation (20m in my case) and the route line to be updated accordingly.

### Your Environment (required)
```
OsmAnd Version: 4.7.4.3
Android/iOS version: iOS 17.4.1
Device model: iPhone 14 Pro
```

**Comment by Excalibur83** [comment]
I get the same issue and send a video to the support.
Recalculation works only in "Direct route" but never works using known trails or road whatever is set the deviation.

**Comment by yuriiurshuliak** [comment]
@Excalibur83 We couldn't locate the video on Zendesk or in the email. Could you please attach the video here or resend it to support@osmand.net? Thank you!

**Comment by Excalibur83** [comment]
Hi,I'm not currently at home and video is stored on my computer. I will send it to you as soon as possible. Is it better for you if I attach it to issue #3679 directly into GitHub ?Best regardManu.Envoyé de mon iPadLe 31 mai 2024 à 12:39, yuriiurshuliak ***@***.***> a écrit :﻿
@Excalibur83 We couldn't locate the video on Zendesk or in the email. Could you please attach the video here or resend it to ***@***.***? Thank you!

**Comment by yuriiurshuliak** [comment]
Yes, it is perfectly fine to attach the video directly here.

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. If you deviate from the route, OsmAnd will automatically recalculate to guide you back. This recalculation ensures you stay on course and reach your destination.

Try updating the app, resetting the bike profile, and updating the maps.

OsmAnd 4.7.6.3

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/73b3e6b2-c7c2-4d0b-bf73-68f2757ba4d6

**Comment by Excalibur83** [comment]
Hi, quite be back,
For information, I've already updated OsmAnd and get map update too when I reported this issue. And also reset profile (Now I use to do it every time I met trouble). So, please find attached the related video. Note that it looks like working fine with the newest release of OsmAnd 4.7.6.3 with standard car profile. But on video I was in Morocco using own profile for off-road use. Recalculation was set to a small value like 50m. And I also try to change it, but nothing better happened.
![IMG_0549](https://github.com/osmandapp/OsmAnd-iOS/assets/29670274/781e1c12-d41f-4c87-89e1-3a56dee8a403)

https://github.com/osmandapp/OsmAnd-iOS/assets/29670274/01d05f6b-85c5-4946-8407-9c4b8077c7e5

I have other video if needed.

Best regards

**Comment by yuriiurshuliak** [comment]
Please ensure that the roads permitted in your profile settings are allowed for recalculation. It is likely that the road you are using is not suitable for cars or bicycles, or specifically not intended for bicycles.

Could you provide the coordinates where you deviate from the route and notice that the recalculation fails? 

Recalculation should work correctly with the basic profile settings.

**Comment by Excalibur83** [comment]
My settings allow recalculation. Coordinates are displayed in bottom screen. Here after other video with some explanation.

https://github.com/osmandapp/OsmAnd-iOS/assets/29670274/ca112f9f-de4b-4f74-bb21-e7084ace9bf5

In that video, at beginning I deviated from original calculated route (trail), and system didn't recalculate it. Then, I stopped navigation and re-launch it after a while when I cross another trail. Calculation was made with a new route using the trail I ran (meaning roads or trails are allowed)

https://github.com/osmandapp/OsmAnd-iOS/assets/29670274/5e721d5c-1873-45a9-9d8c-c3d51cebe05d

Same behaviour, but at the begining OsmAnd is able to tell me how to join the trail until he stops to recalculate.

**Comment by yuriiurshuliak** [comment]
The bug can be reproduced. If you deviate from the calculated route, the system may not recalculate it. However, if you approach the calculated route it will simply be seen that you are moving in the right direction, because the route line will disappear as if you are following it.

If you stop the navigation and try to rejoin again, the navigation will be recalculated to guide you back.

OsmAnd 4.7.6.3

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/f008b3cb-c1b0-4cb0-831e-1b02f52e7d3d

**Comment by DmitryAlexei** [comment]
TestFlight 4.9.0.7
I didn't manage to reproduce the issue reported by @Excalibur83
I've created tracks around 29.84987 -5.95974 and tested route recalculation via GPS simulation. Every time the recalculation for driving profile worked fine. 
@Excalibur83 to reproduce your issue, recorded track and coordinates of the initial route (start-finish) or planned track are needed.

First bug with route recalculation with bicycle profile also cannot be reproduced on 4.9.0.7 (with default settings)
[Real navigation.gpx.txt](https://github.com/user-attachments/files/17937742/Real.navigation.gpx.txt)
[Track.gpx.txt](https://github.com/user-attachments/files/17937743/Track.gpx.txt)


https://github.com/user-attachments/assets/7a485c24-6d4c-4e73-8adb-f568a313a90a
