### ISSUE TITLE
h_topo_bare_rock and h_topo_bare_rock2 not render

### ISSUE THREAD

**Issue by Louis-LJ** [osmandapp/OsmAnd-iOS#3692]
Hi,

Shader or icons of topo bare rock is not displayed on iPhone.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/79785663/a51e74ed-e042-4511-bf1e-b924d4dc8635"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/79785663/909b4d2c-9605-46e6-af53-d344e18b8896"  width="300" height="auto"/> </th>
  </tr>
</table>

iPhone 11pro
OsmAnd 4.7.5.5

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When using the Topo map style, the bare rock is not displayed on the map. However, when switching to the OsmAnd map style, the bare rock is visible on the map.

OsmAnd~ 4.8.0#2288m, released: 2024-05-13

<table style="width:100%">
  </tr>
  <tr>
    <th>OsmAnd</th>
    <th>Topo</th>
  </tr>
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/5bc3e559-10ed-4d05-ab15-52faca7f7886"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/bf7f83d9-cc45-48aa-aa54-821220c0c60f"  width="300" height="auto"/> </th>
  </tr>
</table>

![image](https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/3f3a7056-8d90-49c3-882d-859b87402f19)

**Comment by Louis-LJ** [comment]
it is the h_topo_bare_rock2.svg which is not displayed. whether on topo or on modified renderings from [OsmAnd Rendering](https://github.com/OsmAnd-Rendering/Hiking)

https://github.com/osmandapp/OsmAnd-resources/blob/master/icons/svg/shaders/h_topo_bare_rock2.svg

**Comment by xmd5a2** [comment]
Looks like reducing shader size has no effect in Android OpenGL: shader is still not visible

**Comment by Andrewschenko** [comment]
In order to be displayed properly, several shaders (.svg) in resources need to be modified. ViewBox there should be = "0 0 ...

**Comment by xmd5a2** [comment]
Fixed. No new maps required.

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. When using the Topo map style, the bare rock is displayed on the map.

OsmAnd~ 4.8.0#2559m, released: 2024-06-22

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/97dd6535-2b86-4ee1-b651-37e6c61819eb"  width="300" height="auto"/> </th>
  </tr>
</table>
