### ISSUE TITLE
OsmAnd crashes when rotating screen with 3D Relief active

### ISSUE THREAD

**Issue by ToontjeM** [osmandapp/OsmAnd-iOS#3694]
Phone horizontal.
Enable Topography, Terrain, 3D Relief.
Set altitude amplification to 1.4 (not sure if this has any relevance though)
Go back to map.
Rotate phone to landscape.

OsmAnd crashes.

iPhone 14 Pro Max
OsmAnd 4.7.4.3

**Comment by ToontjeM** [comment]
I noticed that i had OsmAnd (online tiles) as overlay. When you switch this off OsmAnd doesn't crash.

**Comment by yuriiurshuliak** [comment]
I recommend updating your app to the latest version. Additionally, you can test if the issue persists by using the Testflight version available at this link: [Testflight Version](https://osmand.net/docs/versions/nightly_versions#testflight).

**Comment by ToontjeM** [comment]
Osmand on the AppSore is 4.7.5. On TestFlight it's 3.7.4.3. Which one is the latest?

**Comment by vshcherb** [comment]
4.7.5 is latest, tomorrow we will have some crashes fixes with 4.7.6 but probably not yours.

**Comment by ToontjeM** [comment]
4.7.5 is already a lot more stable so something must have changed.

**Comment by vshcherb** [comment]
We fixed many crash reports reproduced in 4.7.5, so 4.7.6 should be even more stable
