### ISSUE TITLE
Public transport does not work in the Netherlands

### ISSUE THREAD

**Issue by ShadowJonathan** [osmandapp/OsmAnd-iOS#3695]
I'm currently trying to make public transport work for the Netherlands.

However, nothing seems to work, it says every time "unfortunately, OsmAnd could not find a route in your settings.

I saw somewhere else that "number of changes" may be a problem, but changing that also doesn't do anything.

This is from a fresh install. I only paid for maps+ and downloaded every single map for the Netherlands.

**Comment by yuriiurshuliak** [comment]
Duplicate of [#19836](https://github.com/osmandapp/OsmAnd/issues/19836)

**Comment by ShadowJonathan** [comment]
(Why did this one get reopened?)

**Comment by DmitryAlexei** [comment]
Different issues Android | iOS

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-core-legacy/commit/150868bc61e72240bd847ecf4610dc6ebe81a10e
