### ISSUE TITLE
Do not modify `<name>` for tracks not created by OsmAnd

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3698]
## Description
OsmAnd should not change `<name>` after renaming for tracks that not created by OsmAnd. Currently OsmAnd always change `<name>` tag: `<name>Mon 13 May 2024Rename.gpx</name>`

> Based on task from OsmAnd Web https://github.com/osmandapp/web/issues/387

### How to reproduce
* Import file [2014 - Aires Camping Farm.gpx.zip](https://github.com/osmandapp/OsmAnd-iOS/files/15294761/2014.-.Aires.Camping.Farm.gpx.zip)
* Tap – **Actions** – **Rename**
* Modify name
* Export file

### Actual result

* `<name>` tag before renaming:
`<name>2014 - Aires Camping Farm.gpx</name>`
* `<name>` tag after renaming:
`<name>2014 - Aires Camping Farm renamed.gpx</name>`

### Expected result

- [x] Change `<name>` tag while renaming only for tracks created by OsmAnd. 
- [x] Remove `.gpx`

**Environment**
OsmAnd Version: 4.7.5.5
Android/iOS version: 17.4
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3853

**Comment by dmpr0** [comment]
## Review

- [ ] Don't add `name` tag  the tracks if it wasn't present

**Track before renaming:**
```
<gpx creator="StravaGPX Android" http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd">
 <metadata>
  <time>2017-08-05T12:21:34Z</time>
 </metadata>
```

**Track after editing:**
```
<gpx version="1.1" creator="StravaGPX Android" xmlns="http://www.topografix.com/GPX/1/1" xmlns:osmand="https://osmand.net" xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
    <metadata>
        <name>My_35_OsmAnd</name>
        <time>2017-08-05T12:21:34Z</time>
    </metadata>
```
