### ISSUE TITLE
Speed limit display

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-ios#370]
On the Powhatan Rd in Johnston County, North Carolina the speed limit is displayed only while driving in one direction, but it is not while driving back on the same road.
The issue is not reproducible in the Android version. 
35.5918
-78.3589
https://www.openstreetmap.org/search?query=35.5918%20-78.3589#map=15/35.5918/-78.3589

**Comment by max-klaus** [comment]
Not reproducible with OsmAnd 2.90
