### ISSUE TITLE
Export from My Places doesn't work on iPad

### ISSUE THREAD

**Issue by Excalibur83** [osmandapp/OsmAnd-iOS#3706]
## Description
In 3 dot menu in favorites/track "export" for previous version or pop-up menu in last version returns nothing
This was true in v4.6.x and still be true in last version 

### How to reproduce
After selecting a folder and click export, there's no pop-up window for selecting a destination and app's go back to track window.
I'm just able to export track one by one. A bit boring.

### Expected result

**Environment**
OsmAnd Version: 4.7.5.
iOS version: 17.4.1
Device model: iPadPro 11"

**Comment by Excalibur83** [comment]
Yep, I've just tested it and it works on iPhone (under 4.6 with 3dots menu and under 4.7 with long press pop-up menu) but on iPad, it doesn't work. Pop-up menu appeared but no window to choose where to export folder.

**Comment by dmpr0** [comment]
Reproduces on iPad
* Export of Favorties and Tracks doesn't work, system share sheet didn't shows up

<table style="width:100%">
  <tr>
    <th>Tracks</th>
    <th>Favorites</th>
  </tr>
  <tr>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/3cb6c645-d743-4104-bfdd-19c928f339e9"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/432d1b19-7472-40f8-8cc1-be3f349bc267"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/issues/3706
