### ISSUE TITLE
Missed subway station icons

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3711]
### How to reproduce

* Open **Menu** – **Search** – **Categories** 
* Find and select **Public transport**
* Tap on filter icon, set **Subway station** to **Yes**

### Actual result

<table style="width:100%">
  <tr>
    <th>Search result</th>
    <th>Context menu</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/19906530-a3a5-40a4-837a-f7ca63fed7d5"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/9f8004c8-582c-4c9b-ac62-e2ea96f0bee3"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Icons is missed for the part of the stations

### Expected result

<details>
    <summary>Android</summary>

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/0fee0176-32d9-47b8-a8b2-432665a749c6"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/0fb85001-0d1d-489f-9b67-d7e28e64c7e7"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>  

* Icons on the search results and in context menu

**Environment**
OsmAnd Version: 4.7.6.2
iOS version: 17.4
Device model: iPhone XS Max

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3773
