### ISSUE TITLE
Change color for public transport route details

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3712]
### How to reproduce
* Open **Menu** – **Navigation**
* Switch to Public transport profile
* Set **Destination**
* Wait until rout will be calculated
* Tap on **Details**

### Actual result

<img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/85f5e938-3da9-4d57-80a9-e91f00741900"  width="300" height="auto"/> 

<details>
    <summary>Screenshot</summary>

<table style="width:100%">
  <tr>
    <th>Dark theme</th>
    <th>Light theme</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/07f9145c-fdb1-4bf3-8d6e-af8e979e0ce3"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/08856743-d658-4c7b-a772-bfa36ac5b849"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>  

* Icon is hardly visible in both app themes

### Expected result
* Stroke – `customSeparator`
* Icon color – `iconColorSecondary`

**Environment**
OsmAnd Version: 4.7.6.2
iOS version: 17.4
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3721
