### ISSUE TITLE
Bodies of water should be displayed above of landuse=quarry

### ISSUE THREAD

**Issue by alexanderneuschl** [osmandapp/OsmAnd-iOS#3719]
Bodies of water should be displayed above of landuse=quarry.

OSM Carto:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/30687174/abfb30de-6570-4264-b052-22e54cc6e014"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/30687174/03959533-9298-4789-81ca-33deb1f13c88"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. While the water object is displayed on OSRM, it is not visible on our map.

OSRM link: https://www.openstreetmap.org/way/162450028

Our web version link (Set the map style to default): https://test.osmand.net/map/?start=47.911731,8.740369&profile=car#17/47.91225/8.73823

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/be850129-b140-49a5-b302-1dff47d7d1b2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/917374be-e987-47bc-8291-fec3db5d2662"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Fixed. No new map required.

**Comment by yuriiurshuliak** [comment]
The bug has been fixed. Currently, this water object is visible on the map.

OsmAnd~ 4.8.0#2422m, released: 2024-05-31

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/28a8b913-e82f-4339-86a4-0ce1420a62af"  width="300" height="auto"/> </th>
  </tr>
</table>
