### ISSUE TITLE
Wrong map is showed as update required in Missing maps dialog

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3724]
## Description
> Previous task https://github.com/osmandapp/OsmAnd-Issues/issues/748

### How to reproduce
Tested in May
* Two maps with diffrent date is required for testing
* In my example:
* *  **Saxony-Anhalt, Germany** was from `1 May`
* * **Brandenburg, Berlin, Germany** was from `1 April`
 
### Actual result

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/5df07bc2-02d9-4260-a85d-8cd9b0bcfb3c"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/1b65844b-0da5-438e-927f-1a973b13a21c"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Updated map is proposed to update

### Expected result
* Older maps should be proposed to update
* `Maps that also be used:` footer is missed too

**Environment**
OsmAnd Version: 4.7.6.3
iOS version: 17.4
Device model: iPhone XS Max

**Comment by dmpr0** [comment]
## Review
- [ ] Doesn't work at all. Tested on 4.7.7.5. Started from 4.7.7.4.

**Comment by dmpr0** [comment]
# Review 2

- [ ] Calculate online should work for all Navigation types

**Comment by RZR-UA** [comment]
Additional (Android && iOS):

routeMode for Online Calculation API request should be

- [ ] routeMode=bicycle for Bicycle || Pedestrian profiles
- [ ] routeMode=car for all other profiles

**Comment by RZR-UA** [comment]
Android part: https://github.com/osmandapp/OsmAnd/pull/20287
