### ISSUE TITLE
Voice prompts language auto-detection doesn't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3727]
### How to reproduce
* Reset setting for Driving profile 
* Open **Menu** – **Settings** – **Navigation Settings** – **Voice prompts** – **Language**, all deselected.
* Open **Menu** – **Navigation**, start Simulation

### Actual result

* Voice prompts does't work until manually selecting Language.
* * System language is set to English
* * OsmAnd language is set to System default

### Expected result

* Language similar to one of the system should be selected

**Environment**
OsmAnd Version: 4.7.6.3
iOS version: 17.4
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3922

**Comment by DmitryAlexei** [comment]
4.8.3.0 fixed
