### ISSUE TITLE
Route Recalculation Error After Deviation

### ISSUE THREAD

**Issue by ToontjeM** [osmandapp/OsmAnd-iOS#3730]
### Description

When navigating a route following a track, when you move away from the track, on CarPlay a dialog appears that the calculated route is empty with an Ok button. This Ok button cannot be tapped. 
The only way to get this dialog from the screen is to switch to another application and then switch back to OsmAnd. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd/assets/98271783/70107e49-b9b2-4b72-85dd-50d14058787f"  width="300" height="auto"/> </th>
  </tr>
</table>

### Steps to reproduce

Navigate a route following a track using CarPlay. 
Move away from the track, for example because you missed an exit. 
The dialog pops up. 
Tap the Ok button. 

### Actual result

Dialog doesn’t close. 

### Expected result

Dialog closes. 

### Your Environment (required)

```
OsmAnd Version: 4.7.6.2
iOS version: 17.4.1 
Device model: iPhone 14 Pro Max
Crash-Logs: Nothing crashes. 
```

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. When I attempted to reproduce it on the iPhone, I deviated from the calculated route, and a dialog window appeared stating "calculated route is empty" with an "OK" button. 

I was able to click the "OK" button, and the dialog closed successfully.

OsmAnd 4.7.6.3

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/6317ab74-f9b5-4183-b6f4-daa34f59e374

**Comment by ToontjeM** [comment]
Probably that works on the iPhone, but not on CarPlay.

**Comment by DmitryAlexei** [comment]
The issue is not in the dialogue itself, the bug is in the fact that "calculated route is empty".

**Comment by ToontjeM** [comment]
So we two issues then:
- Dialog pops up.
- Dialog cannot be removed on a CarPlay display.

**Comment by yuriiurshuliak** [comment]
To reproduce the issue, follow these steps:

- Begin navigation following the designated track.
- Deviate from the track.
- Observe that the route does not recalculate.
- Click the navigation button.
- An error dialog window appears.

Related to #3679

**Comment by ToontjeM** [comment]
I see there is an issue open for "calculated route is empty". Is tehre also an issue for the fact that you cannot close the dialog using the Ok button? 
The dialog disappears when you switch to another application and then back to OsmAnd.
But since i am on a motorbike i prefer to touch the carplay screen as little as possible, obviously.

**Comment by ToontjeM** [comment]
This seems to be resolved. I deviated from the route and didn’t get the “calculated route is empty” message.
