### ISSUE TITLE
Bad visibility of POI icons on CarPlay

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3733]
### Actual result
<table style="width:100%">
  <tr>
    <th>Light mode</th>
    <th>Dark mode</th>
  </tr>
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4f83380d-8026-4909-b83e-a4b0d2d18dab"  width="400" height="auto"/> </td>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/82f5a127-64bb-4c28-8e95-cca73de27883"  width="400" height="auto"/> </td>
  </tr>
</table>   

* White icon is mostly invisible in Light mode

### Expected result

* Previously all POI icons were orange

**Environment**
OsmAnd Version: 4.7.7.1
iOS version: 17
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3850
