### ISSUE TITLE
[Plugin] duplicate online maps bug

### ISSUE THREAD

**Issue by Louis-LJ** [osmandapp/OsmAnd-iOS#3739]
hi,

National Spanish cards are duplicated x2.
The national and regional directory is also duplicated.

here is the correct display of our online map repo

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/79785663/82a67af9-91b3-4aef-9d9a-f4685a71fb76"  width="300" height="auto"/> </th>
  </tr>
</table>

https://github.com/OsmAnd-Rendering/Online-Maps

Bug national and régional:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/79785663/0a8bef68-256a-4190-948a-669a5b6ad427"  width="300" height="auto"/> </th>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/79785663/3a86aab2-ccb6-41f8-bde1-ee16e6566df3"  width="300" height="auto"/> </th>
  </tr>
</table>

Bug national Maps duplicate x2:

Plugin:
[OsmAnd-Rendering plugin.osf](https://github.com/OsmAnd-Rendering/.github/blob/main/profile/OsmAnd-Rendering%20plugin.osf)

iPhone 11pro up to date, OsmAnd 4.7.6.3

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To see it in action, download the OsmAnd-Rendering plugin.osf plugin for the app. Once installed, navigate to Menu - Map and Resources - Extra Maps - OsmAnd rendering online maps. You'll notice multiple duplicate maps for Spain in the results.

OsmAnd TestFlight 4.7.7.1

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/265649a9-7be4-4279-868e-c92046a07f8d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/835d5b78-f2ef-46be-945e-d34c74ea829a"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by EugeneZmeuk** [comment]
The same Custom plugin for Android and iOS versions has a wrong list and duplicate files for the iOS version. 

|Android version| iOS version |
|:-------|:-------|
|<img width="320" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/39a51ea3-c61e-458a-92a6-08355c8834e6">|<img width="320" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/856d38fc-b4f7-43d8-9913-e6f1c3056463">|
|<img width="320" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/7e4d7d67-73c7-4040-ae93-4d9787ec7571">|<img width="320" alt="image" src="https://github.com/osmandapp/OsmAnd-iOS/assets/44466116/d846fedf-8ce9-4785-aa02-7789739153ad">|

**Comment by vshcherb** [comment]
To do: consult with @EugeneZmeuk and repeat same behavior as in Android (no duplicates)

**Comment by tigrim** [comment]
For custom plugins:

1. The issue with duplication in the section is resolved by replacing in the collectCustomItems method:
` _customRegions = self.region.flattenedSubregions;`
with
`_customRegions = self.region.subregions;`
Testing is required.

2. The count of sections is calculated incorrectly.

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3775

**Comment by DmitryAlexei** [comment]
OsmAnd TestFlight 4.7.7.5 
now works as expected - no more duplicated files

<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/beb5c923-ba66-46fc-b92f-61a8dd082af5"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/f513ab09-ca00-4d06-9b4e-d51eca7f6223"  width="300" height="auto"/> </td>
  </tr>
</table>
