### ISSUE TITLE
Route planning very slow on latest release(s)

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#3741]
Since recently route planning for even short routes (15 km with bike profile) has become very slow. Previously such routes were calculated in perhaps just a second, now it's taking close to half a minute. To me the navigation in OsmAnd has become unusable because of this slowdown.

For reference, other OSM based apps like TopoGPS plan the same routes almost instantly.

**Comment by yuriiurshuliak** [comment]
Unfortunately, we could not reproduce this bug. I attempted to plan a 17 km route through a dense road network, which took about 30 seconds. Please provide the exact start and end coordinates, attach your profile settings, and specify the application version you are using.

**Comment by MagielBruntink** [comment]
@yuriiurshuliak I have since learned that the apps I was comparing to were using online services for routing (graphhopper). So, not really a fair comparison. Although it would perhaps be nice to have that online option in OsmAnd as well, since it is much much faster.

I have also enabled dev plugin and saw that it's possible to choose between two algorithms for routing: highway hierarchies and A*. The cycling profile is set to highway hierarchies by default. I tried A* and note significantly faster routing. Perhaps that algorithm was indeed changed in a recent release?

**Comment by MagielBruntink** [comment]
Please find attached a GPX file with start and end waypoints, and the exported Cycling profile.

Wall clock time measurements on iPhone 13 with no other apps active and not in power save mode:
- Highway hierarchies: ~77 seconds with often crashes during calculation.
- A*: ~21 seconds with no crashes observed.

Used navigation mode to calculate the routes. "Directions from" on the start waypoint, then select the end waypoint as destination.

[2024-05-30_18-52_Thu.gpx.txt](https://github.com/osmandapp/OsmAnd-iOS/files/15504053/2024-05-30_18-52_Thu.gpx.txt)
[Cycling.osf.txt](https://github.com/osmandapp/OsmAnd-iOS/files/15504055/Cycling.osf.txt)

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. I tested the issue by importing your track and using two different routing algorithms. First, I reset the bike profile settings and building the route using the Highway hierarchies and A* routing algorithms, which took approximately one second. Then, after importing your profile settings, it took around three seconds to build the route using the same algorithms.

OsmAnd TestFlight 4.7.7.1

<table style="width:100%">
  </tr>
  <tr>
    <th>Highway hierarchies</th>
    <th>A*</th>
    <th>Highway hierarchies (your profile)</th>
    <th>A* (your profile)</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/878feb28-65d0-4843-8e99-80750da79e8e"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/7548af31-dff1-4f7c-8850-589c78a892b6"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/53c6ff7b-cf1c-44d3-a412-17761c7e4a55"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/053c2822-1d84-43fb-917e-ad0c269a01a9"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by MagielBruntink** [comment]
I have now also reset (all) profiles and notice overall greatly improved performance, for route planning and general app responsiveness. This may be something to make users aware of. 

I have not done anything really special with my profiles in the past. Just visual preferences for the map.

**Comment by MagielBruntink** [comment]
With profiles reset to defaults this issue is resolved. I wonder what setting causes slow downs, though.
