### ISSUE TITLE
Calculating a 100km route with no toll roads makes the app crash

### ISSUE THREAD

**Issue by matteoar1** [osmandapp/OsmAnd-iOS#3759]
### Description

[As FOUR months ago](https://github.com/osmandapp/OsmAnd-iOS/issues/3453) I would like to calculate a route with no toll road but is is impossible. The app crashes!
Before you could Enabling Developer plugin and using "Special Routing" which "solve" the issue but now you cannot do it.

### Steps to reproduce

In Menu → Configure profile (Boat, Driving, Walking or another one) → Navigation settings → Navigation type select select the two parameters (avoid paid roads and highways).
Calculate a route
wait for the app to crash.

### Actual result

The app crash.
I cannot use it.

### Expected result

I know that the app calculate the route locally but I didn't expect problems with a 100kms route!
I just want calculate a route without highways!

### Your Environment (required)

**WARNING** Crash-Logs **MAY** contain information you deem sensitive.
Review this **CAREFULLY** before posting your issue!

```
OsmAnd Version: 4.7.7.1
Android/iOS version: iOS 17.5.1
Device model: iPhone 14 Pro
Crash-Logs: ?
```
[giu 05, 2024 12:18.log](https://github.com/user-attachments/files/15585384/giu.05.2024.12.18.log)

**Comment by vshcherb** [comment]
You need to enable Developer plugin, please share example start / end coordinates to check

**Comment by yuriiurshuliak** [comment]
The bug was not reproduced. To reproduce it, I selected the car profile with both "Avoid Toll Roads" and "Avoid Motorways" options activated. After that, I built a route of 202 km, which was promptly calculated without any crashes.

OsmAnd TestFlight 4.7.7.1

https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/ce812990-f166-43e9-a188-9bbb6d94d65a

**Comment by sonora** [comment]
I have seen issues like this with older maps, perhaps a map update helps.

**Comment by yuriiurshuliak** [comment]
The bug could not be reproduced. I tested using a car profile with "Avoid Toll Roads" and "Avoid Motorways" options enabled. After about a minute of calculation, the 110 km route  was built successfully without any crashes. The route also builds without these options enabled.

Here is the link to the web version:[link](https://test.osmand.net/map/navigate/?start=45.553500,8.948560&end=45.035740,9.667710&profile=car&params=car,avoid_toll,avoid_motorway#9/45.4418/8.7863).

OsmAnd TestFlight 4.7.7.1

<table style="width:100%">
  </tr>
  <tr>
    <th>With the "Avoid Toll Roads and Motorways" options enabled</th>
    <th>With the "Avoid Toll Roads and Motorways" options disabled</th>
  </tr>
  <tr>
    <td> <video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/e3220819-b00c-4eda-beb5-69aaca72f15a"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/osmandapp/OsmAnd-iOS/assets/127092082/efad4e1b-5c6a-4d44-931a-cebffae34469"  width="300" height="auto"/>   </td>
  </tr>
</table>
