### ISSUE TITLE
Interface issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-ios#376]
There are different terms (track, route, trip) used for the same subject.

**Comment by max-klaus** [comment]
@katerynakocherhina where exactly? Are there screenshots maybe?

**Comment by dmpr0** [comment]
![photo_2019-08-20 14 09 45](https://user-images.githubusercontent.com/9365308/63342440-2fe95200-c354-11e9-9268-85eb96a45a93.jpeg)
![photo_2019-08-20 14 09 46](https://user-images.githubusercontent.com/9365308/63342441-3081e880-c354-11e9-8d2f-fbd230b19ca6.jpeg)
![photo_2019-08-20 14 09 48](https://user-images.githubusercontent.com/9365308/63342442-3081e880-c354-11e9-9364-8fa43d124771.jpeg)
![photo_2019-08-20 14 09 49](https://user-images.githubusercontent.com/9365308/63342444-3081e880-c354-11e9-9bad-9451a89f7888.jpeg)
