### ISSUE TITLE
Broken Hazmat parameters

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3761]
## Description

> Previous issue 
> * https://github.com/osmandapp/OsmAnd-iOS/issues/2830
> * https://github.com/osmandapp/OsmAnd-Issues/issues/1369

### How to reproduce
* Go to **Menu** – **Settings**, select **Truck** profile
* Open **Navigation settings** – **Route parameters**

### Actual result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/4b018944-9a9d-45e0-9a7a-b9c5ee4d004f"  width="300" height="auto"/> </td>
  </tr>
</table>   

* All parameters showing up in the list.

### Expected result
* Should be grouped 

**Environment**
OsmAnd Version: 4.7.7.2
iOS version: 17.5.1
Device model: iPhone XS Max

**Comment by vshcherb** [comment]
To do: 

Routing parameters (Hazmat) was added via routing.xml and it works fine out of the box in Android. In IOS it doesn't work, so the issue is not about specific parameters Hazmat but support of any  extra custom parameters in routing.xml.

**Comment by DmitryAlexei** [comment]
Testflight 4.7.7.3
Same issue in Configure map > details


<table style="width:100%">
  <tr>
<th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/0e91db88-013e-4986-bd16-2c2f28d1c7d2"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/osmandapp/OsmAnd-iOS/assets/116079541/caa1d9df-28e2-4f3d-aaa4-1e26fb6b8362"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3783

**Comment by dmpr0** [comment]
# Review 
- [ ] **Hazmat category** > **Dangerous goods** for EU

**Comment by dmpr0** [comment]
Documentation team please check the screenshots in the docs.

**Comment by EugeneZmeuk** [comment]
**Docs**
- [ ] [Hazmat section](https://osmand.net/docs/user/navigation/routing/car-based-routing#route-parameters---truck)
