### ISSUE TITLE
[Feature request] Make alerts display dependant on the default speed

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-ios#377]
During navigation, the speed camera alert is displayed after the user has passed the speed camera.
The issue occurs on the route from http://osmand.net/go.html?lat=48.69256&lon=3.18031 
to http://osmand.net/go.html?lat=48.69852&lon=3.27277

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-ios/commit/58860a204cac11a68a6f4c1020b20a4f27715885
