### ISSUE TITLE
Bug report: imported maps do not display the currently navigated route

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-ios#378]
If import the map file to the OsmAnd folder on the device manually from the server, the currently calculated route is not displayed. The issue does not occur with the maps, which are downloaded directly from the app though.

**Comment by dmpr0** [comment]
Also, it seems that the route calculation doesn't start to.

**Comment by max-klaus** [comment]
File needs to be renamed: make it lower case and remove _2 at the end of file.
