### ISSUE TITLE
Favorites lost after the app's auto-update

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-ios#379]
The issue occurred with iPhone SE
iOS 12.3.1
2.90 OsmAnd version

**Comment by PaulStets** [comment]
This should not happen because the favorites are stored as a file in the file system. Perhaps something went wrong during the update. There's nothing we can do on our end. Judging from the fact that this was reported only once, I think it's safe to assume that it was an unfortunate accident.
