### ISSUE TITLE
[Bug] [l10n] Some french wordings have missings whitespaces

### ISSUE THREAD

**Issue by pylapp** [osmandapp/OsmAnd-iOS#3814]
# Details

In french localizables some wordings don't have enough whitespaces around specific symbols like 'à', 'é' or 'ê'.
Some '-' are also missing.
Thus the text content of the app for french reading users can be improved.

# Note

Note that a pull request is ready for review: https://github.com/osmandapp/OsmAnd-iOS/pull/3813

# Screen shots

![IMG_7256](https://github.com/osmandapp/OsmAnd-iOS/assets/7559007/773a6257-40c8-488c-a96c-bf4c5faa5dd0)
![IMG_7257](https://github.com/osmandapp/OsmAnd-iOS/assets/7559007/74ccf6df-e1e4-4529-8fc0-14cfebf597cd)

**Comment by dmpr0** [comment]
Hi! Thank you for the improvements. 
Merged https://github.com/osmandapp/OsmAnd-iOS/commit/435cb60cdb8733948b2897dc98c26bef325c607a

**Comment by pylapp** [comment]
Nice!

It could have been better to preserve Git history to ask me for a rebase (or just make a cherry-pick of the commit) before merging the branch to keep traces of original commit authors.

Glad to see you merged this minor improvement so quickly 😁
