### ISSUE TITLE
[Feature Request] Lock screen navigation at a glance

### ISSUE THREAD

**Issue by balintbarna** [osmandapp/OsmAnd-iOS#3818]
I would like to have turned by turn navigation shown on the lock screen similar to Google Maps or Apple maps so I can save battery while I’m going straight and the screen only turns on when I need to change direction.

**Comment by yuriiurshuliak** [comment]
You can control the screen of your device to save power. This mode has two general settings: Screen timeout and Turn screen on.

Menu → Configure profile → General settings → Screen control

Here is a link to the documentation: https://osmand.net/docs/user/navigation/guidance/voice-navigation#screen-control

**Comment by balintbarna** [comment]
@yuriiurshuliak I was so glad to see your reply and checked literally everywhere and then I saw in the documentation as well that these features aren’t available on the iOS version.

**Comment by NicoleWills01** [comment]
Benefits of Using The Glance Smart Lock Screen 
Android users are constantly seeking ways to streamline their mobile experience, and the Glance Smart Lock Screen emerges as a game-changer in this quest for efficiency. This innovative feature transforms the often-overlooked lock screen into a powerful tool for information and personalization. 

Let's explore the numerous benefits that make [Glance Smart Lock Screen]((https://glance.com/us?utm_source=Glance&utm_medium=external&utm_campaign=Glance+USA)) a must-have for Android users.

**Comment by balintbarna** [comment]
Closing as not using it anymore.

**Comment by kubrickfr** [comment]
That doesn't sound like a valid reason to close the issue.
