### ISSUE TITLE
Use Pro Subscription on TestFlight version

### ISSUE THREAD

**Issue by juliusvaart** [osmandapp/OsmAnd-iOS#3819]
Can’t use my Pro subscription on TestFlight version. It says it’s “Expired”.

**Comment by yuriiurshuliak** [comment]
Please reach out to our support team at support@osmand.net with this inquiry.

**Comment by juliusvaart** [comment]
Beste,

Van 24 juni t/m 12 juli afwezig. U kunt contact opnemen met Peter van der West op ***@***.*** of +31 6 41 47 92 55.

Vriendelijke groet,

Julius van der Vaart
