### ISSUE TITLE
Camera Height not following map height on navigating with auto zoom

### ISSUE THREAD

**Issue by juliusvaart** [osmandapp/OsmAnd-iOS#3823]
When navigating with car, the auto zoom of the camera doesn’t respect the map height (when 3d terrain is activated). This results in a camera so close to the “ground” that you can’t see ahead anymore.

**Comment by yuriiurshuliak** [comment]
Please provide a video demonstrating the bug, along with the app version and detailed steps to reproduce the issue.

**Comment by juliusvaart** [comment]
Can’t make video. Sorry.

Happens when driving from low terrain (sea level) to higher terrain (as low as 100 meters above sea level already).

latest testflight 4.7.7.4. Also on previous versions since 3D maps were introduced.

**Comment by yuriiurshuliak** [comment]
Related to https://github.com/osmandapp/OsmAnd-Issues/issues/2551

**Comment by juliusvaart** [comment]
Hi @yuriiurshuliak the link you posted is not right.

**Comment by vshcherb** [comment]
We've recently changed it as well so needs to be tested with 4.8 release

**Comment by juliusvaart** [comment]
4.8.0.1 testflight is so much better in map rendering. Performance is great!

Unfortunately i’m not in an area with lots of height difference, so can’t test this in the short term. But will do when i get the chance! Maybe someone in a mountainous area can chime in!
