### ISSUE TITLE
Wrong filter is selected

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3824]
### How to reproduce
* Download Berlin map, go to `52.50435° N, 13.39109° E`
* Find restaurant "Da Vinci".
* Find item **Cuisine**
* Tap on arrow to open – tap on **Italian**

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>iOS</th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/9668679d-7888-4227-84ac-5cea84f6445b"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

* Search screen for **Food** category will be opened

### Expected result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Android</th>
      </tr>
      <tr>
        <td><video src="https://github.com/osmandapp/OsmAnd-iOS/assets/9365308/127e2944-e9d9-4c86-b21f-4f744fd9fed0"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

* Search for Food, filtered by cuisine: Italian.
* Probably code sync for search is needed?

**Environment**
OsmAnd Version: 4.7.7.5
iOS version: 18.2
Device model: iPhone XS Max

**Comment by DmitryAlexei** [comment]
https://github.com/osmandapp/OsmAnd/issues/8483

**Comment by Zirochkabila** [comment]
# Testing 1
`52.52007° N, 13.39128° E`

`OsmAnd~ 5.0.0#3911m, Released: 2024-12-09` - **Done**
`4.9.0.14` - **Done**
