### ISSUE TITLE
Search for brands

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#3826]
## Description 
Add support for search by brands. Android task: https://github.com/osmandapp/OsmAnd/issues/16397

## ToDo  
- Load dynamic (brand) categories and combine all objects of it into 1 single top search category
- Support search inside Brand category similar "Vegan" (McDonalds')

> iOS / Core drafts:
> * https://github.com/osmandapp/OsmAnd-iOS/pull/3811
> * https://github.com/osmandapp/OsmAnd-core/pull/765

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-core/pull/780

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3979

**Comment by dmpr0** [comment]
# Review 

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/user-attachments/assets/fe6b51e5-148d-412f-8f7c-ec0302e78399"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  


- [ ] Search for categories is broken, it shows all nearby POI's

**Comment by dmpr0** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-iOS/commit/a17062316fc7b6098fb11c4e1acd645cc8205139
