### ISSUE TITLE
Main Thread Checker issues

### ISSUE THREAD

**Issue by tigrim** [osmandapp/OsmAnd-iOS#3827]
#### Problem:
Currently, there are issues related to Main Thread Checker in XCode, which lead to unexpected crashes and performance degradation due to improper usage of background threads for main thread tasks.

#### Expected Result:
After revising the application's logic and ensuring that code intended to be executed on the main thread is correctly implemented as such, the following improvements are expected:
- Elimination of Main Thread Checker errors in XCode.
- Enhanced application performance.
- Prevention of phantom crashes associated with this issue.

<img width="695" alt="Снимок экрана 2024-07-03 в 17 04 18" src="https://github.com/osmandapp/OsmAnd-iOS/assets/17082167/2ab26c44-c198-489e-9fc0-a645e32cd64c">

**Comment by vshcherb** [comment]
Related https://github.com/osmandapp/OsmAnd-Issues/issues/2580?

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/05f7225772e50d1661ddff87e7f6cd3db6318212
