### ISSUE TITLE
Share icon doesn't show for track context menu on macOS

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3832]
### How to reproduce
* Launch OsmAnd on any Apple computer with external **Full HD monitor**
* Open Menu – My Places – Tracks
* Tap on track to open context menu

### Actual result

<table style="width:100%">
  <tr>
    <th>Full HD</th>
    <th>MacBook Monitor</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/362cd87a-95d6-45da-8b3c-e228e08f01dd"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/49a364ed-21cc-4395-a9d8-58cf02e6a7e9"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result

- [x] All icons should be visible 

**Environment**
OsmAnd Version: 4.7.7.6
OS version: macOS Sonoma 14.4.1 (23E224)
Device model: MacBook Pro 14", 2021 with External Full HD Monitor

**Comment by DmitrySvetlichny** [comment]
![Снимок экрана 2024-07-29 в 17 08 54](https://github.com/user-attachments/assets/3f3c8a7d-36f6-4fff-ad2d-16abf6b0c16a)

**Comment by DmitrySvetlichny** [comment]
![Снимок экрана 2024-07-29 в 17 08 54](https://github.com/user-attachments/assets/f9e6a768-12f4-45e1-bed8-f6a8c5cca697)

**Comment by DmitrySvetlichny** [comment]
<img width="290" alt="Снимок экрана 2024-07-29 в 18 09 09" src="https://github.com/user-attachments/assets/eb493378-0c58-439c-917a-97663fd681d3">

**Comment by DmitrySvetlichny** [comment]
Removed old resources:
change_item_color.png
delete_items.png
export_items.png
move_items.png
ic_tabbar_trips.png
ic_tabbar_osm_edits.png
ic_tabbar_favorites.png
ic_custom_slider.png
ic_custom_export.png

Added to assets:
ic_change_item_color
ic_delete_items
ic_export_items
ic_move_items
ic_tabbar_trips
ic_tabbar_osm_edits
ic_tabbar_favorites
ic_custom_slider
ic_custom_export

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3873
