### ISSUE TITLE
Problem with download map from clicking to area (testflight version 2.94)

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-ios#384]
There is a problem with download map from clicking to the area.

1. I choose Latvia territory, but OsmAnd wants to download Pskovskay oblast from Russia.
![3](https://user-images.githubusercontent.com/44466116/63151612-8ed85f80-c012-11e9-9fa8-509b201857de.jpg)
![4](https://user-images.githubusercontent.com/44466116/63151613-8f70f600-c012-11e9-80f2-71f41e16f9e3.jpg)

2. I choose Kalinigradskay oblast, but OsmAnd doesn't suppose anything for downloading.
![1](https://user-images.githubusercontent.com/44466116/63151747-da8b0900-c012-11e9-918f-9d39a31060fb.jpg)
![2](https://user-images.githubusercontent.com/44466116/63151748-da8b0900-c012-11e9-81e5-f20f01a20542.jpg)

**Comment by max-klaus** [comment]
![IMG_396963D9B300-1](https://user-images.githubusercontent.com/53395422/63344293-c61f7700-c358-11e9-8be2-d5300beebbb2.jpeg)
![IMG_BD716F12EB15-1](https://user-images.githubusercontent.com/53395422/63344299-c881d100-c358-11e9-9a12-f10530b450d3.jpeg)
