### ISSUE TITLE
Wrong slope is displayed on the graph

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#3843]
## Description

> Android / Web task https://github.com/osmandapp/OsmAnd/issues/19142

**Steps to reproduce:**
* Create a route start `53.822860, 9.285870`, end `50.385780, 6.656350`
* * Link https://osmand.net/map/navigate/?start=53.822860,9.285870&end=50.385780,6.656350&profile=car#7/52.147/5.504 on OsmAnd TestFlight 4.7.7.6 (desktop version)
* Compare the graph in route details and it with the android version

<table style="width:100%">
  </tr>
  <tr>
    <th>iOS (wrong) </th>
    <th>Android</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/a386341c-fdb4-41c6-a053-cb57218ccef3"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/a3831256-ccc9-4321-ba0a-0f136be54511"  width="300" height="auto"/> </th>
  </tr>
</table>

## To do:
- [ ] iOS should have the same information on the graph as Android. 6000000000% slope is wrong.

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/bdda83fdec034b831a354ee5c85444b044ee8e12

**Comment by dmpr0** [comment]
## Review 

<table style="width:100%">
  <tr>
    <th>iOS</th>
    <th>Android</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/cd9135b1-6a8b-42f4-96e5-619b3dee56a1"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/e62dabf9-f98c-4db4-b073-8b5f4b64444e"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Slopes is shows more real numbers but they are differentiate from what Android version is shown

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/0d8dce498d600e0491b2ca868518dfcc006b85d6
