### ISSUE TITLE
Display non « World Map » détails at low scales

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-ios#385]
Currently on low zoom the map display what is present in the World Map. It is understandable that this map contains only a limited set of features ton control the memory space it takes. On the other hand, it’s a shame that OSMAnd is not able to display more details at low zoom when the underlying country/regional map is available. In particular I would expect long range cycle / pedestrian routes to be visible at low zoom if I’ve download the appropriate maps. I would also like to see national parks at low zoom. These are my requirements but others can wish for different things, the only thing that remains is to providence a mechanism to show data of non World map at low scale.

**Comment by vshcherb** [comment]
Should be fixed with new maps
