### ISSUE TITLE
Route name should be displayed in selected map language

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3854]
### How to reproduce

**Step 1**
* Open **Menu** – **Configure Map** – **Route** – **Hiking routes**, Turn on
* Change **Map language** to Ukrainian

**Step 2**
* Open Menu – Search
* Search `36.9301/30.7727`, [Lycian Way](https://www.openstreetmap.org/relation/51855#map=9/36.9301/30.7727)
* Select (white/red) route on the map

### Actual result

<table style="width:100%">
  <tr>
    <th>Lycian Way</th>
    <th>Eeiffel tower</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/28759c95-0e40-4259-aa3a-a427c985adf5"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/e1dc3f75-b58c-4c44-9ef3-e8fc485a0e29"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Route name is displayed from `name` tag, `name:uk` is not used.

### Expected result

* Route name language should be selected the same way as for POI

**Environment**
OsmAnd Version: 4.7.7.9
iOS version: 18.0
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3870
