### ISSUE TITLE
Weather iPad RTL issues 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3864]
### How to reproduce
* Change app language to any RTL language
* Open **Menu** – **Configure Map** – **Weather**
* Turn it on 
* Tap on **Temperature** layer

### Actual result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/2036f032-2f6e-44df-b1b2-8640f4fb104f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/b4fbab1c-0e26-44ff-8243-5b3f3c3f05f1"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Switch that allows to turn on selected Weather layer is hidden bellow **Done** button

### Expected result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/65aa9d51-ad85-4cf5-991f-d4bbb9b5abd9"  width="300" height="auto"/> </td>
  </tr>
</table>   

* In LTR languages button is placed outside the menu.

**Environment**
OsmAnd Version: 4.8.0.1

**Comment by DmitryAlexei** [comment]
- [ ] same issue when changing transparency of weather layers in Menu > Configure map > Weather > Temperature (or wind etc.)

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3877
