### ISSUE TITLE
Wrong uphill calculation

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3865]
### How to reproduce
* Calculate Pedestrian [route](https://osmand.net/map?start=46.379314%2C7.626741&end=46.396286%2C7.611460&profile=pedestrian#14/46.373831/7.619929) from `46.37931° N, 7.62674° E`, to `46.39629° N, 7.61146° E`. 
* Disable **Use elevation data**

### Actual result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/osmandapp/OsmAnd/assets/9365308/28a1e5e7-2066-4ec7-877f-3ffe0a3b5937"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Uphill 440 m

### Expected result
* Uphill close to 800 m

**Environment**
Both Android and iOS

**Comment by vshcherb** [comment]
As we need more testing this task is valid Android / iOS for 4.9

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/c0fd8ee1575f25fe0296116c043ecf35dc1cf15b
