### ISSUE TITLE
Add Quick action: to Show / Hide Routes on the map

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3868]
## ToDo
We need to add new set of Quick Actions to Configure Map group.

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a5df0e80-7d97-4459-a18b-342edddb1144"  width="300" height="auto"/> </td>
  </tr>
</table>   

Add new actions to **Configure Map** group
Action name = verb **Show / Hide** + option name

- [x] **Cycle routes**
- - [x] `rendering_attr_showCycleRoutes_name`
- - [x] Icon – `ic_action_bicycle_dark`
- [x] **Mountain bike routes**
- - [x] `rendering_attr_showMtbRoutes_name`
- - [x] Icon – `ic_action_mountain_bike`
- [x] **Hiking routes**
- - [x] `rendering_attr_hikingRoutesOSMC_name`
- - [x] Icon – `ic_action_trekking_dark`
- [x] **Difficulty classification**
- - [x] `rendering_attr_alpineHiking_name`
- - [x] Icon – `ic_action_trekking_dark`
- [x] **Ski slopes**
- - [x] `rendering_attr_pisteRoutes_name`
- - [x] Icon – `ic_action_skiing`
- [x] **Horse routes**
- - [x] `rendering_attr_horseRoutes_name`
- - [x] Icon – `ic_action_horse`
- [x] **Whitewater sports**
- - [x] `rendering_attr_whiteWaterSports_name` 
- - [x] Icon – `ic_action_kayak`
- [x] **Fitness trails**
- - [x] `rendering_attr_showFitnessTrails_name`
- - [x] Icon – `mx_sport_athletics`
- [x] **Running routes**
- - [x] `rendering_attr_showRunningRoutes_name`
- - [x] Icon – `mx_running`

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3909

**Comment by nnngrach** [comment]
Created a note file with coordinated for testing

https://github.com/osmandapp/OsmAnd-Issues/blob/master/Development/Coordinates%20for%20testing.md
