### ISSUE TITLE
Incorrect layout after changing screen orientation + QA button displaced

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#3876]
### Description
Incorrect layout is applied when changing screen orientation in Menu > Configure map or Menu > Weather tabs.
Also Quick action button does not return to its place when changing the screen mode.

### Steps to reproduce
- in portrait mode, open Menu > Configure map or Menu > Weather
- change screen orientation to landscape, then back to portrait mode

- for Quick Action button change screen orientation to landscape, then back to portrait mode

### Actual result
- wrong layout in both landscape and portrait modes (see video)
- wrong place for QA button
<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video src="https://github.com/user-attachments/assets/7a242ba0-7ebf-413f-ba45-3aeb4076b1af"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/744f7985-e62b-49a7-8ae9-4fb505099483"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/a7458ba9-2c5c-49f0-b185-af50f6145871"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
We encountered an issue where the user interface (UI) of the application behaved as if it were in portrait mode even though the device was physically positioned in landscape. This issue arose specifically when the device orientation was detected as faceUp or faceDown.

Steps to Reproduce the Issue:

Open the application and navigate to any view that reacts dynamically to changes in device orientation.
Rotate the device to a landscape orientation.
Place the device on a flat surface facing upwards (faceUp) or downwards (faceDown).
Observed Behavior:
Upon setting the device to faceUp or faceDown, the application's UI reverted to a portrait layout, disregarding the actual landscape orientation prior to the change. This led to a mismatch between the expected landscape UI and the displayed portrait UI.

**Comment by DmitrySvetlichny** [comment]
Resolution:
We modified the orientation handling logic to properly maintain the last known landscape or portrait orientation before the device was moved to a faceUp or faceDown position. Now, if the device orientation is faceUp or faceDown, the application retains and displays the correct UI orientation based on the last recognized landscape or portrait state.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3888

**Comment by dmpr0** [comment]
## Review

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/05cc4615-a522-4227-a092-f1327b5b5275"  width="600" height="auto"/> </td>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/5c09031e-5912-43f9-8bcc-2f05d07d66a5"  width="600" height="auto"/> </td>
  </tr>
</table>   


- [ ] Back button is out of safe area in Configure Map and all inner views

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3901
