### ISSUE TITLE
Next turn and Second next turn widgets disappear from custom profiles and can't be added

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd-iOS#3886]
### Description

In the default Driving profile, the next turn is displayed in the upper left corner prominently as shown below:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e2e8e689-c935-4d27-8603-52f7bd059db0"  width="300" height="auto"/> </th>
  </tr>
</table>

I created a custom profile named RV by copying the default Driving profile.  It worked for a while, but sometimes, the next turn disappears completely, which is bad because it's one of the most useful widgets:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/a42e308d-cde5-4cb5-867b-3e4bbd1988ff"  width="300" height="auto"/> </th>
  </tr>
</table>

I dug into the settings of the custom profile and found that the widgets don't appear in the left panel which has become empty:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/6592d6cb-0ffb-4db5-a83f-07d435762997"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/b547016d-a468-4aa5-a52a-02c4855977d2"  width="300" height="auto"/> </th>
  </tr>
</table>

And I cannot add the widgets back to the panel at all!

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f6325bd1-ac1d-47cf-a01e-beea8ecfc78a"  width="300" height="auto"/> </th>
<th><img src="https://github.com/user-attachments/assets/fbe8146b-af4d-4eab-afc3-019af670a414"  width="300" height="auto"/> </th>
  </tr>
</table>

The only fix was to delete the profile and copy it again, but after a few days, the next turn widget disappeared again.

### Steps to reproduce

Copy the driving profile.

### Actual result

See above.

### Expected result

The Next turn and Second next turn widgets should not disappear from a copied custom profile.

This is what they look like in the default Driving profile which is working correctly.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/1d826ce2-536c-46e6-9bb4-f5fce4d63993"  width="300" height="auto"/> </th>
  </tr>
</table>

### Your Environment (required)

```
OsmAnd Version: 4.7.6.3
Android/iOS version: 17.5.1
Device model: iPhone 15 Pro Max

```

**Comment by yuriiurshuliak** [comment]
The bug cannot be reproduced. To test this, I navigated using a standard driving profile, then created a custom profile by copying all the widgets from the driving profile. I also tested it after some time and after updating the app.

As a result, during navigation on the custom profile, the Next Turn and Second Next Turn widgets were successfully displayed and did not disappear.

This issue might be related to the creation of a custom public transport profile. I also couldn't display these widgets on public transport. Try creating a custom profile using the driving navigation type and see if the bug persists. Additionally, test if this issue occurs on the beta version: https://testflight.apple.com/join/7poGNCKy

OsmAnd 4.8.0.6

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/ea6637bb-57be-4dcf-adee-a182447fc023"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/0ba37f96-4100-45eb-b556-79cb6c03a0a1"  width="300" height="auto"/>   </td>
  </tr>
</table>
