### ISSUE TITLE
Offline map for USA / Alaska does not seem to be updating properly

### ISSUE THREAD

**Issue by kevinp2** [osmandapp/OsmAnd-iOS#3887]
### Description

I am traveling in Alaska and have been updating OSM as I go.  I have noticed that recently, the Alaska map is not showing up to date information.  Daily and hourly updates seem to run without error, but without the expected result.  One of many examples:

Nearly 12 days ago, I updated an RV park in Fairbanks, Alaska.  Here's the OSM link, with buildings and roads added and named: https://www.openstreetmap.org/way/209308535

Here's what the map looks like online:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/00b1ff1d-9fad-4454-8056-21731e7b3803"  width="300" height="auto"/> </th>
  </tr>
</table>

But this is what it looks like today in the OSMAnd app, without my updates:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/70e02a2d-3bdd-408d-b550-8fe85ccad913"  width="300" height="auto"/> </th>
  </tr>
</table>

The app claims that its last update was Aug 1, even though this data was added several days ago. 

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/00b1ff1d-9fad-4454-8056-21731e7b3803"  width="300" height="auto"/> </th>
  </tr>
</table>

But this is what it looks like today in the OSMAnd app, without my updates:

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/cc7a86a4-5fe5-4478-96be-6ac620aca161"  width="300" height="auto"/> </th>
  </tr>
</table>

Perhaps something is stuck in the map backend process?

### Steps to reproduce

See above.

### Actual result

See above.

### Expected result

Changes to OSM should be reflected in the downloaded offline map within a few hours.

### Your Environment (required)

```
OsmAnd Version: 4.7.6.3
Android/iOS version: 17.5.1
Device model: iPhone 15 Pro Max

```

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce this issue, go to these coordinates: 64.8343, -147.5153. Download the Alaska map and enable live updates for it.

As a result, you will notice that the application does not display the current information about RV park names. However, this information is displayed in the web version and in OSM.

Here is the link to the web version: [Web Version](https://test.osmand.net/map/navigate/?start=64.834300,-147.515300&profile=car#16/64.8345/-147.5176)
Here is the link to OSM: [OpenStreetMap](https://www.openstreetmap.org/way/209308535#map=16/64.8343/-147.5153)

OsmAnd~ 4.9.0#2887m, released: 2024-08-01

<table style="width:100%">
  </tr>
  <tr>
    <th>Mobile app</th>
    <th>Web version</th>
    <th>OSM</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/11e91823-d157-4506-90ca-b5fa5d93c622"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/a1bdfcea-4323-4dd8-bbd1-ce29b3a5bdae"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/6fd6e109-af56-4303-8077-482ccbae2037"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by kevinp2** [comment]
I would like to request to prioritize this issue if possible 🙂

I am on a trip to Alaska, adding items to the map on a recon trip, and expecting to be able to use them on my return to the same place.

Unfortunately, they are still not available. For example, this parking spot was added 17 days ago.   I could not find it in the app today.🥲

https://www.openstreetmap.org/way/1302376226

Thanks in advance 🙏

**Comment by Martin868** [comment]
This essentially make the paid service live update inoperative. Could it be prioritized? Thanks.

**Comment by vshcherb** [comment]
Reproduced with 
[Us_alaska_northamerica_24_07_00.obf.zip](https://github.com/user-attachments/files/16496432/Us_alaska_northamerica_24_07_00.obf.zip)

**Comment by vshcherb** [comment]
Unfortunately we wouldn't be able to backport changes to old months, so please use August maps and live maps later on

**Comment by kevinp2** [comment]
Thanks.  When will the August maps become available?

**Comment by vshcherb** [comment]
august maps are ready to download

**Comment by Martin868** [comment]
I just did a test Downloaded the Aug map update, deleted the LiveUpdates from the phone storage, which triggered a re-download of them. Issue still present, no update. Is the fix global or it needs to be applied to my specific region I have issue with. I use the Quebec-Canada-Northamerica map, at least that is the one I see the issue with.

**Comment by ivanPyrohivskyi** [comment]
@Martin868 all new updates on OSM will be in Live Updates from this August 06 2024 (today). Unfortunately we wouldn't be able to backport.
