### ISSUE TITLE
Voice output auto language selection doesn't work

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3892]
### How to reproduce
* Device language is English, OsmAnd language is English
* **Menu** – **Settings** – **Driving profile** – Reset settings
* **Driving** profile – **Navigation settings** – **Voice prompts** – **Language**

### Actual result

<table style="width:100%">
  <tr>
    <th>OsmAnd Settings</th>
    <th>Device settings</th>
    <th>OsmAnd Voice prompts</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/f201a6c4-9fe9-4834-b7a9-6b00394d5a70"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/e0145c02-40fa-426b-be2e-ca25892dadb2"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/33a748ad-cd46-4af2-ab24-eb098900b4c5"  width="300" height="auto"/> </td>
  </tr>
</table>  

* Language is not preselected

### Expected result

* Pre-select language

**Environment**
OsmAnd Version: 4.8.0.9
iOS version: 18.4
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3922

**Comment by DmitryAlexei** [comment]
4.8.3.0 fixed
