### ISSUE TITLE
Add support for iOS 18 dark / tint app icon

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3893]
<table style="width:100%">
  <tr>
    <th>Current</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d6f776c8-2111-42d5-9b85-9daaf5db3e97"  width="375" height="auto"/> </td>
  </tr>
</table>  

https://developer.apple.com/design/human-interface-guidelines/app-icons

**Comment by vshcherb** [comment]
Update build machine.
