### ISSUE TITLE
Unresponsive bottom buttons on map screen after start

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3895]
## Description
Sometimes after app launch bottom buttons on the map screen are unresponsive.

### How to reproduce
* Install OsmAnd
* Start OsmAnd

### Actual result

<table style="width:100%">
  <tr>
    <th>Menu Button</th>
    <th>Bottom buttons in Navigation</th>
  </tr>
  <tr>
    <td><video src="https://github.com/user-attachments/assets/0078224b-361e-422f-ae82-c520998404e8"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/53d4e6a0-7e5c-41f0-8b06-67d43706828f"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Menu button works few times

### Expected result

**Environment**
OsmAnd Version: 4.7.6 / 4.8.0.8
iOS version: 17
Device model: iPhone 11 / iPhone 15

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3903
