### ISSUE TITLE
Help labels

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3900]
### How to reproduce
* Launch latest version of OsmAnd
* **Menu** – **Help**
* Scroll down **User guide** – **Map**

### Actual result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/52398274-d508-416b-97bb-2c7df796b207"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Empty string name is displayed 

### Expected result

* Use `label` from json if string is not available. Labels for Route and Track are present in file
* * Original file https://osmand.net/help-structure.json

**Environment**
OsmAnd Version: 4.8.0.8
iOS version: 18.4
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3907
