### ISSUE TITLE
Crashes 4.7-4.8

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3902]
<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/user-attachments/assets/3c759dd3-af7e-4870-81e8-f4e266b9208f"  width="600" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [ ] `OAPOlHelper findPOlsByFilter:topLatitude:leftLongitude:bottomLatitude:rightLongitude:.`
* * Xcode link – `xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=mloeUg0UN9MdcERx7Er7_&bundleId=net.osmand.maps
`

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/user-attachments/assets/4adb8775-e11f-451c-8675-d3201def67fa"  width="600" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] `OARoutePlanningHudViewController tableView:cellForRowAtindexPath:`
* * Xcode Link – `xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=CT6DLX9AJXc_pi_YUpZ6IW&bundleId=net.osmand.maps
`

- - -

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <td><img src="https://github.com/user-attachments/assets/be3ae6b0-830e-44e1-b3ba-23b5413000ba"  width="600" height="auto"/> </td>
      </tr>
    </table>
</details>  

- [x] `UlViewCommonInitWithFrame`
* * Xcode link – `xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=KHCHc9PGuzVc1QsoJP7so&bundleId=net.osmand.maps`

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3910

**Comment by DmitrySvetlichny** [comment]
The specified crashes were not reproduced.
Implemented code improvement.
