### ISSUE TITLE
Contour lines suspicious size increase after recent update

### ISSUE THREAD

**Issue by amkoro** [osmandapp/OsmAnd-ios#391]
Hello,
I'm using the recent iOS version of OSMAnd. After recent update of contour lines for some European countries I noticed the total storage on my iPhone used by OSMAnd app is significantly increased. I expect some non-significant increase each time I update the maps because some new data added on maps daily. But contour lines should not be changed at all.

Please check - possibly there is an issue in data format.

**Comment by vshcherb** [comment]
contour lines now has an improved version, so increase of 20-30% is expected cause more detailed data is available.

**Comment by amkoro** [comment]
thank you for describing

I noticed they were updated again
