### ISSUE TITLE
When changing building number - we need more than a numeric pad [OSM editing] 

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#3914]
In osmand 4.8.0.12, when I try to edit the street name of a POI, I only get a numeric pad. That doesn’t let me type the correct input in some countries. In Australia for example, numeric address can be written like « 7/64 » or in France some numeric address also have « bis » or « ter » after the number

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/369e9f8a-a426-449d-9b3b-0ab8e3c4ad3b"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/df726645-48ac-4e1d-958c-fbe80331edc0"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
TestFlight 4.8.2.0
- when changing street name full keyboard opens
- when changing building number only short (digits) keyboard opens
- long tap on the digits keyboard doesn't input Latin letters 


<table style="width:100%">
  <tr>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/004758e4-9e04-4ea3-854f-2a6d5af42b68"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/3bf2ac8a-0218-463a-ac2a-188a79966c66"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/15d6c5d0-349c-4e93-9e3f-2c36c878210c"  width="300" height="auto"/> </td>
  </tr>
</table>

Steps to reproduce:
- enable OSM editing plugin
- tap on a POI and in POI contex menu choose > Modify POI
- tap on a building number

**Comment by tigrim** [comment]
**Technical plan**

use `.keyboardType = .default`


![Image](https://github.com/user-attachments/assets/b80aa0a3-91bc-443f-9aa6-52e70985cbf1)

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3984

**Comment by dmpr0** [comment]
# Review
This new implementation is required to switch to numbers mode each time you need enter building number.
