### ISSUE TITLE
Missing icons on external Full HD display – macOS

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3916]
> Part 2 for https://github.com/osmandapp/OsmAnd-iOS/issues/3832

### How to reproduce
* Launch OsmAnd on any Apple computer with external **Full HD monitor**
* Open Menu – Navigation – Set destination, wait until route is calculated 
* Tap on Details 

### Actual result

<table style="width:100%">
  <tr>
    <th>Route Details</th>
    <th>Analyze</th>
    <th>Plan a route</th>
    <th>Search</th>
    <th>Search, empty state</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/ac8b534a-f6d7-4690-b60a-a066517a6f3f"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f5c4343b-27ab-49c2-8b3f-752c5c878a84"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/2eecd430-5585-46d9-989b-10cf56309baf"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/d29ee4e4-e1db-47af-a6a3-3f975945f861"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/ea33fd84-ddad-47f7-962f-61f07a5ed4e1"  width="300" height="auto"/> </td>
  </tr>
</table>   

### Expected result

- [x] Route details
- [x] Analyze on map
- [x] Plan a Route
- [x] Direction arrow in Search
- [x] Search, empty state

**Environment**
OsmAnd Version: 4.8.1.0
OS version: macOS Sonoma 14.4.1 (23E224)
Device model: MacBook Pro 14", 2021 with External Full HD Monitor

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.1.4924`

Tested on a 4K external monitor - **Fixed**

<img width="1920" alt="Screenshot 2024-12-17 at 10 28 09" src="https://github.com/user-attachments/assets/747f3e5d-4ded-4565-ab09-a9dad27e93f3" />
<img width="1920" alt="Screenshot 2024-12-17 at 10 30 24" src="https://github.com/user-attachments/assets/0db3ade1-7d34-447a-814f-9611d513f335" />
<img width="1920" alt="Screenshot 2024-12-17 at 10 31 44" src="https://github.com/user-attachments/assets/d622c776-a550-4794-bf6c-314c8c768861" />
<img width="1920" alt="Screenshot 2024-12-17 at 10 32 10" src="https://github.com/user-attachments/assets/30cd2c84-8efb-4c94-99c6-9ff62b99291e" />
