### ISSUE TITLE
Next corner widget stops updating on Carplay device

### ISSUE THREAD

**Issue by ToontjeM** [osmandapp/OsmAnd-iOS#3925]
After a while, especially when the next corner is several km away, the next corner widget on the Carplay device stops responding.

Not been able to reproduce it and determine root case. I know it usually happens when the next corner is more than 10km away. When the next corner is here, the widget has stopped responding. Map continues to funcion correctly in the background.

OsmAnd 4.8.0.12 on iOS 17.5.1

**Comment by vshcherb** [comment]
We are going to provide public beta tomorrow with fixes related to Car Play. Later this build will be submitted to review and public release

**Comment by ToontjeM** [comment]
Thanks! Available on TestFlight?

**Comment by vshcherb** [comment]
Today build is available, please try that.

**Comment by ToontjeM** [comment]
TestFlight is still 4.8.0.12

**Comment by ToontjeM** [comment]
TestFlight is still 4.8.0.12

**Comment by vshcherb** [comment]
I will ask should be available 4.8.2 tomorrow.

**Comment by dmpr0** [comment]
> TestFlight is still 4.8.0.12

I have added 4.8.2.0 to public TestFlight builds, it should be available in a few hours.

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/befdf5e6-a8ce-4cd3-a06b-31ba911fc339"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f845cd3d-4330-49c0-81c3-3be54523cda9"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/afacf47c-4680-4891-baea-39469f22d3ca"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/c486cd67-205e-4d89-88d2-84385996aed5"  width="300" height="auto"/> </td>
  </tr>
</table>  

Testing on CarPlay simulator on the latest 4.8.2.1 build.
