### ISSUE TITLE
Plural strings are handled incorrectly

### ISSUE THREAD

**Issue by yarons** [osmandapp/OsmAnd-ios#393]
Please change the current handling of plural forms because days 2-4 is irrelevant for Hebrew, we have 1, 2 up to 10 and above.

This is the proper way to to it:
https://crunchybagel.com/localizing-plurals-in-ios-development/

**Comment by max-klaus** [comment]
Thank you for the suggestion, but we do not have Hebrew translation yet in the iOS version of the OsmAnd.

**Comment by yarons** [comment]
It's relevant to many other languages…
It's considered bad practice from i18n perspective.

It doesn't bother me right now but just in case it will bother someone in the future.

Thank you :)
