### ISSUE TITLE
POI Overlay not saved in Configure Map

### ISSUE THREAD

**Issue by clwacker** [osmandapp/OsmAnd-iOS#3937]
For some time now (since at least 2-3 older versions), when using the Configure Map menu and selecting POI Overlay, the POI selection only works for a moment. If you switch to other applications or wait a while, the POI Overlay selection is erased. If you restart OsmaAnd, the selection is also lost. It's as if POI Overlay wasn't saved by Configure Map.

**Comment by yuriiurshuliak** [comment]
The issue could not be reproduced. I enabled the POI Overlay and added Parking, then switched to several other applications, leaving OsmAnd in the background. When I returned, the Parking POI was still visible.

However, if you add a POI, completely close the app, and then reopen it, the POI will disappear, and the setting will reset. This behavior may be expected.

OsmAnd 4.8.2.1

https://github.com/user-attachments/assets/ad1f621f-2a96-4240-95e5-4f420e74e3f9

**Comment by clwacker** [comment]
Thanks for your test, but I don't understand why it is normal for the POI Overlay to be reset when the application is restarted.
 I think that all items in Configure Map should be saved. This is the case for all other items, why not POI Overlay?

Being a big OSM contributor, I now understand that this is the problem I'm having because I use OsmAnd Live and every time the maps are updated, the application is somehow restarted and the POI Overlay is lost.

So it would be very useful if OsmAnd could save the POI Overlay in Configure Map.
Many thanks in advance.

**Comment by vshcherb** [comment]
> If you restart OsmaAnd, the selection is also lost. It's as if POI Overlay wasn't saved by Configure Map.

Nope we didn't reproduce, all is saved after restart, kill, and switch. Probably you can record video and it could help us
