### ISSUE TITLE
Unable to tap on stairs icon

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3955]
### How to reproduce
* Open map, go to `50.44022 30.51342`
* Try tap on stairs icon

### Actual result

* Tap doesn't work

### Expected result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th>Android</th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/37af7fe2-8315-45ee-88e7-00253abe5da3"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

* Tap on stairs should open context menu

**Environment**
OsmAnd Version: 4.8.2.1
iOS version: 18.5
Device model: iPhone XS Max

**Comment by nnngrach** [comment]
- (NSArray<OATargetPoint *> *) selectObjectsForContextMenu:(CGPoint)touchPoint showUnknownLocation:(BOOL)showUnknownLocation

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/81f2b819-9875-409c-94d5-66765b5e5233"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/02d9f087-5a9f-4744-ac4a-c08f50e4d400"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [ ] Missed OSM Link
- [ ] Missed Icon in Nearby POI item
- [ ] Why Android doesn't have Nearby POI?
