### ISSUE TITLE
Switch Navigation to first Car profile when connected to CarPlay

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3957]
## Description
Pedestrian routes showed up on CarPlay if **Default profile** is set to **Last used** and it was a **Walking** profile.

### How to reproduce
* Open **Menu** – **Settings** – **OsmAnd Settings** – **Default profile**
* Set to **Last used**
* Go back to map
* Open **Menu** – **Configure Map** 
* Switch profile to **Walking**
* Connect iPhone to CarPlay

### Actual result

<table style="width:100%">
  <tr>
    <th>Waking</th>
    <th>Car</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/4496299d-4113-45ab-aad5-ba037145b57b"  width="400" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/52467531-048f-4922-80a5-21c3150419be"  width="400" height="auto"/> </td>
  </tr>
</table>   

* Walking route will be calculated 

### Expected result

* Switch to first Car profile 

**Environment**
OsmAnd Version: 4.8.2.1
Android/iOS version: 18.0
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4002

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4008

**Comment by DmitrySvetlichny** [comment]
Fixed returning to the profile that was set before connecting to CarPlay after disconnecting from CarPlay.
Fixed route recalculation when changing the profile during active navigation when connected to CarPlay.
