### ISSUE TITLE
Wrong speedometer height on CarPlay

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3958]
### How to reproduce

**Prepare simulator:**
* Open **CarPlay Simulator** – **Configure** – **General** 
* **Main Display**, set to 800 x 480
* **Driving orientation** – **Left-hand Drive**
* **Status bar edge** – **Driver side**

**iPhone:**
* Turn on Speedometer in Configure Screen
* Run route simulation on iPhone

### Actual result

<table style="width:100%">
  <tr>
    <th>Left-hand Drive</th>
    <th>Right-hand Drive</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/1ca55b94-3709-4ffd-8909-273538a47155"  width="400" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f0a2597d-0f46-4d24-b958-ff69621ffd12"  width="400" height="auto"/> </td>
  </tr>
</table>   
 

* The speedometer is stretched from top to bottom

### Expected result

* Fixed square size

**Environment**
OsmAnd Version: 4.8.2.1
iOS version: 18
Device model: iPhone XS Max

**Comment by nnngrach** [comment]
not reproduced
<img width="300" alt="Screenshot 2024-10-07 at 19 08 43" src="https://github.com/user-attachments/assets/7bc7e93a-8788-49e7-bc86-fefff0374af3"> <img width="300" alt="Screenshot 2024-10-08 at 12 25 36" src="https://github.com/user-attachments/assets/a87f6d0c-4d25-4faf-967a-d3754c1ae256">
