### ISSUE TITLE
Different formatting of opening hours on CarPlay vs iOS

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3961]
### How to reproduce
* Launch CarPlay – tap on map – Navigation
* POI categories – Cafe and restaurants

### Actual result
<table style="width:100%">
  <tr>
    <th>CarPlay</th>
    <th>iPhone</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/9f8e82c3-5fdd-4dc0-96f4-1da516500984"  width="500" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/74cffd91-7f20-41bd-a50b-f58ae69bee5a"  width="300" height="auto"/> </td>
  </tr>
</table>   

* CarPlay – shows full tag info `Mo-Fr 08:00-21:00; Sa,...`
* iOS – show if POI is closed or Open

### Expected result

* Show if POI is closed or Open

**Environment**
OsmAnd Version: 4.8.2.1
iOS version: 18
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4011
