### ISSUE TITLE
Decrease default min. zoom

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3965]
Currently app can launch on min zoom. We can decreased to more normal view.

## iPhone
<table style="width:100%">
  <tr>
    <th colspan=2>Zoom leve = 1</th>
  </tr>
  <tr>
    <th>Landscape</th>
    <th>Portrait</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/80fd3042-237a-4329-834e-2cb854f9ea60"  width="600" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/1b7c222a-3ee3-424e-a65d-b28d7c4e54c6"  width="300" height="auto"/> </td>
  </tr>
</table>   

## iPad Pro 13-inch

<table style="width:100%">
  <tr>
    <th colspan=2>Zoom leve = 1</th>
  </tr>
  <tr>
    <th>Landscape</th>
    <th>Portrait</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/7717fd71-cae5-49a3-82e4-687577ee36f7"  width="600" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/faefebe4-abaa-4b92-8e54-5a5b1861808e"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <td><img src=""  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] It's hard to change zoom

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/5ac857a2511ce6a6d5fa6e93f2c5cfed4f3eb884

**Comment by dmpr0** [comment]
<table style="width:100%">
  <tr>
    <th>Android</th>
    <th>iOS</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a20f3bc9-550d-4c49-89d8-d72895e994ee"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/97869056-6924-4797-b5a8-5b562c8be0e6"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by dmpr0** [comment]
# Review

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/659b4b3e-3434-46aa-92a4-7f471b374c34"  width="300" height="auto"/> </td>
  </tr>
</table>   


- [ ] After app restart

**Comment by vshcherb** [comment]
- [ ] https://github.com/osmandapp/OsmAnd-iOS/issues/3988 problem is not found so it's not fixed. Zoom should not be reset after app restart

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4157

**Comment by Zirochkabila** [comment]
4.9.0.11
"Hard to change zoom" task - looks fixed
Priority task don't see any changes

**Comment by Zirochkabila** [comment]
[Still present](https://github.com/osmandapp/OsmAnd-iOS/issues/4182)
