### ISSUE TITLE
Destination is not pronouncing

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3970]
### How to reproduce
* Calculate route from `‎52.27993° N, 4.95366° E‎` to ‎`52.28603° N, 4.94535° E‎`
* Run Simulation
 
### Actual result

<table style="width:100%">
  <tr>
    <td width="300" ><video src="https://github.com/user-attachments/assets/24e6a77f-4d7c-4e2e-8f2d-71be762199b6"  height="auto"/> </td>
  </tr>
</table>   

* Keep left onto exit two too.

### Expected result

<details>
    <summary>Android</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><video src="https://github.com/user-attachments/assets/de7b03ce-93d6-4e2c-853a-8c5e9a34d8c4"  width="300" height="auto"/> </td>
      </tr>
    </table>
</details>  

* Keep left onto exit two, towards A9.

**Environment**
OsmAnd Version: 4.8.3.0
iOS version: 18.0
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4002
