### ISSUE TITLE
Crash – Boat Route parameters 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3972]
### How to reproduce
* **Menu** – **Settings**
* Find **Boat** profile – **Navigation settings** – **Navigation type**
* Change to **Direct-to-point**
* Go back to **Navigation settings** screen – **Route parameters**

### Actual result

<details>
    <summary>Screenshot</summary>
    <table style="width:100%">
      <tr>
        <th></th>
      </tr>
      <tr>
        <td><img src="https://github.com/user-attachments/assets/6e498bae-9529-4f3d-af78-3aca9c269aa4"  width="600" height="auto"/> </td>
      </tr>
    </table>
</details>  

* Crash, xcode `xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=DDZUiO7F3Axru32XGvAueD&bundleId=net.osmand.maps`

### Expected result

* Route parameters

**Environment**
OsmAnd Version: 4.8.3.0
iOS version: 18.0
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/3996
