### ISSUE TITLE
the TTS voice German speaks at double speed since the last update

### ISSUE THREAD

**Issue by MBj1703** [osmandapp/OsmAnd-iOS#3974]
the TTS voice German speaks at double speed since the last update.
I see no options to change.
Reboot of the iPhone did not fix it.

**Comment by dmpr0** [comment]
Hi! 
You need to change it in iOS Settings:

**Adjust speaking rate**
To adjust the speaking rate:
* Go to **Settings** and tap **Accessibility**.
* Tap **Spoken Content**.
* Use the slider for **Speaking Rate** to adjust the speed.
https://support.apple.com/en-us/111798

**Comment by MBj1703** [comment]
Perfect, thanks a lot.
I was not aware about this option.
