### ISSUE TITLE
Track is visible in My Places after removing

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#3982]
### How to reproduce
* Go to **Menu** – **My Places** – **Tracks**
* Tap on track to open track context menu
* Tap on **Actions** – **Delete**
* Tap Yes

### Actual result

<table style="width:100%">
  <tr>
    <td><video src="https://github.com/user-attachments/assets/fdcf697c-55dc-4e5e-8b22-f595e06546cd"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Track is visible in My Places. After removing of the track, My places – Tracks will be reopened.

### Expected result

* Removing track from the list

**Environment**
OsmAnd Version: 4.8.3.0
iOS version: 18
Device model: iPhone XS Max

**Comment by tigrim** [comment]
It was fixed in RP https://github.com/osmandapp/OsmAnd-iOS/pull/4076
