### ISSUE TITLE
Bottom screen menu controls are invisible with iPhone Dark mode

### ISSUE THREAD

**Issue by n7ihq** [osmandapp/OsmAnd-iOS#3986]
The bottom screen controls in the "Panels" and "Displayed tracks" menus are invisible with iPhone in Dark mode. See screenshots.

<table style="width:100%">
  <tr>
    <th>Configure screen – Right panel</th>
    <th>Configure Map – Tracks</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/48622d82-1b9f-4dae-9d2a-17b7da7151aa"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/879ec0da-37ab-493e-9b9b-b5597f911f43"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
Related to https://github.com/osmandapp/OsmAnd-iOS/issues/3418

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce the issue, enable dark mode and enter the app. Then try selecting any track on the map, or navigate to Configure map → Tracks, or go to Configure screen and choose any panel.

You’ll notice that when dark mode is activated, the panel colors are inconsistent—one part appears dark, while the other part remains light.

Additionally, please let us know which iOS version you are using, as updating to the latest version might help resolve this issue.

OsmAnd Version: 4.8.3.0
iOS version: 16.4.1

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/5a336d60-c7f6-4b3e-89a3-63a725669027"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/ef97a955-128b-49f6-99a4-aac1ec41e26d"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/f010606c-6fc8-465b-a4cb-924601843036"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by dmpr0** [comment]
Don't reproducible on latest TestFlight build.
