### ISSUE TITLE
App startup  map display is zoomed out

### ISSUE THREAD

**Issue by valynor** [osmandapp/OsmAnd-iOS#3988]
iOS 17.6.1, iPhone 13 Pro Max + iPad Mini 5, OsmAnd 4.8.2.1

This has been going on for some months now so I thought I make a bug report: 

- when you launch the app sometimes (maybe 1 in 10-20 starts) the map displays max. zoomed out but still centred on your position
- sometimes the black launch screen is not displaying correctly, e.g. you launch the app, you immediately see the map and then the launchscreen for a split second and then back to the map
- when you close/terminate Osmand e.g. from the maps & resources screen on the next app launch you sometimes see that screen for ~0.2 sec and then the launch screen before the map displays. this happens quite often, perhaps 1 in 5-10 launches
- very rarely on app launch the map renders extremely slowly or only partly

I have a feeling that all of these issues might be connected somehow because they all showed up together starting several (6?) months ago.

**Comment by valynor** [comment]
Update: all the bugs as described above are still present in iOS/iPadOS 18.0

**Comment by dmpr0** [comment]
Hi!
For first item we already have issue https://github.com/osmandapp/OsmAnd-iOS/issues/3965. Other mentioned issue need to be reproduced.

**Comment by valynor** [comment]
I was lucky and caught 2 of the bugs immediately: 

https://github.com/user-attachments/assets/2b53c4b9-8c31-4078-adc9-8c7fdf72c11d

Notice that on the first try OSMand opens correctly: 

1. I tap the icon
2.  the app displays the dark launchscreen 
3. the map appears

I then terminate the app from the app launcher (yes, I do that every time). 

5. I tap the OSMand icon again
6. immediately the map is shown
7. followed by the launch screen
8. map again but OSMand "lost" the zoom level and is all zoomed out 

These issues happen rather regularly - I'd say somewhere between 1 in every 5 to 15 launches. Sometimes several consecutive times.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. Based on my observations, there aren't any specific conditions for it to occur consistently—it may not show up for 15 launches, but then appear on the 16th.

To reproduce the issue, start the app, wait for the launcher and map to load, then close the app and relaunch it.

When you click the app icon, instead of the usual launch screen, the map may briefly appear before the launch screen shows. Additionally, the app may open with the map zoomed out to the maximum, displaying the entire world map.

OsmAnd 4.8.3.5

https://github.com/user-attachments/assets/c92f129b-f498-4b7b-9743-942b1483ab4d

**Comment by valynor** [comment]
> the map may briefly appear before the launch screen shows

One more comment on that: when you terminate the app e.g. with the Maps&Resources screen open _that_ screen will briefly appear before the launch screen (if the bug gets triggered). 
I assume it always show the last screen that was visible.

**Comment by valynor** [comment]
@dmpr0 
Any update now that the bug has been reproduced?

**Comment by dmpr0** [comment]
@valynor 
As I mentioned earlier issue with zoom level on start has separate issue https://github.com/osmandapp/OsmAnd-iOS/issues/3965, and fix it on review phrase. 

All other described cases are seems to me as default iOS behaviour, it takes screenshot of the app before terminating it. As I understand we can replace snapshot with launch screen, so OsmAnd snapshot will be shown in the app switcher or we can remove the launch screen when the app becomes active again.

**Comment by valynor** [comment]
@dmpr0 
I am talking specifically about the launch screen issue as shown in the videos above. 
This is definitely not "default iOS behaviour" as **none** of my other apps do this.

**Comment by vshcherb** [comment]
> when you launch the app sometimes (maybe 1 in 10-20 starts) the map displays max. zoomed out but still centred on your position

This is not clear what's the reason however I didn't manage to reproduce with latest test flight probably those 2 bugs are connected.

**Comment by vshcherb** [comment]
The issue is merged to https://github.com/osmandapp/OsmAnd-iOS/issues/3965

**Comment by valynor** [comment]
@vshcherb 
Issue seems to be fixed. Thanks!

**Comment by valynor** [comment]
@vshcherb 

I think the "app starting all zoomed out" is fixed. 👍 

The other bug I reported above is NOT fixed: The app still sometimes start with no splash screen or some other page briefly displayed instead of the splash screen.
