### ISSUE TITLE
Dirt bike trails in Configure Map

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4000]
## ToDo

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d336021a-ab7f-4ddf-a82e-8661953bfd2c"  width="400" height="auto"/> </td>
  </tr>
</table>   

- [x] Use icon – `ic_action_dirt_motorcycle`
- [x] Rename to `Dirt bike trails`

- - - 

> Android task 
> * https://github.com/osmandapp/OsmAnd/issues/18756

**Comment by rachellawson** [comment]
Very happy to test this once we have something. Been using a slightly hacky way of doing this kind of thing on my maps so far…
