### ISSUE TITLE
Track context menu / appearance screen opens with delay for 1000 km long track

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4027]
### How to reproduce
* Import long track  [2022-08-22_07-58_Mon.gpx.zip](https://github.com/user-attachments/files/17145771/2022-08-22_07-58_Mon.gpx.zip)
* Go to **Menu** – **My Places** – **Tracks** 
* Find imported track, tap on it to open context menu
* Tap on **Appearance** button

### Actual result

<table style="width:100%">
  <tr>
    <th>Context menu</th>
    <th>Appearance</th>
    <th>Color change</th>
  </tr>
  <tr>
    <td><video src="https://github.com/user-attachments/assets/83b76b28-9ab8-4af9-b757-370bc04e6657"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/c79e993a-f9c7-4572-91a5-92810a9afd69"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/2290a807-c416-4928-ab59-53dad0851e64"  width="300" height="auto"/> </td>
  </tr>
</table>  

* Context menu opens with a delay 
* Appearance screen opens with a delay
* Changing track coloring to gradient with a delay 

- - -

<details>
    <summary>Screenshot</summary>

<img src="https://github.com/user-attachments/assets/e35bf224-0682-4215-914e-9fe32f0a7a7b"  width="300" height="auto"/> 

</details>  

* Crash – `xcode://organizer/crashes/downloadPoint?adamId=934850257&platformId=iOS&installPlatformId=iOS&analyticsPointId=GK6RU_NhbRKlM-WGeuYYm&bundleId=net.osmand.maps`

### Expected result

* No delay 

**Environment**
OsmAnd Version: 4.8.3.5
iOS version: 18
Device model: iPhone XS Max

**Comment by DmitrySvetlichny** [comment]
GPX File Loading Time:
Short track: 169.380 ms
Long track: 2273.238 ms
Difference: 2103.858 ms
Analysis: Loading the GPX file is the most resource-intensive operation for long tracks. The huge difference in time indicates inefficiency in the loading process as the data volume increases. In this case, short tracks are in the range of 100 - 200 km, while long tracks are more than 1000 km long.

Time to Execute super initWithGpx:
Short track: 80.686 ms
Long track: 443.971 ms
Difference: 363.285 ms
Analysis: The time spent on basic class initialization also significantly increases for long tracks, which may indicate additional computational or memory-intensive operations related to the size of the data.

Time to Calculate the Document Center:
Short track: 1.876 ms
Long track: 18.959 ms
Difference: 17.083 ms
Analysis: Even the simple calculation of the document center becomes more costly as the track size increases.

Total Time to Execute doShowGpxItem:
Short track: 315.292 ms
Long track: 2790.058 ms
Difference: 2474.766 ms
Analysis: The overall processing time significantly increases for long tracks, confirming that the main time expenditures are related to loading and processing large volumes of data.
This detailed information can be added to your task or report to provide clear evidence of performance bottlenecks when dealing with GPX tracks of varying lengths.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4151

**Comment by Zirochkabila** [comment]
4.9.0.9

- [ ] Still present

Context menu opens with a delay
Appearance screen opens with a delay

Changing track coloring to gradient with a delay - **DONE**


https://github.com/user-attachments/assets/95213eb1-d347-4a20-bd83-a4e187168014
