### ISSUE TITLE
Pin on map doesn't move when using Analyze on map option

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#4033]
### Description
Pin on map doesn't move when you select a specific point on a graph (Analyze on map screen)
Issue was introduced by https://github.com/osmandapp/OsmAnd-iOS/issues/3731  
This issue is blocker for https://github.com/osmandapp/OsmAnd-iOS/issues/3976

### Steps to reproduce
- Tap the track → Options → Analyze on map or tap the track > track screen
- Pick up one or more points on the track and see if the Pin on map is shown

### Actual result
- Pin on map moves near start point of the track (or doesn't move at all)
- see screen recordings

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video src="https://github.com/user-attachments/assets/51e5eba9-42f2-415a-abf4-e6cd81ea51be"  width="300" height="auto"/> </td>    
<td><video src="https://github.com/user-attachments/assets/5469035b-92f1-4f9a-a23b-5d061fd6a264"  width="300" height="auto"/> </td>
  </tr>
</table>

### Expected result
- Sliding along the graph should mark the corresponding location on the map with pin

iPhone 11 iOS 16.4.1
iPhone 13 mini iOS 18.0

**Comment by Skalii** [comment]
- [ ] open track from Hiking - missing Title
- [ ] save the track from Hiking and still in the open Track Menu make some kind of interaction - nothing will happen

**Comment by Skalii** [comment]
coordinate data is long converted
`_locationMarker->setPosition(OsmAnd::Utilities::convertLatLonTo31(OsmAnd::LatLon(trackPoints.highlightedPoint.latitude, trackPoints.highlightedPoint.longitude)));`

**Comment by Skalii** [comment]
- [ ] incorrect work of pin on general segment
- [ ] incorrect work of pin on other segments of the multi-segment track

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4156

**Comment by Zirochkabila** [comment]
4.9.0.9
Still reproduce

https://github.com/user-attachments/assets/85f0cfd4-b6af-41e2-a368-6bdc3949eeca

**Comment by Zirochkabila** [comment]
4.9.0.11
Done
