### ISSUE TITLE
Use translated strings for new Help pages

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4036]
> Android task https://github.com/osmandapp/OsmAnd/issues/20558

- [x] Navigation – Route parameters: `help_article_navigation_routing_name`
- [x] Map – Tracks: `help_article_map_tracks_name`
- [x] Map – Routes: `help_article_map_routes_name`
- [x] Personal – Color schemes: `help_article_personal_color_palette_schemes_name`

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4130
