### ISSUE TITLE
Importing from Organic Maps to Osmand

### ISSUE THREAD

**Issue by Rlatchu** [osmandapp/OsmAnd-iOS#4043]
I'm trying to import favourites from Organic Maps app into OsmAnd Maps. I've tried several ways and each time failed, invariably with the OsmAnd Maps app freezing. Latest app version, iPhone 14, etc.

**Comment by dmpr0** [comment]
Hi! Which file extension did you select? Try to export GPX.

**Comment by Rlatchu** [comment]
Hi, I used GPX.

Regards,
Rainier
***@***.***

**Comment by yuriiurshuliak** [comment]
I tested this on my end. The favorites file from Organic Maps was in .kmz format, and I also couldn't import it into OsmAnd on iOS, receiving the error "Cannot import specified GPX file." However, after converting the file to GPX format using this resource: https://www.gpsvisualizer.com/convert_input, I was able to successfully import it.

For further investigation, please provide us with your export file from Organic Maps so we can check it on our end. You can zip the file for GitHub, or alternatively, send it to us at osmand.help@gmail.com.

**Comment by Rlatchu** [comment]
Hi,

I tried your link, but still not workin. I must be doing something wrong.
Please find the file attached below.

Regards,
Rainier
***@***.***

**Comment by Rlatchu** [comment]
Hi,
Thank you for your help. It is working.

Regards,
Rainier
***@***.***
