### ISSUE TITLE
i18n: Missing translation for regional map name (German locale)

### ISSUE THREAD

**Issue by justjoheinz** [osmandapp/OsmAnd-iOS#4044]
I use OsmAnd 4.8.2.1 on iOS with German locale. 
When I go to "Karten & Resourcen" -> "Europa" -> "Deutschland" -  I can see the regional sub maps of Germany. They are all translated, e.g. "Bayern" instead of "Bavaria", "Sachsen" instead of "Saxony" etc. 

However there is one missing. "Lower Saxony, Bremen" would be "Niedersachsen, Bremen".

**Comment by yuriiurshuliak** [comment]
The names of the regional maps, such as "Lower Saxony, Bremen," are pulled directly from the relevant resource databases. It is important to note that while OsmAnd translates some regional names into German, others may still appear in English depending on the source data.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/7d99bcf6-ba54-4ae7-b2b6-41d7152745f9"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by xmd5a2** [comment]
Should be fixed. Map data from regions.ocbf:
_Way types [osmand_region-yes (4)] add_types [region_roads-yes(18), region_srtm-yes(12), region_map-yes(19), region_wiki-yes(24), region_join_map-yes(124)] Names [name:en(23) - Lower Saxony, Bremen, name:ar(25) - سكسونيا السفلى, بريمن, **name:de(17) - Niedersachsen, Bremen**, name:eo(32) - Malsupra Saksio, Bremeno, name:fa(40) - نیدرزاکسن, برمن, name:fr(15) - Basse-Saxe, Brême, name:hu(26) - Alsó-Szászország, Bréma, name:la(70) - Saxonia Inferior, Brema, name:mk(68) - Долна Саксонија, Бремен, name:pl(22) - Dolna Saksonia, Brema, name:pt(37) - Baixa Saxônia, Bremen, name:ru(10) - Нижняя Саксония, Бремен, name:sk(52) - Dolné Sasko, Brémy, name:uk(14) - Нижня Саксонія, Бремен, region_full_name(1) - europe_germany_niedersachsen, region_parent_name(5) - europe_germany, region_lang(8) - de, download_name(3) - germany_niedersachsen_europe, key_name(2) - niedersachsen, region_suffix(6) - europe, region_prefix(7) - germany] id -20659085 osmid -161400_

Please retest.
