### ISSUE TITLE
Bad behaviour / bug on displaying current location

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-ios#405]
When the location is imprecise OSMAnd as many other app show an area of uncertainty. But if you move the map, and the center of this area goes off screen, then the “location” is no more displayed.
I would like the area to be drawn even if the center is off screen because it helps me find my actual position by reducing the area I should inspect to manually find my position.

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-core/commit/962ca76c9e2539b5f82700e51973b4482ea96947
