### ISSUE TITLE
Long search/navigation history slows down app

### ISSUE THREAD

**Issue by MagielBruntink** [osmandapp/OsmAnd-iOS#4058]
Hard to replicate this one: I notice that having a long (100+) search and/or navigation history slows down many aspects of the app, including panning around on the map. After clearing, the app feels overall a lot more responsive. Is the search history being processed every frame or app refresh?

**Comment by yuriiurshuliak** [comment]
I don't have the exact details on how often the search history is processed per frame or during app refreshes, but it is plausible that frequent data retrieval and updates could contribute to the observed slowdown.

I tried to reproduce this bug myself and have a search history of over 100 entries. I tested various functions, including panning the map, zooming, starting navigation, and planning a route, and I did not notice any slowdown.

OsmAnd 4.8.5.2

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/554717dd-5d32-48e4-9a47-2a57e3db235e"  width="300" height="auto"/> </th>
  </tr>
</table>
