### ISSUE TITLE
Show City name for search results

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4071]
Depends on https://github.com/osmandapp/OsmAnd/issues/21052
Android task https://github.com/osmandapp/OsmAnd/issues/2993

**Comment by Zirochkabila** [comment]
Done
[MAP](https://github.com/osmandapp/OsmAnd/issues/2993#issuecomment-2431214499)
`‎48.78986° N, 9.18304° E‎`




<table style="width:100%">
  <tr>
    <th>4.9.0.7</th>
    <th>OsmAnd~ 5.0.0#3821m, Released: 2024-11-27</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/c79551f0-9f2c-43c1-bf6e-428a53e7406d"  width="425" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/b1e9a586-69ca-4e3f-acea-860929428745"  width="300" height="auto"/> </th>
  </tr>
</table>
