### ISSUE TITLE
The map is unusably slow on macOS

### ISSUE THREAD

**Issue by gy-mate** [osmandapp/OsmAnd-iOS#4072]
1. Install the app on macOS
2. Open it
3. It's unusably slow

Example:
1. Wait 15 seconds for the app to load
2. The map is still not fully loaded
3. Click on Zoom out
4. The zoomed out map doesn't load for a few seconds 
5. The app crashes

_OsmAnd `4.8.4`–`4.9.0.5`
macOS `15.0.1`_

**Comment by DmitryAlexei** [comment]
It appears that the app is much faster on macOS 15.1.1
Tested using Nightly 4.9.0.4

Please try the latest TestFlight build https://osmand.net/docs/versions/nightly_versions#testflight

If you encounter a crash, please report it here, on Github. Please attach ips crash log to your issues. https://osmand.net/docs/user/troubleshooting/crash-logs#send-logs-from-ios-devices

**Comment by gy-mate** [comment]
> Please try the latest TestFlight build https://osmand.net/docs/versions/nightly_versions#testflight

@DmitryAlexei OsmAnd `4.9.0.4` on macOS `15.1.1` doesn't crash anymore, but it's still unusably slow:

https://github.com/user-attachments/assets/d108bb6d-2f19-458f-b484-c9ca8df8fc86

Anyways, here are the logs exported from the app: 
[Nov 25, 2024 08:57.log](https://github.com/user-attachments/files/17899671/Nov.25.2024.08.57.log)

Where can I find IPS files on macOS?

**Comment by vshcherb** [comment]
Can't confirm actually. MacOs - 15.1, OsmAnd - 4.9.0.6
https://github.com/user-attachments/assets/f844f837-db19-4f01-ba0f-a50e3062463d

**Comment by vshcherb** [comment]
Is it hardware dependent? What hardware do you have?

**Comment by gy-mate** [comment]
@vshcherb

Model Name:				MacBook Pro
Model Identifier:			MacBookPro18,3
Model Number:			MKGR3D/A
Chip:					Apple M1 Pro
Total Number of Cores:		8 (6 performance and 2 efficiency)
Memory:					16 GB

**Comment by vshcherb** [comment]
Did you try to fully reinstall it? I don't see any impact on GPU / CPU on my machine, so I suspect M1 Pro is more than enough. Also I will double check colleague with M1 Pro.
