### ISSUE TITLE
Missing Perl PATH after ./prepare.sh

### ISSUE THREAD

**Issue by kuajia** [osmandapp/OsmAnd-ios#408]
I am trying to run the ios-OsmAnd Project, after the 'repo init' and cloning the core and build Osm-and project, I run the prepare.sh script. 

The script reached the configuration of 'qtbase-ios' for 'ios.simulator.clang.static', but it failed because of this error : 

You need perl in your PATH to make a build from GIT.

I added the perl5.28.0 to the PATH: 

export PATH="/Users/_myUserName/perl5/perlbrew/perls/perl-5.28.0/bin/perl:$PATH"

**Comment by max-klaus** [comment]
Thank you!

**Comment by kuajia** [comment]
So there is no way to overcome this issue?

**Comment by max-klaus** [comment]
The addition perl to PATH is not related to OsmAnd build. It is related to perl installation.
