### ISSUE TITLE
Missed UI for Uploading changes when "Offline editing" is Off

### ISSUE THREAD

**Issue by gy-mate** [osmandapp/OsmAnd-iOS#4088]
1. Open the sidebar > _Plugins_ > _OpenStreetMap Editing_ > cogwheel at the top right
2. Turn off _Offline editing_
3. Go back to the map
4. Make an edit
5. Upload it to OSM
6. The changeset is uploaded without a comment. See https://www.openstreetmap.org/changeset/158592444 for example

I think that automatically adding a comment to the changeset (something like _'Deleted grit bin'_ in the case above) would make it more informative.

**Comment by dmpr0** [comment]
The issue is worse. After last redesign, we have lost UI that should be appeared to confirm uploading

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.1.4928` - Still present [OSM](https://www.openstreetmap.org/changeset/160383385#map=19/47.774233/11.270398)

<img width="1433" alt="Screenshot 2024-12-19 at 09 53 40" src="https://github.com/user-attachments/assets/6296e02e-6cda-4169-907b-dd9801ef2b75" />

**Comment by Zirochkabila** [comment]
# Retest 
Fixed - [OSM](https://www.openstreetmap.org/changeset/160384292#map=19/48.129553/13.987597)

<img width="1433" alt="Screenshot 2024-12-19 at 10 15 46" src="https://github.com/user-attachments/assets/58072f75-64b5-47ff-abf0-dbf2eefd99f5" />

**Comment by Zirochkabila** [comment]
@vshcherb Should some default comment be written instead of a blank text input field?

![photo_2024-12-19 10 27 53](https://github.com/user-attachments/assets/9e5f6fa7-543a-464a-ae77-41e856a74aef)

**Comment by dmpr0** [comment]
# Review 

- [ ] Close POI view after downloading changes (if offline editing is Off)
