### ISSUE TITLE
Crash Follow Track - Attach to the roads

### ISSUE THREAD

**Issue by Biker729** [osmandapp/OsmAnd-iOS#4099]
### Description

The same track works with Android without any problems.

The option “[Attach to roads > Start automatically](https://github.com/osmandapp/OsmAnd/issues/19745#top)” is also missing on IOS
which is very inconvenient every time the route is restarted.

### Steps to reproduce

When I press **Apply** on **Follow track** – **Snap to roads** the app crashes.

### Actual result

*  App crashes.
* The option “[Attach to roads > Start automatically](https://github.com/osmandapp/OsmAnd/issues/19745#top)” is also missing on IOS

### Expected result

* **Snap to roads** should work identically to Android.

### Your Environment (required)

```
IOS OsmAnd 4.8.4.1
Android OsmAnd 4.9.3
```

**Comment by Biker729** [comment]
GPX Datei wurde an [support@osmand.net](mailto:support@osmand.net) gesendet.

Mit Android OsmAmd funktioniert  diese GPX-Datei ohne Probleme.

Gruß

**Comment by yuriiurshuliak** [comment]
The bug has been successfully reproduced. To reproduce, import the provided [track](https://github.com/user-attachments/files/17679356/Nagoldtal.504km.zip) into both the Android and iOS apps, then enable and calculate navigation for this track on each platform.

Results:

- On iOS, starting the route calculation causes the app to crash immediately.
- On Android, the route along the track is calculated and attaches to the road as expected, without any issues.

Please find attached the log files from iOS:
[OsmAnd Maps-2024-11-08-162010.000.zip](https://github.com/user-attachments/files/17680169/OsmAnd.Maps-2024-11-08-162010.000.zip)


OsmAnd 4.9.0.1

https://github.com/user-attachments/assets/c6fc79c4-e024-43d2-877e-acd1e803ead0

**Comment by Biker729** [comment]
Dann kann der Fehler in der IOS App behoben und angepasst werden:

Erwartetes Ergebnis
Die Funktion „An Straßen ausrichten“ sollte identisch zu Android funktionieren.
