### ISSUE TITLE
Segment control to switch between Basic / Advanced mode is partially visible

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4112]
### How to reproduce
* Make sure that OpenStreetMap editing plugin is enabled
* Tap on map – select Create POI in context menu

### Actual result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/6471862d-55fd-4dae-a720-ca9e16405aa4"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Segment control is partially visible

### Expected result

* Fully visible segment control 

**Environment**
OsmAnd Version: 4.9.0.1
iOS version: 18.2
Device model: iPhone 16 Pro Max

**Comment by Zirochkabila** [comment]
<table style="width:100%">
  <tr>
 <tr>
    <th>4.9.0.3 - Reproduced</th>
    <th>4.8.4 - Not Reproduced</th>
  </tr>
<th><img src="https://github.com/user-attachments/assets/95c5fa42-57e7-47dd-8f01-0ae77c6a4799"  width="425" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/afc01883-9254-4211-805d-81ee190cca57"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by DmitryAlexei** [comment]
Cannot be reproduced on iOS 18.1
