### ISSUE TITLE
Recently downloaded Denmark contour lines map is displayed in updates

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#4127]
### Description
TestFlight 4.9.0.2 
Downloaded map is shown under updates and can never be completely updated

### Steps to reproduce
- menu > maps and resources > Europe > Denmark > download Contour lines map
- go back to maps and resources > updates and see if Denmark Contour lines map is present on this tab
- try to update that map

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/a20f1f25-f185-470f-b4a6-9afbaa2ff204"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/2ca85faa-25a3-4920-8892-32b19f141c9d"  width="300" height="auto"/> </td>
  </tr>
</table>

### Actual result 

https://github.com/user-attachments/assets/d72390ed-d856-489c-8f7d-bf0e02cb0450

### Expected result
- [ ] up-to-date maps should not be seen on Updates screen
- [ ] map should disappear from the Updates screen after downloading

**Comment by DmitryAlexei** [comment]
OsmAnd~ 5.0.0#3874m, released: 2024-12-04
Issue can also be reproduced on Android (fresh Nightly build) after app restart. For me, the Denmark contour lines map did not appear in Updates immediately after downloading the map.

https://github.com/user-attachments/assets/ff3dd396-9aed-483b-9368-3dde34d4c34c

**Comment by RZR-UA** [comment]
The problem should be fixed now.

@DmitryAlexei, please test:

- [ ] Android
- [ ] iOS

**Comment by Zirochkabila** [comment]
# Testing 1

`OsmAnd~ 5.0.0#3911m, Released: 2024-12-09` - **Done**
`4.9.0.14` - Cant testing (crashed)
