### ISSUE TITLE
Routes won't highlight

### ISSUE THREAD

**Issue by joehoe-its-me** [osmandapp/OsmAnd-iOS#4128]
Hi,
I’ve recently upgraded to the paid version of osmand. Since then existing routes (e.g. GR) that I select do not light up in red like they used to. 
The routes aren’t hidden, I can see all the details (distance, altitude, ...), they just don’t light up on the map so I can’t see where they start and begin.
I do not have this problem with tracks I've created myself. Also with imported GPX files everything works fine. 

**These are the things I've tried:**
- check for app updates
- delete and reinstall the maps, which worked for my partner who experienced a similar issue, but this doesn't fix the issue with me plus it results in routes taking longer to load for some reason. 
- compare all my settings with a friend of mine, who has the free version of the app. All our settings are the same and with her it works perfectly.
- When I select a route and save it first, then the route highlights. But this is not user friendly, I want to be able to compare routes without having to save them. Moreover, when I deselect the route and select it again, I have to save it again in order to be able to see it highlighted.

**These are some technical details:**
- Device: iPhone
- OS: iOS
- OS Version: 17.6.1
- OsmAnd Build: 4.8.2.1

**An example:**
How it should be: a highlighed pre existing route (taken from my friends phone)
![image](https://github.com/user-attachments/assets/63d5fdc7-fbdc-4450-bfa5-8b843b0879c2)
What I see: same details but route is not highlighted
![image](https://github.com/user-attachments/assets/c1f112ab-8776-48d0-b82e-cd4795bdbdae)

What can I do to solve this issue?

thank you

**Comment by yuriiurshuliak** [comment]
- After selecting the track, if you click Download this track, how does it appear? Does it highlight in red as expected?
- I’ve checked that both downloaded and non-downloaded hiking routes should automatically highlight in red. The behavior you’re experiencing does not match with the intended functionality.

Additionally, we recently released a new version of OsmAnd on TestFlight. Could you try testing this version to see if the problem is resolved? You can access it here: [TestFlight link](https://testflight.apple.com/join/7poGNCKy).


https://github.com/user-attachments/assets/61e79291-1fb6-4fc3-80b8-975a4e1e8e93

**Comment by joehoe-its-me** [comment]
Hi,After selecting the track, if you click Download this track, how does it appear? Does it highlight in red as expected?Yes, I share a screenshot before and after downloadAdditionally, we recently released a new version of OsmAnd on TestFlight. Could you try testing this version to see if the problem is resolved?The highlighting issue seems to be resolved but in this version of the app I can’t see details of the routes (distance etc). It’s just a white bar. Some examples belowKind regardsOp 18 nov 2024 om 12:10 heeft yuriiurshuliak ***@***.***> het volgende geschreven:﻿

After selecting the track, if you click Download this track, how does it appear? Does it highlight in red as expected?
I’ve checked that both downloaded and non-downloaded hiking routes should automatically highlight in red. The behavior you’re experiencing does not match with the intended functionality.

Additionally, we recently released a new version of OsmAnd on TestFlight. Could you try testing this version to see if the problem is resolved? You can access it here: TestFlight link.
https://github.com/user-attachments/assets/61e79291-1fb6-4fc3-80b8-975a4e1e8e93

**Comment by vshcherb** [comment]
https://www.openstreetmap.org/search?query=pietrebais#map=15/50.73100/4.77092

**Comment by vshcherb** [comment]
I think now the issue is fixed . We hope to release this month. 
![telegram-cloud-photo-size-4-5900209704133576641-y](https://github.com/user-attachments/assets/4699c1af-61e1-4788-9609-54d7ecb3ed7f)

**Comment by joehoe-its-me** [comment]
Hello,Ok I will make sure to follow up.Should I keep the TestFlight version of the app or go back to the regular one?Thank you Op 18 nov 2024 om 17:00 heeft vshcherb ***@***.***> het volgende geschreven:﻿
I think now the issue is fixed . We hope to release this month.
telegram-cloud-photo-size-4-5900209704133576641-y.jpg (view on web)
