### ISSUE TITLE
RoadLocator_P.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler (1 failure)

### ISSUE THREAD

**Issue by kuajia** [osmandapp/OsmAnd-ios#413]
After building the project with ./prepare.sh with no error, I run ./prebuild-core.sh
During the building the console prompt this error: 
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/davide/Desktop/XCodeProjects/OsmAnd-ios/baked/fat-ios-clang.xcode/core/OsmAnd_projects.build/Debug-iphonesimulator/OsmAndCore_static_standalone.build/Objects-normal/i386/RoadLocator_P.o /Users/davide/Desktop/XCodeProjects/OsmAnd-ios/core/src/RoadLocator_P.cpp normal i386 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

**Comment by vshcherb** [comment]
after prepare.sh you can open project in xcode and build it.
