### ISSUE TITLE
Select segment dialog issues – Follow track

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4132]
### How to reproduce
* Create or import track with more than one segment, for example [Thu 07 Nov 2024.gpx.zip](https://github.com/user-attachments/files/17817058/Thu.07.Nov.2024.gpx.zip)
* Tap **Actions** – **Navigation**
* You will see Select segment dialog

### Actual result

<details>
    <summary>macOS</summary>

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/498e1b6d-425f-4853-9df3-f2bc10b2f532"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/8f2e27df-a488-4228-a3fb-d21a0c5cf467"  width="300" height="auto"/> </td>
  </tr>
</table>   

</details>  

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/d79fff53-67fb-4d6a-8f03-4fb9b9f5acef"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/f9d7eff0-ab66-4b66-9e0b-b146f96a5ebc"  width="300" height="auto"/> </td>
  </tr>
</table>   

* Missed **Cancel** button
* Wrong description background color in Dark mode

### Expected result

* Cancel button
* Proper dark theme colors

**Environment**
OsmAnd Version: 4.9.0.2
iOS version: 18.3 / 15.0.1 (24A348)
Device model: iPhone 16 Pro Max / Macbook Pro 14' 2020

**Comment by DmitryAlexei** [comment]
Osmand TestFlight 4.9.0.4 (both macOS and iPhone)
<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/625d0cd0-4846-4d3d-a5ad-f2147dde59ea"  width="500" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/0cc29209-c043-4f88-b900-ee2c8d9aa0b3"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4209

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.1.4927` - Fixed
