### ISSUE TITLE
macOS 15.1, GPX file import with OsmAnd does not work.

### ISSUE THREAD

**Issue by Biker729** [osmandapp/OsmAnd-iOS#4139]
### Describe the idea

macOS 15.1, GPX file import with OsmAnd does not work.

The "Wed. 20 Nov. 2024.gpx" file is only displayed with a gray background
and cannot be selected & imported.

![macOS 15 1 GPX file with OsmAnd import does not work](https://github.com/user-attachments/assets/0aa114bd-878e-40ec-b53a-1c230c822ec4)

### Expected behaviour

Add function "Import GPX file" with OsmAnd Maps v. 4.8.2

### Alternatives you've considered

Add function "Import GPX file" with OsmAnd Maps v. 4.8.2

**Comment by Zirochkabila** [comment]
```
iOS 15.1.1
OsmAnd 4.9.0.13
```
