### ISSUE TITLE
Search for favorites shows incorrect results when inserting first letters

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#4141]
### Description
When trying to search for favorites inside My places > Favorites tab and only 2 letters inserted, incorrect results are shown.
This creates a false impression that the favorites are missing. Users complain about this behavior in support.

### Steps to reproduce
make sure, that you have some favorite points (probably more than 20 needed) 
- go to My places > Favorites > pull the screen down
- in the search field, input the first letters of a favorite

### Actual result
- when the first two letters of a favorite are inserted, incorrect results are shown (see video and screenshot)
- need to notice, that correct results are shown for a second
- after inserting a space and tap backspace, correct results are shown
- regular search (for example category search) works better. Nevertheless, favorites are shown in the end of the list (not on top)

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a09cb220-a858-488f-b880-126df1a7e0d0"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/a280ef2a-d815-47b3-a590-7afa58473116"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/858e1303-9259-4416-acae-184ac1c1c06a"  width="300" height="auto"/> </td>
  </tr>
</table>

**Comment by yuriiurshuliak** [comment]
The bug has been **reproduced**. It requires having **more than 20 favorites** saved in the list. To reproduce the issue, please follow these steps:
1. Navigate to **My Places > Favorites**.  
2. Scroll through the entire list of favorites to confirm the one you want to find is present.  
3. Enter the first two or three letters of that favorite in the search field.  

**Observed Results:**  
- The search displays **incorrect results**.  
- Correct results appear briefly but then disappear, confirming the described behavior.  

OsmAnd 4.9.0.7
iOS Version 16.4.1

<table style="width:100%">
  </tr>
  <tr>
    <td> <video source src="https://github.com/user-attachments/assets/d77af166-0f11-463c-8c03-b3095183a273"  width="300" height="auto"/>   </td>
    <td><video source src="https://github.com/user-attachments/assets/d1e42c19-eabf-4458-87f2-e117a9db9e24"  width="300" height="auto"/>   </td>
  </tr>
</table>

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4173

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.0.16`

Fixed
