### ISSUE TITLE
The 'Average glide ratio' widget image is missing on the application screen.

### ISSUE THREAD

**Issue by Nastya3003** [osmandapp/OsmAnd-iOS#4146]
Steps to reproduce

1. Open the OsmAnd application.
2. Tap the menu button in the bottom-left corner.
3. Select "Screen Settings."
4. Choose Left/Right/Top/Bottom Panel.
5. Tap the "Add Widget" button.
6. Select the widget "Average glide ratio".
7. Exit the settings menu.
8. On the main screen of the application, locate the added widget.

Expected result: The widget image is displayed on the main screen of the application.

Actual result: The widget image is missing on the main screen of the application.

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/a218b9dc-bbe7-4841-8878-5681aa1dbb38"  width="300" height="auto"/> </th>
  </tr>
</table>

Reproduced on iPhone 15 Pro Max, iOS Version 17.6.1, OsmAnd Version 4.9.0.4.

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. When adding the **Average glide ratio** widget to all panels (Left/Right/Top/Bottom), the icon is missing on the **Left/Right/Top Panels**. On the **Bottom Panel**, the icon appears, but the information itself is not displayed.  

OsmAnd 4.9.0.5
iOS Version 16.4.1

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/f5b602f7-f8ce-4e06-add2-d934952958ed"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
# Testing 1

`4.9.0.18` - Fixed (but, at rest (immediately after adding), the values on Android and iOS are different)

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/b722a8c5-7fd0-4fc4-ba49-6c105611bcfa"  width="300" height="auto"/> </th>
 <th><img src="https://github.com/user-attachments/assets/a7e41d6e-1257-4655-949a-b243d39c4b48"  width="650" height="auto"/> </th>
  </tr>
</table>
