### ISSUE TITLE
Voice navigation as a quick action button does not change the on/off mode

### ISSUE THREAD

**Issue by MurashkevichVer** [osmandapp/OsmAnd-iOS#4148]
### How to reproduce
* Burger Menu > Configure screen > Custom Buttons > Quick Actions 
* Tap Add > Navigation > Add Voice Navigation >
* Press Back until you return to the map screen on the screen. 
* On the map screen in tap the quick action button in the lower right corner > 

### Actual result

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/6c336855-5ac3-421e-85ea-c2293d6d94bf"  width="300" height="auto"/> </td>
  </tr>
</table>   

* the voice navigation icon does not change, it always remains crossed out.

### Expected result

* the icon should switch between on/off modes.

**Environment**
OsmAnd Version: 4.9.0.4
iOS version:  iOS 16.1.1
Device model: iPhone

**Comment by yuriiurshuliak** [comment]
The bug has been successfully reproduced using the following steps:
1. Open the app **Menu** > **Configure Screen** > **Custom Buttons** > **Quick Actions**.
2. Tap **Add** > **Navigation** > **Add Voice Navigation**.
3. Return to the map screen, enable **navigation simulation**, and ensure **voice prompts** are working.
4. Tap the previously configured **Quick Action** for voice prompts.

### Observed Behavior:
- The Quick Action button turns off the previously enabled voice prompts.
- However, tapping the button again does not turn voice prompts back on.
- Additionally, the Quick Action button icon remains crossed out at all times, failing to reflect the current state (on/off) of the voice prompts.


OsmAnd 4.9.0.6
iOS Version 16.4.1

https://github.com/user-attachments/assets/486669a4-ce30-4c68-91af-87ecafcac1c8

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.1.4924`
Button animation after pressing - **Fixed**

But:
1. If enable or disable voice prompts from the Navigation menu, the state of the custom button does not change (**does not affect the state of the custom button**).
2. If turn off or on voice prompts using a custom button, the state of the icon in the navigation menu changes (affects the state of the button in the navigation menu).
3. Navigation menu: if voice guidance is enabled, the icon of enabled voice guidance is displayed, if voice guidance is disabled, the icon of disabled voice guidance is displayed (i.e., the **current state**). 
4. Custom button: if voice prompts are enabled, the icon of disabled voice prompts is displayed, if voice prompts are disabled, the icon of enabled voice prompts (i.e., **action**) is displayed

**Perhaps it is worth synchronizing the logic of the buttons (the 1st item with the 2nd and the 3rd item with the 4th)?**
