### ISSUE TITLE
Reset to default doesn't remove quick action buttons

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#4150]
### Description
When resetting profile to default values, quick actions still present on the screen.
OsmAnd android removes quick actions when resetting profile.
iOS 18.1.1 TestFlight 4.9.0.6

### Steps to reproduce
- create a quick action in a driving profile
- reset driving profile to default (menu > settings > driving > reset to default )
- have a look at the screen

### Actual result
- Quick action still present on the screen (see video)

https://github.com/user-attachments/assets/40af081d-38c3-46e4-9581-33a9a2b363c7

**Comment by dmpr0** [comment]
Custom button list is the same for all profiles in Android, Reset doesn't removes them

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.  

**Steps to reproduce:**  
1. Create a quick action button in the **Driving profile**.  
2. Reset the **Driving profile** settings via **Menu > Settings > Driving > Reset to default**.  
3. Observe the screen after resetting.  

**Actual Result:**  
The quick action buttons remain visible on the screen after resetting the profile to default.  

**Expected Result:**  
The quick action buttons should be removed or deactivated after resetting to default.  

OsmAnd 4.9.0.6
iOS Version 16.4.1

https://github.com/user-attachments/assets/25c95761-9369-4d9c-9752-516c07d258ed

**Comment by Zirochkabila** [comment]
# Testing 1

`4.9.0.18` - **Fixed** (after resetting to the default settings, quick actions are saved in Configure screen > Custom buttons, but disappear from the main screen)
