### ISSUE TITLE
Australia map download loop

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4153]
### How to reproduce
* Open **OsmAnd** – **Menu** – **Maps & Resources**
* Australia and **Oceania** – **Australia**
* Tap download right to **Standart map**

### Actual result

* Map download start again when reach 75-80%

### Expected result

* Map dowloads

**Environment**
OsmAnd Version: 4.9.0.7
iOS version: 18.1
Device model: iPhone 16 Pro Max

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced. To reproduce:  
1. Open **Menu → Maps & Resources → Australia and Oceania → Australia**.  
2. Tap "Download" next to "Standard map."  
3. Observe the download progress.  

**Result**:  
In my case, the map does not reload or restart at 75-80%. Instead, it completes to 100%, then shows a loading window with *"Installing..."*. Once the window disappears, the map is not installed, and the option to download it again is still available.


OsmAnd 4.9.0.7
iOS Version 16.4.1

https://github.com/user-attachments/assets/18f7412d-3693-4671-ae08-37477d67c092

**Comment by EugeneZmeuk** [comment]
The same result with a custom map:

![image](https://github.com/user-attachments/assets/a8868afc-4fc4-401d-b05d-0abcb8f3ddf6)

https://github.com/user-attachments/assets/82af57ec-974e-454d-9999-73b9bec04f68

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4200

**Comment by DmitrySvetlichny** [comment]
Custom map downloading fixed

**Comment by RZR-UA** [comment]
It is fixed now. Please test in the iOS app.

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.1.4923`
Map of Australia as well as custom maps are loaded and displayed
