### ISSUE TITLE
quickaction on map like in osmand for android

### ISSUE THREAD

**Issue by tbkrtz** [osmandapp/OsmAnd-ios#416]
the quickaction function in the osmand app on android is one of the best functions in osmand and it speeds up the daily use a lot!
for the osm editing it is also much more comfortable. 
it would be awesome it this function could be implemented in osmand for ios.

**Comment by max-klaus** [comment]
The Quick Action feature will be available in the next release (3.00). It few days I think.

**Comment by tbkrtz** [comment]
Very cool, thanks! :-)
