### ISSUE TITLE
Missing guide to install properly the project

### ISSUE THREAD

**Issue by kuajia** [osmandapp/OsmAnd-ios#418]
I am facing a lot of issue in order to install and run the ios project.

Those are the instruction I followed: 

1. `git clone https://github.com/osmandapp/OsmAnd-ios.git`
2. `repo init -u https://github.com/osmandapp/OsmAnd-manifest -m readonly.xml`
3. `cd OsmAnd-ios`
4. `git clone https://github.com/osmandapp/OsmAnd-core.git`
5. rename the folder `OsmAnd-core` to `core`
6. `git clone https://github.com/osmandapp/OsmAnd-build.git`
7. rename the folder `OsmAnd-build` to `build`
8. open `./prepare.sh` and update line ROOT="$SRCLOC/../" to ROOT="$SRCLOC/"
9. `git clone https://github.com/osmandapp/OsmAnd-resources.git`
10. rename the folder `OsmAnd-resources` to `resources`
11. run command `./prepare.sh`

After these steps, I'm still getting errors in the XCode project, missing the 'OsmAndCore / QtExtensions.h' file not found. I guess some steps are not correct, so is there a complete guide that makes the project work? 

Thanks.

**Comment by Darshan-Sonigara** [comment]
same error

**Comment by vshcherb** [comment]
./prepare.sh should run successfully and initialize and build qt library

**Comment by kuajia** [comment]
Infact it runs successfully and gave me Succesfully built, but when I run the Xcode project it says missing library OsmAndCore

Maybe I am loading the wrong Xcode Project, where should it be located?

**Comment by kuajia** [comment]
Is ./prebuild-core.sh needed?

**Comment by PaulStets** [comment]
@kuajia Please make sure you have downloaded all the projects needed to build OsmAnd. They are described in this file: https://github.com/osmandapp/OsmAnd-manifest/blob/master/jenkins_ios.xml
Your project folder should have a similar structure to the one I'm attaching to this response. By the way, you also need to clone this repository: https://github.com/osmandapp/osmandapp.github.io.

Let me know if you have any further problems.

<img width="1097" alt="Screen Shot 2019-09-06 at 1 23 00 PM" src="https://user-images.githubusercontent.com/20681525/64421138-8ae7ac80-d0a9-11e9-8d45-6ca213f962b2.png">

**Comment by kuajia** [comment]
Can you describe a full instruction set in order to make the app works?
For example how did you get the repo folder with theCMAkeList.txt and the ios_build_prepare.sh

**Comment by PaulStets** [comment]
The full instructions are as follows:
1. Clone all the necessary repositories and name them as on the screenshot (nevermind the extra folders and files: ios_prepare_build.sh is just my personal script for pulling the changes from all repositories).
2. Install ```brew reinstall imagemagick --with-librsvg```
3. Once everything is set, run ./ios/prepare.sh
4. You may need to #include <stdlib.h> in gif_hash.c
5. Open osmand.xcworkspace in XCode and build

**Comment by kuajia** [comment]
Thanks for the instructions, I have another question, after build it I got this error: 'openingHoursParser.h' file not found 
I checked the dependency, it is related to android project which I included in the main folder.

**Comment by PaulStets** [comment]
Seems like you're missing the ```core-legacy``` project. Make sure you cloned this branch: https://github.com/osmandapp/OsmAnd-core/tree/legacy_core

**Comment by kuajia** [comment]
I added the core legacy... now the issue is related to Charts framework. It is not detected also if it is has been added both in the Embedded binaries and Linked Frameworks and Libraries.

**Comment by PaulStets** [comment]
It should only be included as an embedded binary and not as a linked framework.

**Comment by kuajia** [comment]
<img width="1280" alt="Schermata 2019-09-08 alle 13 12 27" src="https://user-images.githubusercontent.com/20659002/64487409-8f8f9a80-d23a-11e9-9f88-4f2622f25fcd.png">

I just added the library and then ./ios/prepare.sh

**Comment by PaulStets** [comment]
Please remove the Charts.framework from Linked frameworks. It should be included only as an embedded binary.
<img width="1792" alt="Screen Shot 2019-09-08 at 3 23 41 PM" src="https://user-images.githubusercontent.com/20681525/64488132-cec6e700-d24c-11e9-83a7-c2564b6dde2b.png">

**Comment by kuajia** [comment]
I removed it, the clean the build folder and CMD+B to re-built the project: same error (No such module 'Charts')

**Comment by PaulStets** [comment]
Try removing and adding the Charts embedded binary as in this answer: https://stackoverflow.com/a/50738869/9293831

**Comment by kuajia** [comment]
Build failed again...

**Comment by abdulrahmanx** [comment]
>     2\. brew reinstall imagemagick --with-librsvg

Brew are not allowing options anymore any comment on that 

i run this command and what i receive is Error: invalid option: --with-librsvg*

* please refer to this homebrew issue:https://github.com/Homebrew/homebrew-core/issues/31510

**Comment by lodi12** [comment]
I am facing build issues when launching prepare.sh.
My OsmAnd folder contains all the sub-folders described in the post of PaulStets.

I follow all the described steps, but when I run prepare.sh I have some problem building the qt core. In particular, when cmake try to compile qutfcodec.cpp I get this warning:

warning: inline variables are a C++17 extension [-Wc++17-extensions] static Q_ALWAYS_INLINE unsigned _bit_scan_reverse(unsigned val)

and then this error

qsimd_p.h:469:33: error: redefinition of '__bsrd' as different kind of symbol static Q_ALWAYS_INLINE unsigned _bit_scan_reverse(unsigned val).

In particular, I think that make use the definition of _bit_scan_reverse found in /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include/ia32intrin.h 

Can you help me?
Thanks!

**Comment by PaulStets** [comment]
Hi, @lodi12. Here are the latest instructions: https://docs.google.com/document/d/1OAbqgmLJRFiQb9tt8da6zLlKqq8ozziW8GrNiv2nWNk/edit?usp=sharing
Please make sure you have the correct CMake version and try running the script again.

**Comment by lodi12** [comment]
Thank you for your help. I follow these steps but I face the same error. I think it could be a clang problem. What version of command-line tools and Xcode are you using?

**Comment by PaulStets** [comment]
Everything should work fine with the correct version of CMake. Please verify if you installed the CMake 3.11.2 correctly by running: ```cmake --version```. I'm currently using ```Apple clang version 11.0.3``` with latest XCode.

**Comment by lodi12** [comment]
Finally I get it work. During the build process I apply the following fix:

- /Users/teo/Documents/OsmAnd/core/externals/qtbase-ios/upstream.patched.ios.device.clang.static/src/corelib/tools/qsimd_p.h Iine 468: I add "&& !defined(miaVar) " just to skip the next block. I don't know if it is a "global" issue or it is just my set up

- core/externals/geographiclib/configure.sh line 11: the link to geographic lib is wrong. I change "https://builder.osmand.net/dependencies-mirror/geographicLib-1.46.tar.gz" to "http://builder.osmand.net/dependencies-mirror/Geographiclib-1.46.tar.gz". I think this is a GLOBAL issue that can be easily solved.

- core/externals/libpng/configure.sh line 11: the link to libpng lib is wrong. I change "http://builder.osmand.net/dependencies-mirror/libpng-1.6.16.tar.xz" to "http://builder.osmand.net/dependencies-mirror/libpng-1.6.6.tar.xz". I think this is a GLOBAL issue that can be easily solved.

- core/externals/libpng/CMakeLists.txt remove line 17. "upstream.patched/arm/filter_neon_intrinsics.c" do not exist in libpng-1.6.6. I think this is a GLOBAL issue that can be easily solved.

With this correction, I can run ./iOS/prepare.sh and then run the application using Xcode.

For PaulStets, if you want to update your file, you can easily get the whole project through repo by using:
1) repo init -u https://github.com/osmandapp/OsmAnd-manifest -m jenkins_ios.xml
2) repo sync
