### ISSUE TITLE
Zoom level issue 

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#4182]
### Description
Data in the Zoom level widget change when you zoom in/zoom out (using the + - buttons)

### Steps to reproduce

1. Activate the developer plugin > Add the Zoom level widget to the home screen > Zoom to the maximum (for a more accurate result, zoom with your fingers) > Change the zoom level several times

### Actual result
Data in the widget (after the decimal point) changes

https://github.com/user-attachments/assets/565043e2-7ce5-4036-96ed-c0e7171cff4d

### Expected result

- [ ] When working with zoom (zooming in and out), the data in the widget remains constant (using the + - buttons)

https://github.com/user-attachments/assets/f1d6cd1b-b587-479f-9d38-dc12a52e4035

### Your Environment
OsmAnd Version: 4.9.0.15
Android/iOS version: 
Device model:

**Comment by vshcherb** [comment]
Zoom animation shouldn't be stored for +- buttons. After +- target zoomAnimation = 0. Fractional part could be > 0 when you manually change or have bbox preview.

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/048007e0c019d006bb5db8fe25d5a75f7d04ee44

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.1.4923` - Fixed
