### ISSUE TITLE
`Junction:ref` number is displayed above the road name

### ISSUE THREAD

**Issue by Zirochkabila** [osmandapp/OsmAnd-iOS#4184]
### Description
During navigation, the `junction:ref` number is displayed above the road name in the Street name widget
[OSM](https://www.openstreetmap.org/way/22971355#map=19/48.149917/13.982728)

### Steps to reproduce

1. Navigation from `48.14183° N, 13.99145° E` to `48.14183° N, 13.99145° E` > Simulate navigation

### Actual result

 <table style="width:100%">
 <tr>
    <th>Number 11</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/00d122e3-854d-4eef-8cd3-7cad7df46297"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Expected result

- [ ] Junction number is displayed next to the road name

 <table style="width:100%">
 <tr>
    <th>Number 11 - 4OsmAnd~ 5.0.0#3918m, Released: 2024-12-10</th>
  </tr>
  <tr>
<th><img src="https://github.com/user-attachments/assets/1c533da4-e342-4a7e-927f-5e6b36330d52"  width="300" height="auto"/> </th>
  </tr>
</table>  

### Your Environment
OsmAnd Version: 4.9.0.15
Android/iOS version: 
Device model:

**Comment by yuriiurshuliak** [comment]
The bug has been reproduced.  

**Steps to Reproduce**:  
1. Open OsmAnd and initiate navigation.  
2. Start navigation from coordinates **48.14183, 13.99145** to **48.14849, 13.97645**.  
3. Enable **Simulate Navigation** mode.  

**Observed Behavior**:  
The **junction:ref number** (e.g., "11") is displayed above the road name in the **Street Name widget**, which is not the expected layout.  

OsmAnd Version: 4.9.0.(4921)
iOS Version 16.4.1

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/e1060ce6-25bf-43c9-85e2-81538f38670e"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
# Testing 1

`4.9.2.4929` - Fixed
