### ISSUE TITLE
Failed to bake project files 'fat-ios-clang.xcode' 

### ISSUE THREAD

**Issue by Darshan-Sonigara** [osmandapp/OsmAnd-ios#419]
I am trying to setup development environment in xcode for osmand app.Getting the error 
See also "/Users/xxx/Desktop/OsmAnd-ios/baked/fat-ios-clang.xcode/CMakeFiles/CMakeError.log"

Failed to bake project files 'fat-ios-clang.xcode' 
Failed to generate project for XCode, aborting...

**Comment by vshcherb** [comment]
Duplicate #418

**Comment by Darshan-Sonigara** [comment]
@vshcherb  Why you are closing my issue? I am still facing issue.

**Comment by vshcherb** [comment]
It is not end-user issue and so far all team developers don't experience it.
