### ISSUE TITLE
Crashes 4.9.0

### ISSUE THREAD

**Issue by tigrim** [osmandapp/OsmAnd-iOS#4207]
- [x] OsmAnd Maps: -[OARouteDirectionInfo getDestinationRefAndName] + 112
- [x] OsmAnd Maps: closure in DownloadingListHelper.getDownloadingTasks() + 24
- [x]  OsmAnd Maps: +[OAFavoritesHelper getCompositeIcon:backgroundIcon:color:] + 80
- [x] OsmAnd Maps: +[OAPointDescription getSimpleName:] + 20
- [x] OsmAnd Maps: kfun:net.osmand.shared.io.KFile#absolutePath(){}kotlin.String + 96
- [x] OsmAnd Maps: -[OATopTextView updateWaypoint] + 488
- [x] OsmAnd Maps: +[OALocationParser prepareLatLonWithDecimalCommas:] + 96
- [x] Geocoder crash https://github.com/osmandapp/OsmAnd-core/commit/56808dfa1180f6ad3a64bf5c9204cb8a0dc6e23a
- [x] `[OAFavoriteListViewController refreshVisibleRows]_block_invoke`

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.1.4927` - Fixed
Crashes could not be reproduced

**Comment by Zirochkabila** [comment]
# Testing 2
`4.9.1.4928` - Not reproduced anymore
