### ISSUE TITLE
Data not updated on Weather screen

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#4219]
### How to reproduce
* Launch **OsmAnd**, go to **Plugins** – **Turn On** 
* Open **Menu** – **Weather**
* Try to move time slider

### Actual result

<table style="width:100%">
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/ffad5d5d-db41-4b58-a5d9-8ba311b6f6dc"  width="300" height="auto"/> </td>
    <td><img src="https://github.com/user-attachments/assets/15a7357d-e904-43c5-b2e7-ef691fc3b1bb"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/9e6af937-6027-4e7c-9579-2fcf0aa536a7"  width="300" height="auto"/> </td>
  </tr>
</table>  
 

* Weather data: temperature, wind, etc. is not updated

### Expected result

* Move time slider to update data

**Environment**
OsmAnd Version: 4927
iOS version: 18.2
Device model: iPhone 16 Pro Max

**Comment by Zirochkabila** [comment]
# Testing 1
`4.9.1.4928` - Fixed (Data is updated after the slider moves)


https://github.com/user-attachments/assets/fb7744c1-5e9d-4596-9803-74ca854d9ab4
