### ISSUE TITLE
Bugs and crashes in the Context menu for Tracks

### ISSUE THREAD

**Issue by DmitryAlexei** [osmandapp/OsmAnd-iOS#4231]
### Description
Context menu for Track doesn't work whatsoever when it is open for a track from search.  

### Steps to reproduce

- [x] 1. Crash:
- Precondition: have multiple tracks in different folders in My places > tracks
- go to menu > my places > tracks > choose one of the folders > swipe the screen to the bottom and tap on the search field
- there will be many tracks on the search screen. You can search for a specific track or open the track context menu for one of the proposed tracks. In context menu choose Navigation > crash

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><video src="https://github.com/user-attachments/assets/dd9ba116-0ee9-4dbd-9819-57550f9f2dec"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/824fe441-7265-4115-bc30-30dd57b451a8"  width="300" height="auto"/> </td>
  </tr>
</table>

- [x] 2. Track context menu doesn't work properly if track was found via search
- go to menu > my places > tracks > choose one of the folders > swipe the screen to the bottom and tap on the search field
- choose one track from the proposed ones or search for a specific track, long tap on it
- in the Track's context menu choose Edit, duplicate, rename or move 
- see if you can edit your track, if it was duplicated or moved. On the Rename screen, instead of the track's real name you will see the Currently recording track.

https://github.com/user-attachments/assets/841581ea-cdb1-4b60-a732-46244e7ca27c

- [x] 3. The navigation bar cannot be removed
- go to menu > my places > tracks > choose one of the tracks and open its context menu
- choose navigation > and tap on the visible part of the map on the navigation screen
- the navigation bar will remain on the screen and can only be removed after relaunching the app

<table style="width:100%">
  <tr>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/c05f90e0-2e6b-4c06-b6d4-a2cfbad5ef26"  width="300" height="auto"/> </td>
    <td><video src="https://github.com/user-attachments/assets/2387f0d0-d407-4732-bb89-828619e04368"  width="300" height="auto"/> </td>
  </tr>
</table>

- [x] 4. Search bar on the Tracks screen sometimes cannot be open (it opens after visiting one of the folders)
- go to menu > my places > tracks
- swipe the screen to the bottom and see that search bar doesn't open

https://github.com/user-attachments/assets/af696878-1179-4750-a6ed-a2eaab57abbe

- #4243

- [x] 6. Analyze action behavior is weird when it is triggered from the search
- go to menu > my places > tracks > any folder 
- swipe the screen to the bottom and start to type the name of the track from a different folder
- long tap on that track and choose Analyze
- track is not highlighted on the map, the track menu is empty. When the user taps back, the map view goes to the ocean, after another tap back Navigation screen opens.

https://github.com/user-attachments/assets/26de6b23-b6c2-493c-977a-d1403e842137

- [x] 7. Track found via search cannot be shared or uploaded to osm
- go to menu > my places > tracks > any folder 
- swipe the screen to the bottom and start to type the name of the track from a different folder
- long tap on that track and select Share or upload to OSM
- on the share screen, it is proposed to share the tmp folder. But even when you choose any app and select share > that operation cannot be performed. Track also cannot be uploaded to OSM

<table style="width:100%">
  <tr>
<th><img src="https://github.com/user-attachments/assets/b9e4f9a0-12fd-4251-828f-8cfedf5947d9"  width="300" height="auto"/> </td>
<th><img src="https://github.com/user-attachments/assets/47d79b8f-3922-4722-88bd-53610837b30b"  width="300" height="auto"/> </td>
  </tr>
</table>

iPhone 13 mini, OsmAnd TestFlight 4.9.10 4928, iOS 18.2

**Comment by DmitrySvetlichny** [comment]
Additionally, the problem where filters were republished if the search bar was cleared has been fixed.

**Comment by DmitrySvetlichny** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/4242
