### ISSUE TITLE
Export Favourites destroys data

### ISSUE THREAD

**Issue by fortysix2ahead** [osmandapp/OsmAnd-iOS#4234]
I am not using Cloud Sync any longer because of #3347, instead I export my all favourites on a regular basis (basically each time I added/changed favourite places) to a folder on my iPhone. However, there seems to be a related issue. I recently checked my export folder and OsmAnd seems to destroy data as well. The export folder contains files numbered upwards (favourites-1.gpx, favourites-2.gpx ...). A regular file for my exports is about 1.6 MB, but this week I noticed that the size has dropped to 600 KB, which means that almost two thirds of the favourites have been destroyed.

I did not loose that much data but my guess is that there's a severe issue here as both Cloud Sync and Export can destroy saved data and a user will only find out by accident.

The behaviour I described has been seen on an iPhone, running the latest version of OsmAnd. And it's only about favourite places, not any routes or tracks.

**Comment by yuriiurshuliak** [comment]
To help us investigate, could you please provide additional details? Specifically:  

1. Can you explain the exact steps you take when exporting your favorites?  
2. How did you verify the number of favorites before and after the export? Did you notice any specific patterns in the missing data?  
3. Does this issue occur every time you export favorites or only periodically?  
4.Could you share a sample of the exported GPX files (e.g., a working export and the problematic one)? This will help us better understand the issue.

**Comment by fortysix2ahead** [comment]
I think I need to revise this ticket. I have checked for the file size only, which decreased. In the last export I considered "valid" a place is saved like this:
```xml
   <wpt lat="50.9424381" lon="10.3123051">
        <time>2024-11-10T09:37:55Z</time>
        <name>Drachenschlucht</name>
        <type>Natur</type>
        <extensions>
            <osmand:address>Drachenschlucht, Eisenach</osmand:address>
            <osmand:icon>natural</osmand:icon>
            <osmand:background>circle</osmand:background>
            <osmand:color>#ff43a047</osmand:color>
            <osmand:osm_tag_wikidata>Q1254322</osmand:osm_tag_wikidata>
            <osmand:osm_tag_wikimedia_commons>Category:Drachenschlucht</osmand:osm_tag_wikimedia_commons>
            <osmand:amenity_type>natural</osmand:amenity_type>
            <osmand:amenity_name>Drachenschlucht</osmand:amenity_name>
            <osmand:osm_tag_wikipedia>http://de.wikipedia.org/wiki/Drachenschlucht</osmand:osm_tag_wikipedia>
            <osmand:amenity_subtype>gorge</osmand:amenity_subtype>
            <osmand:amenity_origin>Amenity:Drachenschlucht: natural:gorge</osmand:amenity_origin>
        </extensions>
    </wpt>
```

However, in later versions of the export file it looks like this:

```xml
   <wpt lat="50.9424381" lon="10.3123051">
        <time>1970-01-05T03:54:14Z</time>
        <name>Drachenschlucht</name>
        <desc></desc>
        <type>Natur</type>
        <extensions>
            <osmand:address>Drachenschlucht, Eisenach</osmand:address>
            <osmand:icon>natural</osmand:icon>
            <osmand:amenity_origin>Amenity:Drachenschlucht: natural:gorge</osmand:amenity_origin>
        </extensions>
    </wpt>
```

Several tags that existed before have been removed (and are probably not relevant). That's why I guessed that data is missing. But it seems that my assumption was wrong. I'll analyse a bit further, but I think this ticket can be closed.

**Comment by fortysix2ahead** [comment]
I'm closing this issue. I have analyzed my data and no places are missing. The difference is coming from the additional tags not being saved (see comment above), so the exported file is smaller than before.
