### ISSUE TITLE
[Feature Request] Sync Favorites

### ISSUE THREAD

**Issue by brunoschroeder** [osmandapp/OsmAnd-iOS#426]
This is the #1 feature request I have for you. I have acquired your yearly version. I love your work! This tool is brilliant! I really lack an UX similar to googlemaps or maps.me.

Another important feature is a browser version of the UX.

Feature request: As a personal home user who has a photographic memory and spacial sense and perception, I would like to be able to have the same geo-bookmarks synced in my mobile openstreetmaps tool as well as in a browser web editor, so that I can improve and have more productivity on the creation and update of my bookmarks in both platforms.

I have also published this on OsmAnd-tools under https://github.com/osmandapp/OsmAnd-tools/issues/327

**Comment by norz** [comment]
Maybe also add favorites syncing between devices?

Use case: viewing/editing favorites on phone or tablet, depending on the device you have with you.

**Comment by DmitryAlexei** [comment]
Implemented 
see Cloud backup
https://osmand.net/docs/user/personal/osmand-cloud#osmand-start

**Comment by norz** [comment]
Excellent, thanks a lot! 🙏
