### ISSUE TITLE
Bug on subscriptions to OsmAnd Live ?

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-ios#427]
iPhone 5S, iOS 12.4.1, OsmAnd 3.00

Yesterday after starting OsmAnd I was prompt a cancel subscription for OsmAnd Live which is odd because my last — and only — subscription ended in May 2019. I didn't pay attention before that, but since then I've access to OsmAnd Live features (updates, contour lines, hill shades & co). I first though I had renew my subscription, but checking my Apple account show that it's not the case. I'm quite happy to have access for free to OsmAnd Live but it seems you have introduce a bug somewhere ? Or is it a new policy for contributors or part of the monthly challenge ?

**Comment by natolh** [comment]
Got the "cancel subscription" a second time today, I can still access OsmAnd Live features.

**Comment by max-klaus** [comment]
You should have it for three days since you saw the screen first time.

**Comment by natolh** [comment]
@max-klaus still got access to Live today.

**Comment by natolh** [comment]
For the record : until yesterday I was able to use Live. Today, roughly 1 month after, I can't use it anymore.

**Comment by max-klaus** [comment]
Thank you! We will check it before the next release.

**Comment by natolh** [comment]
I think I've, at least partially, solved the problem.

To gain access to OsmAnd Live :
- I did subscribe once for a three months period, that is now over.
- Each time I want to have access to OsmAnd Live I click on the subscribe then I hit "restore"
- Immediatly after the pannel close I activate OsmAnd Live and got the latest updates of the map.

**Comment by max-klaus** [comment]
Looks like it somehow interfere with TestFlight. Closing for now.
