### ISSUE TITLE
OsmAnd Live issue with full Ukraine map

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-ios#440]
I have deleted POI 4 days ago https://www.openstreetmap.org/node/3346702114, update Ukraine map with OsmAnd Live, but it still shows on the full map:
![photo_2019-09-24 11 11 10](https://user-images.githubusercontent.com/9365308/65493702-06c06200-debc-11e9-87a3-8ff8b01edd23.jpeg)
It disappears from Kyiv map, and also on Android with OsmAnd Live it doesn't show too.
![photo_2019-09-24 11 12 20](https://user-images.githubusercontent.com/9365308/65493775-32dbe300-debc-11e9-8add-acae960a23d5.jpeg)

**Comment by PaulStets** [comment]
No longer reproducible.
