### ISSUE TITLE
App crashes when starting navigation

### ISSUE THREAD

**Issue by kuajia** [osmandapp/OsmAnd-ios#442]
After downloading the iOS OsmAnd project, I managed to build and install the app.

I am facing an issue when starting navigation between two points, the app crashed and giving me this error: 

> Calculating route (37): EXC_BAD_ACCESS (code=1, address=0x8)

Am I missing any library or something like that, because the app starts correctly, but I can't navigate.

It seems that the issues is related to memory problems

**Comment by PaulStets** [comment]
Please make sure you have downloaded all the necessary projects for the build. You need to download and rename the necessary folders as specified in https://github.com/osmandapp/OsmAnd-manifest/blob/master/jenkins_ios.xml. You also need to clone the https://github.com/osmandapp/osmandapp.github.io. The project structure should look roughly like the attached screenshot.
<img width="1504" alt="Screenshot 2019-10-23 at 17 09 36" src="https://user-images.githubusercontent.com/20681525/67401501-ea493f80-f5b7-11e9-8469-0a8127db73ea.png">
