### ISSUE TITLE
app crashes immediately after calling navigation

### ISSUE THREAD

**Issue by codaq** [osmandapp/OsmAnd-ios#443]
When I used to start navigation between two points, the app crashes with this error: 
> Calculating route (37): EXC_BAD_ACCESS (code=1, address=0x8)

This seems related to a bad access to a pointer.
Also #442 is facing same issue.
I tried to use Zombie Class in debug mode, but I can't find any relevant info.

Thx (URGENT)

**Comment by PaulStets** [comment]
Hi, could you please specify if you are facing this issue in the release build of the app or when you build the app from the source code as in #442?
