### ISSUE TITLE
url scheme / open map and navigate

### ISSUE THREAD

**Issue by nilsE** [osmandapp/OsmAnd-ios#447]
There seems to be a url scheme (osmandmaps://), but how can I use it to open a map with a specific location and start navigating there from another ios app?

**Comment by PaulStets** [comment]
You can try something like: ```osmandmaps://?lat=45.6313&lon=34.9955&z=8&title=New+York```
or ```https://osmand.net/go.html?lat=45.39849&lon=5.36905&z=15``` Let us know if it works.

**Comment by nilsE** [comment]
Hi @PaulStets - thanks, but unfortunately this does not work (osmandmaps://...). The OsmAnd app opens, but the specified position is not displayed nor does the navigation start. Do you still have an idea? 

tested with osmandmaps://?lat=54.63124358&lon=9.930490588&z=14&title=Arnis on iOS 13.1.3

**Comment by PaulStets** [comment]
Hi, @nilsE. I have fixed the URL scheme. You can now use ```osmandmaps://?lat=45.6313&lon=34.9955&z=8&title=New+York``` to center the map with a context menu or ```osmandmaps://navigate?lat=45.6313&lon=34.9955&z=8&title=New+York``` to navigate to a given point.
