### ISSUE TITLE
Problem with lines of Radius-ruler (Testflight 3.5)

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-ios#449]
There is a problem with lines of Radius-ruler (Testflight 3.5) in different zoom. Note: there was built a bicycle trip at this moment.

![image](https://user-images.githubusercontent.com/44466116/67304283-45b5f780-f4fc-11e9-8bc3-ecfbbcf7fb96.png)
![image](https://user-images.githubusercontent.com/44466116/67304334-55354080-f4fc-11e9-9fe0-cf9e93246a4f.png)

**Comment by PaulStets** [comment]
Fixed with 7a278375be383745c7b267c26ca5cc70982ed370
