### ISSUE TITLE
Online map source list is different from Android version.

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-ios#451]
![photo_2019-10-25 13 21 24](https://user-images.githubusercontent.com/9365308/67563898-5fd51d00-f72a-11e9-8f51-0b3bd108ff75.jpeg)
![photo_2019-10-25 13 22 31](https://user-images.githubusercontent.com/9365308/67563971-85622680-f72a-11e9-83f7-b700b2b7ec25.jpeg)

**Comment by dmpr0** [comment]
https://github.com/osmandapp/osmandapp.github.io/blob/master/website/tile_sources.xml

**Comment by PaulStets** [comment]
No longer an issue. Should we close it?
![2CF971EB-0FFE-4F72-9338-3CC7FE32549B](https://user-images.githubusercontent.com/20681525/70311134-b188c100-1819-11ea-86ac-ed848f9d4d51.png)
![820484CC-616E-46DE-9D17-3094C9066D6E](https://user-images.githubusercontent.com/20681525/70311135-b2215780-1819-11ea-9355-5d46364cb95e.png)
