### ISSUE TITLE
iPhone 4/4S Screen Size and Back Buttons

### ISSUE THREAD

**Issue by ClashTheBunny** [osmandapp/OsmAnd-ios#47]
I'm trying out the nightly from yesterday (13-Jan-2015 19:52).  Install was via SSH and unzipping into the /Applications folder.  After chmod 777 and a reboot, the icon showed up.

First of all, thanks so much for getting this great program working on iOS.  It's one of my favorite features of Android.  Although as previously stated it's very unstable, it downloads the maps and shows my position!  So cool!  The design is also beautiful.  Everything from the splash screen to the menus.

Some issues:
 * Every start it shows the welcome screen.  The button at the bottom is mostly hidden.  Even after I've downloaded the world base map and my local map, it still shows the screen every start up.
 * As seen below, the screen is too small to comfortably show Settings and Feedback.  When trying to click Settings, only About or Feedback is activated.  I assume that maybe the screen density slider may fix some problems, but I still have to experiment with it.

![img_0928](https://cloud.githubusercontent.com/assets/248361/5736719/eaeec20a-9be1-11e4-9a98-663810c02528.PNG)

 * Every settings panel, like the info screen on the map, or the debug panel (below) lacks a back button, so it's impossible to go back to the home screen.  This means I'm stuck in the menu until I close the program and start it again.  When I type something into a number field, it's tough to dismiss the keyboard popup.

![img_0929](https://cloud.githubusercontent.com/assets/248361/5736720/eaf02d48-9be1-11e4-8951-ab830de3beb1.PNG)

 * When scrolling in the settings panels, the clock and info are obscured.  It would be good to change the text of the top bar back to black when you go into a panel.

![img_0930](https://cloud.githubusercontent.com/assets/248361/5736721/eaf25b9a-9be1-11e4-9831-16d20f1afb79.PNG)

**Comment by vshcherb** [comment]
Yes this product is quite unstable. And it could be used only as map display so far! This is not what we want to have released. I'm afraid so far it has none of unique features comparing with competitiors, so it may be useful only for developers and not for users.

**Comment by ClashTheBunny** [comment]
Clearly anybody who figures out how to install it without it being signed
for the devices is more dev than user.  I look forward to watching this
improve!

**Comment by vshcherb** [comment]
There is night build http://download.osmand.net/latest-night-build/OsmAnd_DEV.ipa and it is just not signed correctly for public usage. May be you can help with that?

**Comment by ClashTheBunny** [comment]
That is what I installed and tested.  It was very helpful!

**Comment by sonora** [comment]
Randall, just out of curiosity, do you need a jailbreaked iphone to
install, or are there other ways?

thx - Hardy

**Comment by ClashTheBunny** [comment]
You either need the Dev to whitelist your serial number with Apple or
jailbreak.  I'm jailbroken already.

**Comment by sonora** [comment]
All righty, thx!

**Comment by vshcherb** [comment]
Fixed
