### ISSUE TITLE
Show POI Type in search results if name is empty. 

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-ios#482]
![Group 1](https://user-images.githubusercontent.com/9365308/68749025-365f3100-0606-11ea-9c6c-fecb9a034ea8.png)

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-ios/commit/e0fb579ea986fb481f7cc6244b83fa30056286eb
