### ISSUE TITLE
Map type doesn't show imported maps

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-ios#487]
![Group 3](https://user-images.githubusercontent.com/9365308/69055575-c3dfbe00-0a16-11ea-92ba-4e6208c4d356.png)

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-ios/commit/0b9c4f1d7bc70ccdbb04fc2b25511cd7b3ed873d
