### ISSUE TITLE
Scale bar distance label missing

### ISSUE THREAD

**Issue by brncsk** [osmandapp/OsmAnd-ios#488]
Scale bar distance label is missing on iOS 13 (iPhone Xs). Changing the orientation (as in #146) does not seem to have any effect. See the attached screenshot:

![7AAC93B9-DAF4-4D38-B13C-E80197BB55D6](https://user-images.githubusercontent.com/1205180/69115631-88320c00-0a89-11ea-9fd0-1198dbb0a0ab.jpeg)

**Comment by dmpr0** [comment]
Hello @brncsk! Thank you for the feedback. 
We fixed that issue in current Testflight version, you can get it here https://t.me/ruosmand/28265.
We planning to release stable version on App Store in a few weeks.

**Comment by brncsk** [comment]
Thank you, Dmitriy, for the quick reply!
