### ISSUE TITLE
Crash on Route calculation

### ISSUE THREAD

**Issue by michaelkrnac** [osmandapp/OsmAnd-ios#513]
As soon when i press the "Route" Button the App crashes. (see attached Video) @PaulStets 
I also attached the only OSM Log File i can find in my analytics.
Not sure if it is related to the crash shown in the video.

[OsmAnd Maps-2019-12-09-194615.zip](https://github.com/osmandapp/OsmAnd-ios/files/3949219/OsmAnd.Maps-2019-12-09-194615.zip)

**Comment by PaulStets** [comment]
@michaelkrnac Thank you for the information. I will try to locate the issue and hopefully fix it.

**Comment by PaulStets** [comment]
Hi, @michaelkrnac. I have investigated the log you've sent us. The issue was most likely caused by the rendering problem, which was fixed recently. Please try the next update (it should be available today or tomorrow) and let us know if the issue persists.

**Comment by michaelkrnac** [comment]
Hello @PaulStets, after delete and reinstall It works perfect!! Thanks a lot !! No crashes on scrolling and routing. Works smooth with my > 1000 favorites on my old iPhone 6. Thanks!

Von meinem iPhone gesendet

**Comment by PaulStets** [comment]
Hello, @michaelkrnac. I'm glad it helped.
