### ISSUE TITLE
Add "Other maps"  to map  list

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-ios#519]
Add "Other maps" to map list (like in Android version)

**Comment by vshcherb** [comment]
1) Other maps should contain all maps that are not included in any list!
For example, Antarctica should be there now.
2) Make Antarctica continent and display as a separate item (check android)

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-ios/commit/dfdf3f6edc80690ab2a165c7e85c4ddb4d9a13b3
