### ISSUE TITLE
Hillshades rendering issue

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-ios#523]
The hillshade layer is not rendered on the map after the app reload, after selecting “show current position”, after switching between 2d to 3d view, sometimes after scrolling trough map and zooming in and out.

The issue occurs on IOS 13.3 iPhone 11.

**Comment by katerynakocherhina** [comment]
The issue occurs with OsmAnd v.3.11

**Comment by PaulStets** [comment]
Fixed with https://github.com/osmandapp/OsmAnd-core/pull/116
