### ISSUE TITLE
[bug] Fix margins in installed maps details

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-ios#526]
When I try to my installed map details I got no right margins at all :
![16B4C7E5-9031-4191-89EA-3DA6E6A35280](https://user-images.githubusercontent.com/59312735/71544859-5fecd580-2984-11ea-93b3-a6be25e720c9.jpeg)
I’m running iOS 13.3 on an iPhone 7 and I have this bug with osmand maps 3.11

**Comment by max-klaus** [comment]
Fixed
