### ISSUE TITLE
[bug]Make search more intelligent 

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#528]
I have tried to find a restaurant I know in my city, search missed to find it because it has a “-“ on it’s name. So I typed “rita plage” and then “rita plage Lyon” and I haven’t got a relevant result, because the name of the restaurant was “rita-plage” in osmand maps :
![5A685F4B-BF6B-4CA7-B6E5-9D671762E12E](https://user-images.githubusercontent.com/59312735/71559967-5e92da00-2a64-11ea-9ee1-78c32a6dd214.png)
![CCE1EC7C-46AA-41D8-8A5E-3C3D8ADAAC9E](https://user-images.githubusercontent.com/59312735/71559968-5e92da00-2a64-11ea-8044-dde02d4e1a69.png)
![434755F9-7342-417E-A441-D506ADE56AD8](https://user-images.githubusercontent.com/59312735/71559969-5e92da00-2a64-11ea-8707-97a7fedb9b2a.png)

Issue occurred in osmand maps 3.11 with an iPhone 7 running iOS 13.3

**Comment by stragu** [comment]
Still difficult to get quick, relevant results in version 3.14

Search is very central to apps like OsmAnd, and I have heard from other people that they believed the search performance of OsmAnd was the main drawback.

I think there are at least three issues at hand:

- **Speed**: I just tested searching for a specific cafe in my suburb, called "Alphabet". The search took 50 seconds to return the relevant POI. The map was even already centred on that POI.
- **Fuzzy search** is needed to account for typos or slight variations in spelling, like described above. For example, we should still get the result "Alphabet" when searching for "Alphbet".
- **Better order** of results, reconsidering the relevance of the results. For example, in one of my tests, searching for "the common" will list 3 items that have only the word "common" in their names before the park that is simply named "the common", exactly like the search string (and that is also closer to my location than the three first items).

Some results are **very** unexpected. One example: I searched for a nearby cafe/restaurant with the string "plenty restaurant" and got many restaurants in the list (pretty much all of the restaurants in and around my suburb), but not the relevant one. The names didn't even include the word "plenty". Then I thought "it might be classified as a cafe", so searched for "plenty cafe", and it listed the right POI... which is actually classified as a restaurant! Go figure! :thinking: 

See below the two screeshots. The POI in question is this one, if you want to make sense of the tags: https://www.openstreetmap.org/node/4534860160

Maybe linked to the fact that it has `cuisine=coffee_shop`? Still, very odd behaviour.

![image](https://user-images.githubusercontent.com/1747497/88447892-8cfe5980-ce7b-11ea-9ca9-911378f6dfd1.png)

![image](https://user-images.githubusercontent.com/1747497/88447896-94256780-ce7b-11ea-9aa9-cdcb0eb5e6fd.png)

**Comment by vshcherb** [comment]
I think this bug will be closed with this release cause we've thoroughly addressed item 1 and 3 (especially this one). So changes should be visible in 3.80 and then we will take next steps to improve it.

**Comment by stragu** [comment]
@nabilys : could you test your original issue with searching a hyphenated name? In my tests, it does work fine. I just tried with this node, which has a hyphen in the name: https://www.openstreetmap.org/node/4706709858

@vshcherb : thanks for the work that went in 3.80 regarding search performances. I did notice that the search is quicker, so I agree that my first point is fixed.
About the 3rd one: unforunately, I get the exam same result. Searching for "the common" returns many results, but the park that is called exactly that, "The Common", appears in position 12 (so, even worse than when I reported it, it seems).

Anyway, as long as the issue described by @nabilys is fixed, I am happy to see this issue closed, and I can report more specific things in new, separate issues! :+1:

**Comment by vshcherb** [comment]
Yes we've migrated most of the search changes from android version and in the coming patch all android features will be present. Since then we will work on both versions simultaneously
