### ISSUE TITLE
[bug] incorrect curve of percentage in navigation

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-ios#529]
The view of altitude doesn’t seems to follow percentage view. Here is an example in the following picture : 
![C3CD0C88-3E7C-4FF1-A8F4-C1F2EDF85633](https://user-images.githubusercontent.com/59312735/71585395-ad994780-2b16-11ea-8d87-acfba5e251bd.png)

Percentage ends before altitude and seems wrong

**Comment by nabilys** [comment]
The view of altitude doesn’t seems to follow percentage view. Here is an example in the following picture : 
![8177CE6D-B9C4-4F7E-B10B-B8041A8EBA91](https://user-images.githubusercontent.com/59312735/71585301-5c895380-2b16-11ea-9dcd-755870d87acb.png)
Percentage ends before altitude and seems wrong

**Comment by vshcherb** [comment]
We are going to update that graph, though it is a correct behavior. We don't display slope for first and last 30 meters
