### ISSUE TITLE
[Feature request] Clarify navigation mode

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#534]
Let's say that I have planned a navigation and started it, I have this type of screen : 
![IMG_7044](https://user-images.githubusercontent.com/59312735/71675101-5943d100-2d7d-11ea-9959-67fe2fd4e286.PNG)

Next, if I click on the arrow icon right to the hamburger icon, I get this menu :
![IMG_7045](https://user-images.githubusercontent.com/59312735/71675275-ab84f200-2d7d-11ea-90f0-1a9311f65a3a.PNG)
"Départ" in french means "Start", which is incorrect since the navigation mode already began. It should be "Resume" or "Reprendre" in french.
There is another "Annuler" or "Cancel" button next to it. Again, it is a bit confusing since we could think that this button cancel itinerary modification here, but it act like a "Stop" or "End" navigation button.

So : 
-Shouldn't the icon showing the itinerary modification interface be more explicit? it looks a lot like the geolocalisation icon.
-Could you modify itinerary's modification button "Start"/"Départ" to be more explicit ?
-Shouldn't the "Cancel" button be renamed "Stop" or "End" ? Or even be placed in the navigation screen, like most of the navigation apps?

I got this behaviour with OsmAnd 3.11 running on an iphone 7.

Thank you :-)

**Comment by nabilys** [comment]
Also, could you use native iOS dialogue box to end navigation? 
![3DAF9143-3891-43CB-A5F3-28D7CF0478F2](https://user-images.githubusercontent.com/59312735/71692964-92933580-2dab-11ea-8d12-a8a5bbd17078.png)

Osmand maps use native in other parts of the interface, like here : 

![803DFE4B-2B12-4266-A9E7-398D5C68338B](https://user-images.githubusercontent.com/59312735/71692970-97f08000-2dab-11ea-9912-0b953ba30efb.png)

**Comment by vshcherb** [comment]
I think it's consistent now with android and documentation and probably doesn't need to change.
