### ISSUE TITLE
[Bug Report] wikimedia_commons= Image Not Displayed

### ISSUE THREAD

**Issue by pqhf5kd** [osmandapp/OsmAnd-iOS#538]
Review:
- [x]  Image for https://www.openstreetmap.org/node/6267747285 doesn't show up (On Android version is showing)
- [x]  Hide table cell with URL to the image.
![photo_2020-09-09 13 35 23](https://user-images.githubusercontent.com/9365308/92588211-5486d380-f2a1-11ea-9f1c-cf69ec2a74c4.jpeg)
------------

- [x] Show pictures with tag  `image = *`
- [x] Show pictures with tag  `wikimedia_commons = File:... `
- [x] Show pictures with tag  `wikimedia_commons = Category:... `
- [x] Show pictures with tag  `wikidata =  *`
- [x]  Add icon for wikimedia cards?
--------

Nodes linked to an image with wikimedia_commons= do not show an image when selected in OsmAnd.

Examples: 
676497641
1433298999
5610200725
64795102

They may show Mapillary images but not the wikimedia file

**Comment by pqhf5kd** [comment]
Any support for this?

I feel like it's much more useful to be able to see a clear photo of an object rather than an image from a car driving along a nearby street. Particularly for things like public transport vending machines when visiting a city for the first time.

**Comment by pqhf5kd** [comment]
Looking at previous issues, it appears that this should work.

https://github.com/osmandapp/Osmand/issues/5643 mentions an issue with diacritics but here is an example without any that also doesn't work: https://www.openstreetmap.org/node/6267747285

**Comment by dmpr0** [comment]
We need to add support for wikidata, wikimedia images as we have in android.

**Comment by dmpr0** [comment]
Review:
- [ ]  Image for https://www.openstreetmap.org/node/6267747285 doesn't show up (On Android version is showing)
- [ ]  Hide table cell with URL to the image.
![photo_2020-09-09 13 35 23](https://user-images.githubusercontent.com/9365308/92588211-5486d380-f2a1-11ea-9f1c-cf69ec2a74c4.jpeg)
