### ISSUE TITLE
How to delete Sqlitedb maps?

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd-ios#539]
Hello. Please add the ability to delete added sqlitedb online-maps from the menu "Overlay" and "Underlay". For example, you can add a "Swipe to delete" gesture. 

At the moment, to delete the added maps, I have to delete the application and install it again.

https://www.dropbox.com/s/5ca1pgshf1m56h8/photo%2005.01.2020%2C%2021%2004%2037.jpg?dl=0

**Comment by dmpr0** [comment]
Hello! Thank you for the feedback. We are planning to make some UI changes on those screens. Now you can delete SQLiledb maps, in Menu - Map & Resources - Installed.

**Comment by nnngrach** [comment]
Wow, thanks!
