### ISSUE TITLE
Sqlitedb ellipsoid bug

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd-ios#540]
Hello. Here is a map of an elliptical projection. The "ellipsoid" field is set to 1. But tiles are displayed with an offset. 

https://www.dropbox.com/s/nibc063be53qr38/global-satellites-yandex_proxy.sqlitedb?dl=0

Just compare with the map from Google (ellipsoid = 0)

https://www.dropbox.com/s/j13lwg3bf28jn67/Global-Satellites-Google_with_labels_ru.sqlitedb?dl=0

Screenshot: 

https://www.dropbox.com/s/jm5bluvrie12ghh/ellipsod%20bug.jpg?dl=0

**Comment by nnngrach** [comment]
If it helps, I have a formula for calculating the offset.

**Comment by vshcherb** [comment]
It should be fine cause we have algorithms in Android

**Comment by nnngrach** [comment]
Explaining (in russian).

**Comment by nnngrach** [comment]
Tile number to LatLon

https://github.com/nnngrach/AnyGIS_server/blob/f16575846fb65fcba3ec5b593bb8b8122032966f/Sources/App/ModelsOfLogic/Coordinate%20Tools/CoordinateTransformer.swift#L48

LatLon to EllipsoidTileNumber and Offset

https://github.com/nnngrach/AnyGIS_server/blob/f16575846fb65fcba3ec5b593bb8b8122032966f/Sources/App/ModelsOfLogic/Coordinate%20Tools/CoordinateTransformer.swift#L62

**Comment by nnngrach** [comment]
Sqlitedb of map with offset (if it helps):

https://www.dropbox.com/s/dfx6h4pgksq9uqs/global-satellites-yandex_converted.sqlitedb?dl=0

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-ios/commit/a601e42ccc885b191a4fe069a12b53d503c0ef82

**Comment by nnngrach** [comment]
Thank you!
