### ISSUE TITLE
iOS app loses online map configuration 

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-ios#541]
Version: 3.11 on iOS
Steps to reproduce:

install and run OsmAnd, install the default offline world map
configure online map OpenTopoMap
configure online overlay Waymarkedtrails Hiking
use the app
switch to another app or turn the device off, wait for some time (30 min seems to do the trick)
switch back to OsmAnd
=> OpenTopoMap and Waymarkedtrails Hiking are no more in the list of installed offline maps

**Comment by vshcherb** [comment]
https://github.com/osmandapp/Osmand/issues/8171

**Comment by PaulStets** [comment]
Unfortunately, this can happen if the app was not closed properly (e.g. with a crash). This can be avoided by swiping the app off the active apps list. 
However, during my investigation, I found out that a selected online map source wasn't displayed on the app start and fixed the issue.

**Comment by jamescoverdale** [comment]
I still see this issue in the latest iOS app store version, tried many times, including closing the app by swiping off from active list. It seems after awhile when reopening the app the custom map source has been removed.
