### ISSUE TITLE
Autorecording makes navigation crash

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-ios#544]
On iPhone 5S, iOS 12.4.4.

When the autorecording trip during navigation is set up, it is impossible to launch navigation. Calculation is possible, then when pressing start the app is freezing. This is reproducible. And when I uncheck autorecording all things are back to normal.

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-ios/commit/846bd5c1499cec69c76be02fdfe7d53b0136020a
