### ISSUE TITLE
Directional lines for Markers in iOS

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#556]
I propose to add arrows and directional lines for Markers in iOS like in Android version.
![2aa](https://user-images.githubusercontent.com/44466116/72729365-1026b600-3ba0-11ea-9ddf-6b1ac07d7779.jpg)
![3aa](https://user-images.githubusercontent.com/44466116/72729368-10bf4c80-3ba0-11ea-8d6b-48ec3077d101.jpg)

**Comment by AnnBibyk** [comment]
Fixed by @AnnBibyk in https://github.com/osmandapp/OsmAnd-iOS/pull/667
