### ISSUE TITLE
Route details slope error

### ISSUE THREAD

**Issue by natolh** [osmandapp/OsmAnd-ios#566]
![1753ECE1-B637-487B-AAC4-16BF9A483EDD](https://user-images.githubusercontent.com/30546417/72963236-fdd29500-3db6-11ea-9409-abe1d805f83a.png)

iPhone 5S, iOS 12.4.4, latest OsmAnd on test flight.

Two problems there :
1/ labels are truncated even though there is a lot of space available.
2/ some slope calculations are wrong (244%) !

**Comment by nabilys** [comment]
In iPhone 7, I also have truncated labels :
![BB957362-CD75-429B-889B-F28726270877](https://user-images.githubusercontent.com/59312735/72964576-91f22b80-3dba-11ea-968e-68f53e40c173.png)

**Comment by PaulStets** [comment]
Hi, @natolh. Thank you for reporting this. Concerning the first issue, I understand what may have caused the confusion. The dots here serve as a separator between two values to avoid the confusion with ```-``` sign, however, I see now how it can introduce further confusion for an iOS user. We will think of another way of separating the range. As for the slope percentage, I'll take a look.

**Comment by natolh** [comment]
Maybe something like “2 to 6 %” could solve the problem but this involve translation for other languages.
Middle dot could be another option “2 • 6 % ».

**Comment by PaulStets** [comment]
We’ve already changed it to the arrow. It will look like this:
![74618AAB-E0A2-44FE-872A-4AB5CB84C6BA](https://user-images.githubusercontent.com/20681525/73014184-630fa000-3e22-11ea-93aa-05f8cb4f92e3.png)

**Comment by natolh** [comment]
Yeah, didn't think of that. Seems good ! 👌🏻

**Comment by PaulStets** [comment]
Fixed the slope issue with https://github.com/osmandapp/OsmAnd-core/pull/114/commits/a6c6fc8d9dea544e0ec74bd5a4861f2bbb431dbb
