### ISSUE TITLE
[bug] background refreshed keeps old informations in map view when zooming

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-ios#567]
Hi, in iPhone 7, osmand 3.21, I have the following issue : I zoom where there’s a poi or adress number, and it’s name remains in background, event after waiting enough time for the refresh. I’ve tested it with osmand offline map view in lyon : 
![5A7B63EA-6D21-4358-8BDC-8D8DF9CE86DE](https://user-images.githubusercontent.com/59312735/72969135-34afa780-3dc5-11ea-8530-074312d31958.png)
![77EA9AAE-FAC6-49DB-82F7-EA0916022EF1](https://user-images.githubusercontent.com/59312735/72969136-35483e00-3dc5-11ea-8d15-ba1fa9cddb92.png)

**Comment by vshcherb** [comment]
You need to use Offline maps to get consistent look and feel
