### ISSUE TITLE
[bug]Bad continent name

### ISSUE THREAD

**Issue by nabilys** [osmandapp/OsmAnd-iOS#579]
Hi, using osmand 3.23 in French, I got those names for continents, which aren’t French or English :
![A0101462-D993-48A7-8089-29E22760EA67](https://user-images.githubusercontent.com/59312735/73178700-1a9dfe00-4112-11ea-801e-eec907a5aaec.png)

**Comment by vshcherb** [comment]
https://eo.wikipedia.org/wiki/Kontinento

**Comment by vshcherb** [comment]
This is Esperanto

**Comment by nabilys** [comment]
I do not remember how it used to be, but it also seems that every contry have its cities written on its native language :
![E8A4B52F-2A2F-4AAD-8F20-FC7766CB12F2](https://user-images.githubusercontent.com/59312735/73188489-3c53b100-4123-11ea-8a8c-f9396ec036a8.png)
![D1C0B8C9-6D1F-408D-9E3B-B71E1CE319AA](https://user-images.githubusercontent.com/59312735/73188490-3cec4780-4123-11ea-8c7e-e883a4ecff82.png)

**Comment by Zirochkabila** [comment]
4.3.0.13  **Not reproduced**
Try to apply this setting: Configure map > Map language
