### ISSUE TITLE
Favorites pages show Russian when English is the installed language.

### ISSUE THREAD

**Issue by allthingssatnav** [osmandapp/OsmAnd-ios#59]
Latest iOS release from App Store.

![img_2863](https://cloud.githubusercontent.com/assets/11207242/7222565/0d566f8a-e6c6-11e4-9caf-89c8d57083c9.jpg)

![img_2864](https://cloud.githubusercontent.com/assets/11207242/7222571/3256faf2-e6c6-11e4-9e3b-c2627bf118af.jpg)

**Comment by vshcherb** [comment]
Fixed
