### ISSUE TITLE
Unnecessary padding in OSM Editing UI

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-ios#592]
Add time span button, has unnecessary
![IMG_6BC48F7F6BDF-1](https://user-images.githubusercontent.com/9365308/73726407-2a33cd00-4738-11ea-9caf-2a59fef77d47.jpeg)
 padding that appear recently.

**Comment by iyerin** [comment]
closed in f34d172a265fa2d8abf47a8166b6febb062d115e
