### ISSUE TITLE
Adding a line for end point of route

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-ios#599]
It would be great to add a finish line for graph without data like it was done for Android version (https://github.com/osmandapp/Osmand/issues/8266)
![photo_2020-02-11_20-21-16](https://user-images.githubusercontent.com/44466116/74261438-4de4ad80-4d0c-11ea-97ec-e6f49724d9ed.jpg)

**Comment by vshcherb** [comment]
The code is already present in Android
