### ISSUE TITLE
GPX Extensions

### ISSUE THREAD

**Issue by allthingssatnav** [osmandapp/OsmAnd-ios#60]
I noticed that the GPX Export of a Waypoint is misusing the (type) tag for the Favorites “Group/Category”. The categorizing of a Waypoint should be placed in the (Extensions) of Waypoint in the form of: 

![gpx example](https://cloud.githubusercontent.com/assets/11207242/7286998/83ce2acc-e905-11e4-9bc9-bc3e8467f508.png)

If OsmAnd is going to create Extensions there should be an Extensions xsd published for interoperability.

**Comment by dinamic** [comment]
If this is not fixed yet, maybe you can tag some of the developers who contributed the commits. Just an idea as it has been 3 years since this was posted.

**Comment by vshcherb** [comment]
Yes we still use type for Group in Android version and Ios is compatible, so keeping story short so far there were no complaints about it. So I'm afraid we will keep using it especially for backward compatibility.
