### ISSUE TITLE
Issue with map update icon for maps which don't have any update

### ISSUE THREAD

**Issue by amkoro** [osmandapp/OsmAnd-ios#613]
First of all thanks for nautical depth maps support!
I noticed some issue with "Nautical depth contours Contours" and Great lakes contours maps. I just downloaded them but their update/download icon shows that update available for them.
Expected result: the "i" inside a circle icon should be shown for maps which don't have an update. 

The same issue I noticed earlier with "French - Corsica contour lines" map.

I'm using the recent 3.12 release version on iPhone which were updated (not installed anew) from the previous release version.

**Comment by max-klaus** [comment]
@amkoro please try to press refresh icon at Maps main screen (top-right corner).

**Comment by amkoro** [comment]
I tried but it does not help. You still unable to "download latest version of map". It still shows that new update is available.

**Comment by max-klaus** [comment]
Looks like you have latest version of maps already, but icon shows wrong info. It will be fixed soon.

**Comment by amkoro** [comment]
Exactly,
that's what I'm talking about
