### ISSUE TITLE
OSM Edits: Error while uploading deleted POI's

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-ios#617]
I try to upload deleted POI's but every time I have this error, username and password are correct. It happens when I select few edited, added and deleted POIs (edited and added uploads correctly) or only single deleted POI's.
![IMG_7D17FF09CF7C-1](https://user-images.githubusercontent.com/9365308/74738565-d957c480-525f-11ea-83c3-7a763c3a3939.jpeg)

OsmAnd 3.12, iOS13 (latest stable version).

**Comment by PaulStets** [comment]
This happens when the node representing the POI is a part of the building's contour. In such cases, one should clear the POI's tags manually instead of deleting the object.
