### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by KAMiKAZOW** [osmandapp/OsmAnd-ios#62]
I guess the iOS version is not under GPLv3 because of the App Store but surely LGPLv2+ or something like that, right?

**Comment by SelimAbidin** [comment]
License is still missing.

**Comment by andrewharvey** [comment]
https://github.com/osmandapp/OsmAnd-ios/blob/master/PULL_REQUEST.MIT.LICENSE says that patches and PR's are MIT licensed, but most of the files in the header are "//  Copyright © 2017 OsmAnd. All rights reserved." eg. https://github.com/osmandapp/OsmAnd-ios/blob/master/Sources/OAApplicationMode.m

**Comment by vshcherb** [comment]
License is the same as in OsmAnd project. Licensing and copyright should not be mismatched. So to answer it shortly:
1. Pull requests can only be accepted if they are licensed under MIT though copyright obviously stays with the owner of Pull request.
2. For all code created by OsmAnd BV employers OsmAnd BV owns copyright so it could change license of its code for specific purposes. But all the code created by OsmAnd BV is published on github under GPLv3 license.

**Comment by tbertels** [comment]
Please add a LICENSE file on this repository to make it clear, like [on OsmAnd](https://github.com/osmandapp/Osmand/blob/master/LICENSE).
The [Wikipedia page](https://en.wikipedia.org/wiki/OsmAnd#Licensing) says 
> The iOS version’s source code is available but not under a free license. File headers only say Copyright © 2017 OsmAnd. All rights reserved

**Comment by vshcherb** [comment]
To avoid confusion please, created License file - please check if everything is correct - https://github.com/osmandapp/OsmAnd-ios/blob/master/LICENSE
