### ISSUE TITLE
[Nice to have] Glitch with fitst opening Sqlitedb ellipsoid map file

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd-ios#621]
I noticed that sometimes the first time you turn on any sqlitedb file with map in ellipsoid proection, there is a glitch. It looks like all the tiles on the screen have been moved, but one or two have been accidentally skipped. Here's a screenshot of what it looks like.

[Location with Osmand vector map. All is good.]

https://www.dropbox.com/s/rcup3cx2jcadtdz/photo%2020.02.2020%2C%2023%2034%2011.png?dl=0

[The same location with Yandex map. One tile incorrect]

https://www.dropbox.com/s/6nitpqeus7ar9n3/photo%2020.02.2020%2C%2023%2034%2056.png?dl=0

But as I already wrote, glitch occurs only immediately after the first opening the file. If you scroll or zoom the map, there will be no more glitches. 

[Sliding map aside...]

https://www.dropbox.com/s/9fpbmsxzoqa67g6/photo%2020.02.2020%2C%2023%2035%2010.png?dl=0

[... and going back. Map looks perfect]

https://www.dropbox.com/s/tthxahkglbjq636/photo%2020.02.2020%2C%2023%2035%2017.png?dl=0

In the future, when using the map from this file, there will be no more glitches. After restarting the app too.

Here are a few map files that will help you detect this glitch:

https://www.dropbox.com/sh/hpo75rb6k0pjroq/AABRkQ8f9t6HGUWV1971K78fa?dl=0

**Comment by max-klaus** [comment]
Do you have access to testflight builds? If yes, please try latest build.

**Comment by nnngrach** [comment]
I downloaded today version 3.13 (3.28)

**Comment by nnngrach** [comment]
https://www.dropbox.com/s/ga5hgawmcr2attf/photo%2001.03.2020%2C%2020%2002%2023.png?dl=0

**Comment by max-klaus** [comment]
It should be fixed at sqlite db file. You need to introduce "tilesize" column to "info" table with corresponding value (512). Otherwise it will be filled automatically after first tile will be downloaded.

https://github.com/osmandapp/OsmAnd-ios/blob/master/Sources/Map/OASQLiteTileSource.mm#L158
