### ISSUE TITLE
Sqlitedb doesn’t erase its cache

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd-ios#622]
When you click the delete cache button, it is not actually deleted, but only hidden. The file size is not reduced.

### Example of metainfo file

Osmand online tiles  - before click Erase button.
https://www.dropbox.com/s/qjto1ofd9xkroiy/photo%2020.02.2020%2C%2023%2059%2041.png?dl=0

Osmand online tile - after click Erase button. Tiles deleted correctly.
https://www.dropbox.com/s/xc2idtk5izi4aqv/photo%2021.02.2020%2C%2000%2000%2009.png?dl=0

### Example of sqlitedb file

Yandex map - before click.
https://www.dropbox.com/s/58hd5ujqowrgbye/photo%2021.02.2020%2C%2000%2000%2019.png?dl=0

Yandex map - after click. Nothing happens.
https://www.dropbox.com/s/58hd5ujqowrgbye/photo%2021.02.2020%2C%2000%2000%2019.png?dl=0

I'm guessing this may be the same problem as the Android version that was recently fixed:
https://github.com/osmandapp/Osmand/issues/8484

You can use any of this sqlitedb files for testing purposes:
https://www.dropbox.com/sh/hpo75rb6k0pjroq/AABRkQ8f9t6HGUWV1971K78fa?dl=0

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-ios/commit/2b342cd1b9329bc3f5126cb1bc0bab89ad3e7340

**Comment by nnngrach** [comment]
Thanks
