### ISSUE TITLE
OsmAnd on IPAD => Permanent crash

### ISSUE THREAD

**Issue by SvenHi** [osmandapp/OsmAnd-ios#63]
Environment:
IPad 3 64GB
IOS 8
German
Osmand 1.0.222
Installed Charts: German (all), Italian (all), Switz, Austria, Seemarks

Active view: Nautical

After some actions (zoom in/out) the application freezed.
In "taskmanager" (double click home button) i closed osmand.
Try to open again => Wellcome screen appear (white window, small osmand logo) => after ~10 seconds, the application terminates (back to IOS screen).
=> Open taskmanger again => I can see the freezed chart window before.
=> Restart of IPad => Furthermore freezed osmand

=> So it seems there is a possibility that Osmand crashs, and the consequence is permanent.

Probably i have to re- install OSMAND again.

If you are interested, to have more information about this (maybe error logs, etc), please reply.

**Comment by SvenHi** [comment]
Log:

Hardware Model:      iPad3,3
Process:             OsmAnd Maps [334]
Path:                /private/var/mobile/Containers/Bundle/Application/32AB3238-327D-48BD-8D42-EBD0CAFD1350/OsmAnd Maps.app/OsmAnd Maps
Identifier:          net.osmand.maps
Version:             1.0.222 (1.0.222)
Code Type:           ARM (Native)
Parent Process:      launchd [1]

Date/Time:           2015-05-27 23:17:06.427 +0200
Launch Time:         2015-05-27 23:16:51.171 +0200
OS Version:          iOS 8.3 (12F69)
Report Version:      105

Exception Type:  00000020
Exception Codes: 0x000000008badf00d
Highlighted Thread:  0

Application Specific Information:
<BKNewProcess: 0x1662e5b0; net.osmand.maps; pid: 334; hostpid: -1> has active assertions beyond permitted time: 
{(
    <BKProcessAssertion: 0x16630a40> id: 42-47C8D037-CB3F-4E4B-94B7-EA42630E7E94 name: Suspending process: <BKNewProcess: 0x1662e5b0; net.osmand.maps; pid: 334; hostpid: -1> permittedBackgroundDuration: 10.000000 reason: suspend owner pid:42 preventSuspend  preventThrottleDownCPU  preventThrottleDownUI  preventSuspendOnSleep 
)}

Elapsed total CPU time (seconds): 11.560 (user 11.560, system 0.000), 52% CPU 
Elapsed application CPU time (seconds): 1.638, 7% CPU

**Comment by vshcherb** [comment]
I guess issues is outdated or was already fixed
