### ISSUE TITLE
Speed limits not displayed

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-ios#630]
The issue occurred while navigating through the Covered Bridge Road 
from: 35.688167 -78.384498 
to: 35.692284 -78.416822 
on IOS 13.3

**Comment by katerynakocherhina** [comment]
The same issue occurs at:
35.902270 -78.557947 to 
35.873914 -78.578101 on US 1

35.873914 -78.578101 to 
35.766315 -78.506646 on I540

35.767392 -78.507383 to 
35.766699 -78.464000 on US 64

**Comment by PaulStets** [comment]
Not reproducible with route simulation.
![image](https://user-images.githubusercontent.com/20681525/75865551-65472000-5e0c-11ea-9514-09250925536b.png)
![image](https://user-images.githubusercontent.com/20681525/75865563-69733d80-5e0c-11ea-843b-a09588cf04d5.png)
