### ISSUE TITLE
OsmAnd for Iphone MAJOR CRASH, Bricked after map purchase & downloading some french maps

### ISSUE THREAD

**Issue by stephan75** [osmandapp/OsmAnd-ios#64]
Transfer from https://groups.google.com/d/topic/osmand/30B1kHMpXDw/discussion

It seems that an iOS app user has lost the registration of his map purchase.

How can that be restored?

Aditional information needed?

**Comment by vshcherb** [comment]
As I know the button Refresh on the Purchases screen allows to restore purchases.

**Comment by stephan75** [comment]
issue seems to be no more relevant.
