### ISSUE TITLE
iOS app doesn't allow to change shortcut name for quick actions

### ISSUE THREAD

**Issue by qqvm** [osmandapp/OsmAnd-iOS#649]
iOS application doesn't allow to change shortcut name for quick actions.
If I create few different actions to show some POI category, all of them are named "Show POI" and I am unable to change it.
Since all of them have the same name and icon, it is impossible to differ them.

**Comment by qqvm** [comment]
After the fix “Action name” is still missing at “Quick action” menu. “Show POI” appears instead. 
![F71D0817-AA9F-4CF9-AE2C-0627BF84B6DE](https://user-images.githubusercontent.com/54307539/87529989-6f213f80-c698-11ea-8513-c87cbf9d6157.png)

**Comment by PaulStets** [comment]
Hi, @qqvm. Could you please provide more information on how to reproduce this. When I'm adding a "Show/Hide POI" action, I'm able to edit the action name. Furthermore, the default name changes to the name of selected categories as expected after the fix. Perhaps you need to delete the old actions via the Configure screen - Quick Action menu by pressing the pencil icon. After you deleted the old actions with duplicate names, please try to add them again. 

Let me know if it helps.

**Comment by qqvm** [comment]
I am able to change it too and it shows the correct name while editing, but when I click "Quick action" button on the map it shows all items as "Show POI", ignoring the name I've given them. Deleting all quick actions and adding them again doesn't fix the problem.

**Comment by PaulStets** [comment]
Thanks for the info. I can see the issue now.

**Comment by PaulStets** [comment]
Fixed it. From now on it will look like this:
![image](https://user-images.githubusercontent.com/20681525/88457918-afe83800-ce92-11ea-871c-a7c946406522.png)
