### ISSUE TITLE
Fix background color in selected cell

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#653]
When open My places — Favorites — Edit, select favorites, selected background color only visible under checkbox, but it must change the background of whole cell. Also, we need to find all similar places.
![IMG_FE821AD1F487-1](https://user-images.githubusercontent.com/9365308/77045992-e1279780-69ca-11ea-82ea-d6724b709da3.jpeg)

**Comment by AnnBibyk** [comment]
Fixed by @AnnBibyk 
https://github.com/osmandapp/OsmAnd-iOS/pull/654/commits/5c1eecc6db9b144fb0da70e3a65c5da78b012229
