### ISSUE TITLE
Search issue 

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-ios#657]
While searching for the Stoney Hollow Road in the Pennsylvania map, it is needed to tap on the Show road on map button to see the results but nothing is listed in the search results
41.077374,-75.5061031
The search does not look for buildings or addresses connected to the road
![image](https://user-images.githubusercontent.com/50198677/77409025-4c091200-6dc1-11ea-8f85-bc885d3cea97.png)

**Comment by vshcherb** [comment]
Search show street on the map if there are no buildings
