### ISSUE TITLE
Context menu: lost divider + add multiline line support

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#689]
Context menu cells that can be expanded or collapsed doesn't have bottom dividers.
Also, we must add multiline support for cells like Wikipedia, official name.
![IMG_24DFC275DD7E-1](https://user-images.githubusercontent.com/9365308/81704624-b27fe780-9476-11ea-8d46-f2ec9379197b.jpeg)

**Comment by brncsk** [comment]
Please do add multi-line support for the Description field as well, if you ever get to implementing this. This would help displaying arbitrary information from my custom-made `.obf`s. Thanks a lot.

**Comment by nnngrach** [comment]
- [ ]  fix lost separator

- [ ]  add multiline line support
