### ISSUE TITLE
Map notes

### ISSUE THREAD

**Issue by matthijsmelissen** [osmandapp/OsmAnd-ios#70]
I often use OsmAnd for surveying and contributing to the map. I recently switched from Android to iOS, and so far I'm very happy with the functionality that the iOS-version provides.

However, one thing I really miss, and what is basically a showstopper for me when using OsmAnd for surveying, is the ability to display Map Notes. Are there any plans of including this functionality in the iOS-version of OsmAnd?

Thanks for all your hard work!

**Comment by vshcherb** [comment]
Yes there are plans to make it fully functional and the same as Android version, though there are already short plans to introduce address search & routing and later migrate all plugins functionality.

**Comment by math1985** [comment]
That's great news! Is there perhaps a list of priorities I can read somewhere?

**Comment by vshcherb** [comment]
This is too wide so far, I mentionned priorities N1 (routing and address search) and then it will be release.  And only after we are going to make proper backlog and priorities. Today unfortunately we don't plan that far.

**Comment by max-klaus** [comment]
OSM editing is ready
