### ISSUE TITLE
Downloaded map data is included in iTunes and iCloud backups

### ISSUE THREAD

**Issue by dgelessus** [osmandapp/OsmAnd-iOS#707]
I backed up my iPad (iPad mini 5th gen, running iOS 13.3.1) via iTunes and noticed that the backup was unusually large. Looking through some of the largest files in the backup, I found a few that clearly look like OsmAnd map data, for example:

```
00000000  08 02 90 01 80 b8 a6 98  93 2e 36 08 5f e5 50 12  |..........6._.P.|
00000010  1f 47 65 72 6d 61 6e 79  5f 68 65 73 73 65 6e 5f  |.Germany_hessen_|
00000020  64 61 72 6d 73 74 61 64  74 5f 65 75 72 6f 70 65  |darmstadt_europe|
00000030  22 0a 1a 04 6e 61 6d 65  48 02 50 02 22 0c 1a 08  |"...nameH.P."...|
00000040  62 75 69 6c 64 69 6e 67  48 0f 22 16 1a 10 61 64  |buildingH."...ad|
00000050  64 72 3a 68 6f 75 73 65  6e 75 6d 62 65 72 48 10  |dr:housenumberH.|
00000060  50 02 22 12 1a 07 68 69  67 68 77 61 79 2a 05 74  |P."...highway*.t|
00000070  72 61 63 6b 48 0b 22 21  1a 18 6f 73 6d 61 6e 64  |rackH."!..osmand|
(...)
```

The same thing seems to apply to iCloud backups as well. According to my iCloud backup settings, OsmAnd makes up about 8 gigabytes of my iCloud backup, which roughly matches the size of my map data (as displayed in the app). With iCloud backups this problem is especially relevant, because Apple's free iCloud storage is limited to 5 GB.

All of the maps in my OsmAnd installation are downloaded from within the app, so there's really no need for them to be backed up - if I have to restore from a backup, I can just redownload the maps. It would be very helpful if OsmAnd would [exclude its map data from backups](https://developer.apple.com/library/archive/qa/qa1719/_index.html) so that it doesn't waste space on the backup computer and on iCloud.

**Comment by vshcherb** [comment]
yes totally adree

**Comment by dgelessus** [comment]
Unfortunately this is happening again for me (using OsmAnd 3.81 on iPadOS 13.7). When I backed up my iPad today using iTunes, it started copying large files again. I checked one of the files and it looked like OsmAnd data (I don't have a hex dump this time - I already deleted the backup and forgot to copy the hex dump first, sorry). After I deleted all downloaded maps in the OsmAnd app, the backup completed quickly.

This is quite strange, because I think for some time it worked properly - I had maps installed on the device and they (correctly) weren't included in the backup. I don't know why, but now the problem has appeared again. If you need any other information that would help with debugging this, let me know.

**Comment by dgelessus** [comment]
Sorry for bumping this again, but I'm still having this problem. I'm now on OsmAnd 4.0.6 on iPadOS 14.6, and I've already reinstalled the app, but I still get large OsmAnd files in my iTunes backup. Here are hex dumps of the start of two of these large files. The first file is 325 MB, the second one is 1.4 GB.

<details>
<summary>Hex dumps</summary>

```
00000000  08 02 90 01 bc f0 a5 b6  f1 2e 36 12 6c 9b d1 12  |..........6.l...|
00000010  07 62 61 73 65 6d 61 70  22 0a 1a 04 6e 61 6d 65  |.basemap"...name|
00000020  48 02 50 02 22 10 1a 0a  72 6f 61 64 5f 72 65 66  |H.P."...road_ref|
00000030  5f 31 48 01 50 02 22 09  1a 03 72 65 66 48 01 50  |_1H.P."...refH.P|
00000040  02 22 14 1a 0c 72 6f 75  74 65 5f 72 6f 61 64 5f  |."...route_road_|
00000050  31 2a 00 48 02 50 01 22  16 1a 10 72 6f 75 74 65  |1*.H.P."...route|
00000060  5f 72 6f 61 64 5f 31 5f  72 65 66 48 01 50 02 22  |_road_1_refH.P."|
00000070  0d 1a 07 6e 61 6d 65 3a  65 6e 48 02 50 02 22 11  |...name:enH.P.".|
00000080  1a 07 6e 61 74 75 72 61  6c 2a 04 77 6f 6f 64 48  |..natural*.woodH|
00000090  06 22 0f 1a 05 70 6c 61  63 65 2a 04 74 6f 77 6e  |."...place*.town|
000000a0  48 06 22 15 1a 07 68 69  67 68 77 61 79 2a 08 74  |H."...highway*.t|
000000b0  65 72 74 69 61 72 79 48  0b 22 0d 1a 07 6e 61 6d  |ertiaryH."...nam|
000000c0  65 3a 7a 68 48 02 50 02  22 0d 1a 07 6e 61 6d 65  |e:zhH.P."...name|
000000d0  3a 72 75 48 02 50 02 22  16 1a 07 68 69 67 68 77  |:ruH.P."...highw|
000000e0  61 79 2a 09 73 65 63 6f  6e 64 61 72 79 48 09 22  |ay*.secondaryH."|
000000f0  17 1a 0e 72 6f 61 64 5f  6e 65 74 77 6f 72 6b 5f  |...road_network_|
```

```
00000000  08 02 90 01 80 a8 8e d7  f5 2e 36 0d 02 85 95 12  |..........6.....|
00000010  3c 47 65 72 6d 61 6e 79  5f 6e 6f 72 64 72 68 65  |<Germany_nordrhe|
00000020  69 6e 5f 77 65 73 74 66  61 6c 65 6e 5f 63 6f 6c  |in_westfalen_col|
00000030  6f 67 6e 65 2d 67 6f 76  65 72 6e 6d 65 6e 74 2d  |ogne-government-|
00000040  72 65 67 69 6f 6e 5f 65  75 72 6f 70 65 22 0c 1a  |region_europe"..|
00000050  08 62 75 69 6c 64 69 6e  67 48 0f 22 0a 1a 04 6e  |.buildingH."...n|
00000060  61 6d 65 48 02 50 02 22  16 1a 10 61 64 64 72 3a  |ameH.P."...addr:|
00000070  68 6f 75 73 65 6e 75 6d  62 65 72 48 10 50 02 22  |housenumberH.P."|
00000080  14 1a 07 68 69 67 68 77  61 79 2a 07 73 65 72 76  |...highway*.serv|
00000090  69 63 65 48 0b 22 21 1a  18 6f 73 6d 61 6e 64 5f  |iceH."!..osmand_|
000000a0  68 69 67 68 77 61 79 5f  69 6e 74 65 67 72 69 74  |highway_integrit|
000000b0  79 2a 01 30 48 0b 50 01  22 09 1a 03 72 65 66 48  |y*.0H.P."...refH|
000000c0  01 50 02 22 0d 1a 07 62  75 73 5f 72 65 66 48 01  |.P."...bus_refH.|
000000d0  50 02 22 0c 1a 06 68 65  69 67 68 74 48 02 50 02  |P."...heightH.P.|
000000e0  22 12 1a 07 68 69 67 68  77 61 79 2a 05 74 72 61  |"...highway*.tra|
000000f0  63 6b 48 0b 22 14 1a 08  62 75 69 6c 64 69 6e 67  |ckH."...building|
```
</details>

Again, if there's any other information that I can give you to help with debugging, let me know.

@nnngrach @vshcherb Could one of you please reopen this issue, so it doesn't get lost? Thank you!

**Comment by vshcherb** [comment]
It looks like you have Maps inside backups which is wrong and that's why they are large. Is it possible to delete backup and check again.

Am I understanding correctly that it's different that iTunes backup is different than iCloud  backup?

**Comment by dgelessus** [comment]
> Is it possible to delete backup and check again.

Yes, I can try to delete the backup and make a completely new one. I noticed that the large files have old modification times (March 2021). So maybe they are just old files and iTunes didn't delete them correctly.

> Am I understanding correctly that it's different that iTunes backup is different than iCloud backup?

The last time I checked, both iTunes and iCloud backups had the same problem. Right now I have iCloud backups disabled for OsmAnd, so I can't see how much data it would use in the iCloud backup. I'll turn it on again and see what happens now.

**Comment by dgelessus** [comment]
OK, I deleted the old iTunes backup. To be safe, I also reinstalled OsmAnd again (and downloaded a large map for testing). The new fresh iTunes backup *doesn't* have large map files anymore, and the iCloud backup says that OsmAnd only uses a few MB.

So it looks like the problem is already fixed in OsmAnd, and iTunes was just buggy and didn't delete the map files from my existing backup. Thank you for the help!

**Comment by Zirochkabila** [comment]
Below is a comment from one of our users. With a note that "Cannot easily reproduce bug since map updates occur monthly for me" - maybe it'll help

### Description
iCloud backup inflates during/after map update

### Steps to reproduce
Update local maps and make an iCloud back-up

### Actual result
Local maps are updated and iCloud backup becomes ~half the size of the downloaded maps

### Expected result
Local maps updated and no change in iCloud back-up file size

### Your Environment
OsmAnd Version: 4.2.4
Android/iOS version: iOS 16.1.1
Device model: iPhone 13 mini 128gb
