### ISSUE TITLE
Latest version doesn't open if maps downloaded 

### ISSUE THREAD

**Issue by vrtareg** [osmandapp/OsmAnd-ios#72]
Hi 

I have downloaded latest version by TestFlight and it is not loading.

I have reset app, opened it normally downloaded world and England maps and after close it is not loading again...

Regards, 
Areg

**Comment by vrtareg** [comment]
iPhone 4s
iOS 9.3.1 13E238
Storage 32Gb / 5Gb free

**Comment by crimean** [comment]
@vrtareg I guess you have installed version 1.2.22. Did you try 1.2.4? It is available on the TestFlight now.

**Comment by vrtareg** [comment]
Hi  Alexey

I got latest installed.

I will try to share a screen shot and video.

Regards, 
Areg

**Comment by vrtareg** [comment]
Not sure if you can access this:

https://drive.google.com/file/d/0BzgDxH-iXHygWDVMaWdwY2JQa2c/view?usp=sharing

**Comment by vrtareg** [comment]
Hi

Any update on this? 

Regards, 
Areg

**Comment by crimean** [comment]
@vrtareg Hello, we did some tests and it looks like issue appears on iPhone 4, 4S. Starting from iPhone 5 it works fine. 
I suggest to try reinstall the app and download England map not as single one, but by parts.

**Comment by vrtareg** [comment]
Hi

Did you found problem itself? 
Is it fixable? Is it because of full file size? 

Regards, 
Areg

**Comment by crimean** [comment]
@vrtareg This is the memory issue. The iPhone 4, 4S has 512 MB which is not enough for processing big files. It is not easy to fix and we have low priority of supporting such devices.

**Comment by vrtareg** [comment]
Looks like that it is not available on TestFlight anymore. 
Could you please publish once more?
Or it is released now?

**Comment by vrtareg** [comment]
Ah it is published already sorry.
