### ISSUE TITLE
[Feature request] add multiple coordinates format to the Favorites

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-iOS#720]
Review:

- [x] Navbar blinks when taping on expand/collape section with coordinates.
- [x] Cell height.
-----------------
While it is possible to select any available coordinates format for a random point on the map the same is not possible for the favorite.

**Comment by vshcherb** [comment]
We should format coordinates in the same way on all screens

**Comment by dmpr0** [comment]
Review:
- [ ]  Navbar blinks when taping on expand/collape section with coordinates.
- [ ]  Cell height.
