### ISSUE TITLE
Crash when trying to delete last active markers

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#726]
OsmAnd 3.15 last version from App Store. The crash occurs every time I try to delete all active markers, after restarting all markers that I deleted before the crash appears again.

**Comment by nnngrach** [comment]
Looks like this bug's already fixed. I couldn't find it in an app built from the master branch.

**Comment by dmpr0** [comment]
- [ ] Так же падает, как и падал
