### ISSUE TITLE
On IOS 13.5.5 tracks stored on OsmAnd Maps disappear ???

### ISSUE THREAD

**Issue by Pecita** [osmandapp/OsmAnd-iOS#730]
It is not immediate.
Otherwise everything is in the title. I don't understand anything else.

**Comment by PaulStets** [comment]
@Pecita Hi, could you please describe how it happens? Which version of the app do you have?

**Comment by Pecita** [comment]
OsmAnd 3.14 free versionI change my analyze. The "disappear" is
probably wrong. I think now that the good issue of track recording
depend of the fact I tap the "focus" icon on the low right near the
zooming icons + and - .I record a track then tap "Enregistrer le trajet
actuel" then "NON" to the choice "Voulez-vous continuer
l'enregistrement".1) If before I tapped the focus icon it works.2) if I
do not tapped the focus icon the track is not recorded.
Really sorry for my bad explanation.

**Comment by PaulStets** [comment]
Your explanation is ok. Please go to the iOS Settings - OsmAnd - Location - set to Always. This should resolve the issue. Also, please make sure OsmAnd has determined your location (blue marker is displayed on the map) before recording the trip. Let me know if you have any questions.
