### ISSUE TITLE
"Updates available" for world overview map when the newest map is already installed

### ISSUE THREAD

**Issue by valynor** [osmandapp/OsmAnd-iOS#734]
hardware: iphone 8, iOS 13.5.1, latest OsmAnd

Just downloaded today's new "World Overview Map" update. 
After download&install the "updates available" note does **not** go away. 
Closing+restarting the app doesn't help, neither does deleting and re-downloading the "World Overview Map", it's still offered as an available update.

**Comment by valynor** [comment]
There was an update to the World Overview Map today and I hoped that would fix this bug, but it didn't.

**Comment by Jiehong** [comment]
Today, checking for new updates for maps made the worldwide map "update available" disappear.
Yet, the version of osmAnd is the same.

So perhaps the servers serving the updates for July have changed?
