### ISSUE TITLE
Many empty names in zh-Hans.lproj/Localizable.strings

### ISSUE THREAD

**Issue by hanchao** [osmandapp/OsmAnd-iOS#738]
Example
https://github.com/osmandapp/OsmAnd-iOS/blob/master/Resources/zh-Hans.lproj/Localizable.strings#L431

<table style="width:100%">
  <tr>
<th><img src="https://user-images.githubusercontent.com/1942091/85096081-d24cbd00-b225-11ea-92be-f51bcdfd8c37.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/1942091/85096305-8d755600-b226-11ea-9c76-fb3fff7ba6f7.png"  width="300" height="auto"/> </th>
 <th><img src="https://user-images.githubusercontent.com/1942091/85096308-91a17380-b226-11ea-9034-ed8a2aaf520d.png"  width="300" height="auto"/> </th>
  </tr>
</table>

**Comment by Zirochkabila** [comment]
4.3.0.13 **Not reproduced**
