### ISSUE TITLE
Crash when selecting the destination

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-iOS#745]
No matter whether you select the point from the search results list or in the Navigation menu, the app crashes immediately. 
The issue occurs on iPhones: 6S, 4S, 8, XR
with OsmAnd version: 3.14

**Comment by nnngrach** [comment]
Looks like this bug's already fixed. I couldn't find it in an app built from the master branch.

**Comment by nnngrach** [comment]
I still can't reproduce this bug with XCode in master branch version. Here is some logs and video with and without this crash. https://www.dropbox.com/sh/zkpzfhnepoykbso/AAAwQjF9XXpfkmmwFPoWvl2ja?dl=0
