### ISSUE TITLE
 I am trying to setup development environment in xcodefor osmand app.i am getting the following error . cmake: command not found Failed to bake project files 'fat-ios-clang.xcode' (127)

### ISSUE THREAD

**Issue by EoANishant** [osmandapp/OsmAnd-ios#75]
I am trying to setup development environment in xcodefor osmand app. I executed the following commands

> mkdir ~/bin PATH=~/bin:$PATH $ curl
> http://commondatastorage.googleapis.com/git-repo-downloads/repo >
> ~/bin/repo $ chmod a+x ~/bin/repo $ repo init -u
> git://github.com/osmandapp/OsmAnd-manifest.git -m jenkins_ios.xml  $
> repo sync
Pointed to the ios folder which has the below file and then ran

> bash prepare.sh
I am getting an error at the below line : https://github.com/osmandapp/OsmAnd-ios/blob/master/prepare.sh#L32

Error description:

Baking project files for cross-platform target 'fat-ios-clang'
Baking project files 'fat-ios-clang.xcode'
/Users/ss134/build/utils/generate.sh: line 96: cmake: command not found
Failed to bake project files 'fat-ios-clang.xcode' (127)
Failed to generate project for XCode, aborting...
Please help to resolve this. Should i install cmake in terminal and then run the prepare.sh file ?

**Comment by Bimal-Sharma** [comment]
Hi,

are you able to solve this issue?
I am also facing the same issue,please help.
