### ISSUE TITLE
In horizontal mode the Opacity slider overlaps the Quick Action button.

### ISSUE THREAD

**Issue by nnngrach** [osmandapp/OsmAnd-iOS#752]
vertical
https://www.dropbox.com/s/mgsd05t81xm4k5x/Photo%2006.07.2020%2C%2014%2036%2031.png?dl=0

horizontal
https://www.dropbox.com/s/5yqt4gvj9c59735/Photo%2006.07.2020%2C%2014%2036%2037.jpg?dl=0

**Comment by vshcherb** [comment]
Slider should be centered and width should be limited so it doesn't overlap quick action or ruler most of the time.
