### ISSUE TITLE
POI name is missing

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#765]
http://osmand.net/go.html?lat=50.44724&lon=30.50410&z=18, Android, in this case, showing "Полік.."
![photo_2020-07-17 16 11 43](https://user-images.githubusercontent.com/9365308/87789762-388a2700-c848-11ea-96ee-69908b7bc286.jpeg)

**Comment by dmpr0** [comment]
![photo_2020-07-17 16 13 01](https://user-images.githubusercontent.com/9365308/87789897-696a5c00-c848-11ea-92ad-c637262b9354.jpeg)

**Comment by max-klaus** [comment]
Fixed by https://github.com/osmandapp/OsmAnd-core/commit/61a949a77b49c68aca8c859afd9bfe82a4a452d6
