### ISSUE TITLE
Rendering engine fails with a no-internet network connection

### ISSUE THREAD

**Issue by tohaklim** [osmandapp/OsmAnd-iOS#779]
OsmAnd 3.14, Live enabled (on second thought, this could be due to Live, but I forgot to test with it disabled).
I tried to use OsmAnd today, after previously setting some poi filters while on a wifi connection. Having switched to 3G, I noticed the rendering engine crashed as soon as I tried to zoom/pan the map after loading (initial view on app start rendered ok). Online layers (Mapillary) was disabled. 
I then discovered I had maxed out my fair use traffic allowance, meaning the 3G connection did not provide any internet access. 
Restoring internet access removed the bug

**Comment by tohaklim** [comment]
Also just encountered this while connected to a hotspotting phone which lost signal. OsmAnd rendering lost rendering some time later. Entering flight mode (disabling all radios) immediately restored rendering

**Comment by nnngrach** [comment]
**Замеченные глюки со слабой сетью:**

Для имитации плохой связи можно воспользоваться системной утилитой, встроенной в настройки IOS:
Settings -> Developer -> Network Link Conditioner-> 100% Loss

Или просто подключиться к wifi-роутеру с выдернутым из него проводом интернета.

------

После этого замечены следующие баги:

::Map Style Settings::

- [ ] При включении POI  "Wikipedia English" пропадают вообще все включенные оранжевые poi. После включения интернета появляются только "Wikipedia English", а остальные включенные poi всё равно не показываются.


- [ ] Включить/выключить Mapilary. На экране появляется бесконечный индикатор загрузки.  После переключения с wifi на 3G (или на авиарежим) индикатор загрузки пропадает . 

- [ ] Включить "Osm Notes (Online)". Не зависает, но векторная карта пропадает с экрана. Сразу или после зума/скролла. После отключения карта на экран не возвращается. Только после активации авиарежима или появления сети. Предположу, что это и послужило причиной краха рендера, о котором сообщил пользователь.


- [ ] Оверлей включить (должен быть выбран режим OsmandOnlineTiles), а затем выключить.  Зависает. Экран не реагирует на прикосновения. Индикатор загрузки не появляется. 

- [ ] Оверлей включить (должен быть выбран режим OsmandOnlineTiles). Затем переключить с на другую карту.  Появляется бесконечный индикатор загрузки.

- [ ] Оверлей включить (должен быть выбран режим OsmandOnlineTiles). Переключить режим карты день/ночь. Появляется бесконечный индикатор загрузки.


::Maps & Resources::

- [ ] Экран "Карты и ресурсы". Нажать на иконку "Обновить". Появляется бесконечный индикатор загрузки.

- [ ] Экран со списком купленных карт и плагинов.  Сразу после открытия появляется индикатор загрузки. Пропадает сама через 30 секунд, но всё это время экран не реагирует, а воспринимается это сравнительно долго.


- [ ] Установленные карты -> Детали.  На экране "Детали" высота у нижней плашки с кнопками больше, чем на предыдущем экране.

**Comment by nnngrach** [comment]
It seems that the reason is too long timeout. (5 minutes)
https://github.com/osmandapp/OsmAnd-iOS/blob/master/Sources/OAWebClient.mm#L11

**Comment by alex-osm** [comment]
https://github.com/osmandapp/OsmAnd-iOS/commit/18a92980a19da33987a906026ba7e09bb62508c4
