### ISSUE TITLE
xcode build error

### ISSUE THREAD

**Issue by Bimal-Sharma** [osmandapp/OsmAnd-ios#78]
Hi, I tried to build the project but I get this error:
QtExtensions.h:13:10: 'QtGlobal' file not found

I installed Qt 5.7 for OS X.

How can I fix it? Please help!

**Comment by HimanshuDudhat** [comment]
Facing same issue 'QtGlobal' file not found in multiple files.  

Followed Steps provided [here](https://github.com/osmandapp/OsmAnd-core/blob/master/README.md)

**Comment by jethvatilak** [comment]
Stuck in same error. How to solve this?

OSMAndCore framework is missing how to get it?

**Comment by ZaheerAbbasiOS** [comment]
I am also having the same error, "OSMAndCore framework is missing"

**Comment by jethvatilak** [comment]
I have solved this error.

please follow steps provided [here](http://stackoverflow.com/questions/41739114/implement-osmand-in-ios-application/42409484#42409484).

**Comment by vshcherb** [comment]
Thanks!

**Comment by GovindB-WAL** [comment]
> Stuck in same error. How to solve this?
> 
> OSMAndCore framework is missing how to get it?

Tried following above steps I face this error 

`zsh: no matches found: python3*,`

<img width="568" alt="Screenshot 2021-08-10 at 7 03 30 PM" src="https://user-images.githubusercontent.com/81959312/128876233-5ea65ac5-0719-435b-a267-5a91ee66de55.png">
