### ISSUE TITLE
Crash with Holland maps

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-iOS#793]
With only 1 province in Holland, the app functions normally. But when the complete map from Holland is downloaded, the app crashes as soon as the destination point selected for the navigation.
The problem does not occur if remove everything and only install the map for Noord Holland.

**Comment by nnngrach** [comment]
It looks like we already fixed it:
https://github.com/osmandapp/OsmAnd-iOS/issues/745

This crashes in the version from AppStore and does not crash in the version from Master branch.
