### ISSUE TITLE
No navigation on iOS

### ISSUE THREAD

**Issue by mikix** [osmandapp/OsmAnd-ios#80]
(This appears to be an intentional, known lack. But I didn't see an open issue for tracking and status updates. So here one is.)

I'd be very interested in using OsmAnd navigation on iOS, but the app does not seem to support it. This lack also makes the UI a bit confusing, since you can set destinations but it isn't clear what that does.

**Comment by vshcherb** [comment]
Yes, we plan to have it.

**Comment by mikix** [comment]
If there is something I can do to help, I'm willing. Testing, or code work that doesn't involve in-depth codebase knowledge maybe.

**Comment by ADepic** [comment]
It exists now. Issue can be closed
