### ISSUE TITLE
Click on POI Shows POI Type Not the name

### ISSUE THREAD

**Issue by michaelkrnac** [osmandapp/OsmAnd-iOS#800]

**Comment by michaelkrnac** [comment]
In previous Versions a Click on an POI Shows the POI Name. When i Stored the POI as Favorite i got  a nice Name. In the latest  Version the POI Type is Shown instead of the name . If i Save the POI as Favorite the Name of the Favourite ist the POI Type. 
![7ACA1008-942F-42F0-9C11-0585A5192990](https://user-images.githubusercontent.com/3944657/90333911-fdefe780-dfc9-11ea-8bd1-463f94f45e98.jpeg)

**Comment by nnngrach** [comment]
It looks as if it has already been fixed.

v3.14 - AppStore
https://www.dropbox.com/s/ic4h5qbvi5w3dua/photo%2014.09.2020%2C%2014%2032%2051.png?dl=0

current master build
https://www.dropbox.com/s/emx76y52207l0mh/simulator%20screen%20shot%20-%20iphone%208%20plus%20-%202020-09-14%20at%2014.35.50.png?dl=0

**Comment by michaelkrnac** [comment]
Another thing i discovers is that sometimes the shown POI Name is "Wikipedia" because i usually install the Wikipedia articles offline. Do not know if this is related. And maybe also allready fixed.
