### ISSUE TITLE
Custom tile (online or cached) map sources?

### ISSUE THREAD

**Issue by intelfx** [osmandapp/OsmAnd-ios#81]
In the Android counterpart app, there is support for providing custom data sources for raster (tiled) maps, as well as providing pre-cached tilesets for such maps. However, in the iOS app only certain predefined tile map sources are apparently available.

Is this feature not (yet?) supported in the iOS app, or is it supported but hidden?

**Comment by vshcherb** [comment]
This feature is supported by core engine though on IOS it is not clear if you have access to the file system yourself. If you don't than unfortunately it is limited to what we have in predefined list.

**Comment by intelfx** [comment]
Well, I do (my device is jailbroken). Moreover, there is the per-app user data location accessible via iTunes (w/o jailbreak). Where do I need to make changes?

**Comment by vshcherb** [comment]
For now we use limited set https://github.com/osmandapp/OsmAnd-resources/blob/master/misc/default.online_tile_sources.xml though we could extend it to https://github.com/osmandapp/OsmAnd-misc/blob/master/site/tile_sources.xml.

**Comment by fatuuse** [comment]
I would love to have this future!

**Comment by edrex** [comment]
@intelfx do you mean the Android app supports this by editing XML or in the GUI? If in the GUI, I think not anymore.

**Comment by pqhf5kd** [comment]
The lack of Trail Blazes or [symbols](https://wiki.openstreetmap.org/wiki/Key:symbol) on any of the cached map sources is, IMO, the biggest issue with OsmAnd for hikers

**Comment by PaulStets** [comment]
All of this functionality was added. The latest commits introduced the ability to edit online tile sources.
Related code is here https://github.com/osmandapp/OsmAnd-ios/pull/598
