### ISSUE TITLE
Sandbox: In-app purchases dialogs

### ISSUE THREAD

**Issue by Baikan4ik** [osmandapp/OsmAnd-iOS#817]
After clean install and first start appear this window for 10-12 times. Only one possible variant - click OK while all alerts dismissed. No multitask window, no hide app, no power off. This alert doesn't allow do anything

![image](https://user-images.githubusercontent.com/64836999/91274999-3771e100-e788-11ea-918e-fbce7474348a.png)

**Comment by Baikan4ik** [comment]
On every action on map, ex. Get info about object, alert shown for ~25 times. Or when open settings for download offline maps

**Comment by Baikan4ik** [comment]
[https://share.icloud.com/photos/0ClasIHyKtLBxca7jikbDR8Bg](https://share.icloud.com/photos/0ClasIHyKtLBxca7jikbDR8Bg)

**Comment by Baikan4ik** [comment]
https://share.icloud.com/photos/0ClasIHyKtLBxca7jikbDR8Bg

**Comment by Baikan4ik** [comment]
Подобное поведение, если при первоначальном запуске приложения ввести аккаунт, используемый в приложении. Если отвергнуть это, то иногда выскакивает окно с предложением ввести пароль текущего акка

**Comment by vshcherb** [comment]
Выглядит очень странным что тут Sandbox, похоже это testflight

**Comment by dmpr0** [comment]
Not reproduced.
