### ISSUE TITLE
Route color: customize or adjust for night map

### ISSUE THREAD

**Issue by Baikan4ik** [osmandapp/OsmAnd-iOS#818]
В режиме приложения "Ночь" нитка маршрута желтого цвета и практически сливается с дорожной сеткой. Было бы здорово выбирать цвет линий подобно выбору цвета профиля
![image](https://user-images.githubusercontent.com/64836999/91289096-86287680-e79a-11ea-835f-d2d22e572170.png)

**Comment by dmpr0** [comment]
Done
