### ISSUE TITLE
OSM live on iOs

### ISSUE THREAD

**Issue by dan980** [osmandapp/OsmAnd-ios#82]
Having OSM live on iOs would be really nice. Are you planning about adding it in the future?

**Comment by vshcherb** [comment]
Yes, we are working to get IOS same functional as Android. Soon it will be a release to catch up with all search possibilities, unfortunately, OSM Live won't be implemented this release.

**Comment by ZaheerAbbasiOS** [comment]
Hi,

I am unable to install the app on Xcode 8.0 it is giving error that some of libraries are missing, but I could not found those, Please help me out. 
Thanks

**Comment by jethvatilak** [comment]
@ZaheerAbbasiOS  please see [my answer](http://stackoverflow.com/questions/41739114/implement-osmand-in-ios-application/42409484#42409484) to solve this error.

**Comment by jd0048** [comment]
@jethvatilak i had try above steps still it will giving me errors, can you please help me for missing lib

Thank you

**Comment by PaulStets** [comment]
OsmAnd Live was added in 2.62.
