### ISSUE TITLE
GPX color is not selected for current recording track

### ISSUE THREAD

**Issue by Baikan4ik** [osmandapp/OsmAnd-iOS#820]
В настройках самого трека можно выбрать его цвет. Но этот цвет исключительно для отображения на карте. Если же включить навигацию по треку, то установленным цветом выделяется уже пройденный участок, а предстоящий непонятным (возможно, наложение выбранного цвета и используемого по-умолчанию в приложении для навигации). Нелогично. 
На фото в настройках трека выбран красный цвет и им закрашен пройденный путь уже 

![image](https://user-images.githubusercontent.com/64836999/91473767-fcfc6700-e8a1-11ea-837f-13bb6525b651.png)

**Comment by PaulStets** [comment]
We will introduce many options for route line customization in the next release.
