### ISSUE TITLE
Freezing on opening My places

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#826]
Open menu - My places - freezing occurs. (See log on Chat)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x285ba9bd0 UILabel:0x11e738700'Import favorite'.height >= 22   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-08-21 14:42:29.704557+0300 OsmAnd Maps[16595:5940485] [LayoutConstraints] Unable to simultaneously satisfy constraints.
 Probably at least one of the constraints in the following list is one you don't want. 
 Try this: 
  (1) look at each constraint and try to figure out which you don't expect; 
  (2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x285bc80f0 UILabel:0x11e73b970'Export favorite'.height >= 22   (active)>",
    "<NSLayoutConstraint:0x285bc8280 V:[UILabel:0x11e73b970'Export favorite']-(13)-|   (active, names: '|':UITableViewCellContentView:0x11e73b430 )>",
    "<NSLayoutConstraint:0x285bc83c0 V:|-(13)-[UILabel:0x11e73b970'Export favorite']   (active, names: '|':UITableViewCellContentView:0x11e73b430 )>",
    "<NSLayoutConstraint:0x285bc8960 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x11e73b430.height == 44   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x285bc80f0 UILabel:0x11e73b970'Export favorite'.height >= 22   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by nnngrach** [comment]
https://github.com/osmandapp/OsmAnd-iOS/pull/859
