### ISSUE TITLE
Build failed during executing ./prebuild-core.sh 

### ISSUE THREAD

**Issue by HimanshuDudhat** [osmandapp/OsmAnd-ios#83]
Getting issue during build OSMAnd-iOS repo by following step provided by @vshcherb under issue [#2848](https://github.com/osmandapp/Osmand/issues/2848)

Can you please let to sort out building issue?

[Here](http://pastebin.com/HXGSJ7VP) is log from terminal while executing ./prebuils-core.sh

**Comment by crimean** [comment]
@HimanshuDudhat prebuils-core.sh is not required step for now. Try to open OsmAnd workspace in xcode and build.

**Comment by HimanshuDudhat** [comment]
@crimean I trieded to open OsmAnd workspace in xcode and build getting error related to Undefined symbols for architecture armv7. [Here is a full error log.](http://pastebin.com/sv4wmM0Q)

**Comment by vshcherb** [comment]
@HimanshuDudhat I guess you were already directed to professional help. We usually don't provide help on building infrastructure, though it should be simple cause all code is on github.
