### ISSUE TITLE
!! editing OSM POIs with OsmAnd moved them to incorrect location

### ISSUE THREAD

**Issue by stragu** [osmandapp/OsmAnd-iOS#833]
I changed opening hours of a handful of POIs in OsmAnd 3.14, and uploaded all the changes in one go with My Places -> OSM edits.

The changeset moved the POIs to different locations: https://www.openstreetmap.org/changeset/90741096

The POIs were mostly moved in one direction, towards the east, between 20 and 40 m, but some were moved westward instead. I am not sure what the logic is there.

That is a very serious issue as it deteriorates the quality of the data without the contributor's knowledge.

To be extra clear: I did not use the "change object position" feature (I didn't even know it existed before today).

**Comment by stragu** [comment]
I already fixed the incorrect locations, so here is an illustration of part of what was moved (annotating the current OSM tiles that are still representative of the incorrect locations). The blue arrows show where the POIs should have stayed.

![image](https://user-images.githubusercontent.com/1747497/92986177-42ed3800-f4fc-11ea-9d7c-e0494ca873fc.png)

**Comment by vshcherb** [comment]
Looks like rounding error we need to double check what's going with the code. Thanks for feedback

**Comment by stragu** [comment]
Ah that makes sense, I can see it now:

![image](https://user-images.githubusercontent.com/1747497/93142616-baec7580-f729-11ea-9514-d73d02324d69.png)

For example, on the x axis, it looks like it rounded to the closest 0.001

**Comment by stragu** [comment]
Looks like it is happening to everyone using this version, I can find the issue in changesets dating back to May this year: 
https://osmcha.org/changesets/90754256?filters=%7B%22editor%22%3A%5B%7B%22label%22%3A%22osmand%20maps%203.14%22%2C%22value%22%3A%22osmand%20maps%203.14%22%7D%5D%7D

OSMCha shows me close to 1000 changesets using this version of OsmAnd.

Not sure if previous versions were also affected by the same issue.

**Comment by stragu** [comment]
Actually, it looks like it rounds the coordinates to 6 significant figures, not a specific number of decimals. See for example this history: https://www.openstreetmap.org/node/575564098/history

* x axis: 153.0071854 -> **153.007**0000
* y axis:  -27.4805811 ->  -**27.4806**000

Older versions are also affected.

**Comment by stragu** [comment]
Looking at OSMCha, at least the following versions of OSMAnd are affected:

* 3.11
* 3.12
* 3.13
* 3.14

An example in version 3.13:

![image](https://user-images.githubusercontent.com/1747497/93168478-4b48ab80-f766-11ea-9e8c-ef5dff9335eb.png)

* node history: https://www.openstreetmap.org/node/4422263991/history
* changeset: https://www.openstreetmap.org/changeset/85781647

**Comment by stragu** [comment]
Thanks for releasing that quickly in 3.80.
I'm surprised the fix didn't make it into the release notes. Don't you think there should be some communication about this issue to get people to update as soon as possible?
Or maybe in the blog post, I you write one for the 3.80 release?

**Comment by Firefishy** [comment]
I'm part of the OSM ops team, should we be blocking any particular versions from accessing the API? What user-agent or other headers could we use to match the broken versions?

**Comment by vshcherb** [comment]
New IOS version with new User-Agent and fix is already out. The problem previous versions didn't have User-Agent specified, so this makes it tricky. 
Since OsmAnd 3.80, 3.81,.... both problems are fixed
