### ISSUE TITLE
App crash when trying to make a route

### ISSUE THREAD

**Issue by qqvm** [osmandapp/OsmAnd-iOS#838]
I am getting an app crash every time I make a route (on any profile). I have 'World overview" and "Ukraine" maps installed. Tried to do the same after reinstallation and default settings. Still crashes. No specific errors are shown, app just disappears.
Here is my logs from device
[OsmAnd Maps  14.09.2020, 10-39.txt](https://github.com/osmandapp/OsmAnd-iOS/files/5218136/OsmAnd.Maps.14.09.2020.10-39.txt)
[OsmAnd Maps  14.09.2020, 10-41.txt](https://github.com/osmandapp/OsmAnd-iOS/files/5218137/OsmAnd.Maps.14.09.2020.10-41.txt)

**Comment by max-klaus** [comment]
Should be fixed in the next release
