### ISSUE TITLE
report version in user agent http header on OSM-API calls

### ISSUE THREAD

**Issue by tyrasd** [osmandapp/OsmAnd-iOS#845]
From https://operations.osmfoundation.org/policies/api/ (highlighting below by me):

> Technical Usage Requirements: Valid User-Agent identifying application **and version**. […]

Currently, as far as I can see in the code ~~and from what I read in https://www.openstreetmap.org/user/stragu/diary/394199#comment48153~~, the app does only report its name, but not its version number.

//edit: the relevant code should be here, if I'm not mistaken: https://github.com/osmandapp/OsmAnd-iOS/blob/r3.14/Sources/OsmEdit/OAOpenStreetMapRemoteUtil.mm#L79

**Comment by vshcherb** [comment]
Agree
