### ISSUE TITLE
Version 3.80 tags changesets as version 3.15; Help menu uses "3.15" too

### ISSUE THREAD

**Issue by stragu** [osmandapp/OsmAnd-iOS#861]
I just updated to version 3.80. It looks like there's a leftover from before changing the version number to 3.80, as changesets are tagged with `created_by=OsmAnd Maps 3.15`

See for example this changeset: https://www.openstreetmap.org/changeset/91144886

The Help menu also show the version number 3.15 under "About".

**Comment by vshcherb** [comment]
Should be fixed with todays' update

**Comment by dmpr0** [comment]
Fixed https://www.openstreetmap.org/changeset/91350178
