### ISSUE TITLE
Can I use .osm render functions for our project ?

### ISSUE THREAD

**Issue by xcervi19** [osmandapp/OsmAnd-ios#88]
I'll deploy mobile app as school project and I would like to render osm soubor which has been downloaded. 

I'll can implement my own .osm processing which make picture from .osm but it is overkill and there is no API for osm render or free API for offline maps (I can't use Mapbox).

My idea is if I can use your functions from asmandapp.

Where can I found some file for osm prosessing and is it possible separately use it in my app (I hope that osm render is some class)

note: It is my fist IOS app dev

**Comment by vshcherb** [comment]
Yes feel free to use, I think it is perfectly fine and it doesn't violates GPL license. The 1 issue that you won't have permission to publish to the iOS App Store

**Comment by xcervi19** [comment]
thank you for your answer.
is it possible to tell me where is localted the code for osm render ?
