### ISSUE TITLE
Build failed when running prepare.sh

### ISSUE THREAD

**Issue by khanyasirforu** [osmandapp/OsmAnd-iOS#883]
I followed following steps to start with OSMAND iOS .

1. Setup [MacPorts](https://www.macports.org/install.php) in Mac Terminal.
2. Fire below commands in terminal

         - sudo port install bash
         - sudo port install bzip2
         - sudo port install curl
         - sudo port install git
         - sudo port install ImageMagick +rsvg
         - sudo port install librsvg
         - sudo port install p7zip
         - sudo port install python3*
         - sudo port install wget

3. Install [Google Repo](http://source.android.com/source/downloading.html#installing-repo)
4. mkdir OsmAnd && cd OsmAnd
5. repo init -u https://github.com/osmandapp/OsmAnd-manifest -m readonly.xml
6. repo sync
7. ./ios/prepare.sh(its failing here)

```
Using cross-platform target settings from toolchain file 'targets/fat-ios-clang.cmake'
CMAKE_TARGET_OS = ios
CMAKE_TARGET_CPU_ARCH = fat
CMAKE_TARGET_CPU_ARCH_FAMILY = fat
CMAKE_SHARED_LIBS_ALLOWED_ON_TARGET = FALSE
CMAKE_STATIC_LIBS_ALLOWED_ON_TARGET = TRUE
CMAKE_COMPILER_FAMILY = clang
OSMAND_OUTPUT_ROOT = /Users/ceinfio/Documents/osmand/osm/build/../binaries/ios.clang$(EFFECTIVE_PLATFORM_NAME)
-- The ASM compiler identification is Clang
CMake Error at /usr/local/Cellar/cmake/3.18.3/share/cmake/Modules/CMakeFindBinUtils.cmake:139 (message):
  message called with incorrect number of arguments
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.3/share/cmake/Modules/CMakeDetermineASMCompiler.cmake:193 (include)
  CMakeLists.txt:115 (enable_language)


CMAKE_INSTALL_NAME_TOOL
CMake Error at /usr/local/Cellar/cmake/3.18.3/share/cmake/Modules/CMakeFindBinUtils.cmake:144 (message):
  Could not find install_name_tool, please check your installation.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.3/share/cmake/Modules/CMakeDetermineASMCompiler.cmake:193 (include)
  CMakeLists.txt:115 (enable_language)


-- Configuring incomplete, errors occurred!
See also "/Users/ceinfio/Documents/osmand/osm/baked/fat-ios-clang.xcode/CMakeFiles/CMakeOutput.log".
See also "/Users/ceinfio/Documents/osmand/osm/baked/fat-ios-clang.xcode/CMakeFiles/CMakeError.log".
Failed to bake project files 'fat-ios-clang.xcode' (1)
Failed to generate project for XCode, aborting...
```

NOTE: 

```
$which install_name_tool
returns /usr/bin/install_name_tool
```

8. ./ios/prebuild-core.sh(This is planned step, not running it because step 7 is failing.)

**Comment by Fossil01** [comment]
Uninstalling Cmake and reinstalling it from this document worked for me: https://docs.google.com/document/d/1OAbqgmLJRFiQb9tt8da6zLlKqq8ozziW8GrNiv2nWNk/edit

**Comment by vshcherb** [comment]
The latest documentation is here https://docs.osmand.net/en/main@latest/development/build-osmand/how-to-compile-the-ios-version
