### ISSUE TITLE
Question: Why aren't any new fields for amenity=fuel appearing on the place editor?

### ISSUE THREAD

**Issue by TheAdventurer64** [osmandapp/OsmAnd-iOS#888]
# ToDo 
- [ ] Add new tags to autocomplete

------
If you go onto the iOS version of OSMAnd and try to edit a gas station, you will be given the normal options for editing a place, and nothing else. However on the website, it is shown that the iOS version at one point supported new fields for `amenity=fuel`. Why is this?

**Comment by dmpr0** [comment]
# Review 
- [ ]  Different results.
![Group 139](https://user-images.githubusercontent.com/9365308/107631612-f2763400-6c6d-11eb-8e3f-a241f6978ee6.png)

**Comment by vshcherb** [comment]
I think they are the same, actually iOS might be excluding duplicates
