### ISSUE TITLE
[Feature request] select color and symbol for favorites' icons

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-iOS#899]
Waypoint:
- [x] Load/save new Waypoint fields to file
- [x] Update Waypoint view screen
- [x] Add Waypoint editing screen
- [x] Update Waypoints list view  in Track view screen

Parking:
- [x] Save/load Parking location data to  favorites.gpx

------------------------------
In the Android OsmAnd app, there is an option available to change the Favorites' appearance. It would be convenient to set the icon color and symbols for different favorites and groups of favorites to distinguish them directly on the map.

- [x] Scroll cells problems (nngrach)

As in Android 
- [x] Select shape, color
- [x] Address field
- [x] Select icon with categories (external file)
- [x] Update icon with shape / color / icon
- [x] Replace
- [x] Select group section
- [x] Select group screen
- [x] Add new group screen
- [x] Favorite "Context menu"
- [x] Delete fields for edit name, group, color, description.
- [x] Show description

Next steps:
- [x] Select/save/load color for groups
- [x] Group for "Personal" points (Home / Work), 
- [x] Test import / export
- [x] Favorites screen
- [x] Layer

Linked tasks:

- [x] Save/load elevation and timestamp to favorites.gpx
- [x] Show nearest Wikidata/Mapilary images on Favorite view screen
- [x] Show nearest Wikidata/Mapilary images on Waypoint view screen

------------------------------
# Review 
- [x] Show "Dismiss" alert if user-made changes and swipe screen down.
- [x] Change screen title from "Add favorite" to the user entered name.
- [x] Header text color = #978FA3
- [x] Navbar should change size after scrolling (only icons should be shown).

#### Horizontal icons toggle:
- [x] Buttons corner radius  9px
- [x] Cropped by left/right padding, should scroll up to screen edges.
- - - - - -

#### Icon selector
- [x]  Icons: 1:1 icons size, don't upscale it.

#### Shape selector
- [x] Don't put icon shape into a circle. 
- [x] Use proper contour for selection: `bg_point_circle_contour, bg_point_octagon_contour, bg_point_square_contour.`

**Comment by dmpr0** [comment]
# Review 
- [ ]  Show "Dismiss" alert if user-made changes and swipe screen down.
- [ ] Change screen title from "Add favorite" to the user entered name.
