### ISSUE TITLE
3.8 Default profile is switch back to "Overview"

### ISSUE THREAD

**Issue by dmpr0** [osmandapp/OsmAnd-iOS#900]
Change "Default profile" to any other: "Car" or "Bicycle" for example. Start the navigation – closing the app while navigation. Next time you launch OsmAnd it will change the default profile to "Overview". 
It doesn't reproduce if you close navigation before closing OsmAnd.

**Comment by PaulStets** [comment]
Could not reproduce the change to Overview profile, however, found 2 inconsistencies with Android and fixed them.

**Comment by dmpr0** [comment]
I can still reproduce in the current release and test flight builds.

**Comment by brncsk** [comment]
Reproducible as well with yesterday’s testflight build.
