### ISSUE TITLE
Changing changeset comment makes it impossible to submit changeset

### ISSUE THREAD

**Issue by habi** [osmandapp/OsmAnd-iOS#906]
I have no clue on the underlying cause, but on a relatively small iPhone SE (Original) with iOS 14.0 i cannot submit a changeset with OsmAnd (Version 3.81) when I want to change the changeset comment.

When I edit the changeset comment, the 'Done' button vanishes behind the keyboard, essentially rendering OsmAnd unusable, because it then also stops to react on other input (i.e. I cannot exit this menu).
See the attached short screencast 1.

![ezgif-6-2cba779a4250](https://user-images.githubusercontent.com/1651235/96104872-a2fb4380-0ed9-11eb-8b58-3e44371f1422.gif)

When I don't edit the changeset message, then I can submit the [changeset](https://www.openstreetmap.org/changeset/92460534) without troubles, as seen in screencast 2.

![ezgif-6-f592ce94088b](https://user-images.githubusercontent.com/1651235/96104886-a7bff780-0ed9-11eb-95b7-7a008c4ae4f6.gif)

**Comment by PaulStets** [comment]
@habi Hi, the issue in your video seems like an iOS bug. I have added an extra precaution to prevent this from happening, however, you should try rebooting your phone. This may fix the issue for you.

**Comment by habi** [comment]
I'm rebooting (i.e. turning it off) every evening when I go to bed, this does *not* fix the issue.
Since I initially submitted this issue I got myself a new phone and am now using OsmAnd (3.8.1) on an iPhone 12 mini with iOS 14.2.1

I'm now able to change the changeset comment, but the 'Done' button still vanishes.
I'm still unable to upload a changeset, OsmAnd is unresponsive from the moment on I press enter and crashes consistently after a while.

It's just in total much quicker than on my old iPhone SE where I ultimately always killed OsmAnd before it crashed...
Here's a short screencast again: https://user-images.githubusercontent.com/1651235/105608729-07fde980-5da5-11eb-98ba-b8dfdd00989f.mov

After I input 'Ghhcjkb' and press Enter there's no input anymore from me.

**Comment by habi** [comment]
And just for kicks I rebooted the phone now.
The issue is still exactly the same, OsmAnd consistently crashes after entring a changeset comment and pressing Enter.

**Comment by habi** [comment]
Hey @PaulStets: Does reopening and closing the issue mean that this won't be fixed? It essentially makes OsmAnd unusable for me, since I'd *really* like to change the changeset comment from the default.

And again; I'm very happy to help to find the root cause of this issue with anything I might be able to provide, just let me know.

**Comment by PaulStets** [comment]
Hi @habi, sorry, I closed it again by accident. I have received new details on how to reproduce this issue and will fix probably fix it today. Thank you for all the information you provided.

**Comment by habi** [comment]
> Thank you for all the information you provided.

Very welcome, looking forward for a fix!

**Comment by PaulStets** [comment]
@habi The issue should be fixed now. You will be able to test it in the Testflight on Wednesday or Thursday and it will be available with the next public release.

**Comment by habi** [comment]
Awesome, thanks for the fix!

**Comment by habi** [comment]
Works as expected now: https://www.openstreetmap.org/changeset/98297513

**Comment by PaulStets** [comment]
Glad to hear it. The App Store release with this fix will be out shortly.
