### ISSUE TITLE
Trip recording plugin  settings are not reflected correctly.

### ISSUE THREAD

**Issue by ffff-23** [osmandapp/OsmAnd-iOS#913]
In the 'Trip recording' plugin, 'General recording interval' setting, If select '1 sec', it is saved in '2 sec', The same goes for the other items.
Selecting 'Always ask' will save it correctly as 'Always ask'.
It will crash if select '5 min'.

Operating environment
- iOS 14.1
- OS Language - Reproduction in both Japanese and English
- App Language - Reproduction in both Japanese and English
- OsmAnd 3.81
- Plugin Only 'Trip recording'

Reproduction procedure
1. Start App
2. Open sidebar
3. Sidebar - Settings
4. APP PROFILES - Overview
5. Overview - PLUGINS - Trip recording
6. LOGGING ACCURAY - General logging interval
7. Select 5 min
8. Crash

**Comment by dmpr0** [comment]
Review:
- [ ]  It seems we loose dialog that ask about minimum interval at the start of "Trip recording"
