### ISSUE TITLE
DVR focus

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-iOS#914]
The focus on the “green” mode works fine during the day, but at night the autofocus keeps trying to find focus, there needs to be a focus lock mode or option in each focal mode. If there is one I can’t find it. A focus mode that shows a lock icon on the screen is fuzzy for some reason so I don’t use it. The blue mode is fuzzy too.

**Comment by dmpr0** [comment]
OsmAnd DVR is no longer supported.
