### ISSUE TITLE
[Feature request] DVR video reverse button

### ISSUE THREAD

**Issue by katerynakocherhina** [osmandapp/OsmAnd-iOS#915]
When looking through the footage you can’t reverse direction, only play forward, fast forward, or slow down. The reverse icon would be useful, so you can easily scrub backward a few seconds. Using the scrub bar is hard to only back up a few seconds, often a tiny twitch on that can jump back more than a minute.

**Comment by dmpr0** [comment]
OsmAnd DVR is no longer supported.
