### ISSUE TITLE
How to successfully Build/Run the project after cloning the repo. ?

### ISSUE THREAD

**Issue by Mohamed-Ramadan** [osmandapp/OsmAnd-ios#92]
I cloned the repository, and installing the pods, 
but when trying to build it, a lot of missing libraries errors appears !

it seems that there is dependencies needs to be installs before building the project, and i'm do not know who to install them !
 
so could you please guide me to successfully Build/Run the project ?

**Comment by jd0048** [comment]
@Mohamed-Ramadan Have you find any success?, i am facing issue after cloning repo it will giving me error for `'OsmAndCore/QtExtensions.h' file not found`

**Comment by berabhavin** [comment]
I am facing a same problem after cloning the repo and also download the source code direct and try to build the project but facing a same error.

**Comment by jd0048** [comment]
@crimean @alexey-pelykh From where i can find **"OsmAndCore"** framework to import in iOS project ?

**Comment by alpesh12** [comment]
@crimean  @alexey-pelykh i am facing issue for configuration of project, i am getting error for "QtGlobal" framework

`#include <QtGlobal>`
'QtGlobal' file not found

Can you please guide me how can we fix this issue?
Thank you

**Comment by alexey-pelykh** [comment]
Start with `repo` tool + https://github.com/osmandapp/OsmAnd-manifest/blob/master/jenkins_ios.xml

**Comment by jd0048** [comment]
i had enter command in terminal 
`repo tool + https://github.com/osmandapp/OsmAnd-manifest/blob/master/jenkins_ios.xml`

It will giving me error "repo: 'tool' is not a repo command.  See 'repo help'."

**Comment by alexey-pelykh** [comment]
Well, definitely I'm not going to explain how to use google and terminal, sorry.

**Comment by jd0048** [comment]
Right,
I had clone from below step 
1)repo init -u https://github.com/osmandapp/OsmAnd-manifest -m readonly.xml
2)./ios/prepare.sh
3)./ios/prebuild-core.sh

it will clone build,core,ios and resources folder now when i try to run project it will giving me errors for missing framework.
Currently i am stuck at error 
> 'QtGlobal' file not found from QtExtension.h file #include <QtGlobal>
Can you please guide me how can i fix this error

It will be really helpful if you guide me solve OsmAnd iOS project error
Thank you.

**Comment by guoliang1206** [comment]
@jd0048  do you have find a solution about QtGlobal file not found issue?

**Comment by guoliang1206** [comment]
@alpesh12  do you have find this file? <QtGlobal>

**Comment by jd0048** [comment]
@guoliang1206 No
 i am not able to configure project, so i am switch from OsmAnd to HERE SDK for map related functionality

**Comment by jd0048** [comment]
@vshcherb Why it's closed, we are still facing this issue

**Comment by Mohamed-Ramadan** [comment]
I wonder why it's not easy to configure this project ?!!!
there is no any support from project contributors to make this job done!

**Comment by vshcherb** [comment]
So far instructions looks easy, there were some people who did it successfully.
```
1. Install XCode + command-line tools
2. Install cmake
3. Install brew (https://brew.sh)
   Run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
4. Install imagemagick with librsvg
   Run: brew reinstall imagemagick --with-librsvg
5. mkdir OsmAnd && cd OsmAnd
6. Clone manually or via google repo tool: https://github.com/osmandapp/OsmAnd-manifest/blob/master/jenkins_ios.xml
7. Run ./ios/prepare.sh
8. #include <stdlib.h> in gif_hash.c
9. Open osmand.xcworkspace in XCode and build
```
If this instruction doesn't work, then something needs to be fixed though until it doesn't affect people who are working on the project, I believe it will stay as it is.

The bug is closed cause it is not a product issue.

**Comment by crimean** [comment]
Just modified the jenkins_ios.xml. The android and core-legacy projects are needed for OsmAnd-ios now.
