### ISSUE TITLE
Add "Location position on screen" for "Quick Actions"

### ISSUE THREAD

**Issue by EugeneZmeuk** [osmandapp/OsmAnd-iOS#921]
During riding by bicycle (motorbike) it would be useful to have an action in Quick Actions tool to change Display position ("Location position on screen" on/off) for looking around terrain.

## ToDo 

<table style="width:100%">
  <tr>
    <td><img src="https://github.com/user-attachments/assets/a144a56e-e232-4f28-bb0c-52baca85b8aa"  width="300" height="auto"/> </td>
  </tr>
</table>   

- [x] Add new quick action 
- - [x] Verb – `Change`
- - [x] Name – `Location position on screen`
- - [x] Icon = selected parameter
- - [x] Group – Settings

**Comment by dmpr0** [comment]
Android https://github.com/osmandapp/OsmAnd/issues/18821

**Comment by shurasmiling** [comment]
https://osmand.net/docs/user/widgets/quick-action#settings
