### ISSUE TITLE
OSMAnd crashes while route calculating

### ISSUE THREAD

**Issue by 3mg4** [osmandapp/OsmAnd-ios#93]
iPhone 6 64GB
iOS 10.3.3
OSMAnd for iPhone Version 2.0.1

When trying to calculate a route app crashes.
Example route is Vienna to Salzburg (AUSTRIA), it is longer than 250km, there is no way to enter the route with Waypoints (like Start-Waypoint 1-Waypoint 2-Finish) I can enter Start and Finish but no waypoint in between.

[Cheap workaround: Route from Start to Waypoint 1 than choose Waypoint 2 as destination from current position.]

**Comment by vshcherb** [comment]
Waypoints is current work in progress.

**Comment by michaelkrnac** [comment]
On my iPhone 6 with OsmAnd 2.31 no route calculation works with routes > 200km.
Even without waypoints.
It takes infinity time or the app crashes.

If you could tell me how to provide a debug report please let me know.

**Comment by max-klaus** [comment]
Should be fixed now.
