### ISSUE TITLE
Switching between 'car' and 'public transport' profile works incorrectly

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd-iOS#947]
Switching between 'car' and 'public transport' profile works incorrectly

1) Open Navigation Menu
2) Choose the from/to position with the car profile
3) Start navigation  (simulation)
4) While the navigation (simulation) switch to the 'public transport' profile
5) Click "Show on the map" 
The path will disappear. But the marker will follow the invisible path. And do not recalculate it

change navigation to 'car' profile. The path will appear and OsmAnd will ask press Start

<img src="https://user-images.githubusercontent.com/72389175/100750736-2243c880-33ef-11eb-936d-1a92275524b1.png"  height="400"/>

<img src="https://user-images.githubusercontent.com/72389175/100750736-2243c880-33ef-11eb-936d-1a92275524b1.png"  height="400"/>

<img src="https://user-images.githubusercontent.com/72389175/100750820-3d163d00-33ef-11eb-80d3-2db803a754ab.png"  height="400"/>

**Comment by vshcherb** [comment]
Works same as in Android - simulation continues by old route
