### ISSUE TITLE
Cafe description shows "Internet access" as main category

### ISSUE THREAD

**Issue by stragu** [osmandapp/OsmAnd-iOS#958]
Looking at a cafe POI description, the main category used is "Internet access".

See for example this node: https://www.openstreetmap.org/node/2394634829

<img src="https://user-images.githubusercontent.com/1747497/101326729-6df7e580-38b9-11eb-8526-ef23cc1abbd0.png"  height="500" alt="Screenshot of short description of POI is OsmAnd"/>

Another example: https://www.openstreetmap.org/node/5140688128

But other cafes show the category Cafe instead, as expected, even though the same `internet_access` key is used, for example:

- https://www.openstreetmap.org/node/2353039724
- https://www.openstreetmap.org/node/5140688131

Version: 3.81

**Comment by vshcherb** [comment]
Also we need to synchronize - 
- OsmAnd-java/src/main/java/net/osmand/search/core/SearchCoreFactory.java
- OsmAnd-java/src/main/java/net/osmand/search/SearchUICore.java 
- OsmAnd-java/src/main/java/net/osmand/data/Building.java


(https://github.com/osmandapp/OsmAnd/commit/9251a6bb4af017065cb7d2861baeae1df7f7b130#diff-1d7b76c4d00726b7c32aba6323f9f08114e3b11fd9c01ffab11ba8bbc7147a2e)

(https://github.com/osmandapp/OsmAnd/commit/d416ef0a6a24d25ac35f80f508d4c877c267a1f9#diff-c2d19bfbdde2a943457d8347259696bb5f07b2cbd99ea98cfaf484f7c977c363)
(https://github.com/osmandapp/OsmAnd/commit/e74c72af73f6b6ed14d7f0ad53a9e790bbd594e7#diff-c2d19bfbdde2a943457d8347259696bb5f07b2cbd99ea98cfaf484f7c977c363)
