### ISSUE TITLE
OsmAnd Core Search

### ISSUE THREAD

**Issue by vshcherb** [osmandapp/OsmAnd-ios#99]
Магнитогорск - "Cуворова, 109" - doesn't search correctly. Though Java works good

**Comment by dmpr0** [comment]
"Дмитриевская 45", in Kiev can't find too
![img_0120](https://user-images.githubusercontent.com/9365308/43573025-7ab30378-9649-11e8-9778-8c9ed733d567.PNG)
![img_0121](https://user-images.githubusercontent.com/9365308/43573026-7ad013a0-9649-11e8-9c33-290ca568251f.PNG)
![img_0122](https://user-images.githubusercontent.com/9365308/43573027-7aecbe74-9649-11e8-80ee-8934c33db914.PNG)


.
