### ISSUE TITLE
Rendering issue with the OSMand map in the Montreall area

### ISSUE THREAD

**Issue by AnastasiaTiutina** [osmandapp/OsmAnd-iOS#992]
iOS 14.3 with OSMand updated
Download the NorthAmeria/Canada/Quebec map on devices. Use the mapnik rendering which shows areas tagged with landuse=residential in a light gray color.

So if you look the the Montreal area, for the Montreal island, the Ile Perrot island, the Ile Bizard island and the much smaller Bigras Island (north-west of the city), in all those cases on those island no residential area (light gray) is displayed. However every where else I look for the entire map I see no issue. Laval Island is fine. so are the other suburbs. There should be lots of gray (residential) on the problematic island. If you look the the openstreetmap.org <http://openstreetmap.org/> site you see that. I had a look at the OSM data in ID and see nothing special. Et really seems to be something with the rendering engine that OSMand uses to produce the mapnik tiles, and only for that specific area.

On the following iPhone screenshot you see Laval (upper part) is fine while the Bizard, Bigras, Verte and the portion of the Montreal island displayed, are all missing the gray residential areas.
Interestingly for that same area if I switch to Offroad rendering in your app the residential appears correctly everywhere, except the Bigras and Verte islands which remain not rendered properly.
Same area on the web https://www.openstreetmap.org/#map=15/45.5168/-73.8554 <https://www.openstreetmap.org/#map=15/45.5168/-73.8554>

Something wrong with the way your servers process the landuse=residential tags and render them, and that issue affects many of the tile sets - I mostly use mapnik but the others seems also affected.

![DDB09B7B-7F29-4036-BF71-A6B566067FF9 (2)](https://user-images.githubusercontent.com/72389175/102656215-2f491180-417c-11eb-97d5-fecc97a8a25b.png)

**Comment by xmd5a2** [comment]
To fix this issue we need to change rendering order at line [3273](https://github.com/osmandapp/OsmAnd-resources/blob/master/rendering_styles/default.render.xml#L3273) 
```
<case tag="landuse" value="residential" order="4"/>
```
to `6` (`landuse=residential` on top of `natural=water` and land). But [another issue](https://github.com/osmandapp/Osmand/issues/8743) requires `order="4"` (`landuse=residential` under `natural=water`) and `order="6"` will break it. IMHO issue 8743 is more important than current issue.
