### ISSUE TITLE
No return from the "Avoid certain routes" menu item (back not working)

### ISSUE THREAD

**Issue by ValeriySh** [osmandapp/OsmAnd-iOS#995]
OsmAnd iOS 3.81

Steps to reproduce: 
1. Enter `Settings -> Profile (Car) -> Navigation settings -> Route parameters -> Prefer...`
2. The "back" button ("<") isn't working, the only way to exit is to reboot the app.

**Comment by nnngrach** [comment]
This bug already fixed. Works correctly in TestFlight and in current master version.
